### ISSUE TITLE
Incorrect vlan tag when mirroring traffic from Juniper switch

### ISSUE THREAD

**Issue by hoangtnk** [ntop/nDPI#1001]
I'm using ntopng 4.0 with nDPI 3.2.0. Our network has lots of YouTube traffic, which mostly run on domains `*.googlevideo.com` per my observation. But there's very little has been matched against the YouTube protocol of nDPI. I'm not sure how you currently identify YouTube traffic (can't find the source code for it), but I think matching the SNI against `*.googlevideo.com` should be a good choice.

**Comment by hoangtnk** [comment]
I tried to define a custom application for YouTube based on the instruction [here](https://www.ntop.org/guides/ntopng/web_gui/categories.html), but it doesn't work either. My `protos.txt` file basically looks like this:

```
$ sudo grep "YouTube" /var/lib/ntopng/protos.txt
host:"*.googlevideo.com"@YouTube
```

IP matching for custom app still works fine, only the host setting that does not work. I think it's still relevant to post this issue here, but please let me know if I need to open a separate issue for custom app matching.

**Comment by utoni** [comment]
I'm confused.
In the PCAP, I see two TLS clho's with **googlevideo.com** as SNI suffix and both get classified as YouTube.
The SNI **googlevideo.com** is already part of the `host_match` array in `src/lib/ndpi_content_match.c.inc`.
FYI Wireshark filter: `tcp.stream eq 35 or tcp.stream eq 36`

**Comment by hoangtnk** [comment]
Thanks for pointing me to the source code. Yes, `googlevideo.com` is already part of the source so there should be no problem for ntop to match YouTube traffic. Looks like there's something wrong in my setup, which is currently mirroring traffic from a bonding interface of Juniper switch.

I did a capture on the ntop server itself (the previous one was on my computer), and noticed that traffic from client -> server had vlan-id 4095, while the server -> client did not, causing ntop to think they were separate flows. This is the most likely issue.

I'm not sure where vlan-id 4095 comes from, but looks like it is an internal vlan encapsulation of the switch before forwarding the packet upstream. Trying to find some information about this.

[youtube_captured_on_ntop.pcap.gz](https://github.com/ntop/nDPI/files/5166036/youtube_captured_on_ntop.pcap.gz)

**Comment by hoangtnk** [comment]
Found this paragraph [here](https://www.juniper.net/documentation/en_US/junos/topics/task/configuration/port-mirroring-limitations-qfx-series.html):

_True egress mirroring is defined as mirroring the exact number of copies and the exact packet modifications that went out the egress switched port. Because the processor on QFX5xxx (including QFX5100, QFX5110, QFX5120, QFX5200, and QFX5210) and EX4600 (including EX4600 and EX4650) switches implements egress mirroring in the ingress pipeline, those switches do not provide accurate egress packet modifications, so egress mirrored traffic can carry incorrect VLAN tags that differ from the tags in the original traffic._

I'm using analyzer configuration from one of those switches, which obviously be impacted by this limitation. Looking to try different configuration instead.

**Comment by hoangtnk** [comment]
I ended up enabling the option `--ignore-vlans` for ntopng to categorize flows correctly (basically telling ntop to ignore vlan 4095 sent from Juniper switch). Things are looking good now.
