### ISSUE TITLE
Block torrent traffic

### ISSUE THREAD

**Issue by Arhimad** [ntop/nDPI#1004]
greetings to all
 
I have several proxy servers for shadowsocks please tell me a solution, how to implement a block torrent traffic using ntop or ndpi?

**Comment by utoni** [comment]
As nDPI has it's own `bittorrent` protocol classification, you have to write your own nDPI integration.
This project has some integration examples e.g. [ndpiReader](https://github.com/ntop/nDPI/blob/dev/example/ndpiReader.c) or [ndpiSimpleIntegration](https://github.com/ntop/nDPI/blob/dev/example/ndpiSimpleIntegration.c) which you could use as template. Your integration needs to process packets with nDPI and check the result of the protocol detection for any bittorrent traffic. Last but not least you need a way to block such traffic e.g. via TCP-RST injection or a netfilter interface or something else.
But I do not know how good the nDPI bittorrent detection works.

**Comment by utoni** [comment]
Please open a new issue or re-open this one if you still have questions related to nDPI.
