### ISSUE TITLE
not support MSVC to compile for windows

### ISSUE THREAD

**Issue by muse117** [ntop/nDPI#1005]
Would you consider supporting MSVC compilation?

**Comment by utoni** [comment]
Possible, but not easy to achieve.
It may be easier if this project was CMake based.

**Comment by muse117** [comment]
> Possible, but not easy to achieve.
> It may be easier if this project was CMake based.

yes, alse consider support cmake

**Comment by aouinizied** [comment]
@lnslbrty what would be hard also is the ndpiReader compilation using libpcap (winpcap as npcap do not provide silent installer on CI).
I did a try to compile libndpi dll only using MINGW which can be found in the appveyor file.

**Comment by utoni** [comment]
@muse117 probably does not want a mingw64 xcompile but instead a MSVC integration, which is not as easy as typing `./configure --host=x86_64-mingw-w64`.

**Comment by aouinizied** [comment]
@lnslbrty Maybe a starting point could be from this old opened issue: https://github.com/ntop/nDPI/pull/296

[nDPI.vcxproj.txt](https://github.com/ntop/nDPI/files/5174476/nDPI.vcxproj.txt)

I used it once as a starting point and updated the includes path, etc, and succeeded to compile. But as I failed to load it with cffi, I didn't check if everything was OK.

Hope this would help.

**Comment by lucaderi** [comment]
I have added https://github.com/ntop/nDPI/tree/dev/windows but I hope @lnslbrty adds some notes about mingw that he seems to use.

**Comment by utoni** [comment]
To compile nDPI with mingw-w64 (on Linux), just type: `./configure --host=x86_64-w64-mingw32 && make`.
You need to make sure that mingw-w64 is installed and all CC/LD programs are in your `PATH` env.
