### ISSUE TITLE
documentation for intrusion_detection.c

### ISSUE THREAD

**Issue by Tomasz158** [ntop/nDPI#1007]
Where could I find more tutorial approach for intrusion_detection.c?

I assume that I have to check score at the begining of the packet process function, but I am not familiar with the rating. i.e. which score level would indicate the attack. Do I think correctly that the value between lower and upper bound indicate such attack?

**Comment by utoni** [comment]
I'm not quite sure what score indicates a malicious behaviour. But `example/ndpiReader.c:1068` calculates a `benign_score` which may indicate that a flow is safe if all scores are `< 1.0`.
(dangerous half-knowledge)

**Comment by Tomasz158** [comment]
I will give it a try, thanks
