### ISSUE TITLE
ndpi_includes.h: No such file or directory

### ISSUE THREAD

**Issue by Tomasz158** [ntop/nDPI#1009]
When I try to make (or compile using gcc) intrusion_detection.h, I get an error: 

In file included from intrusion_detection.h:36,
                 from intrusion_detection.c:24:
reader_util.h:34:10: fatal error: ndpi_includes.h: No such file or directory
 #include "ndpi_includes.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by utoni** [comment]
Which OS / Platform? Did you exec `./autogen.sh` beforehand?

**Comment by Tomasz158** [comment]
yes. I run ./autogen.sh and make
Linux

**Comment by utoni** [comment]
I will need more information.
Could you please share all the commands (and the output) required to reproduce this issue (as well as your Linux distribution + version).

**Comment by Tomasz158** [comment]
I would like to integrate intrusion_detection and plan to test it is a part of ndpi_reader.
it works after restarting the system. I have another problem with integrating, but I opened another issue.
[link](https://github.com/ntop/nDPI/issues/1010#issuecomment-688387204)
