### ISSUE TITLE
pkt_timeval

### ISSUE THREAD

**Issue by Tomasz158** [ntop/nDPI#1010]
while compiling reader_util.h I get an error:

error: unknown name type pkt_timeval

**Comment by utoni** [comment]
How did you (try to) compile it?

**Comment by Tomasz158** [comment]
I tried using gcc with -lndpi

**Comment by utoni** [comment]
Same here:
I will need more information.
Could you please share all the commands (and the output) required to reproduce this issue (as well as your Linux distribution + version).

**Comment by Tomasz158** [comment]
-------------- Build: Debug in inz (compiler: GNU GCC Compiler)---------------

gcc -Wall -Wunused -g -Wno-deprecated-declarations -Iinclude -c /home/tomasz/Pulpit/inz/intrusion_detection.c -o obj/Debug/intrusion_detection.o
g++ -Wall -std=c++0x -Wunused -g -Wno-deprecated-declarations -Iinclude -c /home/tomasz/Pulpit/inz/main.cpp -o obj/Debug/main.o
In file included from /home/tomasz/Pulpit/inz/intrusion_detection.h:36,
                 from /home/tomasz/Pulpit/inz/intrusion_detection.c:24:
/home/tomasz/Pulpit/inz/reader_util.h:132:3: error: unknown type name ‘pkt_timeval’
   pkt_timeval src2dst_last_pkt_time, dst2src_last_pkt_time, flow_last_pkt_time;
   ^~~~~~~~~~~
/home/tomasz/Pulpit/inz/reader_util.h:134:3: error: unknown type name ‘pkt_timeval’
   pkt_timeval src2dst_pkt_time[MAX_NUM_PKTS];               /*!< array of arrival times          */
   ^~~~~~~~~~~
/home/tomasz/Pulpit/inz/reader_util.h:136:3: error: unknown type name ‘pkt_timeval’
   pkt_timeval dst2src_pkt_time[MAX_NUM_PKTS];               /*!< array of arrival times          */
   ^~~~~~~~~~~
/home/tomasz/Pulpit/inz/reader_util.h:137:3: error: unknown type name ‘pkt_timeval’
   pkt_timeval src2dst_start;                                /*!< first packet arrival time       */
   ^~~~~~~~~~~
/home/tomasz/Pulpit/inz/reader_util.h:138:3: error: unknown type name ‘pkt_timeval’
   pkt_timeval dst2src_start;                                /*!< first packet arrival time       */
   ^~~~~~~~~~~
Process terminated with status 1 (0 minute(s), 0 second(s))

Linux Debian 10

**Comment by Tomasz158** [comment]
I also got the following:
/home/tomasz/Pulpit/inz/reader_util.h:132:3: error: ‘pkt_timeval’ does not name a type; did you mean ‘timeval’?
   pkt_timeval src2dst_last_pkt_time, dst2src_last_pkt_time, flow_last_pkt_time;
   ^~~~~~~~~~~
   timeval
/home/tomasz/Pulpit/inz/reader_util.h:134:3: error: ‘pkt_timeval’ does not name a type; did you mean ‘timeval’?
   pkt_timeval src2dst_pkt_time[MAX_NUM_PKTS];               /*!< array of arrival times          */
   ^~~~~~~~~~~
   timeval
/home/tomasz/Pulpit/inz/reader_util.h:136:3: error: ‘pkt_timeval’ does not name a type; did you mean ‘timeval’?
   pkt_timeval dst2src_pkt_time[MAX_NUM_PKTS];               /*!< array of arrival times          */
   ^~~~~~~~~~~
   timeval
/home/tomasz/Pulpit/inz/reader_util.h:137:3: error: ‘pkt_timeval’ does not name a type; did you mean ‘timeval’?
   pkt_timeval src2dst_start;                                /*!< first packet arrival time       */
   ^~~~~~~~~~~
   timeval
/home/tomasz/Pulpit/inz/reader_util.h:138:3: error: ‘pkt_timeval’ does not name a type; did you mean ‘timeval’?
   pkt_timeval dst2src_start;                                /*!< first packet arrival time       */
   ^~~~~~~~~~~
   timeval

**Comment by utoni** [comment]
Did you re-run `autogen.sh` ?

**Comment by Tomasz158** [comment]
I fixed the issue.

**Comment by ChrisNelson-CyberReef** [comment]
@Tomasz158 , it'd be nice to know _how_ you fixed it.
