### ISSUE TITLE
issues with intrustion_detection

### ISSUE THREAD

**Issue by Tomasz158** [ntop/nDPI#1011]
I have a problem integrating some of the functions of ndpi detect
I copied typedef struct norm_values from intrustion_detection.h along with proper functions from intrusion_detection.c

`ndpi_norm_value* scores = malloc(n_metrics * sizeof(ndpi_norm_value));`
error: invalid conversion from ‘void*’ to ‘ndpi_norm_value*’ {aka ‘norm_values*’} [-fpermissive]|

`scores[i].value = ndpi_data_max(flow->pktlen_s_to_c);`
error: invalid use of incomplete type ‘struct ndpi_flow_info’

**Comment by Tomasz158** [comment]
compilation and linux version is the same as in other issues.

**Comment by utoni** [comment]
What is the type of `flow`? What about your includes?
Please paste all relevant information in this issue.

> `ndpi_norm_value* scores = malloc(n_metrics * sizeof(ndpi_norm_value));`

an explicit cast to `ndpi_norm_value*` may fix that
