### ISSUE TITLE
SPDY dissection support

### ISSUE THREAD

**Issue by Tomasu** [ntop/nDPI#102]
Currently libndpi does not support detecting the SPDY protocol (precursor to HTTP2). It is fully encrypted via TLS. The easiest way of detecting it that i can tell is there is an application data protocol field set to "spdy", or at least it is in wireshark.

**Comment by kYroL01** [comment]
In my opinion I don't know if it's usefull a dissector for the old SPDY protocol.
The Google group, in February 9, 2015, announces to refuse SPDY in favour of HTTP/2, as you can read this http://blog.chromium.org/2015/02/hello-http2-goodbye-spdy-http-is_9.html.
This is also one of the reasons why Google realeased the Quic protocol.

**Comment by Tomasu** [comment]
I wouldn't ask, but i see a fair bit of SPDY traffic still.

**Comment by lucaderi** [comment]
QUIC is now fully supported
