### ISSUE TITLE
Enable the examples compilation for MINGW Build

### ISSUE THREAD

**Issue by srajeshinfotech** [ntop/nDPI#1020]
Dear Team,

Can you please enable the examples compilation for windows mingw platform?

**irxtx.com@rajesh ~/Projects/21Sep/nDPI-dev/example
$ make
Examples disabled due to mingw build.**

Best Regards,
Rajesh~
[iRxTx.com](https://irxtx.com/)
+91-9600635770

**Comment by utoni** [comment]
This would basically mean that we would have to integrate a Win10PCAP header file together with an import library in the nDPI repository, which I'm not a fan of.

**Comment by utoni** [comment]
Fixed wiith 8d0c7b1faeed1e3df6e6f90658559f373bbf63fb.
