### ISSUE TITLE
Build Error - Mingw platform

### ISSUE THREAD

**Issue by srajeshinfotech** [ntop/nDPI#1021]
Dear Team,

I'm trying to build the nDPI sing mingw compiler. While building the src code getting the below error.

Looks like, In ndpi_utils.c file duplicate strncasecmp() and strcasecmp() added in WIN32 platform.
Would you please check the compilation for win32 mingw platform?

### Build Command

**export LDFLAGS="-L/lib/pcap -lpcap -lpacket"
export CFLAGS="-DWIN32 -I/usr/include/winpcap"
./autogen.sh --host=i686-w64-mingw32
make**

i686-w64-mingw32-gcc -shared -fPIC  -o libndpi-3.3.0.dll  protocols/afp.o  protocols/aimini.o  protocols/ajp.o  protocols/amazon_video.o  protocols/amqp.o  protocols/apple_push.o  protocols/applejuice.o  protocols/armagetron.o  protocols/ayiya.o  protocols/bgp.o  protocols/bittorrent.o  protocols/bjnp.o  protocols/btlib.o  protocols/capwap.o  protocols/checkmk.o  protocols/ciscovpn.o  protocols/citrix.o  protocols/coap.o  protocols/collectd.o  protocols/corba.o  protocols/crossfire.o  protocols/csgo.o  protocols/dcerpc.o  protocols/dhcp.o  protocols/dhcpv6.o  protocols/diameter.o  protocols/directconnect.o  protocols/directdownloadlink.o  protocols/dnp3.o  protocols/dns.o  protocols/dnscrypt.o  protocols/dofus.o  protocols/drda.o  protocols/dropbox.o  protocols/eaq.o  protocols/edonkey.o  protocols/fasttrack.o  protocols/fbzero.o  protocols/fiesta.o  protocols/fix.o  protocols/florensia.o  protocols/ftp_control.o  protocols/ftp_data.o  protocols/git.o  protocols/gnutella.o  protocols/gtp.o  protocols/guildwars.o  protocols/h323.o  protocols/halflife2_and_mods.o  protocols/hangout.o  protocols/http.o  protocols/http_activesync.o  protocols/iax.o  protocols/icecast.o  protocols/iec60870-5-104.o  protocols/imo.o  protocols/ipp.o  protocols/irc.o  protocols/jabber.o  protocols/kakaotalk_voice.o  protocols/kerberos.o  protocols/kontiki.o  protocols/ldap.o  protocols/lisp.o  protocols/lotus_notes.o  protocols/mail_imap.o  protocols/mail_pop.o  protocols/mail_smtp.o  protocols/maplestory.o  protocols/megaco.o  protocols/memcached.o  protocols/mgcp.o  protocols/mining.o  protocols/modbus.o  protocols/mpegts.o  protocols/mqtt.o  protocols/mssql_tds.o  protocols/mysql.o  protocols/nats.o  protocols/nest_log_sink.o  protocols/netbios.o  protocols/netflow.o  protocols/nfs.o  protocols/nintendo.o  protocols/noe.o  protocols/non_tcp_udp.o  protocols/ntp.o  protocols/ookla.o  protocols/openft.o  protocols/openvpn.o  protocols/oracle.o  protocols/pando.o  protocols/postgres.o  protocols/pplive.o  protocols/ppstream.o  protocols/pptp.o  protocols/qq.o  protocols/quic.o  protocols/radius.o  protocols/rdp.o  protocols/redis_net.o  protocols/rsync.o  protocols/rtcp.o  protocols/rtmp.o  protocols/rtp.o  protocols/rtsp.o  protocols/rx.o  protocols/s7comm.o  protocols/sflow.o  protocols/shoutcast.o  protocols/sip.o  protocols/skinny.o  protocols/skype.o  protocols/smb.o  protocols/smpp.o  protocols/snmp_proto.o  protocols/soap.o  protocols/socks45.o  protocols/someip.o  protocols/sopcast.o  protocols/soulseek.o  protocols/spotify.o  protocols/ssdp.o  protocols/ssh.o  protocols/starcraft.o  protocols/stealthnet.o  protocols/steam.o  protocols/stun.o  protocols/syslog.o  protocols/targus_getdata.o  protocols/tcp_udp.o  protocols/teamspeak.o  protocols/teamviewer.o  protocols/telegram.o  protocols/telnet.o  protocols/teredo.o  protocols/tftp.o  protocols/thunder.o  protocols/tinc.o  protocols/tls.o  protocols/tor.o  protocols/tvuplayer.o  protocols/ubntac2.o  protocols/upnp.o  protocols/usenet.o  protocols/vhua.o  protocols/viber.o  protocols/vmware.o  protocols/vnc.o  protocols/warcraft3.o  protocols/websocket.o  protocols/whatsapp.o  protocols/whoisdas.o  protocols/wireguard.o  protocols/world_of_kung_fu.o  protocols/world_of_warcraft.o  protocols/xbox.o  protocols/xdmcp.o  protocols/zabbix.o  protocols/zattoo.o  protocols/zeromq.o  third_party/src/ahocorasick.o  third_party/src/ht_hash.o  third_party/src/libcache.o  third_party/src/libinjection_html5.o  third_party/src/libinjection_sqli.o  third_party/src/libinjection_xss.o  third_party/src/ndpi_md5.o  third_party/src/ndpi_patricia.o  third_party/src/ndpi_sha1.o  third_party/src/node.o  third_party/src/sha1-fast.o  third_party/src/sort.o  third_party/src/strptime.o  ./ndpi_analyze.o  ./ndpi_classify.o  ./ndpi_community_id.o  ./ndpi_main.o  ./ndpi_serializer.o  ./ndpi_utils.o -L/lib/pcap -lpcap -lpacket -lws2_32 -lucrtbase  -lws2_32
**/usr/lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld: /usr/i686-w64-mingw32/sys-root/mingw/lib/../lib/libucrtbase.a(dsiics02051.o):(.text+0x0): multiple definition of `_strnicmp'; ./ndpi_utils.o:ndpi_utils.c:(.text+0x5e6): first defined here
/usr/lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld: /usr/i686-w64-mingw32/sys-root/mingw/lib/../lib/libucrtbase.a(dsiics01987.o):(.text+0x0): multiple definition of `_stricmp'; ./ndpi_utils.o:ndpi_utils.c:(.text+0x579): first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:55: libndpi-3.3.0.dll] Error 1
make[1]: Leaving directory '/home/mariya-maseeha/Projects/21Sep/nDPI-dev/src/lib'
make: *** [Makefile:498: all-recursive] Error 1**

Best Regards,
Rajesh~
[iRxTx.com](https://irxtx.com/)
+91-9600635770

**Comment by utoni** [comment]
Need to check the i686 mingw-w64 build. Thanks for reporting that issue.

**Comment by utoni** [comment]
Does PR #1022 fix that issue for you?

**Comment by srajesh-elisity** [comment]
Yes, Fixed. Thanks for your support.!

Please move the issue to resolved state.

**Comment by lucaderi** [comment]
Fixed by https://github.com/ntop/nDPI/pull/1022
