### ISSUE TITLE
Error in ndpi_data_variance

### ISSUE THREAD

**Issue by ghost** [ntop/nDPI#1029]
Hi,

in ndpi_analyze.c, the variance computation is

float ndpi_data_variance(struct ndpi_analyze_struct *s) {
  return(s->num_data_entries ? (float)(s->stddev.sum_square_total - ((s->sum_total * s->sum_total) / (s->num_data_entries))) / (float)s->num_data_entries : 0);
}
(s->sum_total * s->sum_total) / (s->num_data_entries) these elements in the computation should be casted as floats. s->sum_total * s->sum_total is computed on 32 bits and can easily be greater than 2^32.
For example if s->sum_total is 2^16+1 or greater the result is wrong because of integer overflow.

The variance computation should be :

float ndpi_data_variance(struct ndpi_analyze_struct *s) {
  return(s->num_data_entries ? ((float)s->stddev.sum_square_total - ((float)s->sum_total * (float)s->sum_total / (float)s->num_data_entries)) / (float)s->num_data_entries : 0.0);
}

**Comment by lucaderi** [comment]
Thanks !
