### ISSUE TITLE
dissection support for ports 5228 and 5221 that chrome uses

### ISSUE THREAD

**Issue by Tomasu** [ntop/nDPI#103]
Based on some googling, it looks like they are originally XMPP ports, but chrome is passing some binary data over the connection. The first few bytes are somewhat similar between packets, but there are some variances. I'm not sure how to figure this out without knowing more about the protocol.

http://tomasu.net/~moose/5228.pcap

**Comment by kYroL01** [comment]
I launched this pcap with ndpiReader and i have this results:
**SSL_No_Cert     packets: 40            bytes: 7452     flows: 2**
**Google               packets: 14            bytes: 2218     flows: 2**

So, what's wrong ? nDPI cannot base dissection only on ports without an associated protocol.
Do you think that these ports are only used by the XMPP protocol ?
Please, explain better what is your question.

**Comment by Tomasu** [comment]
HM, so it seems to actually be detecting it as SSL/Google for you? I should check with the ndpi example more often. 

Though I was hoping it'd be possible to actually figure out a more specific protocol for those ports. 

The ports in question are normally XMPP, but chrome is sending binary, non XMPP data across. Maybe it's just encrypted xml, I don't know.

**Comment by kYroL01** [comment]
I tested right now: I launched your pcap with our ndpiReader and yes, the packets are correctly detected as Google/SSL.

As I read on Wiki, "Originally named Jabber, the protocol was developed by the Jabber open-source community [...]. XMPP servers can be isolated (e.g., on a company intranet), and secure authentication (SASL) and encryption (TLS) have been built into the core XMPP specifications.".

So, nDPI has the jabber dissector (nDPI/src/lib/protocols/jabber.c), but just for the UNENCRYPED protocol.

It's a good point understand if is usefull and possibile create a specific dissector for XMPP.

**Comment by Tomasu** [comment]
Ah, if there is an option for encrypted jabber, it could be useful. That's essentially what Google Talk is.

**Comment by kYroL01** [comment]
Yes, but, for example, Google Talk is encrypted. you cannot have a protocol dissector, maybe a service if you know exactly the used servers and ports.
This is why we have only the jabber unencryped dissector.

**Comment by Tomasu** [comment]
I was thinking that since its a connection oriented protocol, it would have some kind of handshake and pattern that can be fingerprinted, even if it is encrypted. How else is each end able to understand each other?

**Comment by kYroL01** [comment]
I think is necessary a better study of the case and how to implement the best way.
The questions is:
- is needed and possibile a XMPP protocol dissector ?
- how is possibile detect it if is encrypted ?

**Comment by lmangani** [comment]
Besides actual XMPP/Jabber/Jingle, please see: https://support.google.com/a/answer/1279090?hl=en

**Comment by kYroL01** [comment]
@lmangani thank you for the support
