### ISSUE TITLE
Error compiling the code...

### ISSUE THREAD

**Issue by gianogli** [ntop/nDPI#1031]
I downloaded the nDPI code (dev branch) and I tried to run `./autogen.sh` but ended with this error:
```
checking for numa_available in -lnuma... yes
checking for pcap_open_live in -lpcap... no

ERROR: Missing libpcap(-dev) library required to compile the example application
ERROR: Please install it and try again
```
This is correct because I haven't installed libpcap-dev package but I've the libpcap library and header files present into a PF_RING folder.

Into nDPI `configure` file I saw the variable PCAP_HOME set as `PCAP_HOME=$HOME/PF_RING/userland` so I created a symbolic link to PF_RING code to my home folder:
```
ln -s /usr/local/src/PF_RING /root/PF_RING
```

After this change `./autogen.sh` end without errors.
At this point I run `./configure` and `make` but:
```
[...]
ln -fs libndpi.so.3.3.0 libndpi.so
ln -fs libndpi.so.3.3.0 libndpi.so.3
make[1]: Leaving directory '/usr/local/src/nDPI.09102020/src/lib'
Making all in example
make[1]: Entering directory '/usr/local/src/nDPI.09102020/example'
gcc -g -fPIC -DPIC -I../src/include -g -O2 -I/usr/include/json-c -c reader_util.c -o reader_util.o
In file included from reader_util.c:86:0:
reader_util.h:33:18: fatal error: pcap.h: No such file or directory
compilation terminated.
Makefile:34: recipe for target 'reader_util.o' failed
make[1]: *** [reader_util.o] Error 1
make[1]: Leaving directory '/usr/local/deri/nDPI.09102020/example'
Makefile:499: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```
Why it happen if libpcap is identified correctly by `./configure`?

Thanks... :-)

**Comment by utoni** [comment]
Could you please attach `config.log`.

**Comment by gianogli** [comment]
As a temporary workaround I've manually added "-I/root/PF_RING/userland/libpcap" to CFLAGS variable into `tests/unit/Makefile` and `example/Makefile`.
Here the requested file: [config.log](https://github.com/ntop/nDPI/files/5359411/config.log)

Thanks :-)

**Comment by utoni** [comment]
Does PR #1034 fix that issue for you?

**Comment by gianogli** [comment]
Yes, now it works.
Thanks... :-)
