### ISSUE TITLE
Error in ndpi_data_add_value

### ISSUE THREAD

**Issue by ghost** [ntop/nDPI#1032]
Hi,

in ndpi_analyze.c

In ndpi_data_add_value there is

s->stddev.sum_square_total += value * value;

If value is greater than 2^16+1 the computation can overflow (depends on the compilation)

the computation should be 

s->stddev.sum_square_total += (u_int64_t) value * (u_int64_t) value;

to be safer.

**Comment by lucaderi** [comment]
Thanks !
