### ISSUE TITLE
With 3.2-stable branch HTTP_Download is not being detected. This was working correctly in the 2.6

### ISSUE THREAD

**Issue by kumar-srivatsa** [ntop/nDPI#1033]
Looks like with 3.2-stable, the ndpi_protocol_match content_match[]  has been removed from ndpi_content_match.c.inc. What is the alternate mechanism to match the mime-type. The HTTP_Download is not being matched because of this change. Earlier this used to work in 2.6. 

What is the alternative mechanism to match on mime-type to set NDPI_PROTOCOL_HTTP_DOWNLOAD. Do we need to change the http.c dissector itself to match?

**Comment by lucaderi** [comment]
Can you please provide a PCAP file for testing and specify what is the expected result?

**Comment by kumar-srivatsa** [comment]
Thanks for the response. The expected result is app_protocol should be NDPI_PROTOCOL_HTTP_DOWNLOAD and master_protocol should be NDPI_PROTOCOL_HTTP. Have attached a pcap where we are downloading a binary data through HTTP. 
[hd.pcap.gz](https://github.com/ntop/nDPI/files/5400854/hd.pcap.gz)


Here's a fix diff that I made.. Not sure if this is the right place to put the fix.

[http.fix.txt](https://github.com/ntop/nDPI/files/5400878/http.fix.txt)

**Comment by lucaderi** [comment]
I had a look at the fix. The thing is that for download we now use categories so NDPI_PROTOCOL_HTTP_DOWNLOAD is gone. I have fix it in a different way along the lines of nDPI philosophy

**Comment by kumar-srivatsa** [comment]
@lucaderi Thanks for the fix. So we will not have a separate sub-protocol for HTTP anymore?  Is that going to be way forward to use categories instead of sub-protocols for other one's too? Thanks
