### ISSUE TITLE
ndpi + dpdk

### ISSUE THREAD

**Issue by Hugh5632** [ntop/nDPI#1043]
我使用dpdk+ndpi测试 ndpiReader示例，从"nDPI: Open-Source High-Speed  Deep Packet Inspection"中我得知ndpiReader可以在10G/Mb带宽中运行，但是我的实际速度达不到，仅仅为1/10

I used dpdk+ndpi to test the ndpiReader example. From "nDPI: Open-Source High-Speed Deep Packet Inspection" I learned that ndpiReader can run in 10G/Mb bandwidth, but my actual speed is not up to 1/ 10

**Comment by mmanoj** [comment]
@Hugh5632 

What is your exact problem? Please elaborate more details about what are you going to acheive?

**Comment by Hugh5632** [comment]
using ndpi + dpdk, I can't achieve 10G/Mb ,I want to know how to do that

**Comment by utoni** [comment]
What exactly is 10G/Mb? 10 Giga per Megabyte?

**Comment by mmanoj** [comment]
@Hugh5632 

Can you provide more details about DPDK app and your testing scenario, So we can give some guidelines. Also, note if you want to test 10Gbps you need to have a network environment for the same.

**Comment by Hugh5632** [comment]
> 10G / Mb到底是什么？每兆字节10 Giga？

10Gb/s

**Comment by Hugh5632** [comment]
Just like the ndpiReader example says, I followed the instructions of README.DPDK.It says:

You need to install and compile DPDK in your HOME directory as explained in
See http://core.dpdk.org/doc/quick-start/ for DPDK installation and setup

Once DPDK is built make sure to create a symbolic link

$ cd
$ ln -s dpdk-18.08 DPDK

so the build process will use the DPDK directory letting you have multiple
DPDK versions available on your system


Build
-----
Everything will happen automagically but if you want to do it by hand
do: make -f Makefile.dpdk


Run Application
---------------
Supposing to capture packets from device eno1 you can start the
application as follows:

sudo ./build/ndpiReader -c 1 --vdev=net_pcap0,iface=eno1 -- -v 1

NOTE:
- ndpiReader without DPDK support sits in this directory
- ndpiReader with DPDK support can be found inside the ./build directory

**Comment by Hugh5632** [comment]
The network environment I use is 10 Gigabit, and I run it under the centos server environment

**Comment by mmanoj** [comment]
Ok, Then what is the test case you going to perform in your env. Did you generate 10Gbps traffic towards the nDPIReader?

**Comment by Hugh5632** [comment]
I use two servers to receive and send packages, one of which uses pkgen to send packages, the other executes ndpiReader example, uses Ethernet 10 Gigabit network card, and the hardware environment meets the test requirements

**Comment by mmanoj** [comment]
Can you share your output or observations?

**Comment by feriel-ux** [comment]
hello , when I run the command make -f Makefile.dpdk I get this error 
LD ndpiReader.dpdk
/usr/bin/ld: cannot find -lrte_pmd_lio
/usr/bin/ld: cannot find -lrte_pmd_sfc_efx
/usr/bin/ld: cannot find -lrte_pmd_thunderx_nicvf
/usr/bin/ld: cannot find -lrte_pmd_vmxnet3_uio
/usr/bin/ld: cannot find -lrte_pmd_octeontx_zip
/usr/bin/ld: cannot find -lrte_pmd_octeontx_ssovf
collect2: error: ld returned 1 exit status
 what should I do

**Comment by mmanoj** [comment]
Did you set RTE SDK dir?

**Comment by feriel-ux** [comment]
done , the problem solved , it was in the library path , he didn't find where the library rte_pmd are located .

**Comment by feriel-ux** [comment]
Hello, I built up ndpi over DPDK and I'm trying to see results from the command "ndpiReader.dpdk",  the same way I used to see them from ndpiReader
but i always get igmp protocol and no other protocols are detected. I

**Comment by mmanoj** [comment]
@feriel-ux 

How are you checking the traffic, can you share the command the trying and a sketch of your setup to better understand.

**Comment by feriel-ux** [comment]
with the command ./ndpiReader.dpdk under /example/build .. I want the same result as ndpiReader only with the same detected protocols but with more performance.
