### ISSUE TITLE
intrusion_detection.c issue

### ISSUE THREAD

**Issue by Tomasz158** [ntop/nDPI#1055]
I have a compilation problem in intrusion_detection.c. When I compile (using gcc c+11) under Linux, I have the following error:
`error: invalid conversion from ‘void*’ to ‘ndpi_norm_value*’ {aka ‘norm_values*’} [-fpermissive]|`
part of the code that causes the error:
` ndpi_norm_value* scores = malloc(n_metrics * sizeof(ndpi_norm_value));`

**Comment by utoni** [comment]
This is a pure C library including most of the examples.
It was not designed to compile with a C++ compiler e.g. `g++`.
But if you really want to Copy'n'Paste the code from `intrustion_detection.c` into your C++ app, you should try to cast the return value from `malloc()` to `(ndpi_norm_value *)`. Or just add the `CXXFLAG` `-fpermissive` to your compilation command.

**Comment by Tomasz158** [comment]
Thanks. I will try and open a new case, if I still have issue. I am more comfortable with C++, so I am mostly using that language
