### ISSUE TITLE
Is vlan_id necessary for flow.hashval in ndpiReader?

### ISSUE THREAD

**Issue by emarshswe** [ntop/nDPI#1073]
Currently, ndpiReader calculates flow.hashval = flow.protocol + flow.vlan_id + flow.src_ip + flow.dst_ip +flow.src_port + flow.dst_port

This causes flow splits in situations where vlan_id is only used in one direction. This is actually pretty common in big datacenters. Src/Dst has vlan_id but other side does not. Removing vlan_id from the flow_hashval calculation remedies this problem.

I have found no problems with changing this since vlan_id is still reported in the session.

What would the impact be if we changed the behavior to not include vlan_id in hashval calculation?

I'll gladly make a pull requests if no problems are found.

**Comment by lucaderi** [comment]
I am not against it, but if you want to make a PR make it adding a new CLI option (soemthing like --ignore-vlanid) and do nto change it for everyone please

**Comment by utoni** [comment]
@emarshswe Does PR #1085 satisfy your needs?

**Comment by hoangtnk** [comment]
Excuse me, I just wonder if this and [Support for ignoring vlan tags](https://github.com/ntop/ntopng/issues/1870) are similar things? Hope someone can clarify.

**Comment by emarshswe** [comment]
> Excuse me, I just wonder if this and [Support for ignoring vlan tags](https://github.com/ntop/ntopng/issues/1870) are similar things? Hope someone can clarify.

@hoangtnk 
The issue I posted only concerns the example ndpiReader application, so no changes here will affect ntop or the nDPI library itself.

I read some of your comments in the ntop repository and I'm afraid that _ignore vlans does not work with RSS_ is unrelated to this issue since ndpiReader is a small demo application to showcase the nDPI library.

**Comment by emarshswe** [comment]
> @emarshswe Does PR #1085 satisfy your needs?

Excellent work @lnslbrty and @lucaderi this is a working solution for me. Thank you!
