### ISSUE TITLE
DPDK-nDPI installation error

### ISSUE THREAD

**Issue by merveorakci12** [ntop/nDPI#1075]
Hi, I try to dpdk for ndpi, but I get error like this:

In file included from /root/nDPI-3.4-original/example/reader_util.c:86:0:
/root/nDPI-3.4/example/reader_util.h:39:10: fatal error: rte_eal.h: No such file or directory
 #include <rte_eal.h>
          ^~~~~~~~~~~
compilation terminated.
/root/DPDK/mk/internal/rte.compile-pre.mk:114: recipe for target 'reader_util.o' failed
make[1]: *** [reader_util.o] Error 1
/root/DPDK/mk/rte.extapp.mk:14: recipe for target 'all' failed
make: *** [all] Error 2

I follow this instructions when i install: (dpdk-18.08 and nDPI last stable version)

ln -s dpdk-18.08 DPDK
do: make -f Makefile.dpdk

What is your recommendation? for this issue.

Second Question : What is the last DPDK version that supports the latest version of nDPI? 
Thanks,

**Comment by lucaderi** [comment]
This looks an include error. Please avoid compiling as root.
As of the second question, I have tested DPDK some time ago but I assume it should work as we have users for it
