### ISSUE TITLE
too many arguments to function ‘ndpi_check_dga_name’ in ndpiReader

### ISSUE THREAD

**Issue by Tomasz158** [ntop/nDPI#1076]
When I compile ndpiReader.c, I have the following error:

too many arguments to function ‘ndpi_check_dga_name’
Line of the code that generates error:
`assert(ndpi_check_dga_name(ndpi_str, NULL, (char*)dga[i], 1) == 1);`

I compile the code using gcc under Debian

**Comment by Tomasz158** [comment]
any ideas?

**Comment by utoni** [comment]
Does this issue still exist after re-running `./autogen.sh` ?

**Comment by lucaderi** [comment]
Everything seems to work. I believe you didn't sync the code or autopen properly
