### ISSUE TITLE
SNI: flow->protos.stun_ssl.ssl.client_requested_server_name vs flow->host_server_name

### ISSUE THREAD

**Issue by IvanNardi** [ntop/nDPI#1077]
Where is the right place to save SNI (for QUIC connections)?

At the moment, the situation is not coherent:
* TLS, IETF-QUIC and GQUIC T05x save the SNI in `flow->protos.stun_ssl.ssl.client_requested_server_name` (QUIC code calls `tls::processClientServerHello()`)
* GQUIC != T05x and FB_ZERO save the SNI in `flow->host_server_name` (note that the original QUIC code already did it; FB_ZERO is a dead protocol, but I report it nonetheless for the sake of completeness)

Having the same protocol saving the same information in two different places (depending on its version) is clearly a bug. 
Where should I save the SNI? I think it should be `flow->protos.stun_ssl.ssl.client_requested_server_name`, but I would like to hear some comments on that.
Note that QUIC dissector already sets a lot of `flow->protos.stun_ssl.ssl` fields other than `client_requested_server_name`

Thanks in advance

**Comment by utoni** [comment]
As more recent QUIC drafts (Google,  IETF / Facebook) use TLS1.3 as cryptographic protocol, I think `flow->protos.stun_ssl.ssl.client_requested_server_name` is more specific than `flow->host_server_name`.

**Comment by IvanNardi** [comment]
@lucaderi, do you agree to always use `flow->protos.stun_ssl.ssl.client_requested_server_name`?
