### ISSUE TITLE
nDPI/ntopng build failed on FreeBSD

### ISSUE THREAD

**Issue by stalsbyt** [ntop/nDPI#108]
Hi. I'am trying to compile ntopng/nDPI on FreeBSD and get different issues.
FreeBSD 9.3-RELEASE
try devel branches of ntopng/nDPI:

```
In file included from src/Ntop.cpp:22:
In file included from /home/dron/ntopstable/ntopng/include/ntop_includes.h:192:
<mypath>/ntopng/include/Host.h:154:23: error: unknown type name 'ndpi_protocol' bool doDropProtocol(ndpi_protocol l7_proto);
```

try stable nDPI and all branches of ntopng:

```
src/NetworkInterface.cpp:864:21: error: member reference base type 'unsigned int' is not a structure or union cli, srv).protocol);
```

**Comment by kYroL01** [comment]
First of all, don't use the stable branch, use the dev one.

This is a ntopng issue. 
It seems that the errors are on ntopng source code, so please open this issue on ntopng.

**Comment by lucaderi** [comment]
@stalsbyt I have just tested on FreeBSD 10 and ntopng+nDPI compiles and works beautifully.
