### ISSUE TITLE
undefined reference to `ndpi_flow_get_byte_count_entropy'|

### ISSUE THREAD

**Issue by Tomasz158** [ntop/nDPI#1081]
I have an unusual error with undefined reference to `ndpi_flow_get_byte_count_entropy', even though reader_util.h is included.
Compiler commands:

`
gcc -Wall -g  -c /inztest/main.c -o obj/Debug/main.o
g++  -o bin/Debug/inztest obj/Debug/main.o  -lpthread -lndpi  
`

I copied the content of reader_util.c into main.c

**Comment by utoni** [comment]
The symbol `ndpi_flow_get_byte_count_entropy` is part of **reader_util** in `example/`.

**Comment by Tomasz158** [comment]
Ok, thanks. How can I fix it, so it pass compilation?

**Comment by utoni** [comment]
You need to generate an object file from `reader_util.c` with:

`gcc -Wall -g -c ./example/reader_util.c -o obj/Debug/reader_util.o`

and include both object files in the linking process with:

`g++ -o bin/Debug/inztest obj/Debug/main.o obj/Debug/reader_util.o -lpthread -lndpi`

**Comment by Tomasz158** [comment]
I will try that, thanks

**Comment by Tomasz158** [comment]
I copied reader_utuil.c and pasted in main.c as a whole. Still same error

**Comment by Tomasz158** [comment]
Most of the errors are gone, when I included missing headers and c files.
However the following undefined left:
ndpi_get_gcrypt_version
I also had problem with enable_doh_dot_detection, but after removing extern part, it worked

`g++  -o bin/Debug/inztest obj/Debug/intrusion_detection.o obj/Debug/main.o obj/Debug/reader_util.o  -lpthread -lndpi -lpcap  lib/libndpi.so
/usr/bin/ld: obj/Debug/main.o: in function main:
/home/tomasz/Pulpit/inztest/main.c:3731: undefined reference to ndpi_get_gcrypt_version
collect2: error: ld returned 1 exit status`

ndpi/ndpi_api.h is included

**Comment by utoni** [comment]
## 1. possible issue
You may be linking against an old `libndpi`. You are using Debian as you mentioned in another issue. Debian Stable ships a quite old `libndpi` (< 3 I guess). If you are compiling `libndpi` from source, make sure `libgcrypt20-dev` is installed and the configure option `--disable-gcrypt` is **not** set.

## 2. possible issue
You need give the linker a "hint" where to look for shared libraries with `-L` if `libndpi` is not installed in the default search paths e.g. `/lib` or `/usr/lib`.
Be aware that the dynamic linker needs also some information where to look for shared libraries (lookup `rpath`or `LD_LIBRARY_PATH` using your favorite search engine).
You can also link against a static version of `libndpi` which eliminates this issue.

**Comment by Tomasz158** [comment]
I commented out this section and it fixed the issue. However, I can't see live statistics of packet capturing (like in wireshark). Simple copy of simple integration would make the trick? Where should i put the reference to it then? I am trying to combine wireshark-like information along with ndpi_reader, beacuse the latter have all the nescessary functions for intrusion_detection.c and h

**Comment by Tomasz158** [comment]
it works now.
