### ISSUE TITLE
hardcoding values to ndpi_reader

### ISSUE THREAD

**Issue by Tomasz158** [ntop/nDPI#1089]
How can I 'hardcode' values like interface or verbose level to ndpi_reader, so to avoid parseOptions?

**Comment by pengtianabc** [comment]
TwoWay:
1. You can check by `argc` from `main`, if `argc` is 1, update `argv` to your custom options string
2. Just change the default value of each variables.

**Comment by Tomasz158** [comment]
I managed to resolve fhe second way, thanks.
