### ISSUE TITLE
Issue Installing nDPI

### ISSUE THREAD

**Issue by Cyclones92** [ntop/nDPI#109]
I am trying to install nDPI for NTOPNG through git and apparently something isn't working correctly. :/

[someuser@someserver nDPI]$ ./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in`.'.
libtoolize: can not copy `/usr/share/libtool/config/ltmain.sh' to`./'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: can not copy`/usr/share/aclocal/libtool.m4' to `m4/'
libtoolize: can not copy`/usr/share/aclocal/ltoptions.m4' to `m4/'
libtoolize: can not copy`/usr/share/aclocal/ltsugar.m4' to `m4/'
libtoolize: can not copy`/usr/share/aclocal/ltversion.m4' to `m4/'
libtoolize: can not copy`/usr/share/aclocal/lt~obsolete.m4' to `m4/'
autoreconf: libtoolize failed with exit status: 1
./autogen.sh: line 33: ./configure: No such file or directory

Any clues on what I can try?

I have these installed on the server.
Package automake-1.11.1-4.el6.noarch already installed and latest version
Package autoconf-2.63-5.1.el6.noarch already installed and latest version
Package libtool-2.2.6-15.5.el6.x86_64 already installed and latest version
Package gcc-4.4.7-16.el6.x86_64 already installed and latest version

**Comment by kYroL01** [comment]
Are you download the repository from dev or stable branch ?

**Comment by Cyclones92** [comment]
Hmm good question.  Here's the steps I took to get to where I am.

git clone https://github.com/ntop/ntopng.git
cd ntopng
./autogen.sh
./configure
...this is where it complained about nDPI being not installed and it gave me a few instructions on how to install it, so I followed those and then it complained about the issue I mentioned.  I just tried to run ./configure again and here's the new error which is the same as above but let me continue.

checking for nDPI... found in ../nDPI
checking for ../nDPI/src/lib/.libs/libndpi.a... not found ../nDPI/src/lib/.libs/libndpi.a: compiling
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in`.'.
libtoolize: can not copy `/usr/share/libtool/config/ltmain.sh' to`./'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: can not copy`/usr/share/aclocal/libtool.m4' to `m4/'
libtoolize: can not copy`/usr/share/aclocal/ltoptions.m4' to `m4/'
libtoolize: can not copy`/usr/share/aclocal/ltsugar.m4' to `m4/'
libtoolize: can not copy`/usr/share/aclocal/ltversion.m4' to `m4/'
libtoolize: can not copy`/usr/share/aclocal/lt~obsolete.m4' to `m4/'
autoreconf: libtoolize failed with exit status: 1
./autogen.sh: line 33: ./configure: No such file or directory
make: **\* No targets specified and no makefile found.  Stop.

**Comment by kYroL01** [comment]
First of all, be sure you download nDPI from the dev branch (default).
Then, where have you put the nDPI folder ?
You must have a ntopng folder "box" where you put the ntopng and nDPI folders you download from repo.

**Comment by kYroL01** [comment]
@Cyclones92 let me know if you solved.

**Comment by lucaderi** [comment]
I think you have problems with permissions. Like if you have checked out the code with an use and run autogen with another that cannot write into the directory. Please fix this and it will work.

**Comment by Cyclones92** [comment]
I used the following:
git clone https://github.com/ntop/nDPI.git

**Comment by lucaderi** [comment]
We compile daily packages on CentoOS6 and it works for us. It is a permission problem. Please fix it.

**Comment by Cyclones92** [comment]
Okay thank you.  Used it as root user and it works. Sorry for wasting your time.

**Comment by lucaderi** [comment]
Thank you for using our tools.

**Comment by kYroL01** [comment]
@Cyclones92  Remember to star ntopng and nDPI ;)
