### ISSUE TITLE
[Question]The priority of curstom web protocols with category.

### ISSUE THREAD

**Issue by pengtianabc** [ntop/nDPI#1095]
Hi everyone, i got a question about the priority of custom protocol:
1. i try to add a custom url proto in `proto.txt`, the content is `host:"baidu.com"@Baidu`, and i found the `baidu.com` is set to `category_match` in `src\lib\ndpi_content_match.c.inc`
2. run `./ndpiReader  -i ../tests/pcap/pps.pcap -v2`, the result is same as `tests/result/pps.pcap.out`: `proto: HTTP category: Web`, no app_proto baidu in that
3. i want to make it be `proto: HTTP.Baidu, Category: Web`, so i comment `rc = master_protocol_id;` in `ndpi_main.c:ndpi_match_host_subprotocol`, then it works

So, i want to know why overwrite the subproto, what designed for ?

**Comment by lucaderi** [comment]
This is not possible at the moment: nDPI needs to be modified. Please provide a PR for this
