### ISSUE TITLE
[HELP] Missing ipv6 address

### ISSUE THREAD

**Issue by bowenYu** [ntop/nDPI#110]
I use the example program of nDPI ndpiReader to classifiy pcap files offline. There are a lot of ipv6 traffic flow missing src or dest address in the result file of the ndpiReader output. Here's one example:

```
TCP :80 <-> 2404:6800:4005:806::1001:14310 [proto: 7/HTTP][7 pkts/542 bytes]
```

The src address was missing.

I checked the pcap file by using wireshark. The missing one should be 

```
2001:250:401:8308:65b7:ec0f:7b6d:af56
```

Could someone help me about this problem? Thanks.

**Comment by vel21ripn** [comment]
change in ndpiReader.c:171 "typedef struct ndpi_flow"
from  "char lower_name[32], upper_name[32];"
to "char lower_name[48], upper_name[48]; // for ipv6"
