### ISSUE TITLE
Adding a dissector for an encapsulated protocol [Question]

### ISSUE THREAD

**Issue by rafaliusz** [ntop/nDPI#1113]
My goal is to add a dissector for a Profinet-CM protocol that is commonly encapsulated within DCE-RPC (eg. tests/pcap/dcerpc.pcap).
DCE-RPC may theoretically contain a wide variety of protocols so I don't want to explicitly invoke a specific disssector function.

From what I've studied in the codebase there isn't a similar case already developed. TLS is complicatedly handled in ndpi_main.c whereas other protocols that can contain subprotocols invoke are expecting them and invoke their dissectors directly.

My question is: is my understanding correct? Does this case require some additional development or am I missing some key function that can do this work?

**Comment by lucaderi** [comment]
I believe that you should extend the DCE-RPC as this is the "mother protocol". On the other hadn't a completely new protocol for Profinet is also possible. You can choose the best option as the first one seems to be more natural to me
