### ISSUE TITLE
[3.4] Configure fails with CPPFLAGS='-D_FORTIFY_SOURCE=2'

### ISSUE THREAD

**Issue by an0nfunc** [ntop/nDPI#1115]
Building on Archlinux, the created `configure` fails with 

```
checking how to run the C preprocessor... /lib/cpp
configure: error: in `/home/build/.cache/yay/ntopng/src/nDPI-3.4':
configure: error: C preprocessor "/lib/cpp" fails sanity check
```

Builds successfully without `CPPFLAGS='-D_FORTIFY_SOURCE=2'`

Attached is config.log.
[config.log](https://github.com/ntop/nDPI/files/5803260/config.log)

**Comment by utoni** [comment]
Your C pre processor executable is set to the nonexistant path `/lib/cpp`. On (Arch)Linux that is not a standard path for the CPP.

For the default GCC shipped with ArchLinux it should point to `/usr/bin/cpp` or `/usr/bin/gcc -E`.

**Comment by an0nfunc** [comment]
It does detect `/usr/bin/gcc -E` but only without `CPPFLAGS='-D_FORTIFY_SOURCE=2'` being set.

If you check the attached log (config.log:359) you also see why that check for gcc -E fails if D_FORTIFY_SOURCE=2 is set. I just haven't figured out how to fix that.

**Comment by utoni** [comment]
Did you try `CPPFLAGS='-D_FORTIFY_SOURCE=2 -O2'` ?

**Comment by an0nfunc** [comment]
That does fix it, thanks!

I didn't think about that because CFLAGS already contained -O2.

Well at least we can build with FORTIFY_SOURCE again :)

Edit: I still don't understand what changed for this to happen. Arch builds a ton of packages with that default set of flags, why does nDPI's configure fail? Maybe GCC10 drops a warning that has not been there before?

**Comment by grgpw** [comment]
current version builds again without modifications, so I think this can be closed.

**Comment by IvanNardi** [comment]
> current version builds again without modifications, so I think this can be closed.

Thanks for confirming that. Closing the issue
