### ISSUE TITLE
UT failures on i386 and s390x platforms

### ISSUE THREAD

**Issue by nickbroon** [ntop/nDPI#1118]
See the s390x UT failures here:
https://buildd.debian.org/status/fetch.php?pkg=ndpi&arch=s390x&ver=3.4-1&stamp=1608333331&raw=0

and i386 UT failures here:
https://buildd.debian.org/status/fetch.php?pkg=ndpi&arch=i386&ver=3.4-1&stamp=1608333656&raw=0

However the same package is passing just fine on other platforms, amd64, arm64, etc
https://buildd.debian.org/status/package.php?p=ndpi&suite=unstable

**Comment by nickbroon** [comment]
Possiblly related to #1092

**Comment by utoni** [comment]
Probably related to #1312, #1315(?) as well.

**Comment by IvanNardi** [comment]
s390x should be fine now.
No idea about i386, though

**Comment by pjaitken** [comment]
i386 has been working since 3.4-3: https://buildd.debian.org/status/logs.php?pkg=ndpi&arch=i386
