### ISSUE TITLE
use OpenSSL rather than libgcrypt

### ISSUE THREAD

**Issue by pjaitken** [ntop/nDPI#1120]
nDPI requires libgcrypt for QUIC support. Could it use OpenSSL rather than libgcrypt, or be designed to be crypto agnostic?

Going forward, what's to prevent nDPI requiring multiple different crypto libs for different applications?

Our product already uses openSSL for encryption. There's push-back against the extra red-tape we'd encounter by adding another crypto library just for nDPI - so we had to build nDPI without libgcrypt.

Thanks.

**Comment by lucaderi** [comment]
Please provide a pull request  for adding OpenSSL support and we'll evaluate it

**Comment by utoni** [comment]
I think it could be worth replacing gcrypt with openssl. With openssl nDPI could easily check for self-signed certs in a TLS handshake.
