### ISSUE TITLE
nDPI unable to diagnose torrent data

### ISSUE THREAD

**Issue by JeevanNailwal** [ntop/nDPI#113]
During testing the latest nDPI codebase (version 1.7), I figured some discrepancy in the output of this application.

Setup: Laptop with Linux ubuntu 15.04
Software: Skype, ndpiReader (1.7) and transmission bittorrent client
1. In my first test case, I made a SKYPE call to my friend who disconnected it, at his end. the data which I received from ndpiReader is :

Unknown              packets: 27            bytes: 1740          flows: 19
Skype                packets: 1240          bytes: 235396        flows: 161

BUT in my next case, when i ran the ndpiReader application with my transmission client (to download a torrent file of size approx. 900 KB), i got this result from ndpiReader:

Unknown              packets: 1390          bytes: 937365        flows: 171
BitTorrent           packets: 256           bytes: 40966         flows: 75

![ndpireader_issue](https://cloud.githubusercontent.com/assets/15610624/10881557/b9ba7c22-8189-11e5-9d7f-b6d5e6d49187.png)

Please let meknow if you need log file/pcap file for same. I am unable to attach them here.

**Comment by JeevanNailwal** [comment]
During testing the latest nDPI codebase (version 1.7), I figured some discrepancy in the output of this application.

Setup: Laptop with Linux ubuntu 15.04
Software: Skype, ndpiReader (1.7) and transmission bittorrent client

1. In my first test case, I made a SKYPE call to my friend who disconnected it, at his end. the data which I received from ndpiReader is :

Unknown              packets: 27            bytes: 1740          flows: 19
Skype                packets: 1240          bytes: 235396        flows: 161

BUT in my next case, when i ran the ndpiReader application with my transmission client (to download a torrent file of size approx. 900 KB), i got this result from ndpiReader:

Unknown              packets: 1390          bytes: 937365        flows: 171
BitTorrent           packets: 256           bytes: 40966         flows: 75


![ndpireader_issue](https://cloud.githubusercontent.com/assets/15610624/10881410/684707e4-8188-11e5-86fc-923f48201ac1.png)

**Comment by lucaderi** [comment]
Pcap to be used for testing https://drive.google.com/file/d/0B4M_moAIGLMSVElMOXJmNWhBUEE/view?usp=sharing

**Comment by kYroL01** [comment]
@JeevanNailwal any news ?

**Comment by JeevanNailwal** [comment]
Not yet. I was waiting for your response as I am still stuck for torrent
data type.
I tried the nDPI app for skype,xbox.... and other web applications but it
worked fine. Only in the case of torrent, I am got lot and lots of
unidentified protocol packets!!

**Comment by vel21ripn** [comment]
Try checking traffic using "ndpiReader -B 4" of branches vel21ripn/nDPI/tree/netfilter-dev

**Comment by JeevanNailwal** [comment]
Hello Vitali,
Is it the command you are talking or I have to download the branch version
of nDPI?(sorry for this naive question as I am new for this section)

I tried both, command got failed as -B is invalid option and
Branchwise, I am unable to locate the code on web.

jeevan@lap-jeevan:~$ ndpiReader -B 4 -i wlan0
ndpiReader: invalid option -- 'B'
ndpiReader -i <file|device> [-f <filter>][-s <duration>]
          [-p <protos>][-l <loops> [-q][-d][-h][-t][-v <level>]
          [-n <threads>] [-w <file>] [-j <file>]

Please help me out.

**Comment by vel21ripn** [comment]
It means that you are running an old ndpiReader. Try running ndpiReader by specifying a full path to the new version.
In my branch has parser DHT messages that can detect encrypted bittorrent.

**Comment by JeevanNailwal** [comment]
Hi Vitally,
I am using version 1.7 of ndpireader, downloaded from the ndpi site. Can
you please post the link, from where I can get the updated code?

**Comment by JeevanNailwal** [comment]
FYI....
Link from where, i got the source code:
http://sourceforge.net/projects/ntop/files/nDPI/

I landed here, when I clicked on stable version NDPI on ntop's download
page! (http://www.ntop.org/get-started/download/ )

**Comment by kYroL01** [comment]
@JeevanNailwal the -B option is not provided in the official repo of nDPI.
@vel21ripn this is not an old version of nDPI, is the current version. If you do any kind of modifies is your personal thing and you can do, of course, but is not a "new" version.
Open source means collaboration. If you added changes that bring improvements to the nDPI community, please, send us a pull request, because this issue is in our official repo, not in your fork.
This is just for respect to our work. Thank you.

**Comment by kYroL01** [comment]
@JeevanNailwal don't use the stable branch, use the dev one.
I'm sure a bittorrent protocol revision is needed.

**Comment by JeevanNailwal** [comment]
ok... Thanks for the clarification Michele. At least you confirmed that I
am using latest Release version.
Can anyone please confirm if its a genuine issue with this version?

Vitally, If possible, can i get a patch of this problem? It will help me to
move forward.

**Comment by kYroL01** [comment]
It's not properly an issue, I think many packets are not totally recognized and we need to improve the bittorrent dissector.
Can u send the pcap you speak about ?

**Comment by JeevanNailwal** [comment]
Thanks for the help Michele. You can find the pcap file at:
https://drive.google.com/file/d/0B4M_moAIGLMSVElMOXJmNWhBUEE/view?usp=sharing

**Comment by vel21ripn** [comment]
I get file from https://drive.google.com/file/d/0B4M_moAIGLMSVElMOXJmNWhBUEE/view?usp=sharing

Detected protocols:
        Unknown              packets: 239           bytes: 19362         flows: 58  
        DNS                  packets: 94            bytes: 9456          flows: 39  
        HTTP                 packets: 20            bytes: 1368          flows: 3  
        MDNS                 packets: 51            bytes: 20799         flows: 12  
        NetBIOS              packets: 105           bytes: 12673         flows: 23  
        SSDP                 packets: 11            bytes: 3220          flows: 3  
        DHCP                 packets: 7             bytes: 2526          flows: 5  
        BitTorrent           packets: 1945          bytes: 1332561       flows: 81  
        IGMP                 packets: 16            bytes: 728           flows: 12  
        SSL                  packets: 36            bytes: 2986          flows: 4  
        ICMPV6               packets: 22            bytes: 1652          flows: 6  
        DHCPV6               packets: 33            bytes: 5179          flows: 13  
        Twitter              packets: 3             bytes: 290           flows: 1  
        DropBox              packets: 7             bytes: 1227          flows: 4  
        LLMNR                packets: 50            bytes: 3768          flows: 26  
        Quic                 packets: 7             bytes: 608           flows: 2            

Protocol statistics:
        Safe                          4213 bytes
        Acceptable                 1394828 bytes
        Unrated                      19362 bytes

**Comment by JeevanNailwal** [comment]
Thanks for the update Vitaly. Is it from your forked branch/stable version
or dev version?
I am just trying to figure our the problem with my app.

**Comment by JeevanNailwal** [comment]
FYI... I downloaded the dev branch and output with that is :(almost similar
to the one, which i got from STABLE release)

jeevan@lap-jeevan:~/CODE/nDPI/dev/nDPI/example$ ./ndpiReader -i
/home/jeevan/Downloads/torrent_snapshot_1MB.pcapng

---
- NOTE: This is demo app to show _some_ nDPI features.
- In this demo we have implemented only some basic features
- just to show you what you can do with the library. Feel

## \* free to extend it and send us the patches for inclusion

Using nDPI (1.7.1-dev-246-169c837) [1 thread(s)]
Reading packets from pcap file
/home/jeevan/Downloads/torrent_snapshot_1MB.pcapng...
Running thread 0...

WARNING: only IPv4/IPv6 packets are supported in this demo (nDPI supports
both IPv4 and IPv6), all other packets will be discarded

nDPI Memory statistics:
    nDPI Memory (once):      104.60 KB
    Flow Memory (per flow):  1.91 KB
    Actual Memory:           2.46 MB
    Peak Memory:             2.46 MB

Traffic statistics:
    Ethernet bytes:        1481907       (includes ethernet CRC/IFC/trailer)
    Discarded bytes:       22023
    IP packets:            2646          of 3013 packets total
    IP bytes:              1418403       (avg pkt size 470 bytes)
    Unique flows:          292
    TCP Packets:           364
    UDP Packets:           2237
    VLAN Packets:          0
    MPLS Packets:          0
    PPPoE Packets:         0
    Fragmented Packets:    0
    Max Packet size:       1446
    Packet Len < 64:       1413
    Packet Len 64-128:     216
    Packet Len 128-256:    77
    Packet Len 256-1024:   101
    Packet Len 1024-1500:  839
    Packet Len > 1500:     0
    nDPI throughput:       675.86 K pps / 2.82 Gb/sec
    Traffic throughput:    47.85 pps / 209.36 Kb/sec
    Traffic duration:      55.300 sec
    Guessed flow protos:   11

Detected protocols:
    Unknown              packets: 1972          bytes: 1320903       flows:
93
    DNS                  packets: 94            bytes: 9456          flows:
39
    HTTP                 packets: 20            bytes: 1368          flows:
3
    MDNS                 packets: 51            bytes: 20799         flows:
12
    NetBIOS              packets: 105           bytes: 12673         flows:
23
    SSDP                 packets: 11            bytes: 3220          flows:
3
    DHCP                 packets: 7             bytes: 2526          flows:
5
    BitTorrent           packets: 212           bytes: 31020         flows:
46
    IGMP                 packets: 16            bytes: 728           flows:
12
    SSL                  packets: 36            bytes: 2986          flows:
4
    ICMPV6               packets: 22            bytes: 1652          flows:
6
    DHCPV6               packets: 33            bytes: 5179          flows:
13
    Twitter              packets: 3             bytes: 290           flows:
1
    DropBox              packets: 7             bytes: 1227          flows:
4
    LLMNR                packets: 50            bytes: 3768          flows:
26
    Quic                 packets: 7             bytes: 608           flows:
2

Protocol statistics:
    Safe                          4213 bytes
    Acceptable                   93287 bytes
    Unrated                    1320903 bytes
jeevan@lap-jeevan:~/CODE/nDPI/dev/nDPI/example$

**Comment by JeevanNailwal** [comment]
Hi Vitaly,
I am still stuck with dev and stable release branches!! Can I get a patch
file(or set of files) to go through this(to run through my issue)?

**Comment by vel21ripn** [comment]
@JeevanNailwal 
git clone -b netfilter https://github.com/vel21ripn/nDPI.git  && cd nDPI && ./autogen.sh && make

**Comment by vel21ripn** [comment]
@kYroL01 I sent a patch, but it makes a lot of changes and it can't adopt to official tree.
The key differences are described [README](https://github.com/vel21ripn/nDPI/blob/netfilter/ndpi-netfilter/README).

**Comment by kYroL01** [comment]
@vel21ripn Ok thank you for the explanation

**Comment by JeevanNailwal** [comment]
Thanks a lot for the help Vitaly.
