### ISSUE TITLE
ndpiReader.dpdk sometime detect the protocols like wikipedia and sometimes it doesn't

### ISSUE THREAD

**Issue by utkarsh0902311047** [ntop/nDPI#1131]
I am using centos 7. 
I go to directory nDPI/example/build and run the following command
tcpdump -ni enp11s0f1 -s0 -w capture5.pcap -v
In the background in firefox browser facebook, wikipedia, youtube are running.
Then I use ./ndpiReader.dpdk --vdev=net_pcap0,rx_pcap=capture5.pcap
I try to run ndpiReader.dpdk to detect protocols. But sometimes it detects and sometimes it doesn't, even when they are running on firefox.

I have attached pcap files for your reference. In capture3 it doesn't detect Wikipedia but in capture5 it does.    
[capture5.zip](https://github.com/ntop/nDPI/files/5936770/capture5.zip)

[capture3.zip](https://github.com/ntop/nDPI/files/5936769/capture3.zip)

**Comment by lucaderi** [comment]
Please provide more information as requested in the chat

**Comment by utkarsh0902311047** [comment]
Hi,
I have written what commands I am running and also attached the pcap files
as you requested so that you can run them and generate the results.
Sorry but I don't know what else I should provide.
Please tell me in more detail what else I should provide.

Thank you

**Comment by lucaderi** [comment]
This is what nDPI detects of your pcap. Is this what you expect?


Detected protocols:
	Unknown              packets: 23            bytes: 6569          flows: 4            
	HTTP                 packets: 4             bytes: 264           flows: 2            
	MDNS                 packets: 42            bytes: 3822          flows: 9            
	NetBIOS              packets: 6             bytes: 552           flows: 1            
	SSDP                 packets: 5             bytes: 1080          flows: 2            
	TLS                  packets: 329           bytes: 832381        flows: 3            
	Facebook             packets: 18            bytes: 1585          flows: 2            
	YouTube              packets: 4             bytes: 992           flows: 1            
	Google               packets: 15            bytes: 1688          flows: 1            
	LLMNR                packets: 36            bytes: 3060          flows: 32           
	Spotify              packets: 1             bytes: 86            flows: 1            
	Wikipedia            packets: 16            bytes: 1951          flows: 4            


Protocol statistics:
	Safe                        834332 bytes
	Acceptable                    8864 bytes
	Fun                           2577 bytes
	Unrated                       1688 bytes
	Unrated                       6569 bytes

**Comment by utkarsh0902311047** [comment]
Yes, but I have attached two .pcap files. Wikipedia was running in the
background but in one of the pcap file, ndpi doesn't detect protocol for
Wikipedia.
So I want to ask is this correct to happen?

**Comment by lucaderi** [comment]
In your pcap I see wikipedia DNS traffic but I cannot find HTTP/TLS traffic towards it. I have just run a quick test on my PC and everything works

	1	TCP 192.168.2.140:59377 <-> 91.198.174.192:443 [proto: 91.176/TLS.Wikipedia][cat: Web/5][66 pkts/4964 bytes <-> 62 pkts/77829 bytes][Goodput ratio: 12/95][0.27 sec][ALPN: h2;http/1.1][bytes ratio: -0.880 (Download)][IAT c2s/s2c min/avg/max/stddev: 0/0 3/2 37/46 9/8][Pkt Len c2s/s2c min/avg/max/stddev: 54/66 75/1255 302/1506 34/527][TLSv1.2][Client: www.wikipedia.org][JA3C: 3faa4ad39f690c4ef1c3160caa375465][ServerNames: *.wikipedia.org,wikimedia.org,mediawiki.org,wikibooks.org,wikidata.org,wikinews.org,wikiquote.org,wikisource.org,wikiversity.org,wikivoyage.org,wiktionary.org,wikimediafoundation.org,w.wiki,wmfusercontent.org,*.m.wikipedia.org,*.wikimedia.org,*.m.wikimedia.org,*.planet.wikimedia.org,*.mediawiki.org,*.m.mediawiki.org,*.wikibooks.org,*.m.wikibooks.org,*.wikidata.org,*.m.wikidata.org,*.wikinews.org,*.m.wikinews.org,*.wikiquote.org,*.m.wikiquote.org,*.wikisource.org,*.m.wikisource.org,*.wikiversity.org,*.m.wikiversity.org,*.wikivoyage.org,*.m.wikivoyage.org,*.wiktionary.org,*.m.wiktionary.org,*.wikimediafoundation.org,*.wmfusercontent.org,wikipedia.org][JA3S: 91f0cf6e8d64ab365ecc17e1f7372ad2][Issuer: C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert SHA2 High Assurance Server CA][Subject: C=US, ST=California, L=San Francisco, O=Wikimedia Foundation, Inc., CN=*.wikipedia.org][Certificate SHA-1: 0F:7A:F7:71:EF:6D:79:66:02:B3:13:71:05:79:98:BA:02:3C:A6:DF][Validity: 2020-11-09 00:00:00 - 2021-11-16 23:59:59][Cipher: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384][Plen Bins: 3,10,3,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,80,0,0]
	3	TCP 192.168.2.140:59378 <-> 91.198.174.192:80 [proto: 7.176/HTTP.Wikipedia][cat: Web/5][6 pkts/485 bytes <-> 4 pkts/803 bytes][Goodput ratio: 16/66][0.10 sec][Host: wikipedia.org][bytes ratio: -0.247 (Download)][IAT c2s/s2c min/avg/max/stddev: 0/0 21/17 35/34 17/17][Pkt Len c2s/s2c min/avg/max/stddev: 66/66 81/201 143/597 28/229][URL: wikipedia.org/][StatusCode: 301][User-Agent: curl/7.64.1][PLAIN TEXT (GET / HTTP/1.1)][Plen Bins: 0,0,50,0,0,0,0,0,0,0,0,0,0,0,0,0,50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
	6	UDP 192.168.2.140:52160 <-> 199.85.126.20:53 [proto: 5.176/DNS.Wikipedia][cat: Web/5][1 pkts/77 bytes <-> 1 pkts/122 bytes][Goodput ratio: 45/65][0.02 sec][Host: www.wikipedia.org][91.198.174.192][PLAIN TEXT (wikipedia)][Plen Bins: 0,50,50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
