### ISSUE TITLE
Hyperscan with nDPI

### ISSUE THREAD

**Issue by utkarsh0902311047** [ntop/nDPI#1135]
The new version of nDPI doesnt support hyperscan. 
I want to run hyperscan and nDPI together. What can be done to run them together?

**Comment by lucaderi** [comment]
We discontinued hyperscan support as it is available only on Intel and also because for what nDPI needs, Aho-Corasick is enough and faster

**Comment by hongyang7** [comment]
> We discontinued hyperscan support as it is available only on Intel and also because for what nDPI needs, Aho-Corasick is enough and faster

It's a pity that Hyperscan is no longer used. As for performance, could you kindly share how much faster AC is than Hyperscan in your scenario?
