### ISSUE TITLE
Tor protocol not identified

### ISSUE THREAD

**Issue by PaoloCmb** [ntop/nDPI#1141]
Hi
I noticed that Ndpi doesn't identify Tor traffic correctly.
The connection to the TOR node is delayed, but it still completes.
Then, traffic is permitted.
It seems that the traffic gets identified as TLS or Unknown.
Attached you can find a packet capture.
Thanks in advance.

**Comment by PaoloCmb** [comment]
[cap1.zip](https://github.com/ntop/nDPI/files/6049714/cap1.zip)

**Comment by utoni** [comment]
One of the issues here is that nDPI stops it's detection after TLS was detected. Even though TLS can have a subprotocol e.g. TOR.

**Comment by IvanNardi** [comment]
AFAIK nDPI detects TOR traffic only via ip match.
The list in ndpi_content_match.h.inc, based on https://torstatus.rueckgr.at/ip_list_all.php/Tor_ip_list_ALL.csv, is not up to date.
The missing addresses (probably 78.47.41.28 and 51.91.102.127) are present in the list available on internet.
Bottom line: we need to update that list, IMO

**Comment by utoni** [comment]
So maybe we should deprecate/remove protocols/tor.c ? It's detection routine gets never called, unfortunately.
