### ISSUE TITLE
how to create filter to block website

### ISSUE THREAD

**Issue by adrienb4** [ntop/nDPI#115]
Hello

I want to create a filter for analyze a particular website traffic. Could you give me a procedure for add this filter ?

Thank

**Comment by lmangani** [comment]
Hi @adrienb4 

nDPI is a library and not an application. You might want to try ntopng which leverages nDPI.

If you are integrating nDPI, check out the example nDPI Reder code:
https://github.com/ntop/nDPI/blob/dev/example/ndpiReader.c

If you want to create custom mappings without additional code use protos.txt:
https://github.com/ntop/nDPI/blob/dev/example/protos.txt

I hope this helps!

**Comment by adrienb4** [comment]
I use nDPI with Iptables (https://github.com/betolj/ndpi-netfilter).
I want to block a particular website from my lan, but i don't know how add this website.

**Comment by lucaderi** [comment]
@adrienb4 We plan to add this feature on ntopng. Please file an issue request under ntopng.

**Comment by adrienb4** [comment]
@lucaderi I have duplicate my issue for ntop project. However how i can add a filter for nDPI for block a website with iptables mod (as is done with Facebook). Thank
