### ISSUE TITLE
JSON Output removed from ndpiReader?

### ISSUE THREAD

**Issue by badloop** [ntop/nDPI#1152]
Is there a reason that json output was removed from ndpiReader?

**Comment by badloop** [comment]
FWIW, there is still language in the usage text that shows json output it still available.

**Comment by utoni** [comment]
> Is there a reason that json output was removed from ndpiReader?

It was probably not much used and/or tested. Removed with commit 51cfdfb0d80a7bbcc11bc3b95d1696d8dae900c2, commit messages states it was unused.
Remember that ndpiReader is only an example, a tool, not a production-ready feature-complete application.


> FWIW, there is still language in the usage text that shows json output it still available.

`-j` is not used for JSON output anymore, re-used for a loadable JA3 file that contains malicious fingerprints

**Comment by utoni** [comment]
@badloop If you still care about nDPI json output you may have a look at https://github.com/lnslbrty/nDPId
