### ISSUE TITLE
Updating Protocol signatures dynamically

### ISSUE THREAD

**Issue by subhajit-cdot** [ntop/nDPI#1158]
Hi,

Currently protocol dissectors are compiled along with the library and protocols.cfg updation needs an application to restart. We know protocol signatures change frequently. Is there any way or plan to implement a feature where we can update protocol signatures dynamically without changing library or restarting our binary?

Thanks
Subhajit

**Comment by lucaderi** [comment]
This is what app have to implement. In essence load libndpi as shared lib (dlopen) and replace it on the fly. Instead for configuration reload you can keep a shadow copy you swap on the fly
