### ISSUE TITLE
SSH and TELNET dissector should not change guessed_host_protocol_id 

### ISSUE THREAD

**Issue by la10736** [ntop/nDPI#1164]
Both ssh and telnet dissector set `guessed_host_protocol_id` to `NDPI_PROTOCOL_SSH` and `NDPI_PROTOCOL_TELNET`. 

I don't think that they need to do it and maybe that is just an error. In our application we use the `guessed_host_protocol_id` to do some check and these kind _strange assignments_ simple scare us :)

If it's welcome I can submit a PR to remove these assignments.

**Comment by lucaderi** [comment]
Please submit a PR and a pcap where you explain why this fix is important. Thank you
