### ISSUE TITLE
fast.com speedtest detected as TLS.NetFlix (Video)

### ISSUE THREAD

**Issue by simonemainardi** [ntop/nDPI#1171]
Expected behavior is to detect this as speedtest under network category.

To reproduce open https://fast.com and execute a speedtest

**Comment by lucaderi** [comment]
This is fast.com
        1       TCP 192.168.1.178:62478 <-> 23.246.50.137:443 [proto: 91.133/TLS.NetFlix][cat: Video/26][3118 pkts/216735 bytes <-> 7458 pkts/11218704 bytes][Goodput ratio: 1/96][7.39 sec][ALPN: h2;http/1.1][TLS Supported Versions: GREASE;TLSv1.3;TLSv1.2;TLSv1.1;TLSv1][bytes ratio: -0.962 (Download)][IAT c2s/s2c min/avg/max/stddev: 0/0 2/1 105/93 6/4][Pkt Len c2s/s2c min/avg/max/stddev: 54/66 70/1504 743/1506 21/45][TLSv1.3][Client: ipv4-c008-mil001-ix.1.oca.nflxvideo.net][JA3C: 7094b0d5b83dec3f4072bbf49e4b480a][JA3S: f4febc55ea12b31ae17cfb7e614afda8][Cipher: TLS_AES_128_GCM_SHA256][Plen Bins: 0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,96,0,0]
        2       TCP 192.168.1.178:62470 <-> 151.99.109.199:443 [proto: 91.133/TLS.NetFlix][cat: Video/26][4214 pkts/291651 bytes <-> 7185 pkts/10805629 bytes][Goodput ratio: 1/96][7.97 sec][ALPN: h2;http/1.1][TLS Supported Versions: GREASE;TLSv1.3;TLSv1.2;TLSv1.1;TLSv1][bytes ratio: -0.947 (Download)][IAT c2s/s2c min/avg/max/stddev: 0/0 1/1 52/96 5/4][Pkt Len c2s/s2c min/avg/max/stddev: 54/66 69/1504 751/1506 18/49][TLSv1.3][Client: ipv4-c002-psa001-teleit-isp.1.oca.nflxvideo.net][JA3C: 7094b0d5b83dec3f4072bbf49e4b480a][JA3S: f4febc55ea12b31ae17cfb7e614afda8][Cipher: TLS_AES_128_GCM_SHA256][Plen Bins: 0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,97,0,0]

and this is Netflix (video)

	1	TCP 192.168.1.178:62478 <-> 23.246.50.137:443 [proto: 91.133/TLS.NetFlix][cat: Video/26][3118 pkts/216735 bytes <-> 7458 pkts/11218704 bytes][Goodput ratio: 1/96][7.39 sec][ALPN: h2;http/1.1][TLS Supported Versions: GREASE;TLSv1.3;TLSv1.2;TLSv1.1;TLSv1][bytes ratio: -0.962 (Download)][IAT c2s/s2c min/avg/max/stddev: 0/0 2/1 105/93 6/4][Pkt Len c2s/s2c min/avg/max/stddev: 54/66 70/1504 743/1506 21/45][TLSv1.3][Client: ipv4-c008-mil001-ix.1.oca.nflxvideo.net][JA3C: 7094b0d5b83dec3f4072bbf49e4b480a][JA3S: f4febc55ea12b31ae17cfb7e614afda8][Cipher: TLS_AES_128_GCM_SHA256][Plen Bins: 0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,96,0,0]
	2	TCP 192.168.1.178:62470 <-> 151.99.109.199:443 [proto: 91.133/TLS.NetFlix][cat: Video/26][4214 pkts/291651 bytes <-> 7185 pkts/10805629 bytes][Goodput ratio: 1/96][7.97 sec][ALPN: h2;http/1.1][TLS Supported Versions: GREASE;TLSv1.3;TLSv1.2;TLSv1.1;TLSv1][bytes ratio: -0.947 (Download)][IAT c2s/s2c min/avg/max/stddev: 0/0 1/1 52/96 5/4][Pkt Len c2s/s2c min/avg/max/stddev: 54/66 69/1504 751/1506 18/49][TLSv1.3][Client: ipv4-c002-psa001-teleit-isp.1.oca.nflxvideo.net][JA3C: 7094b0d5b83dec3f4072bbf49e4b480a][JA3S: f4febc55ea12b31ae17cfb7e614afda8][Cipher: TLS_AES_128_GCM_SHA256][Plen Bins: 0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,97,0,0]

As you can see they are alike
