### ISSUE TITLE
speedtest detected as plain HTTP

### ISSUE THREAD

**Issue by simonemainardi** [ntop/nDPI#1172]
To reproduce

```
curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python
```

**Comment by lucaderi** [comment]
With your method

	1	TCP 192.168.1.178:63840 <-> 194.36.75.6:8080 [proto: 7/HTTP][cat: Web/5][2172 pkts/146220 bytes <-> 7393 pkts/11128255 bytes][Goodput ratio: 0/96][4.84 sec][Host: srv-st08.arcolink.it][bytes ratio: -0.974 (Download)][IAT c2s/s2c min/avg/max/stddev: 0/0 1/0 49/49 5/3][Pkt Len c2s/s2c min/avg/max/stddev: 54/66 67/1505 366/1506 8/33][URL: srv-st08.arcolink.it:8080/speedtest/random2500x2500.jpg?x=1618946907351.24][StatusCode: 200][Content-Type: image/jpeg][User-Agent: Mozilla/5.0 (Darwin-17.7.0-x86_64-i386-64bit; U; 64bit; en-us) Python/2.7.16 (KHTML, like Gecko) speedtest-cli/2.1.3][Risk: ** Known protocol on non standard port **][PLAIN TEXT (GET /speedtest/random)][Plen Bins: 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100,0,0]
	2	TCP 192.168.1.178:63829 <-> 194.36.75.6:8080 [proto: 7/HTTP][cat: Web/5][2054 pkts/139188 bytes <-> 5497 pkts/8270676 bytes][Goodput ratio: 0/96][5.32 sec][Host: srv-st08.arcolink.it][bytes ratio: -0.967 (Download)][IAT c2s/s2c min/avg/max/stddev: 0/0 2/1 59/59 8/5][Pkt Len c2s/s2c min/avg/max/stddev: 66/66 68/1505 366/1506 8/44][URL: srv-st08.arcolink.it:8080/speedtest/random2000x2000.jpg?x=1618946907351.22][StatusCode: 200][Content-Type: image/jpeg][User-Agent: Mozilla/5.0 (Darwin-17.7.0-x86_64-i386-64bit; U; 64bit; en-us) Python/2.7.16 (KHTML, like Gecko) speedtest-cli/2.1.3][Risk: ** Known protocol on non standard port **][PLAIN TEXT (GET /speedtest/random)][Plen Bins: 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100,0,0]
	3	TCP 192.168.1.178:63828 <-> 194.36.75.6:8080 [proto: 7/HTTP][cat: Web/5][2012 pkts/137676 bytes <-> 5497 pkts/8270676 bytes][Goodput ratio: 0/96][3.89 sec][Host: srv-st08.arcolink.it][bytes ratio: -0.967 (Download)][IAT c2s/s2c min/avg/max/stddev: 0/0 1/1 61/55 7/4][Pkt Len c2s/s2c min/avg/max/stddev: 66/66 68/1505 366/1506 8/44][URL: srv-st08.arcolink.it:8080/speedtest/random2000x2000.jpg?x=1618946907351.21][StatusCode: 200][Content-Type: image/jpeg][User-Agent: Mozilla/5.0 (Darwin-17.7.0-x86_64-i386-64bit; U; 64bit; en-us) Python/2.7.16 (KHTML, like Gecko) speedtest-cli/2.1.3][Risk: ** Known protocol on n

with the "real" speedtest app

	1	TCP 192.168.2.20:51777 <-> 164.132.111.127:8080 [proto: 7.191/HTTP.Ookla][cat: Network/14][1158 pkts/82643 bytes <-> 1525 pkts/2290471 bytes][Goodput ratio: 1/96][15.86 sec][Host: speedtest.odytel.it][bytes ratio: -0.930 (Download)][IAT c2s/s2c min/avg/max/stddev: 0/0 13/9 220/219 27/24][Pkt Len c2s/s2c min/avg/max/stddev: 54/66 71/1502 500/1506 20/71][URL: speedtest.odytel.it:8080/hello?nocache=1869cbde-fc64-4767-a6d5-b56863384b07][StatusCode: 200][Content-Type: text/plain][User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36][Risk: ** Known protocol on non standard port **][PLAIN TEXT (GET /hello)][Plen Bins: 0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,96,0,0]
	2	TCP 192.168.2.20:51775 <-> 164.132.111.127:8080 [proto: 7.191/HTTP.Ookla][cat: Network/14][788 pkts/55607 bytes <-> 1030 pkts/1545001 bytes][Goodput ratio: 2/96][15.72 sec][Host: speedtest.odytel.it][bytes ratio: -0.931 (Download)][IAT c2s/s2c min/avg/max/stddev: 0/0 19/15 217/242 38/36][Pkt Len c2s/s2c min/avg/max/stddev: 54/66 71/1500 500/1506 22/87][URL: speedtest.odytel.it:8080/hello?nocache=666f01c0-7169-449b-afbc-7e594c809a89][StatusCode: 200][User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36][Risk: ** Known protocol on non standard port **][PLAIN TEXT (GET /hello)][Plen Bins: 0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,96,0,0]
	3	TCP 192.168.2.20:51776 <-> 164.132.111.127:8080 [proto: 7.191/HTTP.Ookla][cat: Network/14][606 pkts/43871 bytes <-> 773 pkts/1156583 bytes][Goodput ratio: 2/96][15.72 sec][Host: speedtest.odytel.it][bytes ratio: -0.927 (Download)][IAT c2s/s2c min/avg/max/stddev: 0/0 26/20 227/231 44/42][Pkt Len c2s/s2c min/avg/max/stddev: 54/66 72/1496 500/1506 26/111][URL: speedtest.odytel.it:8080/hello?nocache=c68d538b-4632-4054-b900-2074590ecdd6][StatusCode: 200][User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36][Risk: ** Known protocol on non standard port **][PLAIN TEXT (GET /hello)][Plen Bins: 0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,96,0,0]


I believe nDPi works as expected (and as it should)
