### ISSUE TITLE
Potential (also periodic) build failure regarding NDPI_API_VERSION

### ISSUE THREAD

**Issue by JokerQyou** [ntop/nDPI#1189]
There's a potential pitfall here in the `configure` script which generates various header files ahead of building, see the code here:
https://github.com/ntop/nDPI/blob/c4084ca3c7b3657659aff624158a9c4f5710f57d/configure.seed#L82

If we were to build at `Fri May 28 2021 00:09:38 GMT+0000` (or equivalently pass the timestamp `1622160578` via `SOURCE_DATE_EPOCH`), the result of `echo $SOURCE_DATE_EPOCH | cut -c7-10` would be `0578`, which is considered an invalid octal number because it starts with a 0 but contains a digit that's bigger than 7. This would break the build.

This bug will not be hit by many people, but if you re-build the source once a while, it would come back every 2 hour and 46 minutes (9999 seconds).

**Comment by utoni** [comment]
I think it is a bad idea to use a counter that wraps every 9999s as API version.
IMHO an API version should be incremented with every release.

**Comment by utoni** [comment]
For now this issue should only affect people who configured/built nDPI from a source tree which is not managed by git e.g. with an extracted tarball from `make dist` or downloaded from Github.
