### ISSUE TITLE
Bug in ssl.c

### ISSUE THREAD

**Issue by max197616** [ntop/nDPI#119]
Hi.
I think that there is a bug in the file ssl.c at line 291:
if(!packet->iph /\* IPv4 */) return(-1);
If we are using ipv6 packet we always get undetected protocol. I commented this line and nDPI can detect ssl properly.

**Comment by lucaderi** [comment]
@max197616 Can you please send a pcap file to reproduce the problem?

**Comment by kYroL01** [comment]
@max197616 If you comment out, nDPI can properly detected SSL with IPv6 ?
Maybe that control into the dissector must be deleted, 'cause we check for IPv6 before enter in the dissector.

**Comment by max197616** [comment]
Yes, if I commented out described line, nDPI can properly detect SSL in the ipv6 packets.
I attached the dump (rename the extention from .png to .pcap).
![ipv6](https://cloud.githubusercontent.com/assets/14889541/11331509/22f22868-91cd-11e5-8d7f-302156cbb3b3.png)

**Comment by kYroL01** [comment]
I think it's easy to solve as i said before. Now i cant. Later I'll do.
