### ISSUE TITLE
Question about using ndpi_lru_cache

### ISSUE THREAD

**Issue by vel21ripn** [ntop/nDPI#1206]
Hello! 
Has anyone looked into the efficiency of using ndpi_lru_cache?
I recorded approximately 150 gigabytes of traffic and analyzed it using a modified ndpiReader.
Here is the result:
```
lru_free_cache stun request:432382 ok:18058 miss:414324 coll:154418 add:1716 add_coll:1342 add_diff:0 used:374/1024
lru_free_cache tls_cert request:166605 ok:0 miss:166605 coll:2493 add:1 add_coll:0 add_diff:0 used:1/1024
lru_free_cache mining request:141194 ok:6 miss:141188 coll:3382 add:1217 add_coll:7 add_diff:0 used:11/1024
lru_free_cache msteams request:2100 ok:284 miss:1816 coll:1726 add:351 add_coll:18 add_diff:114 used:4/1024

request - number of ndpi_lru_find_cache calls
  ok - key in cache
  miss - no key in cache
  coll - cell is used with a another key
add - number of cache writes
  add_coll - number of cell rewrites with a different key
  add_diff - number of cell rewrites with a different value
used - used cells
```

The worst situation is with the __stuns__ cache. Too many collisions when adding data. The cache is not efficient. Can use libcache?
The __mining__ cache is also ineffective. A total of 6 successful requests out of 142,000. 1200 rewrites to 11 cells.
In the __msteams__ cache, we need to change the algorithm for calculating the key.
Other traffic needs to be collected to determine the effectiveness of the "tls_cert" cache. For the test file simple-dnscrypt.pcap, the result is not happy.
```
tls_cert request:6 ok:0 miss:6 coll:1 add:4 add_coll:1 add_diff:0 used:3/1024
```

The libcache library has implementation oddities too.
The hash size and the limit on the number of elements are specified by one parameter. Ideally, we will get N lists of one element, and in the worst case, there will be 1 list with N elements.
In https://github.com/vel21ripn/nDPI , I rewrote the libcache implementation. If there are no complaints about the code, then I can do a PR.

**Comment by lucaderi** [comment]
I am willing to merge your PR as I know the limitations of the current implementation and I agree with you it's time to address them. Thanks
