### ISSUE TITLE
Application protocol detection question

### ISSUE THREAD

**Issue by vel21ripn** [ntop/nDPI#1207]
Hi!
Developers response required.
After updating the ahocorasick library, it became possible to compare strings more "completely".
The old version did not check all possible string matches.
As a result, IMHO several obvious errors were identified. 

We see in the __tests/result/selfsigned.pcap.out__ file
```
1 [proto: 91/TLS][cat: Web/5] [Issuer: C=IT, ST=Some-State, O=ntop.org]
```

IMHO must be
```
1 [proto: 91.26/TLS.ntop][cat: Network/14] [Issuer: C=IT, ST=Some-State, O=ntop.org]
```

I think the lack of 'ntop' is a bug.
The difference in the traffic category is most likely a consequence of the detected 'ntop'.

We see in the __tests/result/teams.pcap.out__ file
```
72 [proto: 5/DNS][cat: Network/14] [Host: c-flightproxy-euno-01-teams.cloudapp.net]
```

IMHO must be
```
72 [proto: 5.250/DNS.Teams][cat: Collaborative/15] [Host: c-flightproxy-euno-01-teams.cloudapp.net]
```

We see in the __tests/result/alexa-app.pcapng.out__ file
```
125 [proto: 5/DNS][cat: Network/14] [Host: images-na.ssl-images-amazon.com]
```

IMHO must be
```
125 [proto: 5.178/DNS.Amazon][cat: Web/5] [Host: images-na.ssl-images-amazon.com]
```

**Comment by vel21ripn** [comment]
The question about tests/result/selfsigned.pcap remains relevant.

**Comment by lucaderi** [comment]
@vel21ripn Sorry for the late reply and thanks for your contributions. Can you please check if the above fix is addressing your concerns?

**Comment by vel21ripn** [comment]
Excellent! Thanks for fixing this error.
I have another, easier way.
I am currently testing another PR related to the use of the ahocorasick library.
Now I can make a PR that will successfully pass all test cases.
I closed issue https://github.com/ntop/nDPI/issues/1213.
