### ISSUE TITLE
ndpi_match_string_subprotocol() compares strings very strangely

### ISSUE THREAD

**Issue by vel21ripn** [ntop/nDPI#1208]
Hi!
Need help. Very strange behavior of ac_match_handler().
ac_match_handler() thinks that the string "images-na.ssl-images-amazon.com$" does not match the pattern "images-amazon.com$".
Why?

The problem is in the pcap/alexa-app.pcapng file.
```
1 TCP 172.16.42.216:41913 <-> 52.84.62.115:443 
[proto: 91.240/TLS.AmazonVideo][cat: Video/26]
[Client: images-na.ssl-images-amazon.com]
[ServerNames: images-na.ssl-images-amazon.com,images-eu.ssl-images-amazon.com,images-fe.ssl-images-amazon.com,m.media-amazon.com]
[Issuer: C=US, O=Symantec Corporation, OU=Symantec Trust Network, CN=Symantec Class 3 Secure Server CA - G4][Subject: C=US, ST=Washington, L=Seattle, O=Amazon.com, Inc., CN=Images-na.ssl-images-amazon.com]
```
The client requests the name "images-na.ssl-images-amazon.com".
It is comparable to "images-amazon.com$" (Amazon).
But instead we get a match for ".media-amazon.com$" (AmazonVideo) from ServerNames.
May be __[proto: 91.178/TLS.Amazon][cat: Web/5]__ is more correctly?

There is a similar problem in the "pcap/whatsapp_login_call.pcap"  file.
The string "p53-buy.itunes.apple.com$" does not contain the string "buy.itunes.apple.com$"
```
3 TCP 192.168.2.4:49204 <-> 17.173.66.102:443
[proto: 91.140/TLS.Apple][cat: Web/5]
[Client: p53-buy.itunes.apple.com]
```
IMHO more correct result is __[proto: 91.224/TLS.AppleStore][cat: SoftwareUpdate/19]__

**Comment by IvanNardi** [comment]
> Hi!
> Need help. Very strange behavior of ac_match_handler().
> ac_match_handler() thinks that the string "images-na.ssl-images-amazon.com$" does not match the pattern "images-amazon.com$".
> Why?

Because "ssl-images-amazon.com" and "images-amazon.com" are two **very** different domains. Think of "google.com" vs "fake-google.com"....
Only things like "images-amazon.com", "xxx.images-amazon.com", "yyy.zzz.images-amazon.com" should match "images-amazon.com" pattern, IMO.

Am i missing something obvious here?

**Comment by vel21ripn** [comment]
Thank you for responding!
I want to understand how to interpret strings in host_match.
If the pattern does not end with "." , then the comparison occurs at the end of the line. It's clear.
If the pattern does not start with a period, then it is a domain match.
That is, the pattern string "amazon.com" is a regular expression ^(.+\.)?amazon\.com$  ?
If the pattern starts with "-" is it part of the domain name?
If the template starts with ".", Then it is only a subdomain?
Did I understand correctly?

We have
```
 { "..msn-com.",      "Microsoft", 
 { ".-s-msn-com.",   "Microsoft",
 { "*.gateway.messenger.live.com",  "Skype_Teams",
```
What does it mean?

The ac_match_handler() function is not well written.
Why copy a string, and then search for an occurrence of a substring in it via strstr()?
The position of the found template comes to the handler. Knowing it and the length of the pattern, we know in which part of the string the pattern is found.
ac_match_handler() function ignores all templates except the first one. This is weird too.

Issue https://github.com/ntop/nDPI/issues/1207 still has questions on the first two points

**Comment by vel21ripn** [comment]
Issue #1207 still has questions only first point.

**Comment by subhajit-cdot** [comment]
[NDPI] Internal error: please call ndpi_finalize_initalization()

Getting the above error repeatedly in ndpi 3.4 stable , coming from ndpi_match_string_subprotocol().  I was sending a mix traffic having multiple type of applications/urls. Any clue ? @vel21ripn @IvanNardi @lnslbrty

**Comment by vel21ripn** [comment]
This means that ac_automata_finalize() has not been executed for host_automa and/or content_automa.
You need to call ndpi_finalize_initialization() before receiving the first packet.

**Comment by subhajit-cdot** [comment]
This is by default behavior, this is called during initialization with ndpi_finalize_initalization() where host_automa, content_automa, bigram_automa finalized. I am not sure in which we will get   automa not finalized. Moreover, see the below code block  of bigram_match in ndpi-3.4 stable where ac_automata_finalize() is again called if not finalized, should I put a similar code block like this in sub-protocol match?

`int ndpi_match_bigram(struct ndpi_detection_module_struct *ndpi_str,
                      ndpi_automa *automa, char *bigram_to_match) {`
  `AC_TEXT_t ac_input_text;`
`  AC_REP_t match = {NDPI_PROTOCOL_UNKNOWN, NDPI_PROTOCOL_CATEGORY_UNSPECIFIED,` `NDPI_PROTOCOL_UNRATED};`
`  int rc;`

 ` if((automa->ac_automa == NULL) || (bigram_to_match == NULL))`
 `   return(-1);`
`  if(!automa->ac_automa_finalized) {`
`#if 1`
   ` ndpi_finalize_initalization(ndpi_str);`
`#else`
  `  printf("[%s:%d] [NDPI] Internal error: please call ndpi_finalize_initalization()\n", __FILE__, __LINE__);`
  `  return(0); /* No matches */`
`#endif`
 `}`

**Comment by vel21ripn** [comment]
If the call to ndpi_match_bigram() occurs before the call to ndpi_match_string_subprotocol(), then there will be no error.
The order in which these functions are called is traffic dependent, that is, this is undefined behavior.
Calling ndpi_finalize_initalization() from ndpi_match_bigram() is a workaround.
Lack of finalization is a serious bug that should be detected as early as possible.
IMHO printf("[NDPI] Internal error: please call ndpi_finalize_initalization()\n") is a better solution than silently calling ndpi_finalize_initalization().

**Comment by subhajit-cdot** [comment]
@vel21ripn How to handle such undefined behavior as the function will invoke in ndpi depending upon the traffic. Is the work around in  ndpi_match_bigram() required if the app using ndpi calls ndpi_finalize_initalization() after basic ndpi initialization and loading of proto and category files (as shown in the ndpiReader)?

**Comment by vel21ripn** [comment]
ndpi_finalize_initalization() after the basic initialization of NDPI and loading proto and category files, solves all problems with the finalization of the AC_AUTOMATA_t structures.
