### ISSUE TITLE
nDPI operation on cropped packets

### ISSUE THREAD

**Issue by pavel-odintsov** [ntop/nDPI#121]
Hello, folks!

I'm trying to emerge sflow with sampled packet headers and nDPI.

And I stuck here. I need some help..

So you have function:

``` bash
ndpi_detection_process_packet(my_ndpi_struct, flow, iph, ipsize, current_tickt, src, dst)
```

We have ipsize param only here. But for sampled data we haven't single packet size. We have captured_lenght (120 bytes in my case) and full_length (1500 bytes in my case).

How I should use nDPI for sampled data?

**Comment by pavel-odintsov** [comment]
And detection algorithm works really bad. 

For 4000 packets I get following:

``` bash
unknown_unknown 3793 packets
quic_unknown 67 packets
skype_unknown 34 packets
dns_unknown 20 packets
```

For full packets I get about 90% of correctly detected packets!

**Comment by kYroL01** [comment]
Can you provide the interested pcap file ?

**Comment by pavel-odintsov** [comment]
It's bit complicated because there are bunch of personal data here ... :(

**Comment by kYroL01** [comment]
Well, it's bit complicated understand the problem too for me in this way.
I tried to pass to nDPI another pcap with many sflow packets and the program detect the sflow protocol correctly.
Actually I really don't care about your personal data, but if you don't want, send me just few packets with both lengths.

**Comment by pavel-odintsov** [comment]
I will try to isolate problem with some sample data. Thanks for help!

**Comment by kYroL01** [comment]
As you prefer, of course.
It's a strange behaviour btw, but I don't think is a sflow dissector problem in nDPI.
Just to understand, how is it possibile that your packets are full or "truncated" ? Maybe your captured packets are corrupted in some way.

I close the issue. If you find a way to send us a new pcap without "personal" data or you found other issues, re-open.
Thanks

**Comment by pavel-odintsov** [comment]
Packets are truncated because sflow uses packet cropping and sampling. I'm getting only first 110 bytes of each packet from the wire.

**Comment by kYroL01** [comment]
You are right, but it's strange that none of the sflow packets are detected.
I mean, it provides for exporting truncated packets, so, is it possibile that the sampling is too short ?
If you look at sflow dissector, it accept packet with udp payload len >= 24 byte.

It's just an hypothesis.

**Comment by pavel-odintsov** [comment]
Hello!

Yes songs interesting. It could be an root of issue. I will share my nDPI binary output soon.
