### ISSUE TITLE
SYN flood attack mitigation strategy for an app using ndpi

### ISSUE THREAD

**Issue by subhajit-cdot** [ntop/nDPI#1211]
Hi,
I have gone through the thread #139 , where you suggested that the app using ndpi can skip SYN packet send to ndpi. 
" if you see a SYN you do not need to allocate nDPI memory but just when the first payload packets hits your app."

I have few doubts regarding the handling of SYN packets in the app which uses ndpi.

In the ndpi source I can see the below snippet describing that a protocol identification of a tcp flow may go wrong if SYN packet is not seen. Also, the app using ndpi can cause memory or session table overflow  if we send/handle all tcp connection (including enbryonic connections). To mitigate this kind of attack people suggest to use syn proxy, syn cache syn cookies and syn authentication. You also wrote  ([http://luca.ntop.org/CommoditisingDDoSMitigation.pdf](url)) that "For  SYN  flood  attacks,  two  mitigation  methods  have  been implemented  and  compared:  SYN  Cookie  and  SYN  Sanity Check.  Contrary  to  the  SYN  Sanity  Check  that  does  not challenge  traffic,  the  SYN  Cookie  method  needs  to  inject  at least  one  packet  back  for  every  processed  SYN  in  order  to validate  clients. "  I am keeping syn proxy aside because this is a different solution altogether but here I want to know how can SYN sanity check (assuming it similar to syn authentication) detect ip spoofing or similar ddos attacks? What would you suggest for handling SYN flood type of dos/ddos attack in an app using ndpi?

` if((flow->num_processed_pkts == 1) && (ret.master_protocol == NDPI_PROTOCOL_UNKNOWN) &&
     (ret.app_protocol == NDPI_PROTOCOL_UNKNOWN) && flow->packet.tcp && (flow->packet.tcp->syn == 0) &&
     (flow->guessed_protocol_id == 0)) {
    u_int8_t protocol_was_guessed;
`
`    /*`
`      This is a TCP flow`
`      - whose first packet is NOT a SYN`
`      - no protocol has been detected`
 `     We don't see how future packets can match anything`
`      hence we giveup here`
`    */`
 `   ret = ndpi_detection_giveup(ndpi_str, flow, 0, &protocol_was_guessed);`
`  }`

@lucaderi  please comment!

Thanks

**Comment by utoni** [comment]
I agree with @lucaderi in #139. Ignoring SYN packets should be part of your integration and not of nDPI.

If you want to save memory, just don't allocate any flow memory when a SYN packet arrives (and do not call `ndpi_detection_process_packet`).
I think the only drawback might be that you may guess less flows.. But IMHO flow guessing is obsolete anyway especially for your SYN flood use case.

**Comment by subhajit-cdot** [comment]
@lnslbrty I didn't understand why you mentioned "flow guessing is obsolete anyway especially for your SYN flood use case." Why flow guessing is obsolete? If dissector fails to detect we only rely on guessing protocol before giving up the detection. SYN flood use case is different, I wanted to know if we don't send SYN packet to ndpi, will that impact on any protocol detection ? Moreover is there any protocol which needs full connection tracking of TCP packets for it's detection.

**Comment by utoni** [comment]
I need to add to my previous statement: Ignoring TCP-SYN packets may also negatively affect asymmetric detection. But I'm not really sure if that is supported by nDPI.


> I wanted to know if we don't send SYN packet to ndpi, will that impact on any protocol detection ?


For the protocol detection at it's current state: ~~probably not~~ see @aouinizied comment. But if someone implements a protocol in the future that requires to distinguish between client<->server e.g. for direction based pattern matching, then the SYN/ACK/SYN-ACK packets might be coming handy.

**Comment by utoni** [comment]
> @lnslbrty I didn't understand why you mentioned "flow guessing is obsolete anyway especially for your SYN flood use case." Why flow guessing is obsolete? If dissector fails to detect we only rely on guessing protocol before giving up the detection.

I'm not a fan of "guessing". You will definitely get false-positives e.g. when using non standard ports or processing midstream traffic.
I mean, "guessing" is basicially a simple layer3 ip and layer4 port matching algorithm. I would call that *Packet Inspection* but not *Deep Packet Inspection*.

**Comment by aouinizied** [comment]
@subhajit-cdot protocols that may be affected by not passing the syn to nDPI are protocols that have the handshake establishment check in their dissection logic: [**lotus_notes**][lotus], [**citrix**][citrix], [**skype**][skype],  [**ftp_data**][ftp_data] and  [**ftp**][ftp] so far.
You can verify this by looking for **seen_syn** in nDPI source code.

[lotus]: https://github.com/ntop/nDPI/blob/a1dba74346ce8563cf49172d88cfd21ee0938e93/src/lib/protocols/lotus_notes.c#L42
[citrix]: https://github.com/ntop/nDPI/blob/a1dba74346ce8563cf49172d88cfd21ee0938e93/src/lib/protocols/citrix.c#L43
[skype]: https://github.com/ntop/nDPI/blob/8761ac1887c9190a8f5bf4f1439f1316a5df22a2/src/lib/protocols/skype.c#L143
[ftp_data]: https://github.com/ntop/nDPI/blob/a1dba74346ce8563cf49172d88cfd21ee0938e93/src/lib/protocols/ftp_data.c#L235
[ftp]: https://github.com/ntop/nDPI/blob/a1dba74346ce8563cf49172d88cfd21ee0938e93/src/lib/protocols/attic/ftp.c#L167

**Comment by subhajit-cdot** [comment]
@aouinizied That means we can't avoid sending syn packets to ndpi if we need to support the above mentioned protocols (having seen_syn flag). Now I am confused with the @lucaderi's  statement " if you see a SYN you do not need to allocate nDPI memory but just when the first payload packets hits your app." or is there any other way to skip SYN packets tactfully so that the app using nDPI can protect itself from SYN flood type of attack? Although I know it should be taken care before hand using any SYN flood screener and may not be in scope of the app using nDPI.

**Comment by utoni** [comment]
Not sure if this works, but a workaround could be that you cache the 3-way-handshake (caching the SYN packet may be enough) until some layer4 payload arrives.
If that happens, you allocate dynamic memory for nDPI structs and process the handshake packets and the payload packets.
That way you should be able to save a lot of memory.

Another way to save memory is the compression of nDPI data structures such as `ndpi_flow_struct` and both `ndpi_id_struct`'s. I'm currently testing zLib deflate for devices with limited RAM using my nDPI integration: https://github.com/lnslbrty/nDPId
I'm currently observing 1/3 to 1/2 less memory usage (at the cost of some CPU performance, but that is not the bottleneck for me).

**Comment by aouinizied** [comment]
Didn't test the compression way as memory is not the bottleneck in my use cases. But the first option proposed by @lnslbrty is IMHO the solution.

* Your app is maintaining a flow cache which handle the expiration (timeouts etc).
* At TCP flow creation, you do not allocate nDPI structures.
* At TCP flow update, you check 3 packets directions and flag and once you get a packet with payload you allocates nDPI structures.

This will address memory consumption on nDPI side. But depending on your app flow struct (the one contaiing nDPI references) you app can consume memory for each alocated struct in the cache.

**Comment by subhajit-cdot** [comment]
So, what I understand is to implement kind of syn proxy or syn cookies in the app , once we see the 3 way handshake along with a payload, we need to process all the 3 cached packets to along with the payload packet it to ndpi. @aouinizied I hope that's what you meant in your 3 rd point.
@lnslbrty I am not sure if compression of nDPI structure could save syn attack, but these changes are really useful in keeping more flows in the same amount of RAM. Currently nDPI structure alone takes around 4-5KB (?) of size I think even after freeing ndpi_id_struct once detection is completed.

**Comment by aouinizied** [comment]
@subhajit-cdot No, you do not cache the 3 handshake packets. You allocate with the first packet containing payload after the handshake and you accept that some dissectors may be affected (I believe it will have a little impact regarding the entire detection process).

Zied

**Comment by subhajit-cdot** [comment]
Ok, thanks @aouinizied . You meant the protocol you mentioned above in this thread (lotus_notes, citrix, skype, ftp_data and ftp) which requires tcp syn , might not be affected even if we are not sending tcp syn (?)

**Comment by utoni** [comment]
related to #793

**Comment by IvanNardi** [comment]
Since e6b332aa4a1399e33df68998cf8351bccaee3fc4, you can safely implements https://github.com/ntop/nDPI/issues/1211#issuecomment-870462974: the application can avoid to pass TCP handshake packets to the library, without losing any classification capabilities (via `struct ndpi_flow_input_info->seen_flow_beginning`)
