### ISSUE TITLE
Problem about TLS certificate processing

### ISSUE THREAD

**Issue by dogfar** [ntop/nDPI#1212]
Hi, I find that many servers send their CA in ServerHello instead of sending a separate packet. Here is what Wireshark says:

![533a164d6d10627365c5766670aed9a](https://user-images.githubusercontent.com/37035781/122635649-c38a3600-d117-11eb-8323-f942580d3bfd.png)

Does nDPI deal with this situation? I'm not very familiar with TLS and nDPI, but I read the code in tls.c and I think this code believes that ServerHello and Server CA are always sent in 2 different packets. If nDPI can handle this, how can I get the extracted  certificate information? 
Thanks!

**Comment by IvanNardi** [comment]
> Hi, I find that many servers send their CA in ServerHello instead of sending a separate packet.

If with "CA" you mean the certificates, I think there is a confusion between "TLS messages" (SH, Certificate, ...) and "TCP packet".
Certificates are sent  in the "Certificate" message, which is a different message from "ServerHello" one.
Because of it size, certificate message is often split  into multiple TCP packets so it is common to find its first fragment in the same TCP packet with the ServerHello; nDPI correctly handle this case.

Please note that nDPI (and Wireshark...) needs the entire Certificate message (i.e. all the TCP packets containing it) to properly dissect it.

Do you have any pcaps where nDPI is not able to extract certificate information?

**Comment by dogfar** [comment]
Thanks for your explanation! This is part of the pcap file and I don't know why nDPI can't get the issuerDN or subjectDN in some TLS flows, whose src and dst IP are 192.168.137.139 and 103.72.47.249. In these flows I can see the certificate message in the same packet with ServerHello, but in my understanding a certificate message means that there is a certificate, and a certificate has to contain its issuer or subject. 

This file is about 5Mb after unzip and was collected from a Chinese mobile Application. Thanks a lot!
[out.zip](https://github.com/ntop/nDPI/files/6680491/out.zip)

**Comment by IvanNardi** [comment]
I quickly looked at the trace, and I have found only 2 TLS sessions between those 2 IPs with certificates
```
	1	TCP 192.168.137.139:41368 <-> 103.72.47.249:443 [proto: 91/TLS][cat: Web/5][11 pkts/2419 bytes <-> 10 pkts/6971 bytes][Goodput ratio: 70/90][3.28 sec][ALPN: h2;http/1.1][TLS Supported Versions: TLSv1.3;TLSv1.2][bytes ratio: -0.485 (Download)][IAT c2s/s2c min/avg/max/stddev: 0/0 394/396 3042/3095 1001/1020][Pkt Len c2s/s2c min/avg/max/stddev: 66/66 220/697 602/1494 227/578][TLSv1.2][Client: dict.youdao.com][JA3C: f79b6bad2ad0641e1921aef10262856b][ServerNames: *.youdao.com,youdao.com][JA3S: a39e18564e32e1822751c4af0bfba817][Issuer: C=US, O=DigiCert Inc, OU=www.digicert.com, CN=GeoTrust CN RSA CA G1][Subject: C=CN, OU=IT Dept, CN=*.youdao.com][Certificate SHA-1: D7:04:22:90:5A:46:89:3F:DD:22:49:AA:04:DD:CA:21:2B:2C:CF:E1][Safari][Validity: 2020-08-12 00:00:00 - 2022-10-28 12:00:00][Cipher: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384][Plen Bins: 0,0,0,9,0,0,0,0,9,0,9,0,0,0,0,9,18,0,0,0,9,0,0,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,27,0,0,0]
	3	TCP 192.168.137.139:41398 <-> 103.72.47.249:443 [proto: 91/TLS][cat: Web/5][12 pkts/1768 bytes <-> 9 pkts/4804 bytes][Goodput ratio: 55/87][0.99 sec][ALPN: http/1.1][TLS Supported Versions: TLSv1.3;TLSv1.2;TLSv1.1;TLSv1][bytes ratio: -0.462 (Download)][IAT c2s/s2c min/avg/max/stddev: 0/0 109/5 878/16 272/6][Pkt Len c2s/s2c min/avg/max/stddev: 66/66 147/534 583/1494 156/557][TLSv1.2][Client: dict.youdao.com][JA3C: 9b02ebd3a43b62d825e1ac605b621dc8][ServerNames: *.youdao.com,youdao.com][JA3S: a39e18564e32e1822751c4af0bfba817][Issuer: C=US, O=DigiCert Inc, OU=www.digicert.com, CN=GeoTrust CN RSA CA G1][Subject: C=CN, OU=IT Dept, CN=*.youdao.com][Certificate SHA-1: D7:04:22:90:5A:46:89:3F:DD:22:49:AA:04:DD:CA:21:2B:2C:CF:E1][Safari][Validity: 2020-08-12 00:00:00 - 2022-10-28 12:00:00][Cipher: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384][Plen Bins: 11,0,0,11,0,0,0,0,11,11,0,0,0,11,0,0,11,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22,0,0,0]
```

In both cases, some pieces of information about the Issuer and Subject are reported.

Are you looking at some specific data (which?) in some specific flow (which?)?

**Comment by dogfar** [comment]
Yes...it tells me that there are 6 sessions, and only those 2 have certificates. I'm a little confused... I try to printf("%s", the flow->ssh_tls.tls_issuerDN) and  printf("%s", the flow->ssh_tls.tls_subjectDN)  which got '(null)'.

192.168.137.139:41368 -- 103.72.47.249:443   || 11 pkts / 10 pkts || '(null)' / '(null)'
192.168.137.139:41398 -- 103.72.47.249:443   || 12 pkts / 9 pkts || '(null)' / '(null)'

I am using the version whose commit ID is aa5486f5f8815cc4405b1be7d31ef923b51ab3fc. This file is ndpiReader.c in example/, and I add this printf here, in the node_getdbinfo_walker. In this function, imitating the ndpi_proto_guess_walker and port_stats_walker, each time I meet a new  node, I print flow->ssl_tls.tls_issuerDN (or flow->ssl_tls.subjectDN). 

![20210619204830](https://user-images.githubusercontent.com/37035781/122643149-c9484180-d140-11eb-87cd-4936ea9393aa.png)

What could be the problem ?

**Comment by dogfar** [comment]
Yes...it tells me that there are 6 sessions, and only those 2 have certificates. I'm a little confused... I try to printf("%s", the flow->ssh_tls.tls_issuerDN) and  printf("%s", the flow->ssh_tls.tls_subjectDN)  which got '(null)'.

192.168.137.139:41368 -- 103.72.47.249:443   || 11 pkts / 10 pkts || '(null)' / '(null)'
192.168.137.139:41398 -- 103.72.47.249:443   || 12 pkts / 9 pkts || '(null)' / '(null)'

I am using the version whose commit ID is aa5486f5f8815cc4405b1be7d31ef923b51ab3fc. This file is ndpiReader.c in example/, and I add this printf here, in the node_getdbinfo_walker. In this function, imitating the ndpi_proto_guess_walker and port_stats_walker, each time I meet a new  node, I print flow->ssl_tls.tls_issuerDN (or flow->ssl_tls.subjectDN). 

![20210619204830](https://user-images.githubusercontent.com/37035781/122643149-c9484180-d140-11eb-87cd-4936ea9393aa.png)

What could be the problem ?

**Comment by IvanNardi** [comment]
First of all, I strongly suggest to move to latest nDPI code (you are using a 6 months old version)

nDPI doesn't report any certificate information for the other 4 TLS sessions because... there is no certificate in those flows!
(Certificates are not always present in the TLS handshake).
You can verify that with wireshark
![Screenshot from 2021-06-19 16-12-06](https://user-images.githubusercontent.com/12729895/122645135-1f08f380-d119-11eb-842c-d9904ecb53c2.png)

**Comment by dogfar** [comment]
Yes...but I mean the 2 flows that should report the issuerDN or SubjectDN give the result '(null)'. Other flows give an empty string. 
I didn't explain it clearly and I apologized for this.

**Comment by IvanNardi** [comment]
Sorry, I misunderstood your question.
There are probably some issues in your code. As reference, with the attached patch and using a filtered pcap, I easily got what you are looking for:
```
ivan@ivan-Latitude-E6540:~/svnrepos/nDPI(quic-frags)$ ./example/ndpiReader -t -i ~/out1.pcapng -v2

-----------------------------------------------------------
* NOTE: This is demo app to show *some* nDPI features.
* In this demo we have implemented only some basic features
* just to show you what you can do with the library. Feel 
* free to extend it and send us the patches for inclusion
------------------------------------------------------------

Using nDPI (3.5.0-3140-380286c0) [1 thread(s)]
Using libgcrypt version 1.8.5
Reading packets from pcap file /home/ivan/out1.pcapng...
Running thread 0...
START CUSTOM PRINT FLOW
192.168.137.139:41368 <-> 103.72.47.249:443 [Issuer: C=US, O=DigiCert Inc, OU=www.digicert.com, CN=GeoTrust CN RSA CA G1][Subject: C=CN, OU=IT Dept, CN=*.youdao.com]
192.168.137.139:41398 <-> 103.72.47.249:443 [Issuer: C=US, O=DigiCert Inc, OU=www.digicert.com, CN=GeoTrust CN RSA CA G1][Subject: C=CN, OU=IT Dept, CN=*.youdao.com]
192.168.137.139:41464 <-> 103.72.47.249:443 
192.168.137.139:41466 <-> 103.72.47.249:443 
192.168.137.139:41472 <-> 103.72.47.249:443 
192.168.137.139:41474 <-> 103.72.47.249:443 
192.168.137.139:43846 <-> 103.72.47.249:80 
192.168.137.139:43848 <-> 103.72.47.249:80 
192.168.137.139:43858 <-> 103.72.47.249:80 
192.168.137.139:43870 <-> 103.72.47.249:80 
192.168.137.139:43872 <-> 103.72.47.249:80 
192.168.137.139:43876 <-> 103.72.47.249:80 
192.168.137.139:43914 <-> 103.72.47.249:80 
192.168.137.139:43916 <-> 103.72.47.249:80 
192.168.137.139:43918 <-> 103.72.47.249:80 
192.168.137.139:43926 <-> 103.72.47.249:80 
192.168.137.139:43936 <-> 103.72.47.249:80 
END CUSTOM PRINT FLOW

nDPI Memory statistics:
...
```
[diff.patch.txt](https://github.com/ntop/nDPI/files/6680919/diff.patch.txt)

**Comment by dogfar** [comment]
You are right, I think I found the problem in my code. Thank you so much!
