### ISSUE TITLE
Implement risk exceptions

### ISSUE THREAD

**Issue by lucaderi** [ntop/nDPI#1231]
Currently flow risks are general and in some cases can generate false positives. Example binary .exe transfer from microsoft.com or DGA alerts from a local domain are not as such.

This is to request the implementation of flow risk exceptions to avoid these false positives.

**Comment by utoni** [comment]
What are the criteria for a risk exception? Only host/domain based? Not based on protocol or other information?

**Comment by lucaderi** [comment]
@lnslbrty I have implemented both host and IP exclusions. Please see https://www.ntop.org/ndpi/configuring-ndpi-flow-risks-exceptions/
