### ISSUE TITLE
dropbox android app

### ISSUE THREAD

**Issue by adrienb4** [ntop/nDPI#124]
I think the filter for dropbox don't work with android app. Ip in the list works ?

Thank

Adrien

**Comment by lucaderi** [comment]
Please provide a pcap to play with

**Comment by adrienb4** [comment]
See attached file (rename en .pcap).
I have added the ip network in source code, but i think they are not detected.

http://whois.arin.net/rest/org/DROPB/nets
[dropbox.txt](https://github.com/ntop/nDPI/files/54092/dropbox.txt)

**Comment by adrienb4** [comment]
I confirm my theory. I have changed the url in 'ndpi_content_matching.c.inc' file. When I lunch dropbox app, no traffic match. Only url with *.dropbox.com match.

**Comment by lucaderi** [comment]
fixed

**Comment by adrienb4** [comment]
It's works ! Thank
