### ISSUE TITLE
ndpi+dpdk issue

### ISSUE THREAD

**Issue by utkarsh0902311047** [ntop/nDPI#1247]
I am trying to work with ndpi+dpdk on ubuntu.
I bind the port getting traffic to igb_uio (dpdk driver).
Then I run ./ndpiReader.dpdk --vdev=net_pcap0,iface=<port_name>, it shows couldn't open port, no such device exists, but it still shows the protocols detected. How come?
And I know that the port is no more available in the kernel. But then how can I read the traffic on the port through nDPI.

dpdk-stable-19.11.4
nDPI-3.5.0
Ubuntu 20.04
Please help.

**Comment by vipinpv85** [comment]
I am not an expert of ndpi+DPDK, but I can comment on what is going wrong from a DPDK point of view.

1. If you bind a NIC with `igb_uio|uio_pci_generic|vfio-pci` this is no longer part of Kernel netlink representation, That is there is no longer access to ports such `eth0|eth1|eth2` (assuming eth0. eth1, eth2 are bound to UIO driver).
2. But in the application you are passing the PORT to be used as virtual device by ` --vdev=net_pcap0,iface=<port_name>`. PCAP PMD expects the NIC port to bound to kernel driver. 

**_Since you have bind with port UIO driver and then you asking to search for PCAP PMD for kernel NIC port, DPDK rte_eal_init is not able to vdev_probe and find the kernel device._**  So if the expectation of ndpi+dpdk is to use PCAP device **do not bind with any _uio driver_**.

Try the following steps

1. unbind the NIC port from uio driver
2. bind ti back to the kernel driver
3. restart the application with `./ndpiReader.dpdk --vdev=net_pcap0,iface=<port_name>`

If the above works, then try build ndpi+DPDK in static DPDK library mode then

1. bind NIC port to uio driver
2. start the application with ` ./ndpiReader.dpdk`

**Comment by anust** [comment]
@vipinpv85 please explain this
If the above works, then try build **ndpi+DPDK in static DPDK** library mode then
I am also using  UIO driver and getting a huge packet loss. 

 I am staring my application with these arguments, but not getting the insight of it. 
`sudo ./ndpiReader.dpdk -l 0 3 -- -i -n 1 -V 2`

**Comment by lucaderi** [comment]
Sorry we're not a DPDK shop. Please send us a pull request if there is something to fix in the demo application.

**Comment by vipinpv85** [comment]
> @vipinpv85 please explain this
> If the above works, then try build **ndpi+DPDK in static DPDK** library mode then
> I am also using UIO driver and getting a huge packet loss.
> 
> I am staring my application with these arguments, but not getting the insight of it.
> `sudo ./ndpiReader.dpdk -l 0 3 -- -i -n 1 -V 2`

do you have logs of EAL for DPDK failure, as pointed by @lucaderi if the issue is specific to bdpiReader please open and share logs for the same?

**Comment by anust** [comment]
How to start ndpi in multi-threading mode with this application 

always when I try
`sudo ./build/ndpiReader.dpdk -l 0 3 --  -n 2 -V 2`

Using nDPI (4.0.0) [2 thread(s)]
EAL: Error - exiting with code: 1
  Cause: Cannot create mbuf pool: are hugepages ok?
 
but with 

`sudo ./build/ndpiReader.dpdk -l 0 3 --  **-n 1** -V 2`
it works fine

**Comment by utkarsh0902311047** [comment]
Hi,
How to build ndpi+DPDK in static DPDK library mode?

Utkarsh

**Comment by anust** [comment]
@utkarsh0902311047  I am using dpdk-18.11 and have set the SDK on it, 

```
export RTE_SDK=~/dpdk-18.11.11/dpdk-stable-18.11.11/
export nDPI_src=~/nDPI-4.2-stable/
export RTE_TARGET=x86_64-native-linuxapp-gcc
```

then make -f Makefile.dpdk

**Comment by utkarsh0902311047** [comment]
@anust I am doing the same steps but as @vipinpv85  mentioned to build ndpi+dpdk in static DPDK library mode, I didn't get that.

@vipinpv85 Also, I have the same issue with how to run ndpireader.dpdk in multi-threading. It keeps running on one thread only.

**Comment by vipinpv85** [comment]
@utkarsh0902311047 for your original question ` I run ./ndpiReader.dpdk --vdev=net_pcap0,iface=<port_name>, it shows couldn't open port, no such device exists,` **_I shared the answer as You are binding a Kernel interface with DPDK and trying to open in PCAP (which is not expected). To which I added if you do not use static library of DPDK one has to pass couple of shared libraries (including PMD) of DPDK to make it work. Hence use static library of DPDK to build nDPI_**

@utkarsh0902311047 for the question  `I have the same issue with how to run ndpireader.dpdk in multi-threading`, I request you to check with nDPI team or @anust if it is supported or not? 

Note: as mentioned `I am not an expert of ndpi+DPDK` , but from quick analysis

- `sudo ./build/ndpiReader -c 1 --vdev=net_pcap0,iface=eno1 -- -v 1` does not expect the `eno1` to be bound by igb_uio or vfioo_pci or uio_pci_generic
- checking the code `processing_thread` is called by pthread_create which is iterated in a loop from 0 to (num_threads - 1). 

Hence I state I am not clear with your question,

**Comment by anust** [comment]
@vipinpv85 I am unable to do multi-threading with any dpdk application till now. 
 I am following [https://www.dpdk.org/wp-content/uploads/sites/35/2018/12/LUCADERI_NDPI.pdf](this)

and can achieve only 3gbps and a huge packet loss.

**Comment by anust** [comment]
@vipinpv85 I am unable to do multi-threading with any dpdk application till now.

I am following [this](I am following https://www.dpdk.org/wp-content/uploads/sites/35/2018/12/LUCADERI_NDPI.pdf)

and can achieve only 3gbps and a huge packet loss.

**Comment by anust** [comment]
@vipinpv85 I am unable to do multi-threading with any dpdk application till now.

I am following [this](https://www.dpdk.org/wp-content/uploads/sites/35/2018/12/LUCADERI_NDPI.pdf)

and can achieve only 3gbps and a huge packet loss.

**Comment by vipinpv85** [comment]
@anust I am confused with what you are asking from me. I think it is much easier if you can reach over skype. As I have already stated `Note: as mentioned I am not an expert of ndpi+DPDK , but from quick analysis

sudo ./build/ndpiReader -c 1 --vdev=net_pcap0,iface=eno1 -- -v 1 does not expect the eno1 to be bound by igb_uio or vfioo_pci or uio_pci_generic
checking the code processing_thread is called by pthread_create which is iterated in a loop from 0 to (num_threads - 1).`

**Comment by anust** [comment]
@vipinpv85 I am using dpdk interfaces, with sudo ./build/ndpiReader.dpdk -l 0 3 -- -n 2 -V 2

eal is auto initialized by the servers setup. I am not able to do multi-threading with ndpi as there is always a  segmentation fault even with the most stable version. 

Please share your skype id and available timings.

**Comment by vipinpv85** [comment]
I can talk to you now, my skype id is same as github id

**Comment by anust** [comment]
@vipinpv85 thanks for the conversation, I have shared the codes with you.

**Comment by vipinpv85** [comment]
based on the skype interaction with @anust the actual problem statement is `https://www.dpdk.org/wp-content/uploads/sites/35/2018/12/LUCADERI_NDPI.pdf describes 9.9Gbps of nDPI processing, based on the suggestion from page 19 with DPDK example or cure nDPIreader example this is no achievable`. I have requested @anust to open a new tickets and reach out to @lucaderi  for clarification

To address the current problem (after analysing the code and PDF page 19), following work item is suggested for @anust 

if DPDKe example skeleton is used, do the following

1.  enable RX and TX for multiple queues
2. enable RSS of IP tuple for flow distribution
3. modify the main logic to launch threads to equal to rx queues
4. invoke nDPI processing as suggested in page 19 of PDF but across multiple thread-queue pair

Note: I have highlighted based on the packet size the results varies as NDPI uses cpu cycles to process packets.

**Comment by vipinpv85** [comment]
> @vipinpv85 thanks for the conversation, I have shared the codes with you.

I have already replied and shared what are the next steps  as 

- changes to be done
- open a new ticket with @lucaderi  as he is the author for NDPI

**Comment by anust** [comment]
thanks @vipinpv85

**Comment by utkarsh0902311047** [comment]
> based on the skype interaction with @anust the actual problem statement is `https://www.dpdk.org/wp-content/uploads/sites/35/2018/12/LUCADERI_NDPI.pdf describes 9.9Gbps of nDPI processing, based on the suggestion from page 19 with DPDK example or cure nDPIreader example this is no achievable`. I have requested @anust to open a new tickets and reach out to @lucaderi for clarification
> 
> To address the current problem (after analysing the code and PDF page 19), following work item is suggested for @anust
> 
> if DPDKe example skeleton is used, do the following
> 
> 1. enable RX and TX for multiple queues
> 2. enable RSS of IP tuple for flow distribution
> 3. modify the main logic to launch threads to equal to rx queues
> 4. invoke nDPI processing as suggested in page 19 of PDF but across multiple thread-queue pair
> 
> Note: I have highlighted based on the packet size the results varies as NDPI uses cpu cycles to process packets.

@vipinpv85 Please suggest the steps for 1,2,3,4.

**Comment by vipinpv85** [comment]
> > based on the skype interaction with @anust the actual problem statement is `https://www.dpdk.org/wp-content/uploads/sites/35/2018/12/LUCADERI_NDPI.pdf describes 9.9Gbps of nDPI processing, based on the suggestion from page 19 with DPDK example or cure nDPIreader example this is no achievable`. I have requested @anust to open a new tickets and reach out to @lucaderi for clarification
> > To address the current problem (after analysing the code and PDF page 19), following work item is suggested for @anust
> > if DPDKe example skeleton is used, do the following
> > 
> > 1. enable RX and TX for multiple queues
> > 2. enable RSS of IP tuple for flow distribution
> > 3. modify the main logic to launch threads to equal to rx queues
> > 4. invoke nDPI processing as suggested in page 19 of PDF but across multiple thread-queue pair
> > 
> > Note: I have highlighted based on the packet size the results varies as NDPI uses cpu cycles to process packets.
> 
> @vipinpv85 Please suggest the steps for 1,2,3,4.

@utkarsh0902311047 I am not clear what are you asking ? can you come online on skype to explain ?
