### ISSUE TITLE
Implement a function to get flow information

### ISSUE THREAD

**Issue by simonemainardi** [ntop/nDPI#1253]
It is desirable to have an nDPI function returning a string which depends on the L7 protocol detected, e.g., 

- The host name for HTTP flows
-  The DNS query for DNS flows
-  the SNI for TLS flows

This will allow all ntop-tools to use it and have the same results. For example the implementation of https://github.com/ntop/nProbe/issues/494 can just use this function and also ntopng method Flow::getFlowInfo can become a short-circuit of this nDPI function.

**Comment by lucaderi** [comment]
Implemented with new API call ndpi_get_flow_info()
