### ISSUE TITLE
TFTP/PUT is not detected.

### ISSUE THREAD

**Issue by SysMan-One** [ntop/nDPI#1256]
Hi there!

 A yet another problem: TFTP/PUT is not detected. See .PCAP in attachment.
[tftp-put.zip](https://github.com/ntop/nDPI/files/6864012/tftp-put.zip)

**Comment by utoni** [comment]
Thank you very much for that pcap. It definitely helps my investigation.

**Comment by SysMan-One** [comment]
Cool! Good job!
