### ISSUE TITLE
Add support for Google cloud services (Gdrive, Gphoto)

### ISSUE THREAD

**Issue by Mile-Lile** [ntop/nDPI#126]
Google Drive is a file storage and synchronization service created by Google.[2][3] It allows users to store files in the cloud, share files, and edit documents, spreadsheets, and presentations with collaborators. Google Drive encompasses Google Docs, Sheets, and Slides, an office suite that permits collaborative editing of documents, spreadsheets, presentations, drawings, forms, and more.

Google Drive was launched on April 24, 2012 [2] and had 240 million monthly active users as of October 2014.

PCAP here https://drive.google.com/file/d/0B0SCwy1irn3qSTYzejVkT25abFE/view?usp=sharing

**Comment by Mile-Lile** [comment]
Google Photos is a photograph and video sharing and storage service by Google. 
It was announced in May 2015 and spun out from Google+, the company's social network. 
At its launch, reviewers wrote that the service was among the best of its kind.
There is a problem of bandwidth hog due to Android synchronization service on smartphone and tablets. 
On android the sync service takes every photo, video etc on the device and push them in the cloud storage.
Identifying such traffic could help network admins to manage their netwotks...
So, maybe add Google cloud services dissector?
[Google_Photo_http.zip](https://github.com/ntop/nDPI/files/170391/Google_Photo_http.zip)
[Google_Photo_app.zip](https://github.com/ntop/nDPI/files/170392/Google_Photo_app.zip)

**Comment by kYroL01** [comment]
Thank you for sharing this informations

**Comment by Mile-Lile** [comment]
you are wellcome...
[Google_Drive_NEW_app.zip](https://github.com/ntop/nDPI/files/170399/Google_Drive_NEW_app.zip)

**Comment by IvanNardi** [comment]
A lot of things changed in google services/apps in the last years. If you are still interested in some protocols, open a new issue and attached some traces, please
