### ISSUE TITLE
unable to recieve packets using ndpi over dpdk.

### ISSUE THREAD

**Issue by anust** [ntop/nDPI#1267]
I am using the example ndpireader.c , I can see the application statistics , but I cannot receive back packets using t-rex. 

How to forward the packets after processing them to ndpi?
```

 ndpi_process_packet((u_char*)&thread_id, &h, (const u_char *)data);


      /* Send burst of TX packets, to second port of pair. */
      const uint16_t nb_tx = rte_eth_tx_burst(dpdk_port_id ^ 1, 0,
          bufs, num); 
```
cannot receive on tx-port

**Comment by shashankbr11** [comment]
Hi,

I have been facing the same issue of not getting the packets back in T-Rex connected in loopback manner.

I am running the ndpiReader.dpdk executable with --vdev=net_pcap0,rx_iface=eth0,tx_iface=eth1

The nDPI shows the received packets from T-Rex application, however the Rx side of T-Rex doesn't log packets.

How do we forward the packets received by nDPI to the next interface? Kindly suggest

With regards,
Shashank

**Comment by InSdi** [comment]
Facing same issue.Please provide suggestions for forwarding the traffic to next interface using ndpireader dpdk example

**Comment by IvanNardi** [comment]
AFAIK, there is not support whatsover for TX data path in `ndpiReader` (expecially if DPDK is involved).
If you want to add it, I suggest to start looking at `l2fwd` code in DPDK repository

**Comment by IvanNardi** [comment]
Closing. If you have any specific issue, please open a new ticket
