### ISSUE TITLE
dpdk ndpi mem leak

### ISSUE THREAD

**Issue by ygm521** [ntop/nDPI#1268]
426192 bytes in 8879 allocations from stack
		ndpi_malloc+0x28 [ndpiReader.dpdk]
		ndpi_calloc+0x29 [ndpiReader.dpdk]
		ndpi_init_bin+0x58 [ndpiReader.dpdk]
		get_ndpi_flow_info.isra.2+0x630 [ndpiReader.dpdk]
	1137920 bytes in 8890 allocations from stack
		ndpi_malloc+0x28 [ndpiReader.dpdk]
		ndpi_init_data_analysis+0x6b [ndpiReader.dpdk]
		ndpi_alloc_data_analysis+0x35 [ndpiReader.dpdk]
		get_ndpi_flow_info.isra.2+0x609 [ndpiReader.dpdk]
	1138176 bytes in 8892 allocations from stack
		ndpi_malloc+0x28 [ndpiReader.dpdk]
		ndpi_init_data_analysis+0x6b [ndpiReader.dpdk]
		ndpi_alloc_data_analysis+0x35 [ndpiReader.dpdk]
		get_ndpi_flow_info.isra.2+0x61a [ndpiReader.dpdk]
	1139712 bytes in 8904 allocations from stack
		ndpi_malloc+0x28 [ndpiReader.dpdk]
		ndpi_init_data_analysis+0x6b [ndpiReader.dpdk]
		ndpi_alloc_data_analysis+0x35 [ndpiReader.dpdk]
		get_ndpi_flow_info.isra.2+0x5e7 [ndpiReader.dpdk]
	1139840 bytes in 8905 allocations from stack
		ndpi_malloc+0x28 [ndpiReader.dpdk]
		ndpi_init_data_analysis+0x6b [ndpiReader.dpdk]
		ndpi_alloc_data_analysis+0x35 [ndpiReader.dpdk]
		get_ndpi_flow_info.isra.2+0x5f8 [ndpiReader.dpdk]
	1140352 bytes in 8909 allocations from stack
		ndpi_malloc+0x28 [ndpiReader.dpdk]
		ndpi_init_data_analysis+0x6b [ndpiReader.dpdk]
		ndpi_alloc_data_analysis+0x35 [ndpiReader.dpdk]
		get_ndpi_flow_info.isra.2+0x5d6 [ndpiReader.dpdk]
	1888944 bytes in 8142 allocations from stack
		ndpi_malloc+0x28 [ndpiReader.dpdk]
		get_ndpi_flow_info.isra.2+0x6c5 [ndpiReader.dpdk]
	1892424 bytes in 8157 allocations from stack
		ndpi_malloc+0x28 [ndpiReader.dpdk]
		get_ndpi_flow_info.isra.2+0x6ef [ndpiReader.dpdk]
	20701368 bytes in 8163 allocations from stack
		ndpi_malloc+0x28 [ndpiReader.dpdk]
		ndpi_flow_malloc+0x36 [ndpiReader.dpdk]
		get_ndpi_flow_info.isra.2+0x69f [ndpiReader.dpdk]
	65177280 bytes in 8904 allocations from stack
		ndpi_malloc+0x28 [ndpiReader.dpdk]
		get_ndpi_flow_info.isra.2+0x52e [ndpiReader.dpdk]

**Comment by lucaderi** [comment]
We have periodic tests that check for leaks and none is found. Please check the application and send a pull request if necessary

**Comment by ygm521** [comment]
i have soved it, used mem pool like nginx ngx_pool，any one malloc from pool, finally free pool once when not used。
i think it's app mem leak。
