### ISSUE TITLE
Help creating a Load Test

### ISSUE THREAD

**Issue by redbeardmeric** [ntop/nDPI#1269]
I'm looking to create a test on a system that uses nDPI to monitor traffic.  If I use a traffic generator for this, how might I craft the TCP packets to create the greatest stress on the system running nDPI?

Thanks for any help!

**Comment by utoni** [comment]
What does "Load Test" mean exactly? Just care about CPU Load?

IMHO most of the traffic nowadays has something to do with TLS and the corresponding nDPI protocol dissector is a more complex one.
Not sure if this works, but here is what I would do:

1. set the flow timeout very low, so memory consumption won't hit you that hard
2. generate lot's and lot's of TLS handshakes, use different TLS versions, extensions, etc..
3. generate TLS data legitly embedded in other protocols such as QUIC
4. similar to 3. but now use one of the newer QUIC drafts with an encrypted TLS client hello
5. use nDPI pcap's in `tests/pcap` as replay data (less coding effort, hopefully)

**Comment by utoni** [comment]
(I would be interested in your results. At the moment nobody knows exactly how nDPI's performance is doing.)

**Comment by utoni** [comment]
Any progress on this?

**Comment by redbeardmeric** [comment]
@lnslbrty Still working out some kinks in the over all hardware setup and software builds, but actively working on it.

**Comment by utoni** [comment]
I will close that issue (please reopen if necessary).

With #1603 nDPI uses google-pprof together with already existing regression tests to profile CPU/HEAP usage and generate a PNG with that information. I guess the load test is not required anymore as pprof fulfills the need for performance metrics.
