### ISSUE TITLE
ndpiReader.c with inline dpdk application

### ISSUE THREAD

**Issue by anust** [ntop/nDPI#1278]
@lucaderi 
ndpiReader.c in currently working in passive mode, what's the procedure to make it working in fwd mode. 
I tried the basic reader application with dpdk simple fwd , it always say segmentation fault. 

trying to add this

`const uint16_t nb_tx = rte_eth_tx_burst(port ^ 1, 0, bufs, bufs[i]);`

instead of just 
`rte_pktmbuf_free(bufs[buf]);`

**Comment by lucaderi** [comment]
Sorry I am not a DPDK expert. If you move to PF_RING I can help you but not on DPDK

**Comment by anust** [comment]
with PF_RINF , ndpi with flow table (FT) need license, I am developing a custom application to read the high speed packet with L7 detection in inline mode. The current application available is in passive mode.
