### ISSUE TITLE
Purpose of  `struct ndpi_id_struct`

### ISSUE THREAD

**Issue by IvanNardi** [ntop/nDPI#1279]
Looking at ways to reduce memory usage, I bumped into the structure `ndpi_id_struct`. We have 2 of this variables for each `struct ndpi_flow_struct`: `src` and `dst` (plus another pointer `server_id`: let ignore it for the time being)

What is their purpose?

Looking at the comments it seems they are a way to correlate different flows originated or terminated  from/to the same "host/user", i.e a way to collect some information about "host/user". And that makes sense...
However... the lifetime of this structures is the same of the lifetime of the flow they are used in!!!
In other worlds, `src` and `dst` are -always- unconditionally allocated (and freed) when the corresponding `struct ndpi_flow_struct` is allocated (or freed): they are not persistent objects across different sessions. This is the behavior of `ndpiReader` and of `ntop`, too.

I quickly run the unit tests with a slightly modified version of `ndpiReader` where these two structures are never allocated: no difference at all.

Right now, using this structure (in the current way) )seems to be only a huge waste of memory.

Note that the definition of `struct ndpi_id_struct` pre-date git history (~6 years ago) and it has never been touched ever since...

Note also that a similar (but not identical) functionality is achieved, in recent code, via the LRU caches.

Before talking about what should be done to improve the current situation, am I missing something obvious here? Have I mis-read the code?

**Comment by vel21ripn** [comment]
In ndpi-netfilter, these structures are stored in a separate RB-tree. Each ndpi_id_struct has a usage counter and only deletes when the counter is zero.
The ndpi_id_struct number is approximately 60-70% of the number of connections.
Another question is how much ndpi_id_struct is used.

**Comment by lucaderi** [comment]
I agree that this is something inherited from OpenDPI that needs to be cleaned up

**Comment by IvanNardi** [comment]
> I agree that this is something inherited from OpenDPI that needs to be cleaned up

Yeah, this code is present in the original OpenDPI repository. From its manual (emphasis mine):




```
A similar state buffer is maintained for every subscriber. In most situations, a subscriber is identified by its
internal IP address. In this case, ****a memory buffer for every internal IP address must be maintained****.

OpenDPI is designed to work in different network situations. There are two different situations for the subscriber
mapping.
In an access gateway situation, every packet belongs to one subscriber. The subscriber is either the sender or
the receiver of the packet. In this case, either the source or the destination subscriber is known.

In a non access gateway, every packet could belong to up to 2 subscribers. This happens when one subscriber
is the sender while the other is the receiver. In this case, both subscribers can be passed to OpenDPI.

In the following code example, the variable 'src' and 'dst' will be used for the sender and receiver subscriber.
void *src; // pointer to the final state machine of the sender subscriber
void *dst; // pointer to the final state machine of the dest subscriber


The required size for each element is the return value of a built!in function in OpenDPI:
unsigned int ipoque_detection_get_sizeof_ipoque_id_struct(void);
In an access gateway situation where only one subscriber is required, either 'src' or 'dst' can be NULL.

```

**Comment by utoni** [comment]
The definition of `subscriber` is rather obscure. I do not know if we really need those two. They may be useful for something like flow correlation, which we (hopefully) never want to do. But besides that, I do not see any use.

**Comment by IvanNardi** [comment]
With the latest changes, this structure is used only by 4 protocols: DirectConnect, IRC, Gnutella and Jabber.
I don't know these protocols well enough, but the code involved with `struct  ndpi_id_struct` is unchanged from the original OpenDPI import : I am not so sure these checks make still sense so many years later.
To move forward, we have 3 options, at least:
1) nuclear option: remove this stuff altogether
2) since there is at least one application correctly using it (see https://github.com/ntop/nDPI/issues/1279#issuecomment-902906604), keep the feature, but remove it from `ndpiReader`
3) update `ndpiReader` with "persistent" `struct  ndpi_id_struct` structures

Any thoughts?
