### ISSUE TITLE
dpdk ndpi issues: low throughput 

### ISSUE THREAD

**Issue by anust** [ntop/nDPI#1284]
I compiled the application using

 `make -f Makefile.dpdk
`
throughput reached is only  2.56 Gb/sec, whereas in documents it is claimed to be 10G.

`nDPI throughput:       898.82 K pps / 2.56 Gb/sec`

Also how to do nDPI multithreading per core  to achieve a higher data rate?

**Comment by utoni** [comment]
Maybe `example/ndpiSimpleIntegration` can answer your question. For a lock-free multithreading application you need a per thread stable packet distribution. That example does that exactly.
