### ISSUE TITLE
git commnad to check ndpi API revision

### ISSUE THREAD

**Issue by anust** [ntop/nDPI#1287]
I am using ft with ndpi and getting the following error

`*** ndpi library version mismatch, expected API rev.4882 (4.1.0) found rev.5511 (4.1.0) ***`

Please suggest how to download correct ndpi api version for ft

**Comment by cardigliano** [comment]
@anust how did you install nDPI? 
What OS are you running?
(API v.4882 should be the correct one, but it seems you have 5511 installed)

**Comment by anust** [comment]
from the ndpi-dev branch using source code. 

plz tell which branch is corresponding to API v.4882 (4.1.0)

OS ubuntu 16.04

**Comment by cardigliano** [comment]
The dev branch should have version 4882, please start from scratch and run:

git clone https://github.com/ntop/nDPI.git
cd nDPI
./autogen.sh
./configure

The output should now print the detected version like below:

Setting API version to 4882

**Comment by anust** [comment]
the link you shared is giving 

`*** ndpi library version mismatch, expected API rev.4882 (4.1.0) found rev.3329 (4.1.0) ***`

**Comment by cardigliano** [comment]
Could you share the output of ./configure ?

**Comment by anust** [comment]
./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for cos in -lm... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
Setting API version to 3329
checking for JSONC... yes
checking for json_object_put in -ljson-c... yes
checking whether gcc is Clang... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking math.h usability... yes
checking math.h presence... yes
checking for math.h... yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking for sqrt in -lm... no
checking DPDK (used by ndpiReader)... no (missing /home/ta/DPDK)
checking for numa_available in -lnuma... yes
Using libpcap from /home/ta/PF_RING/userland
checking for clock_gettime in -lrt... yes
checking for nl_handle_alloc in -lnl... no
checking for dlopen in -ldl... yes
checking for pthread_setaffinity_np in -lpthread... yes
checking for gcry_cipher_checktag in -lgcrypt... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating example/Makefile
config.status: creating example/Makefile.dpdk
config.status: creating tests/Makefile
config.status: creating tests/unit/Makefile
config.status: creating tests/dga/Makefile
config.status: creating libndpi.pc
config.status: creating src/include/ndpi_define.h
config.status: creating src/lib/Makefile
config.status: creating python/Makefile
config.status: creating fuzz/Makefile
config.status: creating src/include/ndpi_api.h
config.status: creating tests/do.sh
config.status: creating tests/do_valgrind.sh
config.status: creating src/include/ndpi_config.h
config.status: src/include/ndpi_config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

**Comment by cardigliano** [comment]
@anust in order to debug this, could you provide the files generated by the below commands please?

git log src/include/ndpi_typedefs.h > ndpi_typedefs.log
git log src/include/ndpi_protocol_ids.h > ndpi_protocol_ids.log
git log src/include/ndpi_api.h.in > ndpi_api.log

**Comment by anust** [comment]
please find the attachments
[
[ndpi_api.log](https://github.com/ntop/nDPI/files/7090409/ndpi_api.log)
[ndpi_protocol_ids.log](https://github.com/ntop/nDPI/files/7090410/ndpi_protocol_ids.log)
[ndpi_typedefs.log](https://github.com/ntop/nDPI/files/7090413/ndpi_typedefs.log)
](url)

**Comment by cardigliano** [comment]
@anust for some reason the code you cloned is from Oct 2020 (or at least this is what I can see from the logs)

**Comment by anust** [comment]
@cardigliano  thanks I am able to compile it after
`sudo rm -r  /usr/lib/libndpi*`
and then 
```
git clone https://github.com/ntop/nDPI.git
cd nDPI
./autogen.sh
./configure
```
published the ndpi api version , due to your recent commit. 89af9b7e3cdc06609826bcaf2093fae72a687ff6

Please tell me to run the app in the fwd mode, I am only getting ndpi stats and a huge packet loss.

**Comment by utoni** [comment]
> Please tell me to run the app in the fwd mode, I am only getting ndpi stats and a huge packet loss.

Please open a new issue if this problem still exists.
