### ISSUE TITLE
Hit problems when using JSONC_CFLAGS and JSONC_LIBS for nonstandard location

### ISSUE THREAD

**Issue by WendyWeiWan** [ntop/nDPI#1288]
Hi folks,

I use nonstandard location of json-c, and find JSONC_CFLAGS and JSONC_LIBS fail to take effect if I follow the guideline in nDPI_QuickStartGuide. To make it work, I change some places as below, do you have any comments/suggestions on this? Thanks.

1. nDPI-4.0/autogen.sh always generate new configure and run it without parameter, so I have to comment it.

 20  echo "./configure $@"
 21  chmod +x configure
 22 -./configure $@__

2. JSONC_CFLAGS and JSONC_LIBS are overridden in configure.seed which I change it as below

 33  if ! test "${with_mipsel+set}" = set && ! test "${with_only_libndpi+set}" = set; then :
 34     dnl> used by json-c for unit tests
 35 -   PKG_CHECK_MODULES([JSONC], [json-c], [JSONC_LIBS=`pkg-config --libs json-c` JSONC_CFLAGS=`pkg-config --cflags json-c`])
 36 +   PKG_CHECK_MODULES([JSONC], [json-c])
 37  fi
 38  
 39  LIBS="$LIBS $JSONC_LIBS"

**Comment by utoni** [comment]
There are two things here which may be an issue at some point.

1. Overriding JSON_* variables w/o giving the user the option to change those.
2. Using the command `pkg-config` command, which may and probably will cause errors during cross compilation.

**Comment by utoni** [comment]
I've just saw that this issue was fixed already. Your git source tree is not up2date.

You should now be able to use a custom json-c  library by adding the pkg-config directory to the search path.

This issue can be closed.
