### ISSUE TITLE
"ndpi_includes.h" need to be added to "nDPI/src/lib/Makefile.am" too

### ISSUE THREAD

**Issue by xgerligand** [ntop/nDPI#129]
To be properly copied to  : /usr/include/libndpi-1.7.1/libndpi/
i think "ndpi_includes.h" have to be include in this part of "nDPI/src/lib/Makefile.am" like this 

libndpi_la_include_HEADERS = ../include/ndpi_api.h \
                 ../include/ndpi_define.h \
                 ../include/ndpi_includes.h \
                 ../include/ndpi_main.h \
                 ../include/ndpi_protocol_ids.h \
                 ../include/ndpi_protocols.h \
                 ../include/ndpi_typedefs.h

Regards.

**Comment by kYroL01** [comment]
Fixed by 237de95285a0129f1b86fdfe9519e6e14302abc9

Thank you
