### ISSUE TITLE
Missing libpcap(-dev) 

### ISSUE THREAD

**Issue by Aa94865321005** [ntop/nDPI#1291]
When centsos7 installs nDPI, libpcap has been installed, but an error is still reported
configure: error: Missing libpcap(-dev) library required to compile the example application.

**Comment by utoni** [comment]
Please give a detailed summary about what you did.

Did you install nDPI from CentOs as binary package or did you try to compile it from source?
What nDPI version?
What CentOS version?
Does `/usr/include/pcap/pcap.h` exist?

**Comment by Aa94865321005** [comment]
The source code of NDPI is installed. The problem is in the installation of PF_ring, it was solved
