### ISSUE TITLE
Update python bindings

### ISSUE THREAD

**Issue by IvanNardi** [ntop/nDPI#1302]
Python bindings are out-of-sync with current nDPI code.
We should re-sync them, at very least.
Is it possible to auto-generate these files (or some of them)?

**Comment by IvanNardi** [comment]
@aouinizied: AFAIK I can't assign this issue to you until you comment here...
```
You can assign up to 10 people to each issue or pull request, including yourself, anyone who has commented on the issue or pull request, anyone with write permissions to the repository, and organization members
```

**Comment by aouinizied** [comment]
Yes, and here I am. 
We should definitively keep only cffi bindings (ndpi.py) as we can easily automate its generation.
Your feedbacks?

**Comment by IvanNardi** [comment]
Python (and python bindings) are not my area of expertise, so I am not able to give any meaningful advice on this topic :(
Nonetheless, avoiding manually touching these files (or some of them) whenever we update some C definitions would be very useful

**Comment by utoni** [comment]
I was just trying to get `ndpi_example.py` to work by (try) fixing `ndpi_typestruct.py`, but I think it is not as easy to fix.

**Comment by aouinizied** [comment]
@lnslbrty @IvanNardi This is fixed as now Python bindings are automatically generated ans are part of CI testing.
