### ISSUE TITLE
ndpi library version mismatch while using PF_RING with Snort

### ISSUE THREAD

**Issue by MubbashirAdnan** [ntop/nDPI#1305]
Hi,
I am trying to use pfring ft with snort IDS. Pfring is working fine with snort but when i followed these instructions (https://www.ntop.org/guides/pf_ring/thirdparty/snort-daq.html) to integrate pfring ft, i get ndpi library version mismatch error.

Can you please guide on how should i resolve this issue i'm facing
![issue](https://user-images.githubusercontent.com/88712137/133209033-9f2bfc36-6032-4719-a28d-54a346f87802.PNG)

**Comment by MubbashirAdnan** [comment]
I am trying to run it on centos 7

**Comment by utoni** [comment]
It seems like there are two nDPI versions installed. 
Did you install the libnDPI package shipped with CentOs before following the guide you've mentioned?
What is the output of `ldd [path-to-pfring]` and `find /usr -iname "*ndpi*"` ?

**Comment by IvanNardi** [comment]
Missing information. If you still have this problem, please open a new issue, providing all the information.
