### ISSUE TITLE
Custom Applications added into protos.txt file gets matched first, before the actual application detection happens

### ISSUE THREAD

**Issue by subritm** [ntop/nDPI#1322]
I have added a custom protocol entry as 

**tcp:443@HTTPS** 

So what I see is happening is the traffic matching port 443 gets detected as HTTPS, and it doesn't go via full detection module.
Port 443 can be google, Facebook, TLS, or anything.
Not sure if this is the way it is designed or its something I need to add check for.

If traffic is not getting detected, this custom protocol in protos,txt should be the last option to match and mark an application.
Tested with ndpi version 4.0.0 version. 
Thanks in Advance.

**Comment by utoni** [comment]
I agree that protocol dissectors should have precedence over custom defined rules.

But what I do not get: Why would someone want to add a custom port(-only) based rule for HTTPS which already exists as protocol dissector and works definitely better then a port based rule?

**Comment by subritm** [comment]
While testing with actual traffic, in a few occasions I can see that port 443 https is not getting detected. 
So I had added the custom rule. 

I will try to get the pcap for that traffic which doesn't get detected as HTTPS.

**Comment by utoni** [comment]
Can you please check if PR #1541 and PR #1542 fixed your issue?

**Comment by subritm** [comment]
> Can you please check if PR #1541 and PR #1542 fixed your issue?

With the latest version, I can see majorly all traffic are getting detected by the engine, and theres not much need to have a specific port match done unless its exclusively custom. 

Thank You.
