### ISSUE TITLE
issue template

### ISSUE THREAD

**Issue by utoni** [ntop/nDPI#1325]
While crawling through the issues like a bot I've recognized that most of the issues are lacking important information. Information that may be very helpful for all contributors.

To address that issue, this issue is made for. :smile:

I've never written such a template, but Github provides some documentation about it: [using-templates-to-encourage-useful-issues-and-pull-requests](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

Let us brainstorm what the template has to include.
For my part I would like to see the **nDPI release version or git commit hash** as mandatory. If the issue is related to a protocol detection/dissection issue, a **link to a pcap (or as attachment)** describing the issue, should also be mandatory.

What else could be useful information? @aouinizied @IvanNardi @lucaderi

**Comment by aouinizied** [comment]
@lnslbrty Nice idea. 
* We can create a template for issues. Give a checkbox or whatever to select if it's a bug or a feature request etc.
I think the OS version, the architecture, nDPI compilation flags, and ndpiReader options (when reproduced with it) should also be mandatory.
* We can also add a GitHub action that automatically closes and comment issues that do not follow the declared template (I know it's feasible) and mark it with "won't fix" with an automatic message as a comment.
What do you think?

Zied

**Comment by utoni** [comment]
Interesting. I did not know that it could be integrated in Github Actions. Makes sense.
It seems like nfstream already has such a nice template. :smiley_cat: 

1. sounds reasonable
2. not sure if this will scare off new people, who may not have lot's of experience with writing issues

**Comment by IvanNardi** [comment]
Close via a2e9730b23bad7fea0047ac275786115f5912e84
