### ISSUE TITLE
Discussion for custom ip range

### ISSUE THREAD

**Issue by u8906250** [ntop/nDPI#133]
for now , it doesn't support ip range

ip:213.75.170.0/24@CustomProtocol

could add this feature?

**Comment by kYroL01** [comment]
Well, what is the service or protocol related to this ip range ?

**Comment by u8906250** [comment]
for example, LINE service http://at.line.me/en/

LINE Corporation
119.235.224.0/20
119.235.235.0/24

**Comment by kYroL01** [comment]
Actually the ip range associated to a service is well supported by nDPI.
If you see https://github.com/ntop/nDPI/blob/dev/src/lib/ndpi_content_match.c.inc
this feature is well implemented.

**Comment by u8906250** [comment]
yes, but I think the custom proto file is not support this feature.

I trace ndpi_load_protocols_file() -> ndpi_handle_rule() ->  ndpi_add_host_ip_subprotocol() , and found it just call inet_pton() to convert one ip address text to binary.

**Comment by kYroL01** [comment]
Now I understand what you mean.
Yes, that feature is not provided, because nDPI can just load protos passing tcp or udp ports related to a protocol (i.e. `tcp:80,tcp:3128@HTTP`).
This is a good point to implement for the future!

**Comment by u8906250** [comment]
thank you!
and I try to add this feature (it's easy, haha) and already tested, see patch.txt

[patch.txt](https://github.com/ntop/nDPI/files/75455/patch.txt)

**Comment by kYroL01** [comment]
I'm trying and testing! I'll let you know, thanks!

**Comment by kYroL01** [comment]
fix by 5336aecde7e6f40e22810538dba9dd6601291145
