### ISSUE TITLE
IPv6 Custom application protocol support

### ISSUE THREAD

**Issue by MaoPann** [ntop/nDPI#1335]
We need to add IPv6 and IPv6 CIDR support to custom applications in ntopng,This may require a little development. You can evaluate and give a quotation, and we can accept it.

For example, the we wants to set the following IPv4 and IPv6 addresses as custom applications in ntopng.

191.232.2.128/25
2A01:110::/64
2620:1EC::/64
2603:1000::/64
40.100.2.114/32
40.100.2.82/32

![image](https://user-images.githubusercontent.com/44804599/136759969-8302ca01-cdda-4282-a032-b9524966d741.png)

**Comment by MaoPann** [comment]
@lnslbrty  How about this?

**Comment by utoni** [comment]
It is possible to extend custom applications with IPv6 support. But I can not tell you (yet) how long it will take.

**Comment by MaoPann** [comment]
I need this function. Can you roughly evaluate how long it will take? Like three months? In addition, do you plan to develop and support this function for free or for a fee? If you intend to charge, please give me a quotation and send it to my email, mao.pan@hkaco.com,I need to evaluate this scheme. Admittedly, I don't think the development of this function is complicated. I hope you can reply as soon as possible. Thank you.

**Comment by IvanNardi** [comment]
Done
