### ISSUE TITLE
Parsing protocols from L7_PROTO field. 

### ISSUE THREAD

**Issue by zygmuntszpak** [ntop/nDPI#1341]
I am working with a dataset that was extracted using the nProbe tool and it includes the field "L7_PROTO". I would like to recover the name of the protocol represented by the numeric value. 
I found this list of protocols: 
https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_protocol_ids.h  

However, while some L7_PROTO records are integers (e.g. I can match `7.0` with NDPI_PROTOCOL_HTTP), some records have decimals. For example, `1.7`, `51.7` or `7.131`. 

It looks like a pair of protocols are separated by the decimal point. 

So `1.7` would be:
`NDPI_PROTOCOL_FTP_CONTROL .NDPI_PROTOCOL_HTTP`

whereas 7.131 would be:
`NDPI_PROTOCOL_HTTP. NDPI_PROTOCOL_HTTP_PROXY`.

Is my interpretation correct? What is the significance of something appearing before versus after the decimal point. For example, could one obtain 131.7 => `NDPI_PROTOCOL_HTTP_PROXY.NDPI_PROTOCOL_HTTP` and how is the meaning of that different from 7.131? 

Many thanks for any clarifications you may be able to offer.

**Comment by utoni** [comment]
The first protocol represents the "master" protocol which is the first protocol detected after ISO-OSI layer 4. In most cases it refers to the detected layer 7 protocol.

The second protocol (after the decimal dot) has unfortunately two different meanings:

1. It could be an application "protocol" (not really a protocol), which is derived via Hostname/SNI/etc parsing and a lookup in an internal application database. Example: `NDPI_PROTOCOL_TLS.NDPI_PROTOCOL_GOOGLE`
2. Or a subprotocol, which conforms to your example. The subprotocol is set either in the same detection routine (which has to be aware of possible subprotocols) or via another detection routine, which will run after the "master" protocol was detected.

There are also some rare cases, where the protocol detection routine swaps "master"- and sub- protocol.
