### ISSUE TITLE
Paramters for NDPI_LOG_DBG2() function

### ISSUE THREAD

**Issue by choupani** [ntop/nDPI#1349]
In may_be_initial_pkt() function:
line NDPI_LOG_DBG2(ndpi_struct, "Version 0x%x with first byte 0x%x\n", first_byte); should be changed to 
NDPI_LOG_DBG2(ndpi_struct, "Version 0x%x with first byte 0x%x\n", *version, first_byte);

**Comment by IvanNardi** [comment]
You are right, of course. Are you going to push the fix yourself?

**Comment by choupani** [comment]
No, Pls you push.
