### ISSUE TITLE
Ntopng compilation error on debian 8.2 x86

### ISSUE THREAD

**Issue by shadrack222** [ntop/nDPI#135]
Hello,

After nDPI compilation without problems i got the following error while compiling ntopng (date : Wed Jan 6 16:34:53 2016 +0100 )

... 

In file included from /usr/local/include/libndpi-1.7.1/libndpi/ndpi_main.h:33:0,
                 from /opt/ntopng/include/ntop_includes.h:99,
                 from src/NetworkInterface.cpp:22:
/usr/local/include/libndpi-1.7.1/libndpi/ndpi_api.h:77:40: note: initializing argument 2 of ‘ndpi_detection_module_struct\* ndpi_init_detection_module(u_int32_t, void\* (_)(size_t), void (_)(void_), ndpi_debug_function_ptr)’
   struct ndpi_detection_module_struct *ndpi_init_detection_module(u_int32_t ticks_per_second,
                                        ^
src/NetworkInterface.cpp: In member function ‘int NetworkInterface::getFlows(lua_State_, patricia_tree_t_, Host_, bool, char_, u_int32_t, u_int32_t, bool)’:
src/NetworkInterface.cpp:1951:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int i=toSkip, num=0; i<retriever.actNumEntries; i++) {
                               ^
src/NetworkInterface.cpp:1953:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if(++num >= maxHits) break;
                ^
src/NetworkInterface.cpp:1958:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if(++num >= maxHits) break;
                ^
src/NetworkInterface.cpp: In member function ‘int NetworkInterface::getActiveHostsList(lua_State_, patricia_tree_t_, bool, bool, char_, u_int32_t, u_int32_t, bool)’:
src/NetworkInterface.cpp:2013:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int i=toSkip, num=0; i<retriever.actNumEntries; i++) {
                               ^
src/NetworkInterface.cpp:2016:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if(++num >= maxHits) break;
                ^
src/NetworkInterface.cpp:2022:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if(++num >= maxHits) break;
                ^
Makefile:129: recipe for target 'src/NetworkInterface.o' failed
make: **\* [src/NetworkInterface.o] Error 1

Any ideas to help me , thanks in advance.

**Comment by kYroL01** [comment]
Hi @shadrack222 
As you explained, this is a ntopng problem, so I suggest you to open this issue to ntopng and not here.
Thank you

**Comment by shadrack222** [comment]
Ok, thanks kYroL01
