### ISSUE TITLE
nDPI with DPDK Throughput

### ISSUE THREAD

**Issue by sohailanjum97** [ntop/nDPI#1352]
Hi all, 
My Experiment Scenario is based on two nodes.
1. Tx Node: pf_ring version Tx rate up to 100Gbps [Works Fine]
2. Rx Node: nDPI with DPDK 21.11. Capturing the packets but using 1 core and the nDPI Throughput up to 15Gbps maximum, I have used EAL parameters to assign more core still nDPI(DPDK) used 1 core always, Anyone has any idea how to solve this issue.
3. Pics are for your reference. My nDPI throughput is very low how to solve this with the help of more cores or without cores need suggestions.
![htopndpidpdk](https://user-images.githubusercontent.com/48083468/137688020-cbad2cf1-e7f5-42e6-8670-d2664cce5d29.png)
![ndpi](https://user-images.githubusercontent.com/48083468/137688101-4157f91c-4335-413b-8133-b69990165b2e.png)

**Comment by utoni** [comment]
Please use the issue template next time. Did you use nDPI bc5be1e76cd8b3d6733f66bffe346486de89b8a0 for all your tests?

**Comment by sohailanjum97** [comment]
Yes, I am using nDPI. but the nDPI throughput is lower than our expectations.
In the Above Rx Node result, the nDPi+DPDK throughput is 5.05Gbps /sec, HOwever we are sending Tx Node the packet sending is almost 100Gbps.

**Comment by utoni** [comment]
Please update your source tree to the current dev branch and try again.
