### ISSUE TITLE
ftp fail count increase when getting data from port 22

### ISSUE THREAD

**Issue by imagineTh4t** [ntop/nDPI#1361]
Hi,
I have a question about flow->ndpi_flow->protos.ftp_imap_pop_smtp.auth_failed
This count increase when i'm login in port 22 with filezilla. But it is broken maybe. Is this count increasing when i get failed?
Can you explain me ?

**Comment by utoni** [comment]
For clarification: `flow->ndpi_flow->protos.ftp_imap_pop_smtp.auth_failed` is a bitfield of size 1. Only true or false can be stored in there.

Which service is running on port 22 and what protocol is filezilla configured to use?

**Comment by IvanNardi** [comment]
Missing information. If you still have this problem, please open a new issue, providing all the information.
