### ISSUE TITLE
Teams test file contains packets ignored by ndpiReader for no reason 

### ISSUE THREAD

**Issue by aouinizied** [ntop/nDPI#1367]
## Describe the bug
I observed that ndpiReader behavior changed when testing using teams.pcap test file.

### Expected behavior
83 flows generated.
### Obtained behavior
82 flows generated.
The ignored flow comes from 4 packets that I attached in debug_teams file.

## nDPI Environment:
* OS name: Ubuntu.
* OS version: 20.04
* Architecture: x86_64
* nDPI version or commit hash: 55880e4ae4cb651f54a9531ba9732977d9dd517f.
* nDPI compilation flags used: default

### Reproducible using ndpiReader?
- [x] The reported bug is reproducible using ndpiReader.
- [] The reported bug is not reproducible using ndpiReader.

### If applicable, the used ndpiReader options:

``` shell
/usr/local/bin/ndpiReader -q -t -i debug_teams.pcap -C debug_teams.csv  -T 20 -U 20
```

### If your bug is reproducible using a pcap, please attach a pcap file (or a valid link to download it)

[debug_teams.pcap.gz](https://github.com/ntop/nDPI/files/7467790/debug_teams.pcap.gz)

### Steps to reproduce the behavior:
1. Run ndpiReader command.

**Comment by utoni** [comment]
Are you sure that the flow is related to Teams? It looks somehow different compared to the other flows. Maybe it is some background noise from a SSH connection? It uses  TCP port 2222 which is sometimes used for sshd. Not sure if it was ever detected by nDPI. I've checked `git blame` and `git diff` and was not able to get any detection result for that flow.

**Comment by aouinizied** [comment]
@lnslbrty Yes probably background traffic. The issue is not related to teams classification itself but rather regarding packet processing.
What I observed is that the number of flows generated with ndpiReader using the teams test pcap is different from what I get with nfstream.
So I isolated the missing flow (ssh probably) and checked the 4 packets belonging to it. It appears that they are valid IP packets. So I'm wondering at which stage we drop this packets within ndpiReader.

**Comment by IvanNardi** [comment]
The issue seems about the csv export. The output of ndpiReader itself seems fine
```
ivan@ivan-Latitude-E6540:~/svnrepos/nDPI(dev)$ ./example/ndpiReader -t -i ~/debug_teams.pcap -C debug_teams.csv 
[...]
	Unique flows:          1            
[...]
Detected protocols:
	Unknown              packets: 4             bytes: 456           flows: 1            


Protocol statistics:
	Unrated                        456 bytes
ivan@ivan-Latitude-E6540:~/svnrepos/nDPI(dev)$ cat debug_teams.csv 
#flow_id,protocol,first_seen,last_seen,duration,src_ip,src_port,dst_ip,dst_port,ndpi_proto_num,ndpi_proto,server_name,benign_score,dos_slow_score,dos_goldeneye_score,dos_hulk_score,ddos_score,hearthbleed_score,ftp_patator_score,ssh_patator_score,infiltration_score,c_to_s_pkts,c_to_s_bytes,c_to_s_goodput_bytes,s_to_c_pkts,s_to_c_bytes,s_to_c_goodput_bytes,data_ratio,str_data_ratio,c_to_s_goodput_ratio,s_to_c_goodput_ratio,iat_flow_min,iat_flow_avg,iat_flow_max,iat_flow_stddev,iat_c_to_s_min,iat_c_to_s_avg,iat_c_to_s_max,iat_c_to_s_stddev,iat_s_to_c_min,iat_s_to_c_avg,iat_s_to_c_max,iat_s_to_c_stddev,pktlen_c_to_s_min,pktlen_c_to_s_avg,pktlen_c_to_s_max,pktlen_c_to_s_stddev,pktlen_s_to_c_min,pktlen_s_to_c_avg,pktlen_s_to_c_max,pktlen_s_to_c_stddev,cwr,ece,urg,ack,psh,rst,syn,fin,c_to_s_cwr,c_to_s_ece,c_to_s_urg,c_to_s_ack,c_to_s_psh,c_to_s_rst,c_to_s_syn,c_to_s_fin,s_to_c_cwr,s_to_c_ece,s_to_c_urg,s_to_c_ack,s_to_c_psh,s_to_c_rst,s_to_c_syn,s_to_c_fin,c_to_s_init_win,s_to_c_init_win,client_info,server_info,tls_version,ja3c,tls_client_unsafe,ja3s,tls_server_unsafe,tls_alpn,tls_supported_versions,ssh_client_hassh,ssh_server_hassh,flow_info,plen_bins

**Comment by aouinizied** [comment]
@IvanNardi I will close then. Thanks @IvanNardi, this was a False Positive as I didn't try without csv.

**Comment by IvanNardi** [comment]
@aouinizied, to dump unknown flows (like the one reported) you need at least verbose level 2 (both in stdout and in csv file). Something like `ndpiReader -v2 ...`
