### ISSUE TITLE
nDPI API

### ISSUE THREAD

**Issue by ghost** [ntop/nDPI#137]
Hi all,
   I need to know that how to get the packet length,payload,time and indepth details of each packets using nDPI. I got the indepth details of each packet using wireshark. In nDPI they are having some configuration API . but i dont know how to use that. Please ,suggest me the  solution as soon as possible.

Thanks and Regards,

**Comment by lucaderi** [comment]
I suggest you to look at https://github.com/ntop/nDPI/blob/dev/example/ndpiReader.c for an example or to a dissector code you can find in https://github.com/ntop/nDPI/tree/dev/src/lib/protocols

**Comment by ghost** [comment]
Thank you for your response .
i surfed already that you have posted before.still, i didnt get any clear idea.
In the user guide they given that api, thats the exact solution what i think.
I just to know where to use that and how to use that.
Thank you

**Comment by rathnaTech** [comment]
hi 
I am also having the same question.please suggest me any solution
Thanks
