### ISSUE TITLE
ndpi_patricia_best2() coredump

### ISSUE THREAD

**Issue by sobrien1234** [ntop/nDPI#1375]
## Describe the bug

After running call load for about 3 hours, am getting a coredump with the following backtrace. I am using nDPI-4.0.tar.gz.

#0 ndpi_patricia_search_best2 (
patricia=<error reading variable: Cannot access memory at address 0x7f811cbded08>, prefix=0x7f811cbded10,
prefix@entry=<error reading variable: Cannot access memory at address 0x7f811cbded08>, inclusive=1,
inclusive@entry=<error reading variable: Cannot access memory at address 0x7f811cbded08>)
at third_party/src/ndpi_patricia.c:547
Cannot access memory at address 0x7f811cbded08
(gdb)

### Expected behavior

No coredump.

### Obtained behavior
A clear and concise description of what happening.

Running a calload with simple Youtube-Quic pcap and Vine pcap. After 3 hours, hitting segmentation coredump. Note that I am using memory allocation wrappers.

## nDPI Environment (please complete the following information):
* OS name: [e.g. Ubuntu]. Centos
* OS version: [e.g. 18.04] 7.9
* Architecture: [e.g. arm64] x86_64
* nDPI version or commit hash: [e.g. 4.0-stable or 937357e4bc55610f116f66d15a8e0fc1e260c02c]. 4.0-stable
* nDPI compilation flags used: if you are building from source [e.g. --with-pcre --disable-gcrypt]. default
* Attach the `config.log` file generated after `./configure` ran (if you are building from source). Attached

## How to reproduce the reported bug

Run call load for 3 hours.

### Reproducible using ndpiReader?
- [x] The reported bug is reproducible using ndpiReader.
- [x] The reported bug is not reproducible using ndpiReader. --->Not reproducible

### If applicable, the used ndpiReader options:
[config.log](https://github.com/ntop/nDPI/files/7556582/config.log)

``` shell
ndpiReader -q -t -i wlo1 -T 20 -U 20
```

### If your bug is reproducible using a pcap, please attach a pcap file (or a valid link to download it)

Example: test.pcap

### Steps to reproduce the behavior:
1. Run '...'
2. Set '....'
3. Do '....'

**Comment by IvanNardi** [comment]
Sorry, but I don't understand. Did your application crash after 3 hours of "live/random" traffic or after 3 hours analyzing always the same 2 pcaps?
Anyway, it is very difficult to look into this issue without a way to reproduce the error.
Some random advice:
* look very, very carefully at your custom allocation functions
* try using ASAN
* try using Vagrind

**Comment by sobrien1234** [comment]
Ivan,

Thanks for your reply. I recognize the difficulty with these kind of issues. I had wishful thinking and was hoping that you would say, “Oh yes, someone else saw that and I have a fix.” I guess I’m not that lucky.

I’m using a call load generator that uses two pcaps as templates. I can recreate the issue within a few hours. I also tried with the default memory allocation and still hit a coredump. It was a different coredump that did not provide a backtrace. I also tried the ndpiReader routine on both pcaps, and the problem did not show. I’ll continue to debug.

Steve

From: Ivan Nardi ***@***.***>
Sent: Wednesday, November 17, 2021 1:16 PM
To: ntop/nDPI ***@***.***>
Cc: O'Brien, Stephen ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [ntop/nDPI] ndpi_patricia_best2() coredump (Issue #1375)


Sorry, but I don't understand. Did your application crash after 3 hours of "live/random" traffic or after 3 hours analyzing always the same 2 pcaps?
Anyway, it is very difficult to look into this issue without a way to reproduce the error.
Some random advice:

  *   look very, very carefully at your custom allocation functions
  *   try using ASAN
  *   try using Vagrind

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://clicktime.symantec.com/3Y56ZHERJCKUN9keZ2eggav6H2?u=https%3A%2F%2Fgithub.com%2Fntop%2FnDPI%2Fissues%2F1375%23issuecomment-971894178>, or unsubscribe<https://clicktime.symantec.com/33gGGUhwBw1cpbvBgCMWTdz6H2?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWRNCLCXQ26YZKAF3UPJMW3UMP5ONANCNFSM5IHRBXIQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://clicktime.symantec.com/3YABdTviPFWBrrKvQbwefVW6H2?u=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675> or Android<https://clicktime.symantec.com/32EFaEo9W1E47EZfhbkN8Bu6H2?u=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub>.

Notice: This e-mail together with any attachments may contain information of Ribbon Communications Inc. and its Affiliates that is confidential and/or proprietary for the sole use of the intended recipient. Any review, disclosure, reliance or distribution by others or forwarding without express permission is strictly prohibited. If you are not the intended recipient, please notify the sender immediately and then delete all copies, including any attachments.

**Comment by utoni** [comment]
I am also not able to reproduce this issue.

Can you give us a full backtrace of the segfault?
Can tell us more about your custom memory wrappers?

Thanks!

**Comment by sobrien1234** [comment]
Toni,

Thanks for the help. I’m on vacation this week and will be back on Monday Nov 29.

Steve

From: Toni ***@***.***>
Sent: Tuesday, November 23, 2021 6:50 AM
To: ntop/nDPI ***@***.***>
Cc: O'Brien, Stephen ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [ntop/nDPI] ndpi_patricia_best2() coredump (Issue #1375)


I am also not able to reproduce this issue.

Can you give us a full backtrace of the segfault?
Can tell us more about your custom memory wrappers?

Thanks!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://clicktime.symantec.com/3GrdtpURgRwJuyWx6D9t5q26H2?u=https%3A%2F%2Fgithub.com%2Fntop%2FnDPI%2Fissues%2F1375%23issuecomment-976483859>, or unsubscribe<https://clicktime.symantec.com/37Ln7E8qsbHzg7zGfSCgRqn6H2?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWRNCLEYBZX2M6EZSKJTFM3UNOEXBANCNFSM5IHRBXIQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://clicktime.symantec.com/3LD9DDpu2iVqFC2dMSnf4c46H2?u=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675> or Android<https://clicktime.symantec.com/33ynhDekxFHH54r6ifsM5Mf6H2?u=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub>.

Notice: This e-mail together with any attachments may contain information of Ribbon Communications Inc. and its Affiliates that is confidential and/or proprietary for the sole use of the intended recipient. Any review, disclosure, reliance or distribution by others or forwarding without express permission is strictly prohibited. If you are not the intended recipient, please notify the sender immediately and then delete all copies, including any attachments.

**Comment by sobrien1234** [comment]
Toni,

I can reproduce the coredump, it occurs in the nDPI code indicating a bad (ndpi_patricia_tree_t *)ndpi_str->protocols_ptree)->head). However, the corruption is happening prior to the event, maybe packets earlier. I am still, slowly, trying to find the memory corruption event. I tend to think that it is not in the nDPI code.

I introduced a malloc, free, and realloc wrapper. This is because malloc()’s are bad for a mult-threaded/realtime environment. The malloc wrapper introduced uses a linked list of preallocated memory buffers on a per thread basis. So, the malloc_wrapper seizes a buffer off the top of a linked list and frees to the bottom. I also introduced a realloc wrapper because the supplied realloc uses memcpy’s. With preallocated memory buffers, the buffers have a fixed sized generally greater than what was requested. In the cases where the preallocated buffer is large enough to handle the realloc size, a memcpy is avoided.

My progress is slow because it takes awhile to reproduce, I’ll send further updates.

Steve

From: Toni ***@***.***>
Sent: Tuesday, November 23, 2021 6:50 AM
To: ntop/nDPI ***@***.***>
Cc: O'Brien, Stephen ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [ntop/nDPI] ndpi_patricia_best2() coredump (Issue #1375)


I am also not able to reproduce this issue.

Can you give us a full backtrace of the segfault?
Can tell us more about your custom memory wrappers?

Thanks!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://clicktime.symantec.com/3GrdtpURgRwJuyWx6D9t5q26H2?u=https%3A%2F%2Fgithub.com%2Fntop%2FnDPI%2Fissues%2F1375%23issuecomment-976483859>, or unsubscribe<https://clicktime.symantec.com/37Ln7E8qsbHzg7zGfSCgRqn6H2?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWRNCLEYBZX2M6EZSKJTFM3UNOEXBANCNFSM5IHRBXIQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://clicktime.symantec.com/3LD9DDpu2iVqFC2dMSnf4c46H2?u=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675> or Android<https://clicktime.symantec.com/33ynhDekxFHH54r6ifsM5Mf6H2?u=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub>.

Notice: This e-mail together with any attachments may contain information of Ribbon Communications Inc. and its Affiliates that is confidential and/or proprietary for the sole use of the intended recipient. Any review, disclosure, reliance or distribution by others or forwarding without express permission is strictly prohibited. If you are not the intended recipient, please notify the sender immediately and then delete all copies, including any attachments.

**Comment by IvanNardi** [comment]
> * try using ASAN
> 
> * try using Vagrind

Any luck using them? You should be able to detect the memory corruption when it really happens...

**Comment by sobrien1234** [comment]
This issue was due to my code. The coredump was from memory corruption due to incorrect flow resource handling. I am using my own memory handling, including flow resources. The call to ndpi_flow_free() was freeing my flow resources. Switching from ndpi_flow_free() to ndpi_flow_data_free() resolved the problem.

Steve

From: Ivan Nardi ***@***.***>
Sent: Tuesday, November 30, 2021 10:36 AM
To: ntop/nDPI ***@***.***>
Cc: O'Brien, Stephen ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [ntop/nDPI] ndpi_patricia_best2() coredump (Issue #1375)


  *   try using ASAN
  *   try using Vagrind

Any luck using them? You should be able to detect the memory corruption when it really happens...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://clicktime.symantec.com/3RgZm6Vp4LG8HxmdsKEz1nM6H4?u=https%3A%2F%2Fgithub.com%2Fntop%2FnDPI%2Fissues%2F1375%23issuecomment-982808667>, or unsubscribe<https://clicktime.symantec.com/3LLLVqTQ2zC9f8vz7RvPatE6H4?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWRNCLGXV3IZMXZTZKBC72TUOT4OLANCNFSM5IHRBXIQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://clicktime.symantec.com/38xjTh9yAimdF97cRSj34Ah6H4?u=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675> or Android<https://clicktime.symantec.com/32MP7FzxVJ8jVRn4qG6zghw6H4?u=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub>.

Notice: This e-mail together with any attachments may contain information of Ribbon Communications Inc. and its Affiliates that is confidential and/or proprietary for the sole use of the intended recipient. Any review, disclosure, reliance or distribution by others or forwarding without express permission is strictly prohibited. If you are not the intended recipient, please notify the sender immediately and then delete all copies, including any attachments.

**Comment by IvanNardi** [comment]
I am glad you found the bug. Closing the issue
