### ISSUE TITLE
Memory overflow in DDoS attacks by nDPI

### ISSUE THREAD

**Issue by brunodeandrade** [ntop/nDPI#139]
Hello, we are using nDPI and nDPIReader to make a tool that can detect the IP's that are causing a DoS and DDoS attack. We have noticed that when we simulate a DDoS attack with more than 20,000 IP's (sending around 1 million packets per second), nDPI consumes a huge amount of memory (almost 14 GB in 20 minutes of attack). 

Could anyone tell me where I can free the data structures to decrease this memory consumption?

Thank you in advance.

**Comment by lucaderi** [comment]
the nDPIreader is a test application for verifying nDPI implementation. Nothing more than that. For continuous packet capture and classification via nDPI please use tools like nProbe

**Comment by shivanikhosa** [comment]
But if thousands of single packet connections come in e.g someone doing a port scan, then the memory consumption goes extremely high since nDPI needs around 8 packets to classify the connection and it doesn't release the memory until then. Is there a plan of classifying these 1 packet connections based on some heuristics to a port scan so that memory can be released ??

**Comment by lucaderi** [comment]
Correct, but this is not a nDPI issue but of the app that uses it. In fact in non nDPI testing apps (such as nProbe or our upcoming nProbe cento) the flow memory is released/allocated in a different way. Example if you see a SYN you do not need to allocate nDPI memory but just when the first payload packets hits your app.
Bottom line: ndpiReader is just a testing application, nothing more than that. It shows you how to use nDPI, as this is the only purpose.

**Comment by shivanikhosa** [comment]
Thanks for your prompt reply. I actually have a different setup. I'm running nDPI inside the linux kernel and using it to filter packets as and when they pass through the network stack. But with these single packet connections coming in during port scans, I allocate memory for flow and id structs when I receive the first packet of a connection but as we don't see any more packets this session is not classified and memory isn't released for a fairly long time i.e until the conntrack expires. When we get thousands of such packets, it causes the kernel to go OOM. I was thinking that a potential way to resolve this issue would be to add a detector to nDPI for a recognizing some portscan traffic but again its hard to classify a session based on just 1 packet. I know its not an nDPI issue as such but wanted to ask if you had any specific ideas about how to solve this problem (e.g loads of single udp packets being sent)

**Comment by shivanikhosa** [comment]
I resolved my issue before by adding an expiry for each conntrack. I have a timer that wakes up and frees up ndpi memory for unclassified conntracks who have hit their expiry. But I was rethinking about what you have mentioned in your reply i.e to not allocate memory when we see the first SYN packet but do it only when we see the first payload. Would it effect the recognition of the connection in any way ?

**Comment by kYroL01** [comment]
Well the recognition of an app is availlable just if nDPI see the payloads, so it doesn't matter of SYN.
