### ISSUE TITLE
PF_RING zcount error

### ISSUE THREAD

**Issue by rathnaTech** [ntop/nDPI#140]
Hi all,
     When i am executing zcount, i can get the below error. Please give me some solution.
### # ****:~/PF_RING-6.0.3/userland/examples_zc$ ./zcount -i eth0 -c 1

pfring_zc_create_cluster error [Operation not permitted] Please check that pf_ring.ko is loaded and hugetlb fs is mounted**
**

Thankyou

**Comment by lucaderi** [comment]
Hi
1. please sudo first
2. if you want to use ZC you must load the ZC drivers and do zcount -i zc:ethX....

**Comment by rathnaTech** [comment]
Thank you Luca,
 I done everything like loaded ZC drivers,make,make install,configure. while running the command as you mentioned above i will get the below details

**-desktop:/home/nbox/PF_RING-6.0.3/userland/examples_zc# ./zcount -i zc:eth0
zcount - (C) 2014 ntop.org
Using PFRING_ZC v.6.0.3.150330
A simple packet counter application.

Usage:   zcount -i <device> -c <cluster id>
                [-h] [-g <core id>] [-R] [-H] [-S <core id>] [-v] [-a]

-h              Print this help
-i <device>     Device name
-c <cluster id> Cluster id
-g <core id>    Bind this app to a core
-a              Active packet wait
-R              Test hw filters adding a rule (Intel 82599)
-H              High stats refresh rate (workaround for drop counter on 1G Intel cards)
-S <core id>    Pulse-time thread for inter-packet time check
-v              Verbose**

here whats is the cluster id ,how do i get that .please explain me i am confused. 

Thank you
