### ISSUE TITLE
Regarding nDPI

### ISSUE THREAD

**Issue by rathnaTech** [ntop/nDPI#141]
Hi Luca and all,
                Does nDPI is capable to capture 10G interface card packets ??

Thank you,

**Comment by lucaderi** [comment]
Yes of course. You need 2 threads for handling a 10G pipe, but we're developing a micro-nDPI (see http://www.ntop.org/nprobe/towards-100-gbit-flow-based-network-monitoring/) that will be way faster as we are targeting 100G

**Comment by rathnaTech** [comment]
Thank you for your response Luca,
    Is it possible to combine nDPI with (tcpdump or libpcap ) to read the packet indepth.
   For example: 

**14:53:56.978664 IP (tos 0x0, ttl 64, id 14072, offset 0, flags [DF], proto TCP (6), length 60)
    192.168.200.193.49850 > maa03s21-in-f1.1e100.net.https: Flags [S], cksum 0xd23a (correct), seq 593875615, win 29200, options [mss 1460,sackOK,TS val 4465168 ecr 0,nop,wscale 7], length 0**

-----> I want to get the above details for skype,whatsapp  protocols. nDPI is the only library supporting these protocols. So,i have an idea to combine these two things.please suggest me the possible solutions.

Thank you,

**Comment by rathnaTech** [comment]
Hi Luca,
  Are you there ??.Please reply me the above question

Thank you,

**Comment by lmangani** [comment]
@rathnaTech this tracker is dedicated to issues of nDPI, you might want to look into ntopng which already covers such feature to a large extent. if you need custom development or professional support please email support@ntop.org

**Comment by rathnaTech** [comment]
Thank you imagani
