### ISSUE TITLE
VXLAN support

### ISSUE THREAD

**Issue by DimaWittmann** [ntop/nDPI#1428]
Hello,

I noticed that there is no VXLAN support in nDPI at the moment. Maybe you have a suggestion on how to detect this protocol with nDPI or do I just need to add the VXLAN protocol dissector? 

Thank you for your time and work!

**Comment by vitalivanov** [comment]
@lucaderi @cardigliano can you pls comment?

**Comment by IvanNardi** [comment]
To add support for VXLAN you probably need some "decapsulation code" (in `example/reader_utils.c`) instead of a real protocol dissector. Take a look at GTP/CAPWAP.
My 2 cents

**Comment by DimaWittmann** [comment]
@IvanNardi Thank you for the replay. 
I see what you mean, I have the decapsulation code but I want to make it configurable. When I disable the decapsulation code nDPI detects VXLAN tunnel as RX protocol. This is not really intended behavior. 
That is why I want to add VXLAN dissector.

**Comment by IvanNardi** [comment]
Done in 4cf85354
