### ISSUE TITLE
i get an error while compiling nDPI

### ISSUE THREAD

**Issue by rathnaTech** [ntop/nDPI#144]
***_Using nDPI (1.7.0) [1 thread(s)]
Capturing live traffic from device eth0...
Capturing traffic up to 5 seconds
Running thread 0...
Segmentation fault (core dumped)
*_
**
i got the above error while compiling nDPi.

**Comment by lucaderi** [comment]
Please provide a way to reproduce it with nDPIreader

**Comment by kYroL01** [comment]
Try to update your nDPI to the latest version that you can find in the _dev_ branch [1.7.1-dev] and let us know.
I tried and no sigfault arise

**Comment by rathnaTech** [comment]
@kYroL01 
 Hi .Thank you I solved the problem
Please watch the link https://github.com/ntop/nDPI/pull/142 and respond me for the query i asked.
