### ISSUE TITLE
found an issue in nDPI

### ISSUE THREAD

**Issue by rathnaTech** [ntop/nDPI#145]
Dear all,
     while running ./ndpireader  it will detect website as a protocol.

for example:
i am loading www.whatsapp.com it shows in detected protocols (whatsapp packets -1 flows -3) 
My question is that i am loading http protocol right why it show htttp as whatsapp.

And actually nDPI should detect whatsapp protocol for whatsapp application.but it also detect website as protocol.

**Comment by kYroL01** [comment]
I think the point is that for a http packet we also try if there is a host name match here https://github.com/ntop/nDPI/blob/dev/src/lib/ndpi_content_match.c.inc#L7404 .

Later I'll check better.

**Comment by rathnaTech** [comment]
so if i am using application for whatsapp it will  also detect a protocol right.
if i am using whatsapp.com you are tracking the string and marked it as a protocol.
michele

**Comment by kYroL01** [comment]
Yes exactly. nDPI parse the url of the payload to find more information about the application protocol. If you using whatsapp app or visit the website, the packets as inside the host name of the application, and this is why they are detecting as the same protocol.
This is not a bug, is the behaviour of nDPI.
I think this aspect maybe must be re-consider for a better implementation. I'll see in the future.

**Comment by rathnaTech** [comment]
Thank you michele i understood .

you have made some algorithm to read the hostname in that certificate.using that you have printed the DNS and protocol name right.

Is it possible to get the payload and data using that algorithm for application protocols??
i am  looking forward for your response as soon as possible..

**Comment by lucaderi** [comment]
No this is something we won't provide as nDPI is not the place for doing this kind of things.
