### ISSUE TITLE
Size of struct ndpi_detection_module_struct is too big!

### ISSUE THREAD

**Issue by vel21ripn** [ntop/nDPI#1458]
The ndpi_detection_module_struct structure contains 5 "struct ndpi_call_function_struct" arrays of 286*144=41 kB size,
 which are occupied by a small number of elements.

At the moment we have callback_buffer_size = 172, tcp_with_payload=114, tcp_no_payload=8, udp=93, other 8.
NDPI_MAX_SUPPORTED_PROTOCOLS = 285.

Size of struct ndpi_detection_module_struct is 253136 bytes. 
Size of all structs ndpi_call_function_struct 5\*286\*144=205920 bytes.
Real use  memory size for struct ndpi_call_function_struct is  (173+224)\*144=57168 bytes. 

I propose to abandon the static allocation of memory. If there are no objections, then I will prepare a PullRequest.

**Comment by utoni** [comment]
I am curious about that possible change. Everything that reduces memory consumption, even if it's "only" a per-thread allocated detection module struct, is welcome. As long as the performance trade-off does not kill any memory savings.

**Comment by IvanNardi** [comment]
> I am curious about that possible change. Everything that reduces memory consumption, even if it's "only" a per-thread allocated detection module struct, is welcome. As long as the performance trade-off does not kill any memory savings.

+1 (some of these bitmasks are used in hot path (via `check_ndpi_detection_func`))

**Comment by vel21ripn** [comment]
There is already a working version. I will try to make a PR soon.

**Comment by vel21ripn** [comment]
#1487 is directly related to this issue.

**Comment by IvanNardi** [comment]
Done in 4896dabb6b8d3469f87fa8c746ee070b12429024
