### ISSUE TITLE
Azure IPList link has changed

### ISSUE THREAD

**Issue by sharonenoch** [ntop/nDPI#1473]
The link in the azure_ip_addresses_download.sh script that downloads the ips is no longer valid.. MS has changed it couple of days back..   Not sure how we would keep up with the links if it keeps changing often..

Below is the new link though..

https://download.microsoft.com/download/7/1/D/71D86715-5596-4529-9B13-DA13A5DE5B63/ServiceTags_Public_20220228.json

**Comment by sharonenoch** [comment]
Looks like they are changing only the dates in the file name.. This would work to extract the file link first.. and the use that to download the actual ip list.. Not sure if its a long term fix though..

`curl -s -w "%{http_code}" https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519 | grep -E 'ServiceTags_Public_[[:digit:]]+.json' | grep -o -E 'href=\"[^"]+' | sed 's/href="//'  | uniq`

```
root@kickseed:~/nDPI# curl -s -w "%{http_code}" https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519 | grep -E 'ServiceTags_Public_[[:digit:]]+.json' | grep -o -E 'href=\"[^"]+' | sed 's/href="//'  | uniq
https://download.microsoft.com/download/7/1/D/71D86715-5596-4529-9B13-DA13A5DE5B63/ServiceTags_Public_20220228.json
```

**Comment by IvanNardi** [comment]
> Not sure if its a long term fix though..

It can't be worse than the current code...
@sharonenoch, are you going to push a PR yourself?

**Comment by sharonenoch** [comment]
@IvanNardi I added the PR [#1480](https://github.com/ntop/nDPI/pull/1480). 

Can you please check.. Its the first time I am doing this operation in github. I believe I used the proper guidelines and procedure for the same. 

Below is the execution output with the fix.

root@kickseed:~/nDPI/utils# ./azure_ip_addresses_download.sh
(1) Downloading file... https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519
(2) Downloading file... https://download.microsoft.com/download/7/1/D/71D86715-5596-4529-9B13-DA13A5DE5B63/ServiceTags_Public_20220228.json
(3) Processing IP addresses...
(4) Microsoft Azure IPs are available in ../src/lib/ndpi_azure_match.c.inc

**Comment by sharonenoch** [comment]
Has been merged to dev https://github.com/ntop/nDPI/pull/1480.
