### ISSUE TITLE
Fix compile warnings and tests for Windows.

### ISSUE THREAD

**Issue by utoni** [ntop/nDPI#1486]
Starting with PR #1483 there is now CI support for native Windows builds.
As mentioned by @aouinizied and verified via [Github Actions](https://github.com/ntop/nDPI/runs/5474037710?check_suite_focus=true) there some compile warnings. Some unit and/or integration tests will fail as well.

We should also consider to re-activate at least one MingW compilation step. This may be useful, because MingW handles some things more GNU CC alike then the Windows CC does. I am using MingW quite often for cross compilation and nDPI's current build system explicitly supports Mingw cross compilation. So it should be tested in a CI environment.

**Comment by mmaypo** [comment]
so i'm brand new to this party, but i just pulled latest stable, #define'd NDPI_LIB_COMPILATION and tried to build under windows using the .SLN / .VCXPROJ  files, and there are a large number of missing link references.  for example, in ndpi_main.h, most of the function declarations have no corresponding definition in .c
What am i missing here?

**Comment by utoni** [comment]
> tried to build under windows using the .SLN / .VCXPROJ  files, and there are a large number of missing link references

The Visual Studio leftovers are not updated regularly. They are ancient, alone and forsaken.

If you can spare some of your precious time, feel free to fix that and send a PR.

**Comment by utoni** [comment]
> What am i missing here?

Can you please share the output of the VS build log?

**Comment by mmaypo** [comment]
[ndpi_win-mmaypo_2022-03-10.zip](https://github.com/ntop/nDPI/files/8227397/ndpi_win-mmaypo_2022-03-10.zip)

i've attached a combined patch of changes it took to get the project to compile in VS on my windows 10 system under VS2019 (toolset not updated).  There seem to be a number of changes which would have been set up in linux during config, but not under windows. Also some random issues - e.g. roaring has a parameter to several functions with the name `small`  which happened to be an alias for type char somewhere. Changing the name to something else,  like `small_set` fixed it.   The patch is way too kludged up for a PR, but hopefully it can get someone started.

**Comment by mmaypo** [comment]
[ndpi_win-mmaypo_2022-03-10.zip](https://github.com/ntop/nDPI/files/8227493/ndpi_win-mmaypo_2022-03-10.zip)
last comment seems to have disappeared. anyway, i got it compiling under VS 2019 (toolset not updated) on a windows 10 system, and the patch is way too kludged up for a PR. hopefully it may be helpful to a maintainer

**Comment by utoni** [comment]
Got your comment via Mail. Dunno how and why it disappeared.

> [ndpi_win-mmaypo_2022-03-10.zip](https://github.com/ntop/nDPI/files/8227397/ndpi_winmmaypo_2022-03-10.zip)
>
>i've attached a combined patch of changes it took to get the project to compile in VS on my windows 10 system under VS2019 (toolset not updated).  There seem to be a number of changes which would have been set up in linux during config, but not under windows. Also some random issues - e.g. roaring has a parameter to several functions with the name `small`  which happened to be an alias for type char somewhere. Changing the name to something else,  like `small_set` fixed it.   The patch is way too kludged up for a PR, but hopefully it can get someone started.

**Comment by utoni** [comment]
I've tried your vcxproj with VS-2019 w/o success. I am not a VS expert but IMHO as long as nDPI uses autotools there may not be an easy way to automatically update VS files for example when a new protocol dissector or other *.c files are added. And manually updating files crucial for an IDE does not seem to be a good idea (as it is the case right now).

Any ideas? @mmaypo

**Comment by mmaypo** [comment]
agreed - autotools means there isn't an easy way for windows. All i can suggest is an alternative like cmake or bazel

**Comment by utoni** [comment]
Fixed with c3df3a12aa88739e303340ccd7436d467b4662d2 (PR #1491).
