### ISSUE TITLE
False positive for Viber detection

### ISSUE THREAD

**Issue by kYroL01** [ntop/nDPI#149]
In a recent pcap I notice that VIber protocol are detected in a false positive way.
Need to investigate.

**Comment by Mile-Lile** [comment]
I have some Viber traces from desktop if it can help...
[Viber_desktop.zip](https://github.com/ntop/nDPI/files/170388/Viber_desktop.zip)

**Comment by kYroL01** [comment]
7c511fb2f2b827f96349f6fb0e2193f9793aa068
