### ISSUE TITLE
Sometimes NDPI_API_VERSION is empty

### ISSUE THREAD

**Issue by socketpair** [ntop/nDPI#1494]
configure.ac contains these lines of code:

```sh
NDPI_API_VERSION=`echo $SOURCE_DATE_EPOCH | cut -c7-10`
NDPI_API_VERSION=`echo $NDPI_API_VERSION | sed 's/^0*//'`
```
On my build system:
```
setting SOURCE_DATE_EPOCH=1648080000
```
So, according to this code NDPI_API_VERSION= become empty.
This is a bug.

**Comment by socketpair** [comment]
The patch:
```diff
--- a/src/lib/Makefile.in
+++ b/src/lib/Makefile.in
@@ -12,9 +12,9 @@
 # Installation directories
 #
 prefix     = @prefix@
-libdir     = ${prefix}/lib
-includedir = ${prefix}/include/ndpi
-CFLAGS     += -fPIC -DPIC -I../include -Ithird_party/include -DNDPI_LIB_COMPILATION @CFLAGS@ @CUSTOM_NDPI@
+libdir     = @libdir@
+includedir = @includedir@/ndpi
+CFLAGS     += -fPIC -DPIC -I../include -Ithird_party/include -DNDPI_LIB_COMPILATION @CFLAGS@ @CUSTOM_NDPI@ 
 LDFLAGS    = @LDFLAGS@
 LIBS       = @ADDITIONAL_LIBS@ @LIBS@
 
# https://github.com/ntop/nDPI/issues/1494
--- a/configure.ac
+++ b/configure.ac
@@ -75,11 +75,9 @@
      if test -z "$SOURCE_DATE_EPOCH" ; then :
          SOURCE_DATE_EPOCH=`date +%s`
      fi
-     NDPI_API_VERSION=`echo $SOURCE_DATE_EPOCH | cut -c7-10`
+     NDPI_API_VERSION=$((SOURCE_DATE_EPOCH % 65536))  # u_int16_t ndpi_get_api_version()
 fi
 
-NDPI_API_VERSION=`echo $NDPI_API_VERSION | sed 's/^0*//'`
-
 echo "Setting API version to $NDPI_API_VERSION"
 
 AC_DEFINE_UNQUOTED(NDPI_GIT_RELEASE, "${GIT_RELEASE}", [GIT Release])
 ```

**Comment by utoni** [comment]
IMHO using an automatic generated, timestamp based API version is meaningless to me and not fail-safe.
But your patch does fix a bug, but does not fix the "wrapping around" issue described in #1189. You may want to create a PR, so we can check if the CI agrees with your patch.

**Comment by socketpair** [comment]
@lnslbrty Since API is not backward compatible, just incrementing gives nothing. I would generate a random sequence. Or, as a hash of required files. Are you OK with it ? If one compiles from git, the code count number of lines in a few files. I can:
1. calculate some fast hash (MD5?) from contents of these files
2. change API version from uint16_t to uint64_t.
3. store last 8 bytes of hash as a number in API_VERSION.

So, if somthing changes not realted to API, or just one decide to recompile, he will have the same API VERSION.

**Comment by utoni** [comment]
> Are you OK with it ?

Sure.

>     1. calculate some fast hash (MD5?) from contents of these files
> 
>     2. change API version from uint16_t to uint64_t.
> 
>     3. store last 8 bytes of hash as a number in API_VERSION.

But I still think an incremented API version (or something more [semver](https://semver.org/)ish) is useful, because sometimes libnDPI can be backward API compatible e.g. when adding a new function symbol to the public interface, add a new struct member or a bugfix.

There is just no workflow regarding API compatibility, but that may change in the future.

**Comment by socketpair** [comment]
Well if you insist on incremental API version, I would set NDPI_API_VERSION=$SOURCE_DATE_EPOCH. Is it OK, so ?

Anyway, mix of branches, backports and git/non-git builds break the rules. The best way actually to increment API version by hand. Or, stick to hash method :).

Please decide. I vote for hash method.

**Comment by utoni** [comment]
> Well if you insist on incremental API version, I would set NDPI_API_VERSION=$SOURCE_DATE_EPOCH. Is it OK, so ?

Agreed. Let's see if the CI also agrees. :)

> The best way actually to increment API version by hand.

+1

**Comment by socketpair** [comment]
Well. Please decide how to calculate version. I will implement.

**Comment by utoni** [comment]
I am not sure what is the best solution here, but I would go with increasing the size of the API version.

**Comment by utoni** [comment]
Does this issue still persists in the current dev branch? @socketpair

**Comment by socketpair** [comment]
Yes, nothing was changed AFAIK for the problem. I made patches in our build system.
