### ISSUE TITLE
Is it possible to extract the GTP protocols??

### ISSUE THREAD

**Issue by rathnaTech** [ntop/nDPI#150]
Hi all,
     I got the flow details and protocol list using nDPi.Is it possible to extract the GTP protocols.If yes please suggest me the way.

**Comment by lucaderi** [comment]
Yes. See ndpiReader -h
  -t                        | Dissect GTP/TZSP tunnels

**Comment by rathnaTech** [comment]
I used that i want see indepth of GTP. Is it anyway to do that.Like wireshark did.
