### ISSUE TITLE
Build error in ndpi4.2-stable

### ISSUE THREAD

**Issue by subhajit-cdot** [ntop/nDPI#1505]
I was trying to build ndpi 4.2-stable in debian buster. 

**System information:**
subhajit@debian-ndpi:~/migration/ndpi$ uname -a
Linux debian-ndpi 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux

subhajit@debian-ndpi:~/migration/ndpi$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

**Commands used for build:**

sudo mk-build-deps --install --remove debian/control
sudo debuild -uc -us -i -b
`

**ISSUE1:** 
I have updated all required patches , and initially I got an error regarding  math library

`
gcc -Wdate-time -D_FORTIFY_SOURCE=2 -g -fPIC -DPIC -I../src/include -DHAVE_JSON_C  -g -O2 -fdebug-prefix-map=/ndpi/build_dir=. -fstack-protector-strong -Wformat -Werror=format-security -I/usr/include/json-c -Wl,-z,relro -Wl,-z,now ndpiReader.o libndpiReader.a -L../src/lib -lndpi -lpcap   -lpthread -o ndpiReader
/usr/bin/ld: ndpiReader.o: undefined reference to symbol 'sqrt@@GLIBC_2.2.5'
/usr/bin/ld: //lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
`

I resolved this issue adding -lm in example/Makefile.in

LIBS+=-lpthread -lm

**ISSUE2:**
Then I got the below error regarding JSON

`
Type your question in a clear and concise way to help the community answering it.Making all in tests
make[2]: Entering directory '/ndpi/build_dir/tests'
make[2]: Leaving directory '/ndpi/build_dir/tests'
Making all in tests/unit
make[2]: Entering directory '/ndpi/build_dir/tests/unit'
gcc -g -fPIC -DPIC -I../../src/include @JSONC_CFLAGS@  -g -O2 -fdebug-prefix-map=/ndpi/build_dir=. -fstack-protector-strong -Wformat -Werror=format-security -I/usr/include/json-c -Wdate-time -D_FORTIFY_SOURCE=2 -c unit.c -o unit.o
gcc: error: JSONC_CFLAGS@: No such file or directory
make[2]: *** [Makefile:30: unit.o] Error 1
make[2]: Leaving directory '/ndpi/build_dir/tests/unit'
make[1]: *** [Makefile:504: all-recursive] Error 1
make[1]: Leaving directory '/ndpi/build_dir'
dh_auto_build: make -j8 returned exit code 2
make: *** [debian/rules:13: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -i -b failed
`

Where should I add JSONC_CFLAGS information? I am not sure how pkgconfig comes into picture here in debian build.
Please guide.

Thanks
Subhajit

**Comment by subhajit-cdot** [comment]
**example/uthash.h path needs to be changed in  libndpi-dev.docs with src/lib/third_party/include/uthash.h, otherwise below error will come**


/usr/bin/mkdir -p '/home/cdot/migration/ndpi/debian/tmp/usr/lib/x86_64-linux-gnu/pkgconfig'
 /usr/bin/install -c -m 644 libndpi.pc '/home/cdot/migration/ndpi/debian/tmp/usr/lib/x86_64-linux-gnu/pkgconfig'
make[4]: Leaving directory '/home/cdot/migration/ndpi'
make[3]: Leaving directory '/home/cdot/migration/ndpi'
make[2]: Leaving directory '/home/cdot/migration/ndpi'
rm /home/cdot/migration/ndpi/debian/tmp/usr/share/ndpi/*.txt
make[1]: Leaving directory '/home/cdot/migration/ndpi'
   dh_install
   dh_installdocs
dh_installdocs: Cannot find (any matches for) "example/uthash.h" (tried in ., debian/tmp)

make: *** [debian/rules:13: binary] Error 9
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2

**Comment by lucaderi** [comment]
Please provide a pull request with the fix you have identified
