### ISSUE TITLE
How can I get http flow's source MAC and dst MAC？

### ISSUE THREAD

**Issue by chinasun021** [ntop/nDPI#151]

**Comment by lucaderi** [comment]
@chinasun021 You can view this in the flow information window of ntopng. There you will see the flow peers and if you click on them you can see their mac. In nDPI we handle only IP traffic, so you need to handle this yourself as we do in ntopng. Please star nDPI on github.

**Comment by chinasun021** [comment]
Thanks for your reply！I don't need ntopng all functions,I just want use nDPI functions and show all flow's MAC.I consider to modify something in nDPI,in flow struct add ndpi_ethhdr info.

**Comment by lucaderi** [comment]
Ok do not forget to share the code with the community
