### ISSUE TITLE
kernel panic after running make

### ISSUE THREAD

**Issue by alireza11048** [ntop/nDPI#1511]
Hi,
I have just cloned the nDPI in my ubuntu 20.04 and run autogen.sh, configure.sh and make. and then run tests/do.sh. 
after that, I can't boot up the ubuntu and I get "kernel panic not syncing attempted to kill init ..."

I know that it is a little odd, but anybody has experienced this problem?

thanks

**Comment by utoni** [comment]
Does not seem to be related to nDPI.
