### ISSUE TITLE
Some bugs in ndpiReader

### ISSUE THREAD

**Issue by alexspirt** [ntop/nDPI#152]
Hi, all.

Thanks for this great library and example app ndpiReader.
I found some bugs when used ndpiReader.
1. ndpiReader.c
   543: `json_object_object_add(jObj,"host_n.port",json_object_new_int(ntohs(flow->upper_port)));`
   "host_n.port" should be replaced with "host_b.port"
2. When ndpiReader processes pcap list it does not close pcap files. On Linux it can lead to error: "Too many open files". But ndpiReader does not print any error and exits correctly from cycle.

```
pcap_loop:
  runPcapLoop(thread_id);
  if(playlist_fp[thread_id] != NULL) { /* playlist: read next file */
    char filename[256];
    if(getNextPcapFileFromPlaylist(thread_id, filename, sizeof(filename)) == 0 &&
       (ndpi_thread_info[thread_id]._pcap_handle = pcap_open_offline(filename, ndpi_thread_info[thread_id]._pcap_error_buffer)) != NULL) {
      configurePcapHandle(thread_id);
      goto pcap_loop;
    }
  }

```

**Comment by lucaderi** [comment]
@alexspirtmsu Can you please send us a pull request?

**Comment by kYroL01** [comment]
@alexspirtmsu point 1 of course is a typo.
Point 2 I'm not completely agree with you. I did a test and I go through the code with gdb, and the **._pcap_handle** ( the result of _pcap_open_offline_ ) is overwritten every time a pcap is open, so we handle just one open file for pcap avery time we process it.

I also try to put  **pcap_close(ndpi_thread_info[thread_id]._pcap_handle);** in these way:

```
  if(getNextPcapFileFromPlaylist(thread_id, filename, sizeof(filename)) == 0 &&
         (ndpi_thread_info[thread_id]._pcap_handle = pcap_open_offline(filename,   ndpi_thread_info[thread_id]._pcap_error_buffer)) != NULL) {
        configurePcapHandle(thread_id);
        pcap_close(ndpi_thread_info[thread_id]._pcap_handle);
        goto pcap_loop;
  }
}
```

```
  if(getNextPcapFileFromPlaylist(thread_id, filename, sizeof(filename)) == 0 &&
         (ndpi_thread_info[thread_id]._pcap_handle = pcap_open_offline(filename,   ndpi_thread_info[thread_id]._pcap_error_buffer)) != NULL) {
        configurePcapHandle(thread_id);
        goto pcap_loop;
   }
   pcap_close(ndpi_thread_info[thread_id]._pcap_handle);
}
```

in the first case the output say: 

> **\* Error in `./ndpiReader': malloc(): memory corruption: 0x00007fcb14000098 ***

in the second: 

> **\* Error in `./ndpiReader': double free or corruption (out): 0x00007f475808c060 ***

I inspected with Valrind and this function https://github.com/ntop/nDPI/blob/dev/example/ndpiReader.c#L1453
is called here https://github.com/ntop/nDPI/blob/dev/example/ndpiReader.c#L2006, after the _processing_thread_ function (the one who did the work).

Have you noticed something different or collateral errors? Open with any kinda discussion.

**Comment by kYroL01** [comment]
6df31099c21198643336cc3a064df33cb559c547

**Comment by kYroL01** [comment]
@alexspirtmsu any news ? I close the issue. If you're not agree with the things I wrote, write here. Thanks
