### ISSUE TITLE
Add request: Spanning Tree Protocol filter

### ISSUE THREAD

**Issue by Mile-Lile** [ntop/nDPI#156]
`The Spanning Tree Protocol (STP) is a network protocol that ensures a loop-free topology for Ethernet networks. The basic function of STP is to prevent bridge loops and the broadcast radiation that results from them. Spanning tree also allows a network design to include spare (redundant) links to provide automatic backup paths if an active link fails, without the danger of bridge loops, or the need for manual enabling or disabling of these backup links.

Spanning Tree Protocol (STP) was originally standardized as IEEE 802.1D, in 802.1d-1998, but much of the functionality (spanning tree, rapid spanning tree, multiple spanning tree) previously specified in 802.1D, 802.1s, 802.1w has been incorporated into IEEE 802.1Q-2014[1]

As the name suggests, it creates a spanning tree within a network of connected layer-2 bridges (typically Ethernet switches), and disables those links that are not part of the spanning tree, leaving a single active path between any two network`

https://drive.google.com/open?id=0B0SCwy1irn3qVDlhNXkzd3hkVTg

**Comment by kYroL01** [comment]
Hello @Mile-Lile 
The STP protocol dissector is a must-to-do thing that I wanted to do, but I didn't do yet for a reason: nDPI (and ntopng) doesn't show the L2-only packets (i.e. ARP packets also).
This choice is because we are interested in discovery application flows.
For the purpouse you evidence I think that we must re-think to add this features in a good way, also without change completely the nature of nDPI.

**Comment by Mile-Lile** [comment]
Thx @kYroL01 for your time. 
I am aware that nDPI do layer7 inspection and that inspecting L2 packet is not maybe interesting for
nDPI devs and needs lots of your free time. This was just suggestion because I think that marking such packets and prioritizing them in network could be useful... If this is changing the nature of nDPI
then maybe it is not very good idea:)
Thx again

**Comment by kYroL01** [comment]
We'll think better and we will see. 
I think this is a good point in general, but I don't know if usefull here.
For now I let open this issue for thinking about it.

**Comment by kYroL01** [comment]
I think about it and I guess this feature, for now, is not applicable to nDPI. Maybe I guess I could add STP but is better don't add overhead not so usefull for the purpose of nDPI.
