### ISSUE TITLE
Setup ndpi

### ISSUE THREAD

**Issue by ghadaashra** [ntop/nDPI#1568]
Hello
I didn't know how I setup ndpi and how I can use it

**Comment by utoni** [comment]
Please read the [nDPI Readme](https://github.com/ntop/nDPI/blob/dev/README.md) first.

**Comment by utoni** [comment]
@ghadaashra
Any updates? Any specific questions?
Was the ReadMe helpful?
Any critique or suggestions for improvement?

**Comment by httsp0werz** [comment]
> @ghadaashra Any updates? Any specific questions? Was the ReadMe helpful? Any critique or suggestions for improvement?

Can't say, that there is enought information to create protocol by just examples of another protocols. Got a bunch of examples of other peoples protocols created, but its not helpful too. Can silly mortals have a detailed guide please? :)

**Comment by utoni** [comment]
> Can't say, that there is enought information to create protocol by just examples of another protocols. Got a bunch of examples of other peoples protocols created, but its not helpful too. Can silly mortals have a detailed guide please? :)

This issue is not related to protocol dissector development.
But anyway; At first I need to know what kind of guide you desire.
You want some code snippets with explanations and comments?

**Comment by httsp0werz** [comment]
> > Can't say, that there is enought information to create protocol by just examples of another protocols. Got a bunch of examples of other peoples protocols created, but its not helpful too. Can silly mortals have a detailed guide please? :)
> 
> This issue is not related to protocol dissector development.

Woah, thanks for quick reply!
Apologize for offtop, just started to reading all of the issues trying to collect some information to resolve my problems.

> But anyway; At first I need to know what kind of guide you desire. You want some code snippets with explanations and comments?

Yep, that will be great.

ps:
Im just trying to make coursework adding a simple protocol with XX payload, XX XX XX XX bitmask and specified ports. Duplicated rdp.c, made some changes, beat all the compilation problems, but protocol is still [0]Unknown. And ofc have at do.sh "[NDPI] INTERNAL ERROR missing protoName initialization for [protoId=297]: recovering", found ticket in issues with answer like "Send us ur protocol so we'll add it", but it doesnt satisfied me, cause its fun for me to research, its not about "pls devs make it work" :D

**Comment by utoni** [comment]
> ps: Im just trying to make coursework adding a simple protocol with XX payload, XX XX XX XX bitmask and specified ports. Duplicated rdp.c, made some changes, beat all the compilation problems, but protocol is still [0]Unknown. And ofc have at do.sh "[NDPI] INTERNAL ERROR missing protoName initialization for [protoId=297]: recovering", found ticket in issues with answer like "Send us ur protocol so we'll add it", but it doesnt satisfied me, cause its fun for me to research, its not about "pls devs make it work" :D

Did you add `ndpi_set_proto_defaults()` for your protocol dissector in `ndpi_init_protocol_defaults()` ?

**Comment by httsp0werz** [comment]
> > ps: Im just trying to make coursework adding a simple protocol with XX payload, XX XX XX XX bitmask and specified ports. Duplicated rdp.c, made some changes, beat all the compilation problems, but protocol is still [0]Unknown. And ofc have at do.sh "[NDPI] INTERNAL ERROR missing protoName initialization for [protoId=297]: recovering", found ticket in issues with answer like "Send us ur protocol so we'll add it", but it doesnt satisfied me, cause its fun for me to research, its not about "pls devs make it work" :D
> 
> Did you add `ndpi_set_proto_defaults()` for your protocol dissector in `ndpi_init_protocol_defaults()` ?

Yup, just recompiled everything to be sure I didnt broke everything :D

Made it like this:

```
  ndpi_set_proto_defaults(ndpi_str, 1 /* cleartext */, NDPI_PROTOCOL_UNRATED, NDPI_PROTOCOL_RADMIN,
                          "RADMIN", NDPI_PROTOCOL_CATEGORY_REMOTE_ACCESS,
                          ndpi_build_default_ports(ports_a, 0, 0, 0, 0, 0) /* TCP */,
                          ndpi_build_default_ports(ports_b, 0, 0, 0, 0, 0) /* UDP */);
```

just copied one of protocols and changed it

now i solve this problem by changing category to "NDPI_PROTOCOL_CATEGORY_REMOTE_ACCESS" (like in example below)

but its doesnt helped me to detect my protocol in .pcap, and now im 99% sure that problem is in protocol/MYSTUFF.C

and for now i have two not working examples:

First - modified example from coursework explanation:

```
#include "ndpi_protocol_ids.h"
#include "ndpi_api.h"
void ndpi_search_radmin(struct ndpi_detection_module_struct *ndpi_struct,
    struct ndpi_flow_struct *flow){
    struct ndpi_packet_struct *packet = &ndpi_struct->packet;
    if (packet->tcp != NULL) {
        uint32_t w = htonl(get_u_int32_t(packet->payload, 0));

        if(packet->payload_packet_len == 20
            && packet->payload[0] == 0x00
            && packet->payload[1] == 0x00
            && packet->payload[2] == 0x00
            && packet->payload[3] == 0x10){
            ndpi_set_detected_protocol(ndpi_struct, flow, NDPI_PROTOCOL_RADMIN,
            NDPI_PROTOCOL_UNKNOWN, NDPI_CONFIDENCE_DPI);
            return;
        }

        if(packet->payload_packet_len == 52
            && packet->payload[0] == 0x00
            && packet->payload[1] == 0x00
            && packet->payload[2] == 0x00
            && packet->payload[3] == 0x30){
            ndpi_set_detected_protocol(ndpi_struct, flow, NDPI_PROTOCOL_RADMIN,
            NDPI_PROTOCOL_UNKNOWN, NDPI_CONFIDENCE_DPI);
        return;
        }
    }
}
```

And second is mine rdp.c rework attempt:

```
#include "ndpi_protocol_ids.h"
#define RADMIN_PORT 4899
#include "ndpi_api.h"


void ndpi_search_radmin(struct ndpi_detection_module_struct *ndpi_struct,
                     struct ndpi_flow_struct *flow) {
  struct ndpi_packet_struct *packet = &ndpi_struct->packet;

  NDPI_LOG_DBG(ndpi_struct, "search radmin packets \n");

  if (packet->tcp != NULL) {
        u_int16_t s_port = ntohs(packet->tcp->source);
        u_int16_t d_port = ntohs(packet->tcp->dest);
    if ((packet->payload_packet_len == 20 && ((s_port == RADMIN_PORT) || (d_port == RADMIN_PORT)))
                        && get_u_int8_t(packet->payload, 0) == 0x00
                        && get_u_int8_t(packet->payload, 1) == 0x00
                        && get_u_int8_t(packet->payload, 2) == 0x00
                        && get_u_int8_t(packet->payload, 3) == 0x10) {
        NDPI_LOG_INFO(ndpi_struct, "found radmin \n");
        return;
        }
  } else if(packet->tcp != NULL) {
        u_int16_t s_port = ntohs(packet->tcp->source);
           u_int16_t d_port = ntohs(packet->tcp->dest);
    if ((packet->payload_packet_len == 52 && ((s_port == RADMIN_PORT) || (d_port == RADMIN_PORT)))
                        && get_u_int8_t(packet->payload, 0) == 0x00
                        && get_u_int8_t(packet->payload, 1) == 0x00
                        && get_u_int8_t(packet->payload, 2) == 0x00
                        && get_u_int8_t(packet->payload, 3) == 0x30) {
        NDPI_LOG_INFO(ndpi_struct, "found radmin \n");
        return;
                }
        }
}

void init_radmin_dissector(struct ndpi_detection_module_struct *ndpi_struct, u_int32_t *id, NDPI_PROTOCOL_BITMASK *detection_bitmask)
{
  ndpi_set_bitmask_protocol_detection("RADMIN", ndpi_struct, detection_bitmask, *id,
                                      NDPI_PROTOCOL_RADMIN,
                                      ndpi_search_radmin,
                                      NDPI_SELECTION_BITMASK_PROTOCOL_V4_V6_TCP_OR_UDP_WITH_PAYLOAD_WITHOUT_RETRANSMISSION,
                                      SAVE_DETECTION_BITMASK_AS_UNKNOWN,
                                      ADD_TO_DETECTION_BITMASK);

  *id += 1;
}
```

in ndpi_protocols.h i added this two lines:

```
void ndpi_search_radmin(struct ndpi_detection_module_struct *ndpi_struct, struct ndpi_flow_struct *flow);
void init_radmin_dissector(struct ndpi_detection_module_struct *ndpi_struct, u_int32_t *id, NDPI_PROTOCOL_BITMASK *detection_bitmask);
```

I thought that im using working prototypes, and tried to change just bitmask and payload values, but something went wrong

its bit awkward that ur replies if faster than mine :D


quick upd:

you were right, in last build i forgot to change NDPI_PROTOCOL_RDP to my own protocol name

**Comment by utoni** [comment]
So your protocol dissector works now as expected?

**Comment by httsp0werz** [comment]
> So your protocol dissector works now as expected?

nope :D

tried to just change just packet->payload values in existed protocol (xdmcp, and changed ports to default 0,0,0,0,0) but it doesn't work

00 00 00 20 have this signature for tcp frames with payload lenght 36 bytes

```
if (packet->tcp != NULL
      && packet->payload_packet_len == 36
      && packet->payload[0] == 0x00
      && packet->payload[1] == 0x00
      && packet->payload[2] == 0x00)
      && packet->payload[3] == 0x20) {

    NDPI_LOG_INFO(ndpi_struct, "found xdmcp over tcp\n");
    ndpi_int_xdmcp_add_connection(ndpi_struct, flow);
    return;
  }
```

now it doesnt detect xdmcp frames, but it still doesn't recognize this simple masks frames.
am i doing something wrong?

that is how packet looks like in wireshark:
![изображение](https://user-images.githubusercontent.com/53249272/173032910-9806deea-ec2f-4923-a378-98552fc98aab.png)

**Comment by IvanNardi** [comment]
> 
> in ndpi_protocols.h i added this two lines:
> 
> ```
> void ndpi_search_radmin(struct ndpi_detection_module_struct *ndpi_struct, struct ndpi_flow_struct *flow);
> void init_radmin_dissector(struct ndpi_detection_module_struct *ndpi_struct, u_int32_t *id, NDPI_PROTOCOL_BITMASK *detection_bitmask);
> ```

The first line is not really necessary.
Just a shot: did you call `init_radmin_dissector()` from (the end of) `ndpi_callback_init()` in `src/lib/ndpi_main.c()`?

**Comment by IvanNardi** [comment]
> found ticket in issues with answer like "Send us ur protocol so we'll add it", but it doesnt satisfied me, cause its fun for me to research, its not about "pls devs make it work" :D

:heart:

**Comment by httsp0werz** [comment]
> > in ndpi_protocols.h i added this two lines:
> > ```
> > void ndpi_search_radmin(struct ndpi_detection_module_struct *ndpi_struct, struct ndpi_flow_struct *flow);
> > void init_radmin_dissector(struct ndpi_detection_module_struct *ndpi_struct, u_int32_t *id, NDPI_PROTOCOL_BITMASK *detection_bitmask);
> > ```
> 
> The first line is not really necessary. Just a shot: did you call `init_radmin_dissector()` from (the end of) `ndpi_callback_init()` in `src/lib/ndpi_main.c()`?

just found out that i didnt call it, so i added `init_radmin_dissector(ndpi_str, &a, detection_bitmask);` at the end of `ndpi_callback_init()`, then `./autogen.sh && make && ndpiReader -i example/test.pcap` and it still doesnt detect my protocol

<details>
  <summary>So that how I did radmin.c from xdmcp code:</summary>
    
  ```
  #include "ndpi_protocol_ids.h"

#define NDPI_CURRENT_PROTO NDPI_PROTOCOL_RADMIN

#include "ndpi_api.h"


static void ndpi_int_radmin_add_connection(struct ndpi_detection_module_struct
                                          *ndpi_struct, struct ndpi_flow_struct *flow)
{
  ndpi_set_detected_protocol(ndpi_struct, flow, NDPI_PROTOCOL_RADMIN, NDPI_PROTOCOL_UNKNOWN, NDPI_CONFIDENCE_DPI);
}

void ndpi_search_radmin(struct ndpi_detection_module_struct
                       *ndpi_struct, struct ndpi_flow_struct *flow)
{
  struct ndpi_packet_struct *packet = &ndpi_struct->packet;

  NDPI_LOG_DBG(ndpi_struct, "search radmin\n");

  if (packet->tcp != NULL
      && packet->payload_packet_len == 20
      && packet->payload[0] == 0x00 && packet->payload[1] == 0x00
      && packet->payload[2] == 0x00 && packet->payload[3] == 0x10) {

    NDPI_LOG_INFO(ndpi_struct, "found radmin over tcp\n");
    ndpi_int_radmin_add_connection(ndpi_struct, flow);
    return;
  }
  if (packet->tcp != NULL
      && packet->payload_packet_len == 52
      && packet->payload[0] == 0x00 && packet->payload[1] == 0x00
      && packet->payload[2] == 0x00 && packet->payload[3] == 0x30) {

    NDPI_LOG_INFO(ndpi_struct, "found xdmcp over udp\n");
    ndpi_int_radmin_add_connection(ndpi_struct, flow);
    return;
  }

  NDPI_EXCLUDE_PROTO(ndpi_struct, flow);
}


void init_radmin_dissector(struct ndpi_detection_module_struct *ndpi_struct, u_int32_t *id, NDPI_PROTOCOL_BITMASK *detection_bitmask)
{
  ndpi_set_bitmask_protocol_detection("radmin", ndpi_struct, detection_bitmask, *id,
                                      NDPI_PROTOCOL_RADMIN,
                                      ndpi_search_radmin,
                                      NDPI_SELECTION_BITMASK_PROTOCOL_V4_V6_TCP_OR_UDP_WITH_PAYLOAD_WITHOUT_RETRANSMISSION,
                                      SAVE_DETECTION_BITMASK_AS_UNKNOWN,
                                      ADD_TO_DETECTION_BITMASK);

  *id += 1;
}
  ```
  
</details>

**Comment by httsp0werz** [comment]
Ok guys, im here with my greatest solution. Problem was in this command, that i mentioned below:
`./autogen.sh && make && ndpiReader -i example/test.pcap`
idk WHERE ndpiReader was in PATH, and where he took signatures, but when...

i FINALLY used ndpiReader from examples folder, with ./ndpiReader command I got my signature detected.

Thanks @utoni and @IvanNardi for your time and attention! Ill mention you in my coursework haha

**Comment by IvanNardi** [comment]
Glad you did it!
