### ISSUE TITLE
Bug in ssl.c

### ISSUE THREAD

**Issue by max197616** [ntop/nDPI#157]
When in TLS extension server_name uses punycoded server name, function stripCertificateTrailer from ssl.c removes symbols from server_name and in the flow->protos.ssl.client_certificate placed incorrect value. Samlpe output:
./ndpiReader -v2 -i 1xbet.pcap 

---
- NOTE: This is demo app to show _some_ nDPI features.
- In this demo we have implemented only some basic features
- just to show you what you can do with the library. Feel 
## \* free to extend it and send us the patches for inclusion

Using nDPI (1.7.1) [1 thread(s)]
Reading packets from pcap file 1xbet.pcap...
Running thread 0...
        1       TCP 89.250.0.12:55653 <-> 46.28.207.109:443 [proto: 91/SSL][3 pkts/479 bytes][SSL client: 1xbet.xn--]

nDPI Memory statistics:
        nDPI Memory (once):      105.91 KB  
        Flow Memory (per flow):  1.88 KB  
        Actual Memory:           1.93 MB  
        Peak Memory:             1.93 MB      

Traffic statistics:
        Ethernet bytes:        6491          (includes ethernet CRC/IFC/trailer)
        Discarded bytes:       0  
        IP packets:            66            of 66 packets total
        IP bytes:              4907          (avg pkt size 74 bytes)
        Unique flows:          1  
        TCP Packets:           66  
        UDP Packets:           0  
        VLAN Packets:          0  
        MPLS Packets:          0  
        PPPoE Packets:         0  
        Fragmented Packets:    0  
        Max Packet size:       305  
        Packet Len < 64:       63  
        Packet Len 64-128:     0  
        Packet Len 128-256:    2  
        Packet Len 256-1024:   1  
        Packet Len 1024-1500:  0  
        Packet Len > 1500:     0  
        nDPI throughput:       94.56 K pps / 70.95 Mb/sec
        Traffic throughput:    84.72 pps / 65.10 Kb/sec
        Traffic duration:      0.779 sec
        Guessed flow protos:   0            

Detected protocols:
        SSL                  packets: 66            bytes: 4907          flows: 1            

Protocol statistics:
        Safe                          4907 bytes

```
    1       TCP 89.250.0.12:55653 <-> 46.28.207.109:443 [proto: 91/SSL][66 pkts/4907 bytes][SSL client: 1xbet.xn--]
```

Full server name is 1xbet.xn--3ds443g , not 1xbet.xn-- as shown in output.

[1xbet.zip](https://github.com/ntop/nDPI/files/163799/1xbet.zip)

**Comment by kYroL01** [comment]
I'll fix asap !

**Comment by kYroL01** [comment]
Fixed by https://github.com/ntop/nDPI/commit/7ae06a114df358010c27cdf5819d1abdadd099fb

Thank you support!
