### ISSUE TITLE
Stack-buffer-overflow in ndpi_is_printable_string

### ISSUE THREAD

**Issue by koltiradw** [ntop/nDPI#1575]
Hi! I found stack-buffer-overflow( occurs at src/lib/ndpi_utils.c:2200:9 ) during testing with libFuzzer. 

## nDPI Environment:
* OS name: Ubuntu
* OS version: 20.04.4 LTS (Focal Fossa)
* Architecture: x86-64
* nDPI  commit hash: 5f05054c8a9c4e11a6e1d346036ceb9316500eb8
* nDPI compilation flags used: --with-sanitizer --enable-fuzztargets
* [config.log](https://github.com/ntop/nDPI/files/8822790/config.log)

### Reproducible using ndpiReader?
- [ ] The reported bug is reproducible using ndpiReader.
- [x] The reported bug is not reproducible using ndpiReader.

### File for reproducing:   
 -  [crash-7380646abb8ec7d2cf0b5a50fd75bed97c8f19c3.zip](https://github.com/ntop/nDPI/files/8822796/crash-7380646abb8ec7d2cf0b5a50fd75bed97c8f19c3.zip)

### Steps to reproduce the behavior:
1. Run './fuzz_process_packet_with_main <crash_file>'.
2. See ASAN  crash report.

**Comment by utoni** [comment]
The crash is not triggered with the current dev branch.
But I can not tell yet if the bug was fixed.

**Comment by koltiradw** [comment]
Yes, this bug was found in the 4.2 stable branch. 
I will continue my research on the current dev branch.
