### ISSUE TITLE
Heap-buffer-overflow in ndpi_search_syslog

### ISSUE THREAD

**Issue by koltiradw** [ntop/nDPI#1578]
Hi! I found heap-buffer-overflow ( occurs at src/lib/protocols/syslog.c:87:9 ) during testing with libFuzzer. 

## nDPI Environment:
* OS name: Ubuntu
* OS version: 20.04.4 LTS (Focal Fossa)
* Architecture: x86-64
* nDPI  commit hash: 09fbe0a64a11b08a35435f516e9a19f7e0c20d7c
* nDPI compilation flags used:  --enable-fuzztargets
*  [config.log](https://github.com/ntop/nDPI/files/8835908/config.log)

### Reproducible using ndpiReader?
- [ ] The reported bug is reproducible using ndpiReader.
- [x] The reported bug is not reproducible using ndpiReader.

### File for reproducing:   
 -  [crash-01b1db2206cb0d66304231f7188a788b029048ad.log](https://github.com/ntop/nDPI/files/8835909/crash-01b1db2206cb0d66304231f7188a788b029048ad.log)

### Steps to reproduce the behavior:
1. Run './fuzz_process_packet_with_main <crash_file>'.
2. See ASAN  crash report.

**Comment by utoni** [comment]
Whoops! My fault. Thanks!
