### ISSUE TITLE
Traffic falsely identified as Bittorrent

### ISSUE THREAD

**Issue by u-Map** [ntop/nDPI#158]
Hi,

In recent testing we've found that many non bitrorrent SSL traffic was falsely identified as bittorrent traffic (including google,viber,facebook and many more).

Testing Environment:
We've used ndpireader output for detection analysis.
Client IP : 192.168.200.222 (android phone with no bittorrent client) GW: 192.168.200.60

Server eth0: 192.168.200.60
Server eth0: 192.168.10.200
GW: 192.168.10.1 (my.firewall)
Server is configured to ip forward internet traffic from eth1 to eth0.

I've attached pcap file and ndpireader output.

[ndpi_detection_problem.zip](https://github.com/ntop/nDPI/files/166653/ndpi_detection_problem.zip)

Thanks.

**Comment by kYroL01** [comment]
ALL the BitTorrent are wrong in your capture ? I mean, you are sure NO BitTorrent app is open when you captured (just to understand).

**Comment by kYroL01** [comment]
Actually the packet detected as BitTorrent in your pcap are only UDP packets (I extract a sub-pcap with only packets detected as BitTorrent). No SSL are involved.
I Investigate on this.

**Comment by u-Map** [comment]
@kYroL01 Yes. Client was an Android Phone with no BitTorrent app installed.

**Comment by u-Map** [comment]
Just to add something. I got a Viber call during a previous testing while I'm looking at the ndpireader output. All viber traffic for that call was marked as Bittorrent/37. Unfortunately I couldn't get a packet trace for that incident.

**Comment by kYroL01** [comment]
I know that a new Viber dissector is needed (https://github.com/ntop/nDPI/issues/149).
Are u able to send me a pcap of only an entire Viber session ? Thanks

**Comment by u-Map** [comment]
> > Are u able to send me a pcap of only an entire Viber session ? 

Sure. I'll send one asap.

**Comment by kYroL01** [comment]
Thanks a lot!

**Comment by lucaderi** [comment]
I have looked at a few flows of your pcap. For instance capturing port 192.168.200.222:45493 I see UDP traffic as below
that IMHO is BitTorrent. Open your pcap and will see.

d1:ad2:id20:U.!4.....N.. ..L....9:info_hash20:N....t...D>."?+.....e1:q9:get_peers1:t2:Fw1:v4:LT..1:y1:qe

Furthermore looking at the MAC addresses, this is not a mobile-originated traffic (we see VMware MAC addresses). Please explain again your setup. Note that BitTorrent is NOT used just for file download, but also by other services so I was wondering if this also applies to your case with other apps running on your system.

**Comment by lucaderi** [comment]
Please remember to send us a viber trace.

**Comment by Mile-Lile** [comment]
Check if my trace can help...
[Viber_desktop.zip](https://github.com/ntop/nDPI/files/170440/Viber_desktop.zip)

**Comment by u-Map** [comment]
Sorry for the delay. Viber trace attached.
[viber_mobile_cap_1.zip](https://github.com/ntop/nDPI/files/171572/viber_mobile_cap_1.zip)

**Comment by u-Map** [comment]
Btw, I see a huge difference of packet count in pcap file and ndpi reader output.

Below are the commands I've used for testing.

sudo tcpdump -i eth1 -vvv -nnn -s0 host 192.168.200.222 -w viber_mobile_cap_1.pcap
sudo ./ndpiReader -i eth1 -v2 | grep 192.168.200.222 > /home/ndpi/ndpireader_viber_mobile.txt

As I've already send the pcap I attach the latter below.

Can you please clarify this?

[ndpireader_viber_mobile.zip](https://github.com/ntop/nDPI/files/171578/ndpireader_viber_mobile.zip)

**Comment by kYroL01** [comment]
@Mile-Lile & @u-Map Thanks for the pcap. Hope to write a new Viber dissector soon.

@u-Map Did u understand what Luca said you about the BitTorrent flows you see ?

**Comment by u-Map** [comment]
@lucaderi 

> > > Furthermore looking at the MAC addresses, this is not a mobile-originated traffic (we see VMware MAC addresses).

No. The static IP 192.168.200.222 was assigned to the Android by the time of testing.

> > > we see VMware MAC addresses

The gateway server used for testing was a VM (VMware). And there may be other broadcast traffic from other VMs.

> > > Note that BitTorrent is NOT used just for file download, but also by other services so I was wondering if this also applies to your case with other apps running on your system.

Ok. I got it. I have no idea about other apps that could sent Bittorrent traffic installed on test Android phone. I will investigate.

@kYroL01's correction on SSL vs UDP was right. It was my error specifying it as false detection of SSL traffic. The reason for my fault was output like following in the [Host] field of ndpireader output. 

2016-03-10 23:36:36 INFO         | Src: UDP 1.24.12.188:11101 | Dest: 192.168.200.222:40504 | [proto: 37/BitTorrent] | [1 pkts/146 bytes] | [Host: mtalk.google.com] | [SSL client: ] | [SSL server: ] 
2016-03-10 23:36:36 INFO         | Src: UDP 192.168.200.10:5353 | Dest: 224.0.0.251:5353 | [proto: 8/MDNS] | [1 pkts/87 bytes] | [Host: mtalk.google.com] | [SSL client: ] | [SSL server: ]

**Comment by kYroL01** [comment]
> > > Btw, I see a huge difference of packet count in pcap file and ndpi reader output.

This is normal, because **tcpdump** is a packet sniffer/analyzer, while **nDPI** use the deep packet inspection to classify the flows of packets.
Consider that ndpiReader is a demo for testing the application protocol flows, not singles UDP/TCP packets.

I see that the majority of the flows are detected as _Unknown_ because (i think) it is Viber flows not correctly detected (and this is why is necessary a new dissector).

**Comment by u-Map** [comment]
@kYroL01 Thanks for clarification. But this is little confusing for me. I though ndpiReader demo application output should be like following.

Total packets in pcap: 100
Ndpireader output: 
prot 1 : 10pkts 
prot2: 30 packets 
prot 3: 15packts 
prot n: 5 packets
unknown (unidentified/other) prot: (100 - (10+30+15+5)) = 60
TOTAL = 100

Because I see the packet count too in the ndpiReader output.

Detected protocols:
        Unknown              packets: 43274         bytes: 8733525       flows: 17745  
        DNS                  packets: 6958          bytes: 1115539       flows: 3211  
        HTTP                 packets: 46782         bytes: 27222846      flows: 1934  
        MDNS                 packets: 2296          bytes: 468316        flows: 430          

Can you kindly clarify what kind packets may go missing in flow detection process? 

sorry if this sounds dumb, but I really need to understand it. :)

**Comment by kYroL01** [comment]
@u-Map No packets are missing in the detection, but ndpiReader discard the only-L2 packets (i.e. ARP).
If you see:
IP packets:            **_10680         of 10701 packets total_**
and the "missing" packets are exactly the 21 ARP packets in your pcap.

p.s. I almost finished to do the Viber dissector and Viber service detection. I have to do some test and then push a commit.

**Comment by kYroL01** [comment]
7c511fb2f2b827f96349f6fb0e2193f9793aa068 (for Viber)
I have to finish the dissector, but this commit I think solved many problems of detection.

**Comment by kYroL01** [comment]
I close this issue as the BitTorrent in your pcap is right. If you'll see other inconsistency open new issue.

Thank you.
