### ISSUE TITLE
nDPI not detecting all BitTorrent flows

### ISSUE THREAD

**Issue by jahanzeb-arshad** [ntop/nDPI#159]
The nDPi engine is not detecting all Bittorrent flows. Attached is the pcap file of traffic flow which it is not able to detect.

[bittorrent.pcapng.zip](https://github.com/ntop/nDPI/files/177253/bittorrent.pcapng.zip)

**Comment by kYroL01** [comment]
Thank you for the pcap.

**Comment by lucaderi** [comment]
@jahanzeb-arshad I have analysed the pcap with @kYroL01 and we do not see issues. Can you please narrow down the problem and provide a new pcap with _only_ the bit torrent traffic that is not detected?

**Comment by jahanzeb-arshad** [comment]
Following is the flow information as detected by nDPI

![ndpi-flows](https://cloud.githubusercontent.com/assets/17155548/13871146/fffb67b0-ed03-11e5-88a8-c2e88f7c33e9.png)

Attached is the pcap file with only the flows which are shown as unknown by the nDPI. 
[bittorrent.pcapng.zip](https://github.com/ntop/nDPI/files/179206/bittorrent.pcapng.zip)

**Comment by lucaderi** [comment]
As you can see the flows with a strikethrough have been blocked. Now it seems there is a flow with relatively high bandwidth that was not blocked. This is the issue I will try to solve. Stay tuned.

**Comment by kYroL01** [comment]
Thanks @lucaderi
