### ISSUE TITLE
Add Request: Git

### ISSUE THREAD

**Issue by alberk8** [ntop/nDPI#160]
Hi,
Please add the git protocol.  Thanks.

**Comment by kYroL01** [comment]
Can you provide a good pcap with the _git_ protocol ?
Thanks

**Comment by giomasce** [comment]
You can find a capture attached. I think a reasonably quick and robust filter would be to check for the string `git-upload-pack` beginning at the fifth byte of the first client packet.

[git_filtered.pcapng.zip](https://github.com/ntop/nDPI/files/222285/git_filtered.pcapng.zip)

**Comment by kYroL01** [comment]
@giomasce thank you !

**Comment by kYroL01** [comment]
@alberk8 please, do some test  0f089bd49a8bfa1e57e862cef1352c6514f4719f
