### ISSUE TITLE
Compile as a DLL

### ISSUE THREAD

**Issue by ayle** [ntop/nDPI#162]
Hello,

I'm not very good in C/C++ but I'm currently asked to develop a soft based on nDPI using C#/.Net.

I'm not able to build neither the Win32 example (PcapExample) nor the library as a DLL. Is there any existant procedure as the Linux one to compile nDPI on Windows/Visual Studio ?

Thanks in advance, and sorry for the disturbance...

**Comment by kYroL01** [comment]
Try if this could help you: http://www.codeproject.com/Articles/9826/How-to-create-a-DLL-library-in-C-and-then-use-it-w

**Comment by ayle** [comment]
Hi,

Thanks for your link. I understand the concept, but between the example and a project like nDPI, the difference seems huge to me...

I started to generate the project but there are incompatibilities between the Windows environment and the Linux one (due to several libraries as strings.h for example). For now, it is the btlib.c / btlib.h that generates errors and stops the build... and with my experience in C, I'm not able to recode this...

I don't understand why I have this difficulties since nDPI supports Windows

**Comment by lucaderi** [comment]
@ayle See https://github.com/ntop/nDPI/tree/dev/example/Win32 and if you happen to update it, please send us a pull request.

**Comment by kYroL01** [comment]
I close the issue but @ayle if you have news or update to send us, follow what Luca sayd. Thanks
