### ISSUE TITLE
nDPI multi-layer identification 

### ISSUE THREAD

**Issue by alihushyar** [ntop/nDPI#1630]
Im trying to to do multi-level protocol detection with nDPI.  For example, with SMTPS, currently I am only able to get NDPI to classify the top-level as SMTP.Google and it disregards the subsequent TLS handshake even though I see it processing those packets.  If I remove the beginning SMTP handshake from the pcap, then nDPI sees the TLS.  Any ideas on how to achieve both SMTP.Google and TLS/JA3 classification?  Sample pcap attached.  
[smtp-starttls.zip](https://github.com/ntop/nDPI/files/9035175/smtp-starttls.zip)

**Comment by alihushyar** [comment]
Thank you folks - this is confirmed fix with one caveat if you think it  is
worth addressing.

For HTTPS, nDPI will process both Client and Server Hello and therefore
provide both JA3 and JA3S hashes.

For SMTPS, nDPI stops at processing the client hello.

In the pcap attached to the ticket, you will see that packets don't get
processed after the 11th packet which is the Client Hello.

Best,
Ali

**Comment by utoni** [comment]
Thank you for this hint. This will be a subject to change during refactoring the `mail_*` dissectors.
