### ISSUE TITLE
Include server-side Initial Packet processing for QUIC

### ISSUE THREAD

**Issue by alihushyar** [ntop/nDPI#1640]
I understand that only client-side Initial Packet is needed for QUIC classification.  However, server-side is needed to generate the JA3S hashes along with the JA3.  Are there plans to process SHLO as well as derive the server-side initial secrets (server_in) to process encrypted server initial packet so both client/server JA3/JA3S can be generated?

**Comment by IvanNardi** [comment]
It is definitely possible, but a little bit costly from a performance POV.
But the real question is: do you need JA3S in QUIC for some specific reasons? I really don't expect a lot of different values for JA3S in QUIC

**Comment by alihushyar** [comment]
Yes this is a fair point.  There will not be a lot of values here for
quic.  Thank you for your response.

Ali
