### ISSUE TITLE
1.7 release tag

### ISSUE THREAD

**Issue by Enteee** [ntop/nDPI#165]
According to [1] and [2] there should be a 1.7 release of this software but there is no git tag 1.7. Is there a reason for this? Could you please tag the 1.7 release commit. That would help me a lot. Thank you.

[1] : http://www.ntop.org/announce/released-ndpi-1-7/
[2] : https://sourceforge.net/projects/ntop/files/nDPI/

**Comment by kYroL01** [comment]
@Enteee If you see branches, there are the 1.7 stable branch of nDPI.
Then, the dev branch is the _always-updated_ branch.
If you're looking for commits you ask: 0a4c8e2959facfe1c03c6216f017c740e8b4c4da

**Comment by Enteee** [comment]
thanks I saw the branches before, so is there a reason you didn't tag the 0a4c8e2959facfe1c03c6216f017c740e8b4c4da as 1.7? A simple

```
git tag 0a4c8e2959facfe1c03c6216f017c740e8b4c4da 1.7 && git push --tags
```

would help me a lot.

**Comment by lucaderi** [comment]
@Enteee What about this?
![screen shot 2016-03-31 at 17 23 21](https://cloud.githubusercontent.com/assets/4493366/14180934/4f9c4b8e-f765-11e5-8570-97517015e53e.png)
Don't forget to star nDPI on github

**Comment by Enteee** [comment]
I do work on a project which has _A LOT_ of dependencies to other projects. We include them as submodules and on release we do something like

```
foreach submodule:
    git checkout newest tag
```

this works nicely for all of the dependencies except this one. Also I didn't notice that there is a 1.7 release just until today because your [Releases page](https://github.com/ntop/nDPI/releases) only contains the 1.6 release. Adding a tag for 1.7 would solve this.

**Comment by lucaderi** [comment]
@Enteee As your project uses our tools, do you plan to contribute to nDPI ?

**Comment by Enteee** [comment]
@lucaderi If I need a new protocol I might consider doing so. But right now the library works pretty fine for me. But how is this question related to the topic?

**Comment by lucaderi** [comment]
@Enteee As you seem to have experience, your help would be desirable. Please consider contributing to the project as you did with your tag suggestion.

**Comment by kYroL01** [comment]
@lucaderi Do you think we can add that tag for the commit evidenced ?

**Comment by Enteee** [comment]
so is this off the table?

**Comment by lucaderi** [comment]
When we'll release 1.8 we'll tag it

**Comment by kYroL01** [comment]
@Enteee https://github.com/ntop/nDPI/tree/1.7

**Comment by Enteee** [comment]
thank you!
