### ISSUE TITLE
undefined reference to `ndpi_set_detected_protocol',`ndpi_protocol2name'

### ISSUE THREAD

**Issue by HaochuanXJTU** [ntop/nDPI#166]
When I use DPDK to link the lib of ndpi，it‘s show that undefined reference to `ndpi_set_detected_protocol' and`ndpi_protocol2name'. But another function can be linked.

**Comment by kYroL01** [comment]
@HaochuanXJTU Have you tried to upgrade the nDPI from the dev branch from here ? Maybe the link from you downloaded is old.

**Comment by kYroL01** [comment]
@HaochuanXJTU I close for inactivity. In case let us know

**Comment by HaochuanXJTU** [comment]
OK， thanks for you help, I have solved this problem by redefine the function.

**Comment by kYroL01** [comment]
I suggest you to keep update nDPI by the dev branch that you can find here on github.
Regards

**Comment by HaochuanXJTU** [comment]
Do you know a high speed processing packet libraries DPDK, I have made a program using DPDK to capture packet, and using ndpi to process packet. But the program will be quit when recieved a packet.Can you give me some advice?

**Comment by kYroL01** [comment]
Sorry, i never used DPDK. 
IMHO It seems to be strange that you use two different programs to do capture and processing packets when you just need one.
