### ISSUE TITLE
Viber protocol is not recognized

### ISSUE THREAD

**Issue by vnetserg** [ntop/nDPI#167]
Hello all,
I've build the latest dev version of nDPI and still it does not recognize Viber protocol. I am using ndpiReader executable from "examples" folder. Pcap file with Viber voice call can be found here: https://drive.google.com/file/d/0B_nvZYkh0O5NYW5RZlo5czJmYzg/view?usp=sharing
Target session is "UDP 192.168.1.94:39242 <-> 87.228.93.187:41959".
Am I doing something wrong or this is a bug?
Thanks!

**Comment by kYroL01** [comment]
Yes @vnetserg . Viber protocol completely changed and a new dissector is needed.
It's a thing we'll do.
Stay tuned here: https://github.com/ntop/nDPI/issues/168

Thanks for the pcap. This is very helpfull!
