### ISSUE TITLE
nDPI profiling stats

### ISSUE THREAD

**Issue by subhajit-cdot** [ntop/nDPI#1681]
Hi,
Can we export few more profiling stats like (LRU cache usage stats (as entries are fixed and if there is any perf bottleneck happening due to this?, avg no of dissectors involved in detection, avg no of system calls, no of certificate/cypher decryption calls, conn track calls ,  etc). We can do hotspot analysis using vTune like tools but it would be great if ndpi can provide similar insights .

Thanks
Subhajit

**Comment by IvanNardi** [comment]
Some of these info will be available when https://github.com/ntop/nDPI/pull/1677 is merged

**Comment by subhajit-cdot** [comment]
Ok thanks for the info. Along with the Data structure usage stats we can also avg no of dissectors involved in detection, no of system calls, no of certificate/cypher decryption calls, conn track calls etc in future releases.

Thanks
Subhajit

**Comment by IvanNardi** [comment]
> avg no of dissectors involved in detection

Already available

```
./example/ndpiReader -t -i ./tests/pcap/whatsapp_login_call.pcap
[...]
	Num dissector calls:   236           (4.14 diss/flow)
```

**Comment by utoni** [comment]
Done with #1677.
