### ISSUE TITLE
HTTP sub-classification: best protocol classification

### ISSUE THREAD

**Issue by IvanNardi** [ntop/nDPI#1687]
The attached session (extracted from the unit tests) contains a SOAP flow over HTTP with a Microsoft hostname.
How this flow should be classified?

1) SOAP.Microsoft: current result. We lost that information that it is an HTTP flow and so we don't dump HTTP metadata (note that we can have SOAP without HTTP...)
2) HTTP.SOAP
3) HTTP.Microsoft

I don't like the current code because we lose HTTP attribute, but I don't have strong opinions.
What do you think? What is the best classification? @utoni @lucaderi 

Clearly, there is the same issue with all the HTTP sub-protocols.

[soap.zip](https://github.com/ntop/nDPI/files/9222503/soap.zip)

**Comment by utoni** [comment]
> The attached session (extracted from the unit tests) contains a SOAP flow over HTTP with a Microsoft hostname. How this flow should be classified?
> 
>     1. SOAP.Microsoft: current result. We lost that information that it is an HTTP flow and so we don't dump HTTP metadata (note that we can have SOAP without HTTP...)
> 
>     2. HTTP.SOAP
> 
>     3. HTTP.Microsoft
> 
> 
> I don't like the current code because we lose HTTP attribute, but I don't have strong opinions. What do you think? What is the best classification? @utoni @lucaderi
> 
> Clearly, there is the same issue with all the HTTP sub-protocols.
> 
> [soap.zip](https://github.com/ntop/nDPI/files/9222503/soap.zip)

I would probably stick to `HTTP.SOAP`, because `Microsoft` should be still available via `guessed_host_protocol_id`. That way we won't loose information IMHO.

**Comment by lucaderi** [comment]
In my opinion Tony is right but in the short term. For a long term solution i think we need to rethink how protocols are reported. Microsoft, Amazon or Google are not protocols and I have added them years ago to make easy for people to implement things like "How much traffic to I send to Google?". So IMHO IP classification can either be a third-level protocol (e.g.  HTTP.SOAP.Microsoft) or another "attribute" of the traffic similar to breed: in essence they are similar but we need to decide if they are part of the protocol (so HTTP.SOAP.Microsoft) or as an external attribute to HTTP.SOAP.

The first solution is better IMHO but it has the problem of layers. Example: DNS.Microsoft is two layer with respect to HTTP.SOAP.Microsoft that is 3. Due to this we don't have a clean way of identifying what protocol items represent,

**Comment by IvanNardi** [comment]
> So IMHO IP classification can either be a third-level protocol (e.g. HTTP.SOAP.Microsoft) or another "attribute" of the traffic similar to breed: in essence they are similar but we need to decide if they are part of the protocol (so HTTP.SOAP.Microsoft) or as an external attribute to HTTP.SOAP.

No strong opinions on that, but moving from a "master + app" pair to a generic "protocol stack" might be the more generic solution

> 
> The first solution is better IMHO but it has the problem of layers. Example: DNS.Microsoft is two layer with respect to HTTP.SOAP.Microsoft that is 3. Due to this we don't have a clean way of identifying what protocol items represent,

I don't know if that is a really problem; we already have classification with different layers lengths (1 vs 2)

Let's proceed this way: for the time being use the `HTTP.SOAP` approach and then we can think of a better/general solution about how handling "ip classification". Is that agreeable to you?

**Comment by lucaderi** [comment]
Yes that's ok for me, but I think it's time to move IP classification on a separate "field" as discussed above,

**Comment by IvanNardi** [comment]
Just to be sure, you would like:
1) having a separate field with the "by-ip classification" (pretty much what we already have in `flow->guessed_host_protocol_id`); OR
2) having a separate field with the "by-ip classification" AND (un)conditionally(?) remove it from the protocol classification too, i.e. from `flow->detected_protocol_stack[]`

?

**Comment by lucaderi** [comment]
Yes i would like (my option, we're here to discuss) is that IP classification should go on a different field so we need to remove it from where it is today and move it there. This way the design i cleaner IMHO

**Comment by IvanNardi** [comment]
I agree that removing "ip-classificaton" from `flow->detected_protocol_stack[]` might be a good idea, in general.
For example, as noted in #1425, classifications as `NTP/Apple`, `BitTorrent/Azure`, `DNScrypt.AmazonAWS` don't make any sense, IMO.
However, we might need some exceptions:
1) for unknown traffic, returning the "ip-classificaton" in `flow->detected_protocol_stack[0]` seems fine (with a proper confidence value); we already do the exact same things with the "port-classification"
2) For some "master" protocol (HTTP, QUIC and TLS; no sure if this list is complete), **without** any **proper** sub-classifications (based on SNI, certificate, hostname,...) it might be ok to add the "ip-classificaton" in `flow->detected_protocol_stack[]`.

I think 1) should be supported; no strong opinions on 2)
