### ISSUE TITLE
How to study nDPI and develop dissection support for a specific application

### ISSUE THREAD

**Issue by tianzhishuizhu** [ntop/nDPI#171]
I'm a student and interested in protocol/application classification. I have run ntopng on my ubuntu and read some documentation. But I have some problems about learning.
1. I can't find documentation about how nDPI determines which application flows belong to based on pcap file detailedly, from the viewpoint of developer instead of user. For instance, to classify YouTube flows, how can a developer inspect the header and payload of packets and what algorithm can be used?
2. I want to learn the process of developing a dissection support for a specific application(maybe YouTube). Are there documentation avaliable for this?

Thanks for all the work you have done.

**Comment by lucaderi** [comment]
I suggest you to read http://luca.ntop.org/nDPI.pdf and then explore the source code with a debugger.

**Comment by tianzhishuizhu** [comment]
Thanks for your reply! I have read that article bofore and need some time to understand it. I find algorithm like: string-based matching, Aho-Corasick and encryption protocol, certificate.  Can you instruct me the outline of algorithms being used by nDPI? I will study about that. Debugging is really useful process, Thanks! I'll try it.

**Comment by kYroL01** [comment]
@tianzhishuizhu If u have specific questions about, you could send me a private mail instead ask here.
I could answer to your doubt asap.
Thank you

**Comment by tianzhishuizhu** [comment]
@kYroL01 Thanks!
