### ISSUE TITLE
discover about QQ and facebook using nDPI and ndpiReader

### ISSUE THREAD

**Issue by tianzhishuizhu** [ntop/nDPI#176]
I have several problems, mainly about discovery of facebook and QQ protocol.
1. I run the command `sudo ./ndpiReader -i eth0 -s 20` several times and login on facebook.com. But the ndpi Reader doesn't output information about facebook.
2. Really, on ubuntu, there is only webqq avaliable, does it mean nDPI can also discover webqq? In windows, there is QQ avaliable. But when I login webqq, it hasn't been discovered.

.

**Comment by kYroL01** [comment]
1. I did a test right now and I detected correctly facebook
2. I also went to web.qq to and nDPI detect QQ application as well.

It seems that the problem is not about nDPI. Are u sure you're using the correct version ?

**Comment by tianzhishuizhu** [comment]
I install the latest version on github. I just install nDPI and ndpiReader, and nothing more. The output also shows that: `packet capture size is smaller than packet size, DETECTION MIGHT NOT WORK CORRECTLY`.

**Comment by kYroL01** [comment]
That "warning" comment is normal, and it inform you that the ndpiReader is just a test demo for nDPI and maybe some packets are not properly detected.
It's not an error.
I suggest you to upgrade nDPI and try again.
go in your nDPI folder and do `git pull && make` and try again, because I see that nDPI detect correctly both application protocols.

**Comment by tianzhishuizhu** [comment]
I run `git pull && make` in my nDPI directory. In the same time , I watch video on facebook.com. The output is:  
       Unknown              packets: 2             bytes: 692           flows: 2  
    DNS                  packets: 10            bytes: 1892          flows: 5  
    HTTP                 packets: 12            bytes: 2791          flows: 2  
    NetBIOS              packets: 2             bytes: 208           flows: 2  
    SSL_No_Cert          packets: 189           bytes: 58244         flows: 11  
    ICMP                 packets: 2             bytes: 395           flows: 2  
    SSL                  packets: 11861         bytes: 7347898       flows: 625  
    YouTube              packets: 358           bytes: 286510        flows: 4  
    Google               packets: 250           bytes: 70865         flows: 22

No information about facebook. I only install nDPI and ndpiReader. Is there anything else needed to discover facebook flow? I login facebook.com through chrome.

**Comment by kYroL01** [comment]
@tianzhishuizhu any news ?

**Comment by kYroL01** [comment]
Close for inactivity
