### ISSUE TITLE
Promiscuous mode

### ISSUE THREAD

**Issue by jibanes** [ntop/nDPI#1763]
Specs: Linux 5.15.x
Interface: 1 (eth0) and naturally the loopback interface.

I would like to monitor (with nDPI) my host's egress traffic.
I am only interested in the traffic initiated (read: established from) the host itself from the interface eth0 and going to a non rfc-1918 ip address AND traffic going to DNS servers (exposed in a rfc-1918 range).
I am only interested in monitoring TCP and UDP traffic at this time.
I have root access on the host, can run any iptables/nftables operations or insert ebpf probe(s) as necessary (possibly sending a subset of packets to userland?)
However for performance and security reasons, I am **not allowed to turn the interface in promiscuous mode**.

What would be the best way to inspect the traffic from the host itself without using any form of port or traffic mirroring to another host, as this isn't permitted either; I wouldn't want to setup a local proxy or socks server either. I know that snort has an option to run in non-promiscuous mode while inspecting live traffic (not from pcaps), but I haven't researched how they achieve this.

Please let me know what comes to mind, thank you.

**Comment by vel21ripn** [comment]
In your case, the promisc mode is not needed for nDPI to work.
Look in the ndpiReader.c file for the line "int promisc = 1;" fix it.

**Comment by jibanes** [comment]
Excellent, thank you!
