### ISSUE TITLE
ntopng -ndpi-protocols -p /var/lib/ntopng/protos.txt failed to parse lines

### ISSUE THREAD

**Issue by LennyV95** [ntop/nDPI#1773]
APCON runs nTOP on our virtual desktop linux side for people to try it out. We have a customer who is trying our ntop community package running on our IntellaStore system and client really likes it. He wants to add custom ports. There seems to be an issue running the command to enable custom application list. We created the protos.txt file, stop ntopng service and run the command:

sudo systemctl start ntopng -ndpi-protocols -p /var/lib/ntopng/protos.txt

I get the ‘failed to parse lines dpi-protocols. The ntopng log file has nothing and /var/log/messages has nothing

the file has these two lines only:
tcp:9002@Elasticsearch
tcp:5601@Kibana

Centos 7 Linux
ntopng version is 5.1.2.11018
nDPI: 4.1.0

**Comment by IvanNardi** [comment]
It seems a ntopng issue. Could you open a similar issue in https://github.com/ntop/ntopng/issues, please?
You probably get a better support there for this issue

**Comment by LennyV95** [comment]
when I click on New Issue, there is no option to put it under ntopng.
Thanks

**Comment by IvanNardi** [comment]
the first one, from the link I provided
![Screenshot from 2022-10-14 17-11-52](https://user-images.githubusercontent.com/12729895/195881144-4d7288d6-ef51-4be6-b94b-4a66daba551a.png)

**Comment by IvanNardi** [comment]
Moved to https://github.com/ntop/ntopng/issues/6933
