### ISSUE TITLE
Patch from voidlinux

### ISSUE THREAD

**Issue by radare** [ntop/nDPI#179]
https://github.com/voidlinux/void-packages/tree/master/srcpkgs/ndpi/patches

this patch is not even included in git version of ndpi

**Comment by Vaelatern** [comment]
Context: This patch is required for [the musl libc](http://www.musl-libc.org/)

**Comment by kYroL01** [comment]
@radare For what is necessary to nDPI ?

**Comment by radare** [comment]
Is ndpi a verb?

**Comment by kYroL01** [comment]
@radare well, are you using "to" only with verbs ?
I meant: is **really necessary** that patch for nDPI ?

**Comment by radare** [comment]
This patch is necessary to build ndpi with musl instead of glibc. Its not really a big problem if you dont use musl :p

**Comment by kYroL01** [comment]
@radare thanks for explanation. I'll do it ;)

**Comment by radare** [comment]
👍

**Comment by lucaderi** [comment]
Fixed in https://github.com/ntop/nDPI/commit/8cb6172e4bb44fdb45bf80dd3328a0f57173b45b
