### ISSUE TITLE
ZOOM UDP flow not detected 

### ISSUE THREAD

**Issue by sharonenoch** [ntop/nDPI#1805]
We were testing zoom calls and noticed that at times it was not detected.

When I ran it via nDPIReader it detected only the TLS.Zoom but there were 3 UDP flows through which the audio call took place but it did not get classified.

Secondly the protocol by IP was classified as Zoom but the confidence level was not set to NDPI_CONFIDENCE_MATCH_BY_IP. I had thought that if the IP matched the protocol the confidence would have been set accordingly

Attached is the pcap and nDPIReader output

[newzoom.zip](https://github.com/ntop/nDPI/files/10025654/newzoom.zip)

root@kickseed:~/pcaps/nDPI/example#  ./ndpiReader -i /root/pcaps/NDPI_Zoom_audiotestnov16/newzoom.pcapng -v2 -v3

Using nDPI (4.5.0-4208-dcff3ef8) [1 thread(s)]
Using libgcrypt version 1.8.6internal
Reading packets from pcap file /root/pcaps/NDPI_Zoom_audiotestnov16/newzoom.pcapng...
Running thread 0...

nDPI Memory statistics:
        nDPI Memory (once):      36.86 KB
        Flow Memory (per flow):  912 B
        Actual Memory:           30.79 MB
        Peak Memory:             30.79 MB
        Setup Time:              26 msec
        Packet Processing Time:  59 msec

Traffic statistics:
        Ethernet bytes:        28437955      (includes ethernet CRC/IFC/trailer)
        Discarded bytes:       3322
        IP packets:            99935         of 100000 packets total
        IP bytes:              26039515      (avg pkt size 260 bytes)
        Unique flows:          105
        TCP Packets:           10622
        UDP Packets:           89310
        VLAN Packets:          0
        MPLS Packets:          0
        PPPoE Packets:         0
        Fragmented Packets:    0
        Max Packet size:       1480
        Packet Len < 64:       7531
        Packet Len 64-128:     18156
        Packet Len 128-256:    17515
        Packet Len 256-1024:   56485
        Packet Len 1024-1500:  248
        Packet Len > 1500:     0
        nDPI throughput:       1.68 M pps / 3.57 Gb/sec
        Analysis begin:        16/Nov/2022 03:32:57
        Analysis end:          16/Nov/2022 03:46:56
        Traffic throughput:    119.01 pps / 264.58 Kb/sec
        Traffic duration:      839.724 sec
        Guessed flow protos:   42
        DPI Packets (TCP):     655           (10.74 pkts/flow)
        DPI Packets (UDP):     152           (3.53 pkts/flow)
        DPI Packets (other):   1             (1.00 pkts/flow)
        Confidence: Unknown    4             (flows)
        Confidence: Match by port 8             (flows)
        Confidence: DPI        93            (flows)

Detected protocols:
        Unknown              packets: 89231         bytes: 24687943      flows: 4
        DNS                  packets: 22            bytes: 2888          flows: 9
        SSDP                 packets: 30            bytes: 6434          flows: 9
        SMBv1                packets: 1             bytes: 243           flows: 1
        SMBv23               packets: 25            bytes: 7232          flows: 1
        ICMP                 packets: 3             bytes: 710           flows: 1
        TLS                  packets: 9685          bytes: 916525        flows: 17
        RPC                  packets: 12            bytes: 1292          flows: 1
        Zoom                 packets: 188           bytes: 40024         flows: 40
        Microsoft            packets: 682           bytes: 353548        flows: 18
        Microsoft365         packets: 48            bytes: 22244         flows: 2
        NAT-PMP              packets: 8             bytes: 432           flows: 2

Protocol statistics:
        Safe                       1270073 bytes
        Acceptable                   81256 bytes
        Dangerous                      243 bytes
        Unrated                   24687943 bytes

Risk stats [found 16 (15.2 %) flows with risks]:
        TLS (probably) Not Carrying HTTPS            5 [31.2 %]
        Unsafe Protocol                              1 [ 6.2 %]
        Error Code                                   4 [25.0 %]
        Unidirectional Traffic                       6 [37.5 %]

        NOTE: as one flow can have multiple risks set, the sum of the
              last column can exceed the number of flows with risks.

Additional flow output which was not detected

Undetected flows:
        1       UDP 172.8.0.100:60751 <-> 144.195.91.120:8801 [proto: 0/Unknown][**IP: 189/Zoom**][ClearText][Confidence: Unknown][44449 pkts/12365662 bytes <-> 42809 pkts/12053728 bytes][Goodput ratio: 85/85][839.71 sec][bytes ratio: 0.013 (Mixed)][IAT c2s/s2c min/avg/max/stddev: 0/0 18/15 183/184 5/17][Pkt Len c2s/s2c min/avg/max/stddev: 106/106 278/282 404/400 73/79][Plen Bins: 0,0,8,12,3,2,7,12,31,20,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        2       UDP 172.8.0.100:52751 <-> 144.195.91.120:8801 [proto: 0/Unknown][**IP: 189/Zoom**][ClearText][Confidence: Unknown][448 pkts/61376 bytes <-> 607 pkts/82625 bytes][Goodput ratio: 69/69][837.17 sec][bytes ratio: -0.148 (Mixed)][IAT c2s/s2c min/avg/max/stddev: 228/0 1817/1376 3522/3751 1636/1411][Pkt Len c2s/s2c min/avg/max/stddev: 123/123 137/136 151/159 14/14][PLAIN TEXT (acRnTpR)][Plen Bins: 0,0,65,34,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        3       UDP 172.8.0.100:60752 <-> 144.195.91.120:8801 [proto: 0/Unknown][**IP: 189/Zoom**][ClearText][Confidence: Unknown][448 pkts/61376 bytes <-> 448 pkts/57344 bytes][Goodput ratio: 69/67][836.50 sec][bytes ratio: 0.034 (Mixed)][IAT c2s/s2c min/avg/max/stddev: 234/0 1874/1874 3514/3755 1629/1872][Pkt Len c2s/s2c min/avg/max/stddev: 123/123 137/128 151/133 14/5][PLAIN TEXT (18TPUNc)][Plen Bins: 0,0,75,24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]

**Comment by IvanNardi** [comment]
@sharonenoch , thanks for the report.
It is quite likely that ZOOM detection needs to be improved in nDPI.
However, please note that the VOIP stream in your trace (`udp.stream == 0`) is definitely a mid-stream, i.e. its initial packets are missing. Could you attached an example (unclassified) with the complete flow, please?

Note that `NDPI_CONFIDENCE_MATCH_BY_IP` has been recently removed: see a7c2734b387f6817088593f7c4e78d01dd6e0b74 for more details.
Anyway, `confidence` metadata always relates to proper stack classification.

**Comment by sharonenoch** [comment]
Thanks @IvanNardi ..  I had a feeling it could be a partial capture but was not entirely sure.. Since we captured like 6 captures but this was the only one which had this issue.. So thought I might as well post it here.. 

So where are we seeing this udp.stream == 0  output? Is it in ndpireader.. This way next time I can look for it and not have to open an issue

Also I noticed ZOOM has increased their port ranges for  UDP 8801 - 8810. I did not get time to make the change for this.. But if someone can add it to check for the range of ports, since currently the check is only for 8801 in the code. 

https://support.zoom.us/hc/en-us/articles/201362683-Network-firewall-or-proxy-server-settings-for-Zoom

So just to understand the ip classification change, if IP alone matches will the proto still be set? For example in a case where zoom used port 8808 but the IP belonged to zoom but the nDPI code did not support that port yet, would the proto be set to Zoom?

**Comment by sharonenoch** [comment]
Ignore the udp.stream question.. I realized you were referring from the context of Wireshark pcap capture filter options.

**Comment by IvanNardi** [comment]
> Also I noticed ZOOM has increased their port ranges for UDP 8801 - 8810. 

Thanks for pointing out that; as far as you know, is that a recent change? I have never found ZOOM on a port in the 8802-8810 range... but I think that it is only a matter of probability...

> So just to understand the ip classification change, if IP alone matches will the proto still be set? For example in a case where zoom used port 8808 but the IP belonged to zoom but the nDPI code did not support that port yet, would the proto be set to Zoom?

No. "Classification-by-ip" is completely unrelated to the "proper" classification set in `flow->detected_protocol_stack[]`. The former depends only on the ip address (L3 info), the latter only on deep-packet inspection logic (L4-7 info).
It goes without saying that the application might use these two separated pieces of information as it likes...

**Comment by sharonenoch** [comment]
Thanks for the explanation. 

I have also not yet seen a pcap where the ports are from 8802-8810 but I think zoom recently (Nov 2) updated that link showing the new ports.. So I feel it will start showing up

We had an instance where zoom did not get detected but I am yet to receive the pcap file for it.. Once I receive it will let you know what I find..

**Comment by sharonenoch** [comment]
I am closing this issue..
