### ISSUE TITLE
BGP detection crashes on Android

### ISSUE THREAD

**Issue by binkybear** [ntop/nDPI#181]
Running ntopng in chroot on Android phone run into this error (seen in gdb):

```
Program received signal SIGBUS, Bus error.
[Switching to Thread 0xf0dff440 (LWP 26621)]
ndpi_search_bgp (ndpi_struct=0xc90140, flow=0xf0418198) at protocols/bgp.c:43
43      if (packet->payload_packet_len > 18 &&
```

Removing BGP from nDPI fixes issue and ntopng will continue to run.  Unsure what is causing issue and I know it's a bit unusual to run on Android phone.

**Comment by kYroL01** [comment]
Are u able to send us a pcap that cause the crash ?

**Comment by lucaderi** [comment]
@binkybear I have made a fix https://github.com/ntop/nDPI/commit/1be91947343c6b1737d138d91947cdaa7f5891ad that might help. Better would be a pcap file or a better trace dump. Please upgrade and let us know.
This said, can you please comment (just curious) what are you doing with nDPi on Android?

**Comment by binkybear** [comment]
I can confirm that commit has fixed issue.  I wasn't expecting such a quick response/fix-amazing work!  Sorry I wasn't able to provide a pcap/trace dump soon.

So a quick background: I work on a project called Nethunter with is Kali Linux chroot running on android phones.  A request was made to get ntopng working within the chroot.  I was getting a bus error but wasn't sure where it was occurring so I tried building it from source.  Running it in gdb I could see error produced above.

In the end I was able to get ntopng running on android phone (OnePlus 1) [Imgur](http://i.imgur.com/QntmzNt.png) and wrote a [build guide](https://gist.github.com/binkybear/81c2115053a61ceae42dc984eb0384cf) for the user.  What the user wishes to do with it, I'm unsure but it's a very useful tool and thanks again for the help.

**Comment by lucaderi** [comment]
@binkybear This looks very interesting and it demonstrates the power of open source as I would have never expected to see ntopng on an Android device. If you want to write a README file to add into ntopng/docs please send me a pull request so we can document this. Thank you.

**Comment by kYroL01** [comment]
That's sounds great!
@binkybear is the software could be use in a stand-alone version to try it also in other Linux distributions ?
