### ISSUE TITLE
does ntopng include nProbe automically

### ISSUE THREAD

**Issue by tianzhishuizhu** [ntop/nDPI#182]
1. Does ntopng include nProbe automically?
2. I have seen documentation about nProbe.That shows it is necessary to create the nProbe license otherwise the probe will operate in demo mode. If ntopng has included nProbe, does nProbe work in demo mode? thanks!

**Comment by lucaderi** [comment]
nProbe is not necessary to ntopng unless you need to convert flows. Please see http://www.ntop.org/nprobe/advanced-flow-collection-with-ntopng-and-nprobe/
Yes if you want to use nProbe you need a license. Manual is here https://github.com/ntop/nProbe/tree/master/doc

**Comment by tianzhishuizhu** [comment]
Does it mean ntopng analyse traffic just by packets instead of flow without nprobe? Without nprobe, just by libpcap to capture packets?
