### ISSUE TITLE
When the port of the custom tcp/udp protocol is set to 65535, there is a problem with the ndpi interface

### ISSUE THREAD

**Issue by bryanlu2026** [ntop/nDPI#1829]
## Describe the bug
When the port of the custom tcp/udp protocol is set to 65535，loop can‘t be beak!
I found in the function addDefaultPort that when port = 65535, the for loop cannot be beak，I use ndpi 4.0.0。

**Comment by IvanNardi** [comment]
Thanks for finding and reporting this bug
