### ISSUE TITLE
ndpi_guess_undetected_protocol() only supports IPv4

### ISSUE THREAD

**Issue by aperezdc** [ntop/nDPI#183]
The function does not support using IPv6 addresses. Its prototype is (from `ndpi_api.h`):

``` c
ndpi_protocol
ndpi_guess_undetected_protocol(struct ndpi_detection_module_struct *ndpi_struct,
                               u_int8_t proto,
                               u_int32_t shost,
                               u_int16_t sport,
                               u_int32_t dhost,
                               u_int16_t dport);
```

The source/destination host addresses are 32-bit values, which is IPv4 only. One alternative could be that the `shost` and `sport` parameters have type `const u_int8_t*` (byte arrays), and adding an additional parameter to indicate the type of the addresses (en `enum` value).

**Comment by lucaderi** [comment]
I understand your point but at the moment we do not haver IPv6 to guess. Do you have any?

**Comment by lucaderi** [comment]
Closed for inactivity. Will resume when input will be provided.

**Comment by aperezdc** [comment]
@lucaderi: Sorry, I do not understand your reasoning that there are no IPv6 addresses to guess. Do you mean that the IP addresses passed to `ndpi_guess_undetected_protocol` are not used at all? Or is it something else?

**Comment by lucaderi** [comment]
@aperezdc I do not see a use case at the moment to justify its implementation. If you have time please implement it as one day we'll need to do it.
