### ISSUE TITLE
 nDPI integration

### ISSUE THREAD

**Issue by 0xA50C1A1** [ntop/nDPI#1848]
Hi guys! Are there any stuff that can help to figure out about the nDPI integration? Except for ndpiReader (it looks too complicated) and ndpiSimpleIntegration (well, it's much more clear), of course.

Do I need to implement my own connection tracker (similar to _ndpi_flow_info_ & _ndpi_workflow_ from ndpiSimpleIntegration) to integrate nDPI into my project?

**Comment by IvanNardi** [comment]
> Are there any stuff that can help to figure out about the nDPI integration? Except for ndpiReader (it looks too complicated) and ndpiSimpleIntegration (well, it's much more clear), of course.

Not much; `ndpiReader` and `ndpiSimpleIntegration` are the reference implementations.
Some basic (outdated) information are available in a pdf file under `doc\guide` and you could take a look at some projects that are using nDPI: ntopng, nDPId, nfstream (you can find them on github)
If you are starting from scratch, I advise you to start from `ndpiSimpleIntegration`

> Do I need to implement my own connection tracker (similar to _ndpi_flow_info_ & _ndpi_workflow_ from ndpiSimpleIntegration) to integrate nDPI into my project?

Yes, you do. Flow management (and packet dissection) is not performed by nDPI itself.

Sorry for not being more useful

**Comment by 0xA50C1A1** [comment]
tyvm for help
