### ISSUE TITLE
I can't understand this  

### ISSUE THREAD

**Issue by HaochuanXJTU** [ntop/nDPI#186]
if((iph->ihl \* 4) > ipsize || ipsize < ntohs(iph->tot_len) || (iph->frag_off & htons(0x1FFF)) != 0)
      return NULL;

what's the meaning of iph->frag_off & htons(0x1FFF)) != 0 ?

**Comment by kYroL01** [comment]
We check if an IP packet is fragmented or not. If yes, we discarted.
This is to keep thing simple in ndpiReader, becuase actually is only a demo app for test.
