### ISSUE TITLE
Bittorrent TCP restored sessions

### ISSUE THREAD

**Issue by nitroyar** [ntop/nDPI#1866]
Bittorrent protocol is not recognized under the following conditions:
- Restored torrent connection 
- TCP
- Handshake is not in the first packet with payload

PCAP:
[bittorrent_tcp_miss.zip](https://github.com/ntop/nDPI/files/10456062/bittorrent_tcp_miss.zip)

[bittorrent.c](https://github.com/ntop/nDPI/blob/dev/src/lib/protocols/bittorrent.c)
``` cpp
static void ndpi_int_search_bittorrent_tcp(struct ndpi_detection_module_struct *ndpi_struct, struct ndpi_flow_struct *flow)
{
  struct ndpi_packet_struct *packet = &ndpi_struct->packet;

  if(packet->payload_packet_len == 0) {
    return;
  }

  if(flow->bittorrent_stage == 0 && packet->payload_packet_len != 0) {
    /* exclude stage 0 detection from next run */
    flow->bittorrent_stage = 1;
    if(ndpi_int_search_bittorrent_tcp_zero(ndpi_struct, flow) != 0) {
      NDPI_LOG_DBG2(ndpi_struct, "stage 0 has detected something, returning\n");
      return;
    }

    NDPI_LOG_DBG2(ndpi_struct, "stage 0 has no direct detection, fall through\n");
  }
  return;
}
```

## nDPI Environment:
* Docker: https://hub.docker.com/r/ntop/ntopng

**Comment by IvanNardi** [comment]
Thanks for reporting this issue
