### ISSUE TITLE
How to enable protocols that are not initialized by default, e.g. vimeo, googleclassroom, ..

### ISSUE THREAD

**Issue by dinarsalem** [ntop/nDPI#1871]
I am trying to enable some protocols that are not initialized by default, but do exist in the protocol id file:
https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_protocol_ids.h
Like: vimeo, googleclassroom and others.

**Comment by IvanNardi** [comment]
@dinarsalem, are you sure you are writing to the right people/repository? :)
There is no such a thing like `/proc/net/xt_ndpi/proto` in upstream nDPI; maybe some fork?

**Comment by dinarsalem** [comment]
Correct, updated my question. 
I have been trying both upstream and the fork.
For the upstream, how can I  enable the above two protocols?

**Comment by IvanNardi** [comment]
I am pretty sure that, by default, all protocols are enabled (in upstream)
For example:
```
ivan@ivan-Latitude-E6540:~/svnrepos/nDPI(dev)$ ./example/ndpiReader -t -i tests/pcap/sites.pcapng | grep Vimeo
	Vimeo                packets: 25            bytes: 7256          flows: 1  
```

**Comment by IvanNardi** [comment]
Closing. If you have other questions, please open a new ticket
