### ISSUE TITLE
Failure to detect OpenVPN traffic when using `tls-crypt`

### ISSUE THREAD

**Issue by hfz1337** [ntop/nDPI#1873]
## Describe the bug
The OpenVPN dissector assumes that all packets contain an HMAC.

### Obtained behavior
When using OpenVPN in `tls-crypt` mode, control packets won't have an HMAC, like shown in the following picture:

![OpenVPN layer](https://ctrlv.link/shots/2023/01/24/hte7.png)

It would be great to add support for this mode using something like:

```diff
 #define P_SHA1_HMAC_SIZE 20
 #define P_HMAC_128 16                            // (RSA-)MD5, (RSA-)MD4, ..others
 #define P_HMAC_160 20                            // (RSA-|DSA-)SHA(1), ..others, SHA1 is openvpn default
+#define P_HMAC_NONE 0                            // No HMAC
 #define P_HARD_RESET_PACKET_ID_OFFSET(hmac_size) (9 + hmac_size)
-#define P_PACKET_ID_ARRAY_LEN_OFFSET(hmac_size)  (P_HARD_RESET_PACKET_ID_OFFSET(hmac_size) + 8)
+#define P_PACKET_ID_ARRAY_LEN_OFFSET(hmac_size)  (P_HARD_RESET_PACKET_ID_OFFSET(hmac_size) + (hmac_size == P_HMAC_NONE ? 0 : 8))
 #define P_HARD_RESET_CLIENT_MAX_COUNT  5
 
 static 
@@ -75,6 +76,9 @@ int8_t check_pkid_and_detect_hmac_size(const u_int8_t * payload) {
   
   if(get_packet_id(payload, P_HMAC_128) == 1)    
     return P_HMAC_128;
+
+  if((get_packet_id(payload, P_HMAC_NONE) & 0xffffff) == 0)
+    return P_HMAC_NONE;
   
   return(-1);
 }
@@ -90,7 +94,7 @@ void ndpi_search_openvpn(struct ndpi_detection_module_struct* ndpi_struct,
   int8_t failed = 0;
   /* No u_ */int16_t ovpn_payload_len = packet->payload_packet_len;
   
-  if(ovpn_payload_len >= 40) {
+  if(ovpn_payload_len >= 16) {
     // skip openvpn TCP transport packet size
     if(packet->tcp != NULL)
       ovpn_payload += 2, ovpn_payload_len -= 2;;
@@ -122,7 +126,7 @@ void ndpi_search_openvpn(struct ndpi_detection_module_struct* ndpi_struct,
     
     if(flow->ovpn_counter < P_HARD_RESET_CLIENT_MAX_COUNT && (opcode == P_CONTROL_HARD_RESET_CLIENT_V1 ||
                                                              opcode == P_CONTROL_HARD_RESET_CLIENT_V2)) {
-      if(check_pkid_and_detect_hmac_size(ovpn_payload) > 0) {
+      if(check_pkid_and_detect_hmac_size(ovpn_payload) > -1) {
         memcpy(flow->ovpn_session_id, ovpn_payload+1, 8);
 
         NDPI_LOG_DBG2(ndpi_struct,
@@ -135,7 +139,7 @@ void ndpi_search_openvpn(struct ndpi_detection_module_struct* ndpi_struct,
 
       hmac_size = check_pkid_and_detect_hmac_size(ovpn_payload);
 
-      if(hmac_size > 0) {
+      if(hmac_size > -1) {
```

PS: The above changes don't work with the PCAP provided at the end, I later realized that the packets don't have a remote session ID either (I'm still reading on OpenVPN internals to know why).

### Expected behavior
nDPI properly detects OpenVPN traffic when `tls-crypt` mode is used.

### Reproducible using ndpiReader?
- [x] The reported bug is reproducible using ndpiReader.
- [ ] The reported bug is not reproducible using ndpiReader.

### If applicable, the used ndpiReader options:

``` shell
ndpiReader -i openvpn_tcp.pcap
```

### If your bug is reproducible using a pcap, please attach a pcap file (or a valid link to download it)

[openvpn_tcp.zip](https://github.com/ntop/nDPI/files/10489946/openvpn_tcp.zip)

nDPI will detect the above traffic as TLS (only because the server's port is 443, otherwise it doesn't detect anything, i.e., `Unknown`).

**Comment by IvanNardi** [comment]
I think we might have 2 different issues here:
1) nDPI is not able to detect OpenVPN flows without HMAC
2) nDPI is not able to detect OpenVPN flows where in the RESET_SERVER msg there is not a Remote-Session-Id field (no idea if this combination is likely or even possible; it seem so, thought)
