### ISSUE TITLE
A bug with ipv6 address format

### ISSUE THREAD

**Issue by hungcm95** [ntop/nDPI#1890]
## Describe the bug
Because ndpi_patchIPv6Address will replace all :0: to ::, the results may have ip like this 2600:1901::16a9:: . It's a wrong ipv6 format, it has multiple '::'

**Comment by IvanNardi** [comment]
This issue is real and has been already reported in the past (https://github.com/ntop/nDPI/issues/819)
No sure how to move forward...

**Comment by IvanNardi** [comment]
I think that we can leave this issue open: we should fix it, somehow....

**Comment by paolomonti** [comment]
Hi guys, I have a very easy patch for this, If you're still interested:
```
--- a/src/lib/ndpi_utils.c
+++ b/src/lib/ndpi_utils.c
@@ -918,6 +921,9 @@
 void ndpi_patchIPv6Address(char *str) {
   int i = 0, j = 0;

+  if(strstr(str, "::"))
+   return;
+
   while(str[i] != '\0') {
     if((str[i] == ':')
        && (str[i+1] == '0')
```
Bye.

**Comment by IvanNardi** [comment]
It seems reasonable. Are you going to push a PR?

**Comment by paolomonti** [comment]
ok
