### ISSUE TITLE
Add nDPI support for Beta application

### ISSUE THREAD

**Issue by tomerto** [ntop/nDPI#19]
Add nDPI support for Beta application. PCAP file with example sent separately.

**Comment by lucaderi** [comment]
@tomerto The trace you sent me for testing contains a few SSL handshake sessions, but in real traffic to analyse. Example the connections below have just SSL handshake.
	6	TCP 10.8.0.1:60406 <-> 72.246.97.26:443 [proto: 64/SSL_No_Cert][13 pkts/845 bytes]
	7	TCP 10.8.0.1:60408 <-> 72.246.97.26:443 [proto: 64/SSL_No_Cert][13 pkts/845 bytes]
	8	TCP 10.8.0.1:60410 <-> 72.246.97.26:443 [proto: 64/SSL_No_Cert][13 pkts/845 bytes]
	9	TCP 10.8.0.1:60412 <-> 72.246.97.26:443 [proto: 64/SSL_No_Cert][13 pkts/845 bytes]
	10	TCP 10.8.0.1:60430 <-> 72.246.97.26:443 [proto: 64/SSL_No_Cert][11 pkts/737 bytes]

Please provide a longer pcap with real traffic.

**Comment by lucaderi** [comment]
Fixed in https://github.com/ntop/nDPI/commit/2f347a33d8564ebb9f2bf42d344398912f682898
