### ISSUE TITLE
block icmp

### ISSUE THREAD

**Issue by jldoper** [ntop/nDPI#1907]
Can I block ICMP traffic with this program?

**Comment by IvanNardi** [comment]
You can't out-of-the-box. nDPI is a *library* that allow to classify/identify traffic (and lots more features...). It is up to the *application* using it to implement any logic (pass/block/log/export/...).
For example you can take a look at https://github.com/vel21ripn/nDPI or https://www.ntop.org/products/traffic-analysis/ntopng-edge/
