### ISSUE TITLE
How to debug nDPI

### ISSUE THREAD

**Issue by tianzhishuizhu** [ntop/nDPI#191]
How can I debug nDPI source code in linux? Can you help me?

**Comment by kYroL01** [comment]
Do you want debug because you find issues or to understand how it works ?
I suggest you to use _gdb_ and see how the program go on.

**Comment by tianzhishuizhu** [comment]
@kYroL01  I want to understand how it works. I have downloaded the source code of ndpi. How can I compile to debug the whole code? Thanks

**Comment by kYroL01** [comment]
There isn't a debug mode. Once you have downloaded the code you have to do:
- ./autogen.sh
- ./configure
- make

Now your code is ready and I suggest you to run _**gdb**_ on [ndpiReader](https://github.com/ntop/nDPI/blob/dev/example/ndpiReader.c) make a breakpoint on main (and on other functions) and see the flow of execution.

**Comment by tianzhishuizhu** [comment]
@kYroL01 Thanks for your reply!

**Comment by kYroL01** [comment]
You're welcome.

**Comment by tianzhishuizhu** [comment]
@kYroL01  I have done the three steps you mentioned. I find a execute file named **ndpiReader** in the directory
`nDPI/example/ndpiReader`. Do you mean debug nDPI just with the command `gdb ndpiReader`?  **But how to refer the pcap file as input packet?**

**Comment by kYroL01** [comment]
@tianzhishuizhu Have you ever program in C ? Do you know how gdb work ? 
If you are not a programmer it's hard to explain how to do.
I suggest you to read the documentation of nDPI if you are not able to navigate through the code.

https://github.com/ntop/nDPI/blob/dev/doc/nDPI_QuickStartGuide.pdf

**Comment by tianzhishuizhu** [comment]
@kYroL01  I have read it. I try `gdb ./ndpiReader -i my.pcap`. But gdb outputs `Interpreter my.pcap' unrecognized`. The document shows `ndpiReader -i <file|device>`

**Comment by kYroL01** [comment]
Well, It's impossible for me teach you in this way how a debugger like gdb could be use.
It's not a fast thing to explain: http://www.delorie.com/gnu/docs/gdb/gdb_toc.html

**Comment by zhangwh1996** [comment]
Log files generated using ndpireader is too small.In Ubunt,I use "sudo ./ndpiReader. ndpiReader -i data.cap  -f "ip and (tcp or udp)" -z a.log"to complete a traffic classification.The data.cap is 2.7GB,but the  a.log is only 4000KB.WHY?Who can help me?Thank you.
