### ISSUE TITLE
Not able to store the nDPI logs as and when it is streaming

### ISSUE THREAD

**Issue by Balukn11** [ntop/nDPI#1912]
## Describe the bug
When trying to write the captured logs in JSON format to a custom file using -k & -K modes, the data collected is not getting stored to the custom file location until the ndpiReader command is stopped. As soon as the CLI command is stopped the entire log is getting written to the file. 

### Expected behavior
The data logs must be written to the custom destination file as and when it is encountered and not as a bulk at the end of the execution.

## nDPI Environment (please complete the following information):
* OS name: Ubuntu
* OS version: 22.04.1
* nDPI version: 4.6.0

### Reproducible using ndpiReader?
- [x] The reported bug is reproducible using ndpiReader.

### If applicable, the used ndpiReader options:

``` shell
ndpiReader -i eth0 -k /mnt/home/ubuntu/logstest.log -K json -q
```

**Comment by utoni** [comment]
Please note that `ndpiReader` is just an example application not meant to run in a production environment and stream JSON data continuously.

**Comment by Balukn11** [comment]
Is there any possible way to stream JSON data using nDPI?

**Comment by IvanNardi** [comment]
> Is there any possible way to stream JSON data using nDPI?

AFAIK, no out-of-the-box. It could be possible updating `ndpiReader` code (I don't have experience with json export): patches are welcome :)

**Comment by Balukn11** [comment]
Otherwise, if not JSON, do you have any idea on how to stream the nDPI logs as soon as it is read?

**Comment by utoni** [comment]
You may try https://github.com/utoni/nDPId which is meant to be used as nDPI JSON streaming application.

**Comment by Balukn11** [comment]
Tried nDPId, but not able to get the application name from the flow. And experienced a delay in getting the logs from the socket.
