### ISSUE TITLE
how to use ndpi to block specific protocol(mysql,http,https,etc...) and Integration with istio

### ISSUE THREAD

**Issue by INT2ECALL** [ntop/nDPI#1917]
any example or suggestion

**Comment by IvanNardi** [comment]
No experience with istio, sorry.
You can't block traffic directly only with nDPI. nDPI is a library that allow to classify/identify traffic (and lots more features...). It is up to the *application* using it to implement any logic (pass/block/log/export/...).
Some example of applications that allow you to block traffic and that are based on nDPI:  https://github.com/vel21ripn/nDPI or https://www.ntop.org/products/traffic-analysis/ntopng-edge/

**Comment by INT2ECALL** [comment]
thank for help,i know how to do it,use nfq
