### ISSUE TITLE
Get domain name from URL

### ISSUE THREAD

**Issue by subhajit-cdot** [ntop/nDPI#1919]
Hi,
In http or https parser, ndpi has support to extract URL/SNI info. There are other fields ( method/mime type etc) as well which are extracted in nDPI from http/https packets. How can we get domain name/SLD, subdomain name, TLDs etc. from URL? Is there any function/API already available or used inside nDPI?

Thanks
Subhajit

**Comment by IvanNardi** [comment]
AFAIK, no there is not.
However, curl guys are just creating a similar tool: you might take a look at https://daniel.haxx.se/blog/2023/04/03/introducing-trurl/
