### ISSUE TITLE
how to make a debug libndpi?

### ISSUE THREAD

**Issue by ccworkhard** [ntop/nDPI#1925]
this is my command, but it is not a debug ndpi.

 1  ./autogen.sh
 2  ./configure --enable-debug-messages
 3  make

**Comment by IvanNardi** [comment]
If you mean "a build with debug symbols" you can try something like:
`NDPI_CFLAGS="-g" ./autogen.sh && make -s -j`

**Comment by utoni** [comment]
Hm, @IvanNardi what about adding `--enable-debug` to autoconf?

**Comment by ccworkhard** [comment]
> If you mean "a build with debug symbols" you can try something like: `NDPI_CFLAGS="-g" ./autogen.sh && make -s -j`

yeah, it help me to build a debug symbols, thanks a lot.
