### ISSUE TITLE
Does nDPI supports multi instance ?

### ISSUE THREAD

**Issue by subritm** [ntop/nDPI#196]
I have a Linux system which has multiple people login.
I need to detect custom applications as well as predefine ones?
How can we achieve this ?

Each user is expected to have different custom applications.
Also out of 256 applications total, over 190 is predefined so leaving very less for custom. 
So taking approx values , we have 66 number custom application left.

if there are 6 people adding 11 each that will be over.
So there is no way we can have more..!

If I can run multiple instance of the nDPI and each instance for a specific user, every one will get at least 66 custom app option.

Thanks in advance.

**Comment by lucaderi** [comment]
For new protocols you need to create a dissector this unless the protocol can be detected by configuring nDPI (see ndpireader -p). If your protocols to add will exceed 256 we will find a solution. Start sending pull requests and we'll see what we can do.
