### ISSUE TITLE
Questrion about detected mysql database source.

### ISSUE THREAD

**Issue by ccworkhard** [ntop/nDPI#1961]
I use the ndpiReader demo to detect several version of mysql source, including 5.6, 5.7, 8.0, 8.0.26, 8.0.33.

When I use 3306 port as mysql data source, nDPI can detect the any version of mysql. But when I use other port (not 3306, such as 10000), nDPI can only detect 5.6, 5.7 version,  can't detect 8.0, 8.0.26, 8.0.33 version.

So what is the principle of nDPI detect mysql?  How can i detected mysql source in any version and any port ?

Thanks a lot.

**Comment by IvanNardi** [comment]
> So what is the principle of nDPI detect mysql? How can i detected mysql source in any version and any port ?

You should be able to detect mysql regardless the version and the port. If not, please share the traces triggering the issue

**Comment by ccworkhard** [comment]
> > So what is the principle of nDPI detect mysql? How can i detected mysql source in any version and any port ?
> 
> You should be able to detect mysql regardless the version and the port. If not, please share the traces triggering the issue

> - 1. I change the ndpi_process_packet of nDPIReader.c, I add several code, here is :

                  static void ndpi_process_packet(u_char *args,
		                  		const struct pcap_pkthdr *header,
				                  const u_char *packet) {
                    struct ndpi_proto p;
                    ndpi_risk flow_risk;
                    u_int16_t thread_id = *((u_int16_t*)args);

                    /* allocate an exact size buffer to check overflows */
                    uint8_t *packet_checked = ndpi_malloc(header->caplen);

                    if(packet_checked == NULL) {
                      return ;
                    }

                    memcpy(packet_checked, packet, header->caplen);
                    p = ndpi_workflow_process_packet(ndpi_thread_info[thread_id].workflow, header, packet_checked, &flow_risk, a_probe_info);


                    /**************  here is my code beginning **************/

                    u_int16_t probe_app_protocol = p.app_protocol;
                    char *probe_proto_name = ndpi_get_proto_name(ndpi_thread_info[thread_id].workflow->ndpi_struct, probe_app_protocol);
                                    
                    switch (probe_app_protocol) {
                      case 1: // FTP_CONTROL
                      case 5: // DNS
                      case 7: // HTTP
                      case 175: // FTP_DATA
                      case 20: // MYSQL
                        printf("app_protocol is %d, probe_proto_name is %s", probe_app_protocol,probe_proto_name);
                        break;
                    }
                                    
                    /**************  here is my code ending **************/
                                    
                    if(!pcap_start.tv_sec) pcap_start.tv_sec = header->ts.tv_sec, pcap_start.tv_usec = header->ts.tv_usec;
                    pcap_end.tv_sec = header->ts.tv_sec, pcap_end.tv_usec = header->ts.tv_usec;
                    .....
                    .....
                    .....
                      /*
                      Leave the free as last statement to avoid crashes when ndpi_detection_giveup()
                      is called above by printResults()
                    */
                    if(packet_checked) {
                      ndpi_free(packet_checked);
                      packet_checked = NULL;
                    }
                  }
  
  
  
  

>   2. then i pull mysql images and run the docker 


          (1) docker pull mysql:8.0.33
          (2) docker run --name mysql -e MYSQL_ROOT_PASSWORD=1234qwer -d -p 4000:3306 mysql:8.0.33
          
          

>   3. finally, i use ndpiReader to detected mysql source which is using 4000 port, but i can't detected the source.(Howerver, i can detected mysql when i use 3306 port)

**Comment by utoni** [comment]
>       (1) docker pull mysql:8.0.33
>       (2) docker run --name mysql -e MYSQL_ROOT_PASSWORD=1234qwer -d -p 4000:3306 mysql:8.0.33

Please record and provide a PCAP traces that contains the packets that were not detected.

**Comment by ccworkhard** [comment]
> > So what is the principle of nDPI detect mysql? How can i detected mysql source in any version and any port ?
> 
> You should be able to detect mysql regardless the version and the port. If not, please share the traces triggering the issue

> 
                  
> 

> > ```
> >   (1) docker pull mysql:8.0.33
> >   (2) docker run --name mysql -e MYSQL_ROOT_PASSWORD=1234qwer -d -p 4000:3306 mysql:8.0.33
> > ```
> 
> Please record and provide a PCAP traces that contains the packets that were not detected.

it's a binary file of pcap, how can i send it to you?

**Comment by utoni** [comment]
You can upload it right here in the issue.

**Comment by ccworkhard** [comment]
[](url)

**Comment by ccworkhard** [comment]
> You can upload it right here in the issue.
[output.log](https://github.com/ntop/nDPI/files/11402735/output.log)


github don't support pcap file, so i change the file suffix to log, you can rename it to a output.pcap. 
Thanks a lot.

**Comment by IvanNardi** [comment]
@ccworkhard I checked the pcap. Which nDPI version are you using? It works with current master

**Comment by ccworkhard** [comment]
> @ccworkhard I checked the pcap. Which nDPI version are you using? It works with current master

4.6 version with debug

**Comment by IvanNardi** [comment]
> > @ccworkhard I checked the pcap. Which nDPI version are you using? It works with current master
> 
> 4.6 version with debug, which port you test?

You should update to master and it will work

**Comment by ccworkhard** [comment]
> > > @ccworkhard I checked the pcap. Which nDPI version are you using? It works with current master
> > 
> > 
> > 4.6 version with debug, which port you test?
> 
> You should update to master and it will work

yeah, i tried dev branch, and it can detected mysql source in any port. Do dev is a stable version?

**Comment by IvanNardi** [comment]
Technically speaking, it is not; it is the development branch. But for almost any purposes , you can safely use dev

**Comment by ccworkhard** [comment]
> Technically speaking, it is not; it is the development branch. But for almost any purposes , you can safely use dev

thanks a lot.

**Comment by IvanNardi** [comment]
Closing. If you have other issues, please open a new ticket, specifying nDPI version and attaching a trace
