### ISSUE TITLE
add protocols : db2 and hsrp

### ISSUE THREAD

**Issue by Niko78** [ntop/nDPI#198]
hi,
I use ntopng with ndpi and that would be great if ndpi could detect db2 & hsrp protocols
You can can get pcap from here

HSRP : https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=get&target=hsrp.pcap
DB2 : https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=get&target=drda_db2_sample.tgz

thanks, regards

Nico

**Comment by Niko78** [comment]
hi,
just for my information
what's the ETA for protocols integration in ndpi usually ?
thanks

Nico

**Comment by lucaderi** [comment]
These protocols are added in best effort mode. If you want to expedite the process please consider funding the development.

**Comment by Niko78** [comment]
ok thanks for info
it was just to know

have a nice week end

Nico

**Comment by alagoutte** [comment]
I start to looking for add HSRP support !

**Comment by Niko78** [comment]
great

**Comment by kYroL01** [comment]
DRDA / DB2 https://github.com/ntop/nDPI/commit/0e49eb1d17c33b784359f8dbdbb59041cac7aaab

**Comment by Niko78** [comment]
thanks

**Comment by kYroL01** [comment]
@alagoutte any update for HSRP support ?

**Comment by alagoutte** [comment]
Sorry to busy for the moment...

**Comment by kYroL01** [comment]
No problem, just to know.

**Comment by IvanNardi** [comment]
HSRP support added in be5a29ba9d4da849992b7a4b42047e591bde20aa
