### ISSUE TITLE
Add support for LISP

### ISSUE THREAD

**Issue by anubisg1** [ntop/nDPI#199]
Locator/ID Separation protocol has control plane and dataplane udp encapsulation.
Encapsulated user data packets are transported using UDP port 4341, and LISP control packets are transported using UDP port 4342.

really easy to detect.

**Comment by lucaderi** [comment]
Please provide a pcap file with packets

**Comment by anubisg1** [comment]
Here:

https://www.cloudshark.org/captures/457f86a4c0f0

last 2 packets are data-plane transported over a lisp tunnel.

**Comment by huniyaarif1** [comment]
I created a protocol decoder for LISP based on this raised issue. I tested it by creating UDP packets in Scapy and it's working correctly. I wanted to know if I can contribute and what is the testing process?

**Comment by kYroL01** [comment]
Send a pull request with code, thanks
