### ISSUE TITLE
False positive TOR detection by domain from SNI

### ISSUE THREAD

**Issue by Mirraz** [ntop/nDPI#2068]
When I open site https://accuweather.com libndpi classifies requests to https://www.awxcdn.com as TOR.
Also I checked this domain with tests/dga/dga_evaluate:
```
 [NON DGA]	google.com
 [NON DGA]	accuweather.com
     [DGA]	www.awxcdn.com
1
```

This is very similar to issue https://github.com/ntop/nDPI/issues/1397

**Comment by utoni** [comment]
I've observed a similar behavior for live traffic analyzing environments.
The DGA algorithm generates false-positives in some rare cases e.g. for the mentioned domain.

**Comment by lucaderi** [comment]
Fixed
