### ISSUE TITLE
JA4+ Network Fingerprinting

### ISSUE THREAD

**Issue by IvanNardi** [ntop/nDPI#2093]
Should we add support on nDPI to these new fingerprints?

https://blog.foxio.io/ja4-network-fingerprinting-9376fe9ca637

Wireshark issue: https://gitlab.com/wireshark/wireshark/-/issues/19370

**Comment by IvanNardi** [comment]
Patent issues: https://github.com/FoxIO-LLC/ja4/issues/15

**Comment by lucaderi** [comment]
Implemented just the patent-free JA4 (no JA+)
