### ISSUE TITLE
I can't understand this  

### ISSUE THREAD

**Issue by HaochuanXJTU** [ntop/nDPI#211]
I can't understand of the utility of "excluded_protocol_bitmask", looking forward to your favourable reply.

**Comment by kYroL01** [comment]
The field _"excluded_protocol_bitmask"_ , as self-explained its name, is necessary to exclude a protocol during the classification for a flow.
If you see a protocol dissector, it is called when we are sure that the packet/flow we're analyzing cannot detected with that protocol. So in the bitmask for _protocols we can exclude for this flow_ we set the bit representing that protocol.
