### ISSUE TITLE
Custom protocol file precedence

### ISSUE THREAD

**Issue by bcronje** [ntop/nDPI#212]
If I load a custom protocol file via ndpi_load_protocols_file() , will any custom protocols in that file take precedence over the build-in nDPI detection? Or will the custom protocols only be used as last resort if nDPI cannot detect the protocol?

**Comment by lucaderi** [comment]
The loaded protocols have no precedence with respect to the native dissectors. They are not for last resort, but for characterising traffic not handled by the native engine
