### ISSUE TITLE
WhatsApp detection

### ISSUE THREAD

**Issue by alrferreira** [ntop/nDPI#213]
Hello,
I use ndpi with iptables. After the implementation of encryption, WhatsApp messages not be blocked and detected by ndpi.

**Comment by lucaderi** [comment]
@alrferreira Please share a pcap file we can use for troubleshooting

**Comment by kYroL01** [comment]
@alrferreira any news or pcap to share ?

**Comment by Mile-Lile** [comment]
I'm not sure if this can help but I did my best...
[WhatsApp_SSL.zip](https://github.com/ntop/nDPI/files/344658/WhatsApp_SSL.zip)

**Comment by kYroL01** [comment]
After analyzed that pcap, I think that is not a good WhatsApp session.
I did a test and WA is still detected.
Please open a new issue in case of problems.
Thanks
