### ISSUE TITLE
Use nDPI on socket payload

### ISSUE THREAD

**Issue by sduponch** [ntop/nDPI#214]
Hi ,

I want to use libndpi on a shadowsocks TCP proxy to set the TOS flag of a socket from his payload.
Unfortunatly , NDPI seem to do not Provide direct access to L4 detection.

Best regards ,
Sébastien DUPONCHEEL

**Comment by lucaderi** [comment]
nDPI is for packet inspection and application characterisation. If you want to change the TOS, you can do that by setting the TOS bit and recomputing the checksum without any nDPI need

**Comment by sduponch** [comment]
I want to classify the payload of my socket without the IP header (as i have no acces to it from the application level). I already know how set TOS inside shadowsocks...
