### ISSUE TITLE
Port 4343 IANA registered for: UNICALL app

### ISSUE THREAD

**Issue by sharonenoch** [ntop/nDPI#2141]
Is it possible to add support for UNICALL? It has a IANA registered port at 4343.. but I see that Whois-das code path is also checking for 4343 when it is registered only for port 43. 

I don't have a tcpdump to share for UNICALL but since it is a pre-defined port, is it possible to add UNICALL app as the preferred application for port 4343 on both tcp and udp

**Comment by utoni** [comment]
I would like to implement that protocol as dissector, but I was not able to find any information regarding protocol specification. Do you have any hints for me?

**Comment by sharonenoch** [comment]
Unfortunately the only data I had was a screenshot from Kibana where nDPI detected the app as TLS from the tcp protocol and kibana listed the service name as unicall.. I know for sure though that the end user was using unicall application.. (attached screenshot)
![unicall](https://github.com/ntop/nDPI/assets/52180175/e5e00a7b-2254-49ca-8aaa-f2ceeba90f90)


Initially I thought of adding the dissector with the ports alone but then I saw the conflicting port with whois and was not sure how to go about it.. Probably the dissector can check for both TCP + TLS and port 4343?  whereas regular whois is always cleartext

**Comment by utoni** [comment]
That could work and I guess there won't be lot's of other options to solve this if Unicall uses TLS.
But I am too scared to implement this w/o a PCAP or protocol specification.

// EDIT: I am not a fan of port based detection in general. ;)

**Comment by sharonenoch** [comment]
So I have some more data based on which we do not need to add this..  We also did some experiments to confirm this.. 

It looks like they were just redirecting the port 4343 to port 443, so it got detected as TLS.. and Kibana was just mapping it to service based on IANA defined port.. :-(

We also found that this was some sort of norm.. Check the below link and port 4343
https://www.arubanetworks.com/techdocs/ArubaOS_83_Web_Help/Content/ArubaFrameStyles/Defaults/Default_Open_Ports.htm

Some other information on Unicall which I found, and it seems to be some very old protocol..  Check the comments sections in the link below
https://networklessons.com/cisco/ccie-routing-switching-written/eigrp-otp-over-the-top

https://www.soft-switch.org/unicall/mfcr2/ch01.html

We also tried the unicall voice app on the app store just to be sure it was not a voice application.. and that pcap showed STUN and RTP similar to other voice applications

I will close this issue..
