### ISSUE TITLE
No default values for NDPI_PROTOCOL_SINA_WEIBO

### ISSUE THREAD

**Issue by TxS-7** [ntop/nDPI#2146]
Hello,

when running nDPI (dev branch, 38f9a74713c9905ab9fe4761ff975aa20ea1a8e8), I got a warning from ndpi_main.c: ndpi_validate_protocol_initialization for protocol ID 356: NDPI_PROTOCOL_SINA_WEIBO.

Is the initialization for this protocol ID missing from ndpi_init_protocol_defaults?

Thank you.

**Comment by koltiradw** [comment]
@TxS-7 hi!
I cannot reproduce this behaviour.
Can you describe what u do?

**Comment by TxS-7** [comment]
Closing issue, as it was not a problem with the nDPI code. It was a mistake on my part.
