### ISSUE TITLE
ndpi does no longer flag traffic correctly for custom applications

### ISSUE THREAD

**Issue by mfahrner-mpg** [ntop/nDPI#2147]
Since the ntopng update to 6.0 my ndpi does no longer seem to correctly flag traffic corresponding to custom application rules.
For example, I've set custom applications for TSM and CEPH, those show up in the /var/lib/ntopng/protos.txt as follows:

`# CEPH`
`tcp:6800-7300@CEPH=1025`
`# TSM`
`tcp:1500@TSM=1024`

In the flow view or dashboard the traffic does still get incorrectly flagged as 'unknown', it _DOES_ however get flagged correctly in the traffic report.

**Comment by utoni** [comment]
Does it work within `ndpiReader` ?
E.g. I've just tried

```txt
tcp:70-90@TEST=1024
tcp:443@FOOBAR=1025
```

and it works with `ndpiReader`.

I think this issue might be related to [ntop](https://github.com/ntop/ntopng).

**Comment by mfahrner-mpg** [comment]
You are right, it works within ndpiReader for me too. Do you want me to open a new issue with ntop?

**Comment by IvanNardi** [comment]
I didn't run any tests, but AFAIK, port ranges are not supported in nDPI yet (https://github.com/ntop/nDPI/issues/2124).
ntopng *may* un-rolls these rules, though; no idea if it does that...
