### ISSUE TITLE
Skype dissector gives false positive response on Omron FINS traffic

### ISSUE THREAD

**Issue by 0xA50C1A1** [ntop/nDPI#2158]
## Describe the bug
I'm trying to write an Omron FINS protocol dissector and for a while I couldn't figure out why it wasn't working as intended. This protocol can use either TCP or UDP, but incorrect detection only occurs when using UDP as a transport. At first I thought it was some kind of logical error in my code (I check almost all header fields to make sure there are no false positives), but then I looked into the skype dissector and saw a lot of kludges.

### Expected behavior
Detection as `OmronFINS` if compiled with my dissector, or as `Unknown` if compiled without.

![Omron FINS packet](https://github.com/ntop/nDPI/assets/105977161/711d4629-58ec-4fb6-a601-6e63bfe1f6f3)

### Obtained behavior
Invalid detection [caused by this](https://github.com/ntop/nDPI/blob/bdb73db1a49d271bfb958eaabcce489013d84f3c/src/lib/protocols/skype.c#L72C1-L75C3)

## nDPI Environment (please complete the following information):
* OS name: Ubuntu
* OS version: 23.04
* Architecture: x86_64
* nDPI version or commit hash: bdb73db1a49d271bfb958eaabcce489013d84f3c
* nDPI compilation flags used:  --with-pcre2 --with-nbpf-path=~/PF_RING/userland/nbpf/

[config.log](https://github.com/ntop/nDPI/files/13404601/config.log)

### Reproducible using ndpiReader?
- [x] The reported bug is reproducible using ndpiReader.

### If applicable, the used ndpiReader options:

``` shell
ndpiReader -i ~/omron.pcap
```

### If your bug is reproducible using a pcap, please attach a pcap file (or a valid link to download it)

[omron.zip](https://github.com/ntop/nDPI/files/13404543/omron.zip)

### Steps to reproduce the behavior:
1. Run 'ndpiReader -i omron.pcap'
4. See false-positive detection as SkypeTeams_Call

**Comment by IvanNardi** [comment]
There are some issues with the Skype code...
Since it seems that Omron protocol usually uses 9600 as port, you can add a quick workaround adding a new exception around line 52 of `skype.c`
