### ISSUE TITLE
Get rid of the old Skype dissector

### ISSUE THREAD

**Issue by 0xA50C1A1** [ntop/nDPI#2166]
**Is your feature request related to a problem? Please describe.**
[Skype protocol dissector](https://raw.githubusercontent.com/ntop/nDPI/dev/src/lib/protocols/skype.c) is obsolete and causes false positives - #2158. #1954 - there has already been discussion under this pull request, but the broken dissector has been kept for now.

**Describe the solution you'd like**
Skype hasn't used P2P connections over UDP for a long time and uses TLS+STUN like every other messengers. There's no point in keeping an old Skype protocol dissector that doesn't work anymore, especially since it gives false positives on various UDP traffic.

Here is a pcap with modern Skype traffic and [ndpiReader output](https://pastebin.com/uVBXGutE) to prove my point.
[PCAP](https://github.com/ntop/nDPI/files/13460980/skype_desktop_linux.zip)

![Снимок экрана от 2023-11-24 18-11-52](https://github.com/ntop/nDPI/assets/105977161/2eb70653-1099-42c7-815a-d2d80086cfd8)

**Comment by IvanNardi** [comment]
It might be time to push again for this old PR https://github.com/ntop/nDPI/pull/1954...

**Comment by IvanNardi** [comment]
Done in https://github.com/ntop/nDPI/commit/ae36648c6cc08a5ef170a719a4476fe16e3a0e37
