### ISSUE TITLE
Add ISC/SCADA Support

### ISSUE THREAD

**Issue by lucaderi** [ntop/nDPI#217]
See packet traces at https://github.com/automayt/ICS-pcap

**Comment by send2cny** [comment]
Any updates on this?

**Comment by utoni** [comment]
Most of the pcap files in ICS-pcap are using an invalid / unsupported pcap format.
But the few working pcap's are getting successfully detected by the nDPI engine.

**Comment by IvanNardi** [comment]
In the last 6 years a lot of industrial/scada protocols have been added...
If someone is interested in a specific, missing protocol, please open a new ticket
