### ISSUE TITLE
RTP reported as WhatsAppVoice when STUN packets present

### ISSUE THREAD

**Issue by lmangani** [ntop/nDPI#218]
The `WhatsAppVoice` detector seems to be extremely greedy and in all my tests wrongly overrides RTP flows when a STUN request/answer preceeds them from the same port. This is common behavior for many SIP User-Agents, including Linphone when configured to use STUN.

No special PCAP required, any SIP+STUN+RTP (in this sequence) call seems to present this issue

**Comment by kYroL01** [comment]
Thanks @lmangani . Do you have a pcap to share to evidence this bug ?

**Comment by lmangani** [comment]
@kYroL01 will share it privately if needed but ANY SIP/RTP call with STUN will trigger it

EDIT: traces sent with my comments

**Comment by Opendium** [comment]
This bug also misidentifies STUN traffic associated with Skype as WhatsAppVoice.  pcap attached.

[skype.zip](https://github.com/ntop/nDPI/files/456853/skype.zip)

**Comment by lucaderi** [comment]
I have fixed the issues identified. In case STUN is still not recognised properly, please open a new issue and attach a pcap file as evidence
