### ISSUE TITLE
Add fast CRC-16 implementation

### ISSUE THREAD

**Issue by 0xA50C1A1** [ntop/nDPI#2194]
**Is your feature request related to a problem? Please describe.**

Some protocols use the CRC16 for integrity control and store this checksum in the header or at the end of the packet payload (most commonly), so it can be used in dissectors to improve detection quality. Unfortunately, nDPI has no implementation of this algorithm, so when writing dissectors for such protocols [developers will have to look for workarounds](https://github.com/ntop/nDPI/pull/2193).

**Describe the solution you'd like**

I guess it is worth to add a  lookup table based fast implementation of the CRC-16 algorithm to nDPI to avoid code duplication and improve performance.

**Comment by IvanNardi** [comment]
Done in https://github.com/ntop/nDPI/commit/72601a69ffb97709136ad6b67ba720ca8109f898
