### ISSUE TITLE
RTP packets appear as unknown

### ISSUE THREAD

**Issue by Niko78** [ntop/nDPI#221]
I have all my RTP packets which appear as unknown in ntop
I adde pcap
[rtp.zip](https://github.com/ntop/nDPI/files/343423/rtp.zip)

ntop 2.5.160630
ndpi 1.8.0-dev-457-ff6b193

Nico

**Comment by lucaderi** [comment]
![screen shot 2016-07-01 at 22 26 24](https://cloud.githubusercontent.com/assets/4493366/16533692/ea771e82-3fda-11e6-85f7-c2fa326c3571.png)
Using the code in git it works

**Comment by Niko78** [comment]
well so on my side again a protocol which not appears ok in interface
<img width="922" alt="rtp" src="https://cloud.githubusercontent.com/assets/17108017/16539060/8dbee05a-4037-11e6-98e2-0e4264ca9648.PNG">

**Comment by lucaderi** [comment]
Shall you have a pcap able to reproduce the problem (ntopng -i <pcap>) we'll reopen this issue

**Comment by Niko78** [comment]
I tried to start ntop with -i and the pcap
this time I can see well the right informations
so something is wrong somewhere... but where and how can I help ?

nico
