### ISSUE TITLE
Add category support for user-defined protocols

### ISSUE THREAD

**Issue by 0xA50C1A1** [ntop/nDPI#2210]
**Is your feature request related to a problem? Please describe.**

Currently there's no way to set a category for custom protocols and by default it's set to `NDPI_PROTOCOL_CATEGORY_UNSPECIFIED`, so I think it would be worth it to add this feature. But I'm not sure how best to add a category to a rule, maybe something like this:

```ip:3.3.3.3:443@CustomProtocolA,100```

where 100 is the category ID.

**Comment by IvanNardi** [comment]
I am fine with that solution.
When testing, we need to pay attention to:
* iteration with custom category
* iteration with custom protocol id, i.e. `ip:3.3.3.3:443@CustomProtocolA=1024,100`
