### ISSUE TITLE
flow missing in ndpiReader csv 

### ISSUE THREAD

**Issue by dammeax** [ntop/nDPI#2219]
## Describe the bug
The ndpiReader -C in some specific cases doesn't output the detected flows.
While doing some bandwidth test with iperf tool (https://iperf.fr), I noticed that the ndpiReader -C doesn't write the flows identified to the output file.
I'm sure that ndpiReader is able to detect the flows because it reports them in the summary section:
...
        DPI Packets (TCP):     8             (8.00 pkts/flow)
        DPI Packets (UDP):     13            (13.00 pkts/flow)
        Confidence: Unknown    2             (flows)

but nothing is present in the csv

### Expected behavior
It is expected that 2 flows should be present in the ndpiReader -C output file
### Obtained behavior
Currently the ndpiReader -C outputfile has just the csv headers on the first line of the file, but no other lines are present in the file

## nDPI Environment (please complete the following information):
* OS name: Ubuntu
* OS version: 22.04.3 LTS
* Architecture: x86_64
* nDPI version or commit hash: 4.9.0-4419-59c8eabc
* nDPI compilation flags used: if you are building from source : None
* Attach the `config.log` file generated after `./configure` ran: [config.log](https://github.com/ntop/nDPI/files/13713652/config.log)

### Reproducible using ndpiReader?
- [x] The reported bug is reproducible using ndpiReader.
- [] The reported bug is not reproducible using ndpiReader.

### If applicable, the used ndpiReader options:

``` shell
ndpiReader -i test_mini_iperf.pcap -C test_mini_iperf.csv
```

### If your bug is reproducible using a pcap, please attach a pcap file (or a valid link to download it)

The pcapng file to reproduce: [test_mini_iperf.zip](https://github.com/ntop/nDPI/files/13713577/test_mini_iperf.zip)

### Steps to reproduce the behavior:
See ndpiReader section

## Additional context
Many thanks for your work

**Comment by IvanNardi** [comment]
Try adding "-v2"

**Comment by dammeax** [comment]
Thanks, indeed -v2 does the job !
