### ISSUE TITLE
Packet by packet detection

### ISSUE THREAD

**Issue by aidinfreedom** [ntop/nDPI#222]
I am not sure if this is the right place to ask question but I need a guidance to be able to modify the ndpiReader to be able to show each individual packet instead of flows and detected protocols. for example:
1. packet 1 : src_ip -> dst_ip  flow_id detected_protocol ...
thank you in advance

**Comment by kYroL01** [comment]
@aidinfreedom Your requests is not an issue, but a requests for a personalized work.
I suggest you to read this http://www.ntop.org/support/need-help-2/commercial-support/
