### ISSUE TITLE
Telemetry detection support

### ISSUE THREAD

**Issue by 0xA50C1A1** [ntop/nDPI#2225]
In today's world, all this spying bullshit (called telemetry) from Google, Microsoft and other corporations is a pretty sore subject. It's pretty strange that nDPI still doesn't have detection of this stuff and I'm planning to implement it myself, so I have a few questions about how best to do it:

- Should telemetry be assessed as a network risk or not?
- Should I add a separate category for telemetry or is it better to use some existing one?
- Is it worth to use IP address lists (which may change very frequently) or it's better to just use hostnames?

@utoni @IvanNardi what do you think about it?

**Comment by IvanNardi** [comment]
I think we can treat it in the same way we are handling gambling stuff:
* a new category; no risk, no protocol id
* some "well know" domains directly in `src/lib/ndpi_content_match.c.inc` (lets say "telemetry.dropbox.com", "watson.data.microsoft.com"...)
* if we have ip or domains lists (from where?) we can put them in `./lists`. It definitely works for domain lists; it should work for ip lists too. A mandatory point is to have a script to automatically generate and update them

Just my 2 cents

**Comment by 0xA50C1A1** [comment]
> I think we can treat it in the same way we are handling gambling stuff:

Well, how about handling it in the same way as adult content? I.e. add new protocol (`NDPI_PROTOCOL_TELEMETRY`) and category (`NDPI_PROTOCOL_CATEGORY_TELEMETRY`) IDs and aggregate all telemetry-related hostnames and IP address lists under it.

My original idea was to add separate protocol IDs for different telemetry services, but then I changed my mind - IDGAF (well, probably other people too) which big brother is watching, whether it's Google or Microsoft and Apple, I just want to stop it and DPI can be a good tool for that.

**Comment by utoni** [comment]
I am not sure if adding a new protocol category *and* a generic protocol id for those services is a good idea. AFAIR this was done for adult content, because there is (or was) an nDPI limitation e.g. a custom  application which is built on top of nDPI may not get the category information if the protocol id is set unknown. But I don't know if this is already fixed.

**Comment by 0xA50C1A1** [comment]
> I am not sure if adding a new protocol category _and_ a generic protocol id for those services is a good idea. AFAIR this was done for adult content, because there is (or was) an nDPI limitation e.g. a custom application which is built on top of nDPI may not get the category information if the protocol id is set unknown. But I don't know if this is already fixed.

Well, I dunno. I don't really like the idea of loading lists from a file, as that's not always possible. For example, it's not possible in the case of using nDPI as a [Linux kernel module (iptables match)](https://github.com/vel21ripn/nDPI).

A solution of the form ```protocol ID + category ID``` is suitable for all cases.
