### ISSUE TITLE
can nDPI use PF_RNG DNA or ZC mode to capture packet?

### ISSUE THREAD

**Issue by chinasun021** [ntop/nDPI#223]
Hi,
    nDPI can support analyze 10Gbit/s data？

```
I find example/ndpiReader.c use libpcap to capture packet,can we use pfring interface(such as  pfring_open instead of pcap_open_live) to capture packet to achieve 10Gbit/s speed.
```

**Comment by mmanoj** [comment]
Hi,

I'm also trying to use the same way, as per the following guide section 6.4 it's possible to recompile the pcaplibs and apps to use PF_RING. Need more clarifications to how to use advantage of PF_RING to nDPI reader.

https://github.com/ntop/PF_RING/blob/dev/doc/PF_RING-UsersGuide.pdf

Please advice.

**Comment by chinasun021** [comment]
thanks for your reply！
I want to know libpcap over PF_RING can support analyze 10Gbit/s data？

**Comment by mmanoj** [comment]
Hi,

I never try it yet. I'm also exploring the details.

**Comment by Skryabind** [comment]
I successfully use nDPI with PF_RING in ZC mode. My traffic is about 20Gbps.

**Comment by mmanoj** [comment]
Hi,

Can you share the steps, so I also can try and contribute. I'm using ndpi reader for test.

Thank you,

**Comment by mmanoj** [comment]
@Skryabind  

I compiled the PF_RING and libpcap as per the above mentioned PF_RING guide section 6.4, I need to know how to use it in nDPI and nDPI reader now. I dont have ZC yet. Please advice.

**Comment by Skryabind** [comment]
@mmanoj 
First, for high speed you can use threading, so look at example how to use zc cluster and balancer in  PF_RING/userland/examples_zc/zbalance.c
In this file find a line:
`if(pfring_zc_recv_pkt(outzq[id], &b, wait_for_packet) > 0) {`

b - is packet buffer, let's get a header and packet data:

```
u_char *packet = pfring_zc_pkt_buff_data(b, outzq[id]);

struct pfring_pkthdr header;
memset(&header, 0, sizeof(header));
header.len = b->len;
header.caplen = b->len;
memset((void*)&header.extended_hdr.parsed_pkt, 0, sizeof(struct pkt_parsing_info));
pfring_parse_pkt((u_char*)packet, (struct pfring_pkthdr*)header, 4, 1, 1);
```

Now you can use a code from pcap_packet_callback (in ndpiReader.c file) to get nDPI functionality. Just use a _packet_ and _header_ variables defined above.

**Comment by chinasun021** [comment]
thanks very much！ @Skryabind

**Comment by mmanoj** [comment]
@Skryabind 

Thanks for quick reply, I will try and update you.

**Comment by mmanoj** [comment]
@Skryabind 

can you also let us know how to test the processing throughput ?

**Comment by Skryabind** [comment]
@mmanoj, I haven't solution to test it. I work in ISP, so I test my applications in real traffic mirrored to dev infrastructure.

**Comment by mmanoj** [comment]
@Skryabind Ok, I will check with some traffic. Thanks.

**Comment by mmanoj** [comment]
@Skryabind Can you mention how to link libpcap (PF_RING) version with nDPI/nDPIReader.c

**Comment by Skryabind** [comment]
@mmanoj  You can install PF_RING kernel module, corresponding network driver, userland from PF_RING/userland/. I do it with this commands:

```
cd PF_RING/kernel
./configure
make && make install
cd /src/PF_RING/drivers/
make
cd intel/ixgbe/ixgbe-4.1.5-zc/src
make install
cd /src/PF_RING/userland
make
cd lib && make install
cd ../libpcap && make install
```

And then compile your app with -lpcap option.

P.S. This is my experience, probably @cardigliano or @lucaderi may correct me.

**Comment by mmanoj** [comment]
@Skryabind Thanks for quick support, I will try this and update you. Your support is highly appreciated.

**Comment by chinasun021** [comment]
I don't find libpcap.so in PF_RING/userland/libpcap,I just find libpcap.a,so you can complie nDPI/nDPIReader.c statically with libpcap.a

**Comment by Skryabind** [comment]
@chinasun021 after 'make' in PF_RING/userland/libpcap a file libpcap.so.1.7.4 is appears. And after 'make install' this library installs in system directories.

**Comment by chinasun021** [comment]
my version is 6.0.2,there is only libndpcap.so ,I don't know why.
I have download the newest version and it is ok

**Comment by lucaderi** [comment]
So far we do not build -dev packages, so for developing code you need to use the cod ewe put on github and not the binary packages. nDPI can handle 10G links, but it boils down to number of pps and low you have. If you start the nDPIreader you will see the performance you an achieve on your box. Note that ZC can accelerate the data path but if this is not your bottleneck, you need to spawn multiple threads and use RSS, where one thread handles a portion of the traffic.

**Comment by vel21ripn** [comment]
@chinasun021 You can try ndpi-netfilter (see https://github.com/vel21ripn/nDPI/tree/netfilter )

**Comment by mmanoj** [comment]
@lucaderi  Can you explain more about RSS and  spawn multiple threads to process traffic, as you said packet processing also need to support as incoming speed if I'm correctly understood. Other wise packet incoming rate higher then processing speed.

**Comment by mmanoj** [comment]
@vel21ripn can you explain the relationship of your NDPI link with PF_RING ?

**Comment by Skryabind** [comment]
@lucaderi Are there any benefits of using RSS as compared to zc balancer? I use zc balancer, it's more flexible, I think.

**Comment by cardigliano** [comment]
@mmanoj you can spawn multiple threads by specifying multiple interfaces (or queues in case of RSS) in ndpiReader using a comma-separated list in -i, and set the threads cpu affinity with -g (please read the help)

**Comment by cardigliano** [comment]
@Skryabind RSS is hw-based, thus in some cases it is faster than zbalance, zbalance is definitely more flexible as you can define custom distribution functions and also distribute the same traffic to multiple applications/instances.

**Comment by vel21ripn** [comment]
@mmanoj Traffic can be identified in the kernel using ndpi-netfilter. Any data processing in user space will be slower than in the kernel.

**Comment by mmanoj** [comment]
@cardigliano  Thanks for the advice, I will try the -g option as I have one network interface. I will use PF_RING with modified code as advice by @Skryabind with -g option. Later I will try same with ZC. Hope no more code modification required. Please confirm.

@vel21ripn Thanks for the clarification, in my scenario I will process packet in both places. In netfilter we cannot use PF_RING +ZC as it bypass the kernal if I'm correct.

**Comment by lucaderi** [comment]
@mmanoj You need to enable RSS, spawn a thread per queue for packet processing, each with an instance of nDPI so that you are fully reentrant

**Comment by mmanoj** [comment]
@lucaderi  sorry for late reply, can you give little example and reference doc/link for RSS technology, so I can read more about it.

**Comment by mmanoj** [comment]
@cardigliano  can you explain how threads cpu affinity improve ndpi reader performance for packet processing as it bind thread to cpu core. Also not clear how multiple threads will bind to given cpu core with -g option. Can you give some example scenario/syntax.

**Comment by cardigliano** [comment]
@mmanoj please read https://github.com/ntop/PF_RING/blob/dev/doc/README.RSS to learn more about RSS.
In order to bind multiple threads to multiple cpu cores, supposing you have 4 threads and want to bind them to cores 2,3,4,5, you can use -g 2:3:4:5

**Comment by mmanoj** [comment]
@cardigliano Thanks for the details. I'm start testing the ndpiReader with PF_RING and update you the status. Currently I'm going to use zbalance for initial test.

**Comment by mmanoj** [comment]
@lucaderi  I'm going to use as below with nDPIReader instance bind to zc balance for two nDPIReader instances for test. Is this correct approach ? nDPI reader compile with -lpcap

#zbalance_ipc -i zc:eth2 -c 99 -n 2 -m 0 -g 1

#ndpiReader -i zc:99@0
#ndpiReader -i zc:99@1

@Skryabind  are you modify zbalance or nDPI reader as per your above comment ?

**Comment by lucaderi** [comment]
You do not need the balancer: just enable RSS with 2 queues and attach nDPIreader to individual queues

**Comment by Skryabind** [comment]
@mmanoj In my comment above I wanted to show you how to connect nDPI and PF_RING in one application.  But if you just want to test the example, you shell use RSS without zbalance as said @lucaderi

**Comment by mmanoj** [comment]
@lucaderi  and @Skryabind  Thanks for quick comments. I will try as advice. As I saw example with zbalance for tcpdump that's why I try above methodology. What will happen if I use zbalance in same scenario.

**Comment by mmanoj** [comment]
@lucaderi  i'm getting following error while test, any idea

./ndpiReader -i zc:enp0s31f6@0 -v2

ERROR: could not open pcap file or playlist: zc:enp0s31f6@0: No such file or directory

Note: I tested queue from pfcount and it's fine. and ndpi reader compile with libpcap

**Comment by mmanoj** [comment]
@lucaderi  if I dont have the ZC driver , how can I use RSS or what is the alternative solution? pls advice.

**Comment by mmanoj** [comment]
I want to use PF_RING first with ndpiReader

**Comment by lucaderi** [comment]
@mmanoj ndpiReader -i enp0s31f6@0 will work
