### ISSUE TITLE
add canon bjnp protocol

### ISSUE THREAD

**Issue by Niko78** [ntop/nDPI#224]
on my network I have few packets generated by canon software (kind of scan)
it is named BJNP protocol

I added pcap
[bjnp.zip](https://github.com/ntop/nDPI/files/347812/bjnp.zip)

thanks

Nico

**Comment by alagoutte** [comment]
It is easy to write a heuristic ! each packet start with magic ID: BJNP

**Comment by mkfsn** [comment]
Hi, I make a solution for it, and here is my solution:

https://github.com/mkfsn/nDPI/commit/66e646bed58f5354c19727671e9194f4ceefc005

**Comment by alagoutte** [comment]
Look good, it is possible to make a PR ?

**Comment by mkfsn** [comment]
@alagoutte: I'm new to Github projects, should I make a new PR for this, or [attach a PR to this issue](https://www.topbug.net/blog/2012/03/25/attach-a-pull-request-to-an-existing-github-issue/) ?

Thank you.

**Comment by kYroL01** [comment]
@mkfsn Thanks for your work.
Just send a pull request normally, then I check it and merge into the main project.
If it's good I close this issue after merge.
Thanks

**Comment by kYroL01** [comment]
Implemented [here](https://github.com/ntop/nDPI/commit/0f94a46f868e6818790b0c278121c081a63c9eeb)
