### ISSUE TITLE
nDPI crashes when detecting GIT

### ISSUE THREAD

**Issue by simonemainardi** [ntop/nDPI#225]
![image](https://cloud.githubusercontent.com/assets/3397663/16586485/7938fa62-42c6-11e6-9ecd-56a9ea8aad2c.png)

@kYroL01 can you please check? It looks that it fails here: https://github.com/ntop/nDPI/blob/dev/src/lib/protocols/git.c#L75
also `git_len` is at `0`

**Comment by kYroL01** [comment]
@simonemainardi Sure I'll check asap ! Thanks

**Comment by lucaderi** [comment]
@kYroL01 This code was (at best) suboptimal. It was crashing, it contained a memory leak and it was doing un-necessary things. Please pay attention to what you are doing next time you commit code. Thank you.

**Comment by kYroL01** [comment]
Sorry, I'm apologize for it. My bad. I'll pay much more attention.
