### ISSUE TITLE
CI: documentation job is failing

### ISSUE THREAD

**Issue by IvanNardi** [ntop/nDPI#2267]
Lately, CI documentation job is failing

```
Sphinx version error:
The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.
make[1]: *** [Makefile:59: html] Error 2
```

Example: https://github.com/ntop/nDPI/actions/runs/7563438175/job/20595850606

**Comment by IvanNardi** [comment]
Not sure why, but this job has been fine in the last two days...

![Screenshot from 2024-01-23 09-26-56](https://github.com/ntop/nDPI/assets/12729895/8d2c57d1-c521-47b0-82b0-14924478bf9e)

**Comment by utoni** [comment]
Maybe that was an upstream issue. We're at least not trying to install `sphinxcontrib-applehelp` explicitly and it is/was AFAIK not needed to generate the documentation.
I am closing this. Let's reopen it if this pops up again.
