### ISSUE TITLE
ndpi_search_git causes ntopng to hang indefinitely

### ISSUE THREAD

**Issue by simonemainardi** [ntop/nDPI#227]
after running for a few minutes, ntopng hangs. The web server keeps serving but data is no longer updated. There is one cpu that is spinning at 100% and packet loss grows indefinitely. Memory consumption is not an issue.

I run ntopng within gdb and found that there is always one thread inside `ndpi_search_git`. The vast majority of the other threads are waiting on condition variables.

Here are the results of three different runs:

![screen shot 2016-07-12 at 1 00 12 pm](https://cloud.githubusercontent.com/assets/3397663/16765858/dd314536-4836-11e6-934e-46f50d0e14f2.png)
![screen shot 2016-07-12 at 1 08 02 pm](https://cloud.githubusercontent.com/assets/3397663/16765861/df300426-4836-11e6-8973-c77ec09435d0.png)
![screen shot 2016-07-12 at 1 08 24 pm](https://cloud.githubusercontent.com/assets/3397663/16765876/e9671cd6-4836-11e6-9459-2f8ee7b3ece9.png)

**Comment by kYroL01** [comment]
imho is because atoi is prone to multi-threading issues.
I think it must be changed to equivalent strtol function.

**Comment by simonemainardi** [comment]
if you look at the traces, `atoi` calls `strtol`

**Comment by simonemainardi** [comment]
I can confirm that `ndpi_search_git` is causing ntopng to hang indefinitely.

To make sure that was the cause, I started ntopng using a BPF filter to exclude git traffic based on the default git port:

`--packet-filter "not port 9418"`

ntopng has been running smoothly for a couple of hours whereas it hangs just after a few minutes without the BPF filter.

**Comment by lucaderi** [comment]
@simonemainardi I have made a fix. please try to crash it again

**Comment by simonemainardi** [comment]
It works @lucaderi . Now ntopng is stable and doesn't hang anymore. Thanks for the fix.
