### ISSUE TITLE
Hangout has been matched as WhatsappVoice

### ISSUE THREAD

**Issue by rafaelchieza** [ntop/nDPI#228]
Hi,

I am using ntopng  (2.5.160629 - Community Edition) with ndpi (1.8.0-dev-457-ff6b193) on centos (  7.2.1511) and I saw that hangout traffic is matched as whatsappVoice.

As you can see in the following screen
(https://cloud.githubusercontent.com/assets/20460535/16844169/716ea278-49ba-11e6-8e69-ee62b33fe33c.png)

dport is 19305 that is the  port that hangout use (https://support.google.com/a/answer/1279090?hl=en)

and    vj-in-f127.1e100.net  is a domain registered for google.

Thanks
Rafa

**Comment by alagoutte** [comment]
Can you attach a pcap ?

**Comment by rafaelchieza** [comment]
[whatsappvoice.pcap.zip](https://github.com/ntop/nDPI/files/364428/whatsappvoice.pcap.zip)

**Comment by kYroL01** [comment]
@rafaelchieza Yes, you're right.

**Comment by lucaderi** [comment]
This is what ndpiReader (1.8.0-dev-468-a93c83f) says
Detected protocols:
    STUN                 packets: 115           bytes: 17246         flows: 1  
    Google               packets: 31017         bytes: 16778972      flows: 1            

Protocol statistics:
    Acceptable                16796218 bytes

```
1   UDP 10.89.61.13:56406 <-> 74.125.134.127:19305 [proto: 78/STUN][115 pkts/17246 bytes]
2   UDP 10.89.61.13:48651 <-> 74.125.134.127:19305 [proto: 126/Google][31017 pkts/16778972 bytes]
```

Flow 1 is really STUN and is ok, the problem is that the second is note detected as hangout, so I coded the dissector

**Comment by kYroL01** [comment]
@lucaderi Do you think is more correct to detect **stun** packet as STUN than GoogleHangout even if the packets flow through hangout ports (Same thing for RTP, RTCP and SRTP) ?

**Comment by lucaderi** [comment]
I think hangout is better
