### ISSUE TITLE
http protocol src ip error

### ISSUE THREAD

**Issue by chinasun021** [ntop/nDPI#229]
I test the ndpiReader with option -v 1，and I find one flow info is error
![2](https://cloud.githubusercontent.com/assets/3906374/16864661/2a6da1e4-4a91-11e6-83b6-88e8cd6fc5db.jpg)
![1](https://cloud.githubusercontent.com/assets/3906374/16864670/392b837c-4a91-11e6-83c7-99678cabe74e.jpg)

it is http protocol with get option，how ever ndpiReader identify the flow as HTTPDownload，and in fact src ip is the dst ip.
I don't know why,please help

**Comment by lucaderi** [comment]
Please post the pcap

**Comment by chinasun021** [comment]
please download this file
https://github.com/chinasun021/chinasun021.github.io/raw/master/test.pcap

**Comment by chinasun021** [comment]
@lucaderi please help me，thanks！

**Comment by chinasun021** [comment]
I have find the reason...
in ndpi_util.c line 250 --256,the code is
` if(iph->saddr < iph->daddr) {
    lower_ip = iph->saddr;
    upper_ip = iph->daddr;
  } else {
    lower_ip = iph->daddr;
    upper_ip = iph->saddr;
  }`
I don't konw why to do this,I change the code to 
` lower_ip = iph->saddr;
    upper_ip = iph->daddr;`
the src ip and dst ip is right already.

**Comment by chinasun021** [comment]
maybe I have know the reason,the ndpiReader print info is simple,and it don't  distinguish src and dst.
I add src_to_dst_direction into struct ndpi_flow info,and 
 newflow->src_to_dst_direction=*src_to_dst_direction; in ndpi_util.c

**Comment by kYroL01** [comment]
@chinasun021 going to invesitgate the issue soon. thanks for reporting issue

**Comment by lucaderi** [comment]
@chinasun021 These are the two flows identified as download

> ./example/ndpiReader -i ~/Downloads/test.pcap -v 1|grep Dow
> Reading packets from pcap file /Users/deri/Downloads/test.pcap...
>     HTTPDownload         packets: 24            bytes: 3888          flows: 2  
>     23  TCP 113.108.225.18:80 <-> 192.168.188.212:7945 [proto: 7.60/HTTP.HTTPDownload][12 pkts/1944 bytes][Host: gztp.127.net]
>     156 TCP 192.168.188.212:7943 <-> 218.107.63.222:80 [proto: 7.60/HTTP.HTTPDownload][12 pkts/1944 bytes][Host: gzcp.127.net]

In both flows the response MIME type is
Content-Type: application/octet-stream
so the detection is correct IMHO

**Comment by chinasun021** [comment]
23 TCP 113.108.225.18:80 <-> 192.168.188.212:7945 [proto: 7.60/HTTP.HTTPDownload][12 pkts/1944 bytes][Host: gztp.127.net]
this flow src ip is192.168.188.212 in fact，how ever the output src ip is 113.108.225.18

**Comment by kYroL01** [comment]
@chinasun021 This is because when we print the results, we put on the left the `lower_ip` and on the right the `uppr_ip` that not always corresponds to the source and destinatiion ip.
See [here](https://github.com/ntop/nDPI/blob/dev/example/ndpi_util.h#L45)

During the detection (I [checked](https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_typedefs.h#L202)) the source ip and destination ip are correctly detected as in Wireshark.

**Comment by chinasun021** [comment]
okay,I have got it,thanks!
