### ISSUE TITLE
Add nDPI support for Popcorn Time application

### ISSUE THREAD

**Issue by Mile-Lile** [ntop/nDPI#23]
There is application called Popcorn Time. It is very popular in our county (Serbia) and I believe in others too. Because of the local laws you can watch movies online but it is prohibited to download them, it is against the law. This app do exactely that. Popcorn Time streams movies, popular series and TV shows from torrents. So, this application is widely used. It can be used on Windows, Andoids etc. Popcorn Time uses, among others protocol, Bittorrent client for temporary downloading content (other P2P users downloads from you at the same time). And that is a problem. nDPI recognizes Popcorn Time as Bittorrent so it can not be properly prioritized. Most users wants it with higher priority while downloading other (P2P) stuff in backgroung. Can you make filter (protocol) for Popcorn Time? Aplication can be downloaded here https://popcorntime.io/ It is only 40-50MB...
here is pcap file https://drive.google.com/file/d/0B0SCwy1irn3qOGY4WFdxalQyVFk/view?usp=sharing and here is fiew screenshots of it:
http://www.dodaj.rs/f/3Y/2d/3SYEjWhH/popcorntimescshot.png
http://www.dodaj.rs/f/S/Gj/2MNcZwaG/popcorntimemv.png

**Comment by lucaderi** [comment]
@Mile-Lile I have looked at the pcap you sent me and this is basically BitTorrent traffic. I don't see how to   bind this BitTorrent traffic to Popcorn Time rather than to BitTorrent. What do you think?

**Comment by Mile-Lile** [comment]
I just thought there is some workaround. I was thinking that they (Popcorn time app) have and use their own "swarm" so that connections can be traced somehow? But, on the second thought "mission is inpossible" :)... IP of peers, src and dst ports changes all the time, the only way is to bind traffic to protocol... Sorry for wasting your time, ticket can be closed as invalid. I just tried to block torrents with bittorrent filter and it blocks Popcorn Time too...:( Anyway I love nDPI, keep good work! Cheers!

**Comment by lucaderi** [comment]
@Mile-Lile Let's close it and leave this ticket in pending state until a better idea comes out.

**Comment by backer-and** [comment]
Popcorn Time has been dismissed according to: http://getpopcornti.me

**Comment by SrPatinhas** [comment]
@backer-and the original team yes, but this one https://popcorntime.io is continuing the project for over a year
