### ISSUE TITLE
How to setting server certificate for ndpi?

### ISSUE THREAD

**Issue by bmhoang** [ntop/nDPI#230]
please guide me how to add server key for ndpi?
Thanks,

**Comment by kYroL01** [comment]
Maybe @lucaderi could help you

**Comment by lucaderi** [comment]
@DiodeZ What do you mean exactly? I do not understand your question

**Comment by kYroL01** [comment]
@DiodeZ try to explain better the problem. If u need reopen the issue. 
Thanks
