### ISSUE TITLE
How to get http header information from ndpi_packet_struct

### ISSUE THREAD

**Issue by tgogos** [ntop/nDPI#231]
I cannot figure out how to use ptr and len inside ndpi_int_one_line_struct in order to get information about http headers (like: http_url_name for example).

**Comment by chinasun021** [comment]
you can use interface ndpi_get_http_url to get http url，ndpi_get_http_method to get http method and etc.

**Comment by kYroL01** [comment]
@tgogos the struct `ndpi_int_one_line_struct` is used to declare all the structs needed to get informations about (specially) http header.
If you see, the declaration is inside `ndpi_packet_struct` in `ndpi_typedef.h`, [here](https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_typedefs.h#L663)

To understand how **ptr** and **len** works, you have to see (maybe use _gdb_) how http dissector works on packets to extract related information from payload.
You can see that the workflow pass through this [function](https://github.com/ntop/nDPI/blob/dev/src/lib/ndpi_main.c#L3628) in `ndpi_main.c` to extract informations

**Comment by elrawy** [comment]
@kYroL01 is the payload encrypted or encoded ?? this is my output for payload


 " **%ÇÙdú\u0017t§*Éµ\u0013²\u0007V© lm¬±ólÈj \u001cª\u0005ñº«Ð8êÉëOù_°Òô\u0017KçgG\u001cãß\u001d¹¬\u0012Ç€g¡øû\u001eý.1-ÐŒÆ5vÔ·TÊËY¥;XÂ,\u001b2(_|\u0011f\u0014S\u0015³Ðx|J>L\u0012Í\tUÑU²o4\u0013n­À\u000fOL\/ÖÛ¥ïë'èÇZµöý\u001f\u0019mÍYîWr\r¥Oç\u0002Ôpo»ao8œ\u001d:WŸMtöå_œ·Å€¥©V·#Èk5ØÕ<¡RA±ÅŠŒ\u0010IT\u001eR¥¹(¡¢ñk\u001e®KóXn-Ønõ\u000fŽË\u001d'\\òÿ\u001d\u0016Ü¡|^ÕŒh3t:¹\u0003\u0006«f{bÎ$Kš©aµÁð\u0003ò«1JôùukûX0Ò\tA×** "


could you tell me what is this ?

**Comment by kYroL01** [comment]
@elrawy how do you print that ?

**Comment by elrawy** [comment]
@kYroL01 
by adding this two lines in ndpi_util.c **struct ndpi_flow_info *get_ndpi_flow_info**

flow.payload_edit = &l4[sizeof(struct ndpi_udphdr)];
workflow->stats.payload_edit = &l4[sizeof(struct ndpi_udphdr)];

then in ndpiReader.c i added those

cumulative_stats.payload_edit  = ndpi_thread_info[thread_id].workflow->stats.payload_edit;

and

json_object_object_add(jObj_trafficStats,"payload",json_object_new_string(cumulative_stats.payload_edit));

**Comment by kYroL01** [comment]
I think this is just a conversion problem when you print the output.
I think the problem is the conversion when you print after creation of json payload, isn't it ? You create a json object and then you print, right ?
No encryption or decoding is perfomed on a simple HTTP traffic.

**Comment by elrawy** [comment]
@kYroL01 yes i created a json object then print it, this the payload of a youtube page.
Is this a right way to extract payload ? and how can i convert it to a readable format ?

**Comment by kYroL01** [comment]
@elrawy 

> this the payload of a youtube page

This sentence has the answer inside. 
A Youtube page is **not** simple HTTP traffic, so you can't print as a normal and clear HTTP payload.
Maybe you're seeing TLS or QUIC traffic, that's encrypted.

**Comment by elrawy** [comment]
@kYroL01 when I opened speedtest.net it shows this \u0017\u0003\u0003 what is that ? Do you think what I am doing is a right way to extract payload ? sorry for asking too much

**Comment by kYroL01** [comment]
YouTube payload (as many others application) **DOES NOT HAVE CLEAR PAYLOAD, JUST ENCRYPTED.**
So, you correctly take the payload, BUT if you print as a normal text, you can't see readable things, just "mud".
