### ISSUE TITLE
The protocol of the connection, its port and IP version (if not IPv4). This is determined by analyzing the raw packets of the connection by using nDPI.
The SNI (server name information) or DNS query, if available. Otherwise, the remote IP address

### ISSUE THREAD

**Issue by Chrisisgoing** [ntop/nDPI#2316]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I always need to [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here.[]()

**Comment by IvanNardi** [comment]
Cut & paste from https://emanuele-f.github.io/PCAPdroid/quick_start.html...
If you have a really issue, please open a new ticket
