### ISSUE TITLE
ndpiReader statistics mismatch

### ISSUE THREAD

**Issue by rsweerarathna** [ntop/nDPI#236]
Hi,
I run ndpiReader with -v2 to get all traffic passing through the interface,  But there is a huge difference in summary statistics and the sum of total byte count in the detail log.  according to summary total size is 15MB but when i get the sum of byte counts in each line in the log, it's less than 1MB. why is that?

is summary not based on what you print in the console log?

pcap and log file attached.

https://www.mediafire.com/?49s29rmv97n5syl
[ndpi_reader_log.txt](https://github.com/ntop/nDPI/files/383482/ndpi_reader_log.txt)

**Comment by mmanoj** [comment]
@rsweerarathna  can you do only youtube capture and upload the pcap. as per the pcap it's having more protocols:

***_Detected protocols**_*:
    Unknown              packets: 5             bytes: 430           flows: 1  
    DNS                  packets: 64            bytes: 12349         flows: 32  
    HTTP                 packets: 183           bytes: 98435         flows: 21  
    HTTPDownload         packets: 5             bytes: 538           flows: 1  
    STUN                 packets: 20            bytes: 1720          flows: 1  
    ICMP                 packets: 2             bytes: 601           flows: 1  
    SSL                  packets: 9791          bytes: 7249844       flows: 60  
    SSH                  packets: 200           bytes: 76340         flows: 2  
    Facebook             packets: 1475          bytes: 1157369       flows: 40  
    GMail                packets: 10            bytes: 6265          flows: 1  
    YouTube              packets: 8994          bytes: 7577143       flows: 81  
    Skype                packets: 82            bytes: 13560         flows: 11  
    Google               packets: 1438          bytes: 518280        flows: 65  
    QUIC                 packets: 38            bytes: 9059          flows: 2  
    MS_OneDrive          packets: 1             bytes: 54            flows: 1

**Comment by mmanoj** [comment]
will focus on youtube packetss in summary and verbose output to narrow down the issue.

**Comment by rsweerarathna** [comment]
here it is, only browsing youtube.
pcap and log file.

http://www.mediafire.com/download/ixdiakt7u2byd9b/ndpiReader.pcap
[ndpiReader.txt](https://github.com/ntop/nDPI/files/387730/ndpiReader.txt)

**Comment by rsweerarathna** [comment]
Are you only focusing on detecting the protocol using first several flows and not then worry about the packet count and total statistics?

**Comment by kYroL01** [comment]
I understand your doubt.
If you see the log resume stats, yes, total **ethernet bytes** are **13372845**,
but if you see 3 lines above you can see **IP bytes** are **12996093** that exactly the sum of every lines you see under Detected protocols:
10998+10933+18398+1146+60054+36478+594+12391115+60737+404125+1515 = **12996093**
Remember that non-IP packets (and its bytes) are not counted.
