### ISSUE TITLE
Are there any manual about API of nDPI

### ISSUE THREAD

**Issue by tianzhishuizhu** [ntop/nDPI#238]
Are there any manual about API of nDPI? I have read code of ndpiReader.c. But it seems complicated. Thanks!

**Comment by kYroL01** [comment]
Actually there isn't a manual that explain all the API of nDPI, but It's a work must be done for future and soon.
For now you can see the API used reading [ndpi_api.h](https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_api.h) and [ndpi_main.h](https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_main.h).
Soon these two files must be merged into one.

**Comment by tianzhishuizhu** [comment]
Thanks! @kYroL01
