### ISSUE TITLE
Question about source of test files

### ISSUE THREAD

**Issue by gemartinezr** [ntop/nDPI#2380]
Hello, 

Just had a couple of questions regarding the tests... 

1. How were the PCAP files in [this directory](https://github.com/ntop/nDPI/tree/dev/tests/cfgs/default/pcap) generated? 

2. If I have a sample of a particular protocol or app, can I add it to the repo? 

Thanks in advance,

**Comment by IvanNardi** [comment]
>     1. How were the PCAP files in [this directory](https://github.com/ntop/nDPI/tree/dev/tests/cfgs/default/pcap) generated?
> 

Most of them  have been collected over public internet over the years or they have been locally generated simply running the "desired" application and capturing the traffic

>     2. If I have a sample of a particular protocol or app, can I add it to the repo?
> 

If the sample improves nDPI tests coverage, definitely yes [example: a protocol supported but without any example under `tests/pcap`]

**Comment by utoni** [comment]
@gemartinezr 
Please make sure that the pcap files do not contain any personal (e.g. authentication) data.
You may use tools like `editcap` or [pcap-editor](https://github.com/utoni/pcap-editor) to edit sensitive data and replace it with fake data.

**Comment by IvanNardi** [comment]
@gemartinezr, can we close this issue?

**Comment by gemartinezr** [comment]
Yes! thank you for the help.
