### ISSUE TITLE
Add nDPI support for TIM_WiFi application

### ISSUE THREAD

**Issue by tomerto** [ntop/nDPI#24]
Add nDPI support for TIM_WiFi application. Trace sent in a separate email.

**Comment by lucaderi** [comment]
@tomerto Implemented in https://github.com/ntop/nDPI/commit/ce94b7e545bca595a87c50379b37432423f395b6

As this traffic is TIM traffic that can be accessed on Wifi or plain ethernet, I marked it as TIM (no Wifi extension).
