### ISSUE TITLE
YouTube Traffic goes Undetected

### ISSUE THREAD

**Issue by u-Map** [ntop/nDPI#243]
Hi, 
I see majority of youtube traffic goes undetected (ssl.unknown) through my installation (ndpiReader - nDPI (1.8.0-dev-494-0e04068). I've attached a sample capture.

Detected protocols:

```
    DNS                  packets: 43            bytes: 7618          flows: 3            
    HTTP                 packets: 71            bytes: 57552         flows: 1            
    SSL                  packets: 3058          bytes: 2987135       flows: 3            
    Google               packets: 40            bytes: 10301         flows: 6 
```

Thanks.

[10.130.0.146_YT.pcap.gz](https://github.com/ntop/nDPI/files/412877/10.130.0.146_YT.pcap.gz)

**Comment by kYroL01** [comment]
Thanks for sharing pcap. Going to see asap

**Comment by kYroL01** [comment]
@u-Map The question is easy: nDPI does not have a specific dissector for YouTube.
I analyzed your pcap and we cannot do much more with these packets
The only way (for now) to detect YT traffic is by detecting it by dns query or ssl server name.
This is why YouTube is classified as a _service_ and not as a _protocol_
See https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_protocol_ids.h#L223
Unfortunately all is cripted and also is very hard to do a reverse engeneering for these kind of protocols.
If you have any ideas or suggestion to improve the detection, you're welcome.
