### ISSUE TITLE
Use efficient algorithms for string matching instead of memcmp

### ISSUE THREAD

**Issue by tianzhishuizhu** [ntop/nDPI#246]
I learn the source code in directory /nDPI/src/lib/protocols. I find `memcmp`is called for pattern searching, that is, for comparision. There are some algorithms for string matching, like **KMP, Boyer Moore Algorithm and AC algotithm**. Have you ever considered to use these efficient algorithms for string matching in nDPI, or they have been used in nDPI? Are they useful for nDPI?

`memcmp` is used when comparison of specific location is needed. For example, the first 5 bytes comparison. When a long string is given, KMP algorithm is used for searching pattern like "GET" in the long string. Are these algorithms needed in nDPI to improve performance?

**Comment by lucaderi** [comment]
yes we did. See for instance https://github.com/ntop/nDPI/blob/dev/src/lib/third_party/src/ahocorasick.c

if you want to extend it to other code dissectors, please do so, and send us a pull request. Thank you in advance

**Comment by tianzhishuizhu** [comment]
Thanks for your time. I see the source code and find AC algorithm are only declared in nDPI. But nDPI doesn't really use it, right? Are there any places for using pattern searching in nDPI? Because searching are always done in directory /protocols  for specific position in a packet load . So memcmp is used.

**Comment by lucaderi** [comment]
No you can use them from outside nDPI using the API.
Please provide a patch for inclusion

**Comment by tianzhishuizhu** [comment]
Is it right to say `memcmp` can nearly do all the work of searching in dissectors currently in nDPI ?

**Comment by kYroL01** [comment]
`memcmp` inside dissectors is used like

>   [...] memcmp(packet->payload, "GET ", 4) == 0 [...]
