### ISSUE TITLE
ndpi_serialize_uint32_float function is doubly declared since 4.6 in ndpi_api.h

### ISSUE THREAD

**Issue by anshulthakur** [ntop/nDPI#2478]
`ndpi_serialize_uint32_double` function is doubly declared since 4.6 in `ndpi_api.h` at lines 1341, and 1351 (4.8-stable branch). In an external application, this is causing the compiler to complain about multiple declarations.

--
*Update*

`ndpi_serialize_uint32_double`, not `ndpi_serialize_uint32_float`

**Comment by IvanNardi** [comment]
Good catch; same issue on master...
@anshulthakur, are you going to push a PR yourself to fix it?

**Comment by anshulthakur** [comment]
Right, will create a PR :)
