### ISSUE TITLE
can we use nDPI with Kernel ?

### ISSUE THREAD

**Issue by subritm** [ntop/nDPI#250]
In latest code 1.8 version I can see that the KERNEL macro check have been removed.
# ifndef **KERNEL**
# endif

So does it mean that, nDPI cannot be used in kernel ?
If it can be how ?
As these header files mentioned in ndpi_includes.h
# include <stdint.h>
# include <stdio.h>
# include <stdarg.h>
# include <string.h>
# include <ctype.h>
# include <time.h>
# include <limits.h>

are only for user space!

**Comment by vel21ripn** [comment]
Yes. And uses printf() for the debugging printing.
I tried to port ndpi-netfilter to version 1.8, but only to the level of assembly and short-term test, which showed a low level of traffic identification. Too many changes between versions 1.7 and 1.8

**Comment by kYroL01** [comment]
@subritm We prefer to avoid the use of nDPI in kernel space. We had made some changes but also in 1.7 the kernel mode was deleted. This does not mean that in future we don't think again to put again the kernel mode, but not in the old way.
@vel21ripn If you see the changes are to slim the code and we put few new APIs and to have a better organizzation of the code, excluding the daily fixing of the dissector.
