### ISSUE TITLE
New releases scheduling

### ISSUE THREAD

**Issue by IvanNardi** [ntop/nDPI#2520]
nDPI releases have always been cut approximately every 6-9 months.
As reported by @lucaderi (https://www.ntop.org/ndpi/released-ndpi-4-10-421-protocols-55-flow-risks-several-improvements-getting-ready-for-fpc/) there were some discussions recently to change that and provide a new release more frequently with some kind of hard scheduling (i.e. a new release every X months), similar to what other projects (linux kernel, ubuntu, DPDK, ...) are doing.

The idea is to make a new release every 4 months with a roadmap like: 01/12/2024, 01/04/2025,...

That is a tradeoff between providing frequent updates and the cost of cutting a release.

Any thoughts/suggestions?

**Comment by mmanoj** [comment]
@IvanNardi 

Thank for opening this discussion, lets focus to prepare some priority list/enhancements, based on that we can bucket them in to future releases.Hope this make sense.

**Comment by IvanNardi** [comment]
Pinging @utoni, @0xA50C1A1, @aouinizied, @vel21ripn, @dsokoloski, @koltiradw

**Comment by dsokoloski** [comment]
@IvanNardi 

My apologies for not seeing this sooner!

I love the idea of a more structured (eg: 4 month cycle), and rapid release schedule.  The project activity, number of commits, new features, bug fixes, dissectors, etc. is IMHO high enough to support a faster release schedule.

Thumbs up from Team Netify!

...and if we can collaborate in anyway, please let me know.

**Comment by mmanoj** [comment]
@IvanNardi and all Participants 

Can we create the agenda/wish list we can address with next roadmap.From my side I'm adding following.
1.VPN and  Anonymize/proxy detection in encrypted traffic with ML/DL,
2.Adding more popular services and protocols (we can create list later)
3.Adding more detection techniques / algorithms with AI/ML

**Comment by IvanNardi** [comment]
This discussion is more about the (new) scheduling of the new releases.
Anyway, I think having some kind of public non-binding roadmap/"wish-list" for each release is a very good idea! I'll open a dedicated issue for tracking that.

I renamed this issue to make it clearer

**Comment by mmanoj** [comment]
@IvanNardi 

Thanks for the advice, Will update the Roadmap discussion.

**Comment by utoni** [comment]
In general I would appreciate having more frequent nDPI releases. But from my perspective it would be great if that wishlist could be somehow integrated into GitHub for transparency. I think of having a project/milestone(s), so everyone knows what the next release release includes. That'll also help me upgrading nDPId.

**Comment by IvanNardi** [comment]
Closing. Let's continue on #2645
