### ISSUE TITLE
Hotmail IMAPS recognized as Skype

### ISSUE THREAD

**Issue by emanuele-f** [ntop/nDPI#254]
IP 157.56.195.250. The address range should be fixed.

![skype](https://cloud.githubusercontent.com/assets/5488003/18028639/a90022b0-6c84-11e6-965e-f8c0a55ac142.png)

**Comment by kYroL01** [comment]
I'm looking ar the right range

**Comment by kYroL01** [comment]
@emanuele-f https://github.com/ntop/nDPI/commit/58e37f813084e1d7c39a7c7014efbd66923e2409 test if this is ok

**Comment by emanuele-f** [comment]
Yes, thank you, My imaps client always connects to 157.56.195.250 so I cannot help much about other IPs

**Comment by kYroL01** [comment]
No problem for the other IPs, i did a check with my Skype and it seems ok.
