### ISSUE TITLE
More information about the potential risk in flow

### ISSUE THREAD

**Issue by ronygut** [ntop/nDPI#2555]
Hi

I'm using the ftflow_pcap sample code and I can see that there is a code  the generates JSON:
ndpi_flow2json(ndpi_struct, ndpi_flow,
                   k->ip_version, k->protocol, k->vlan_id,
                   ntohl(k->saddr.v4), ntohl(k->daddr.v4),
                   (struct ndpi_in6_addr*)&k->saddr.v6,
                   (struct ndpi_in6_addr*)&k->daddr.v6,
                   k->sport, k->dport,
                   ndpi_proto,
                   &serializer);

I can see for example that is generates the following JSON
Where can I see more information and documentation about what each field means?
Also how it is detected and how accurate is it?

{
  "src_ip": "10.164.130.230",
  "dest_ip": "10.164.255.255",
  "src_port": 35328,
  "dst_port": 35328,
  "ip": 4,
  "proto": "UDP",
  "ndpi": {
    "flow_risk": {
      "22": {
        "risk": "Unsafe Protocol",
        "severity": "Low",
        "risk_score": {
          "total": 450,
          "client": 345,
          "server": 105
        }
      }
    },
    "confidence": {
      "6": "DPI"
    },
    "proto": "NetBIOS.SMBv1",
    "proto_id": "10.16",
    "proto_by_ip": "Unknown",
    "proto_by_ip_id": 0,
    "encrypted": 0,
    "breed": "Dangerous",
    "category_id": 18,
    "category": "System",
    "hostname": "secrecy1"
  }
}

**Comment by IvanNardi** [comment]
For the flow risks, you can look at:
https://www.ntop.org/guides/nDPI/flow_risks.html
https://github.com/ntop/ntopng/blob/dev/doc/src/remediations/ndpi_flow_risks.rst

**Comment by ronygut** [comment]
@IvanNardi the links you sent are description of the risks.
I'm looking for explanation about each field in the JSON.
risk_score
confidence
proto_id
encrypted
breed
etc...
What are the possible values?
Is there a document that explains about those fields and what are the possible values?

**Comment by IvanNardi** [comment]
> Is there a document that explains about those fields and what are the possible values?

In general, no, AFAIK

Some information:
proto_id, breed, category and risk_score: take a look at the output of `ndpiReader -H`
confidence: https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_typedefs.h#L1005

**Comment by ronygut** [comment]
@IvanNardi 

 when using FT , if I have a connection on port 80, does the NDPI classifier will classify the connection as HTTP only if it see HTTP data or it can also classify it as HTTP protocol if no HTTP data found, but because the connection is on known HTTP port, in this case port 80?
What I mean is if I have connection on port 80 and there is no HTTP data, will the NDPI classifier classify this as HTTP because it is on know HTTP port 80 or as Unknown?

**Comment by IvanNardi** [comment]
> What I mean is if I have connection on port 80 and there is no HTTP data, will the NDPI classifier classify this as HTTP?

Yes, it does (with "by-port" as confidence value), @ronygut

**Comment by ronygut** [comment]
@IvanNardi 
is is something that can be changed in NDPI, or it is hardcoded in the code?
Meaning, can I ask NDPI to identify such cases as a Unknown protocol?

**Comment by IvanNardi** [comment]
yes, you can configure it, disabling guessing by port.
Take a look at `tests/cfgs/guessing_disable/config.txt` and `doc/configuration_parameters.md`

**Comment by ronygut** [comment]
@IvanNardi 
I'm using FT , how do I configure it from there?

**Comment by IvanNardi** [comment]
If with "FT" you mean PF_RING Flow Table, I think you should ask to @cardigliano, better on PF_RING repository, IMO

**Comment by cardigliano** [comment]
FT can return the nDPI handle with pfring_ft_get_ndpi_handle(table) on which you can call ndpi functions, however I guess ndpi_set_config(handle, NULL, "dpi.guess_on_giveup", "0") should be called before the ndpi handle is finalized. Is it correct @IvanNardi? This means we have to extend the FT API to allow that.

**Comment by IvanNardi** [comment]
@cardigliano , you are right. Function `ndpi_set_config()` must be called before `ndpi_finalize_initialization()`

**Comment by cardigliano** [comment]
@ronygut please open a feature request in the pf_ring repo under issues

**Comment by ronygut** [comment]
@cardigliano 
opened:
https://github.com/ntop/PF_RING/issues/965

Thanks,
Rony.

**Comment by IvanNardi** [comment]
Closing. If you have other questions, please open a new ticket
