### ISSUE TITLE
nDPI integrating with PF_RING

### ISSUE THREAD

**Issue by mmanoj** [ntop/nDPI#256]
with reference to previous thread
https://github.com/ntop/nDPI/issues/223
I'm working to integrate nDPI with PF_RING zbalance application. I follow the instructions however I'm not able to initialize ndpi_thread_info[thread_id].workflow with PF ring . Please advise how to proceed this step. Your advice is really appreciated. Also any other helpful advice welcome.

**Comment by lucaderi** [comment]
Duplicate of #223
