### ISSUE TITLE
How to add custom protocol at runtime?

### ISSUE THREAD

**Issue by vshuper1298** [ntop/nDPI#2567]
Hi,

I am using nDPI for my traffic analysis app and I want to allow a user to add custom protocol based on the domain.
From what I can see from the nDPI source code we can only extend the protocol list by adding custom protocols header and rebuilding the library.

Does anyone know if nDPI supports extending protocol list at runtime and could you suggest any API for that? 

Regards,
Vitalii

**Comment by IvanNardi** [comment]
@vshuper1298, AFAIK, you can't add new domain-> protocol mappings at runtime.
However, you don't need to rebuild the library to do that: you can use some custom rules. See `example/protos.txt`

**Comment by vshuper1298** [comment]
@IvanNardi so basically I can load new rules in such format at runtime: ip:mydomain.com@CustomProtocolName=800 right?

One more important question, how does it resolve DNS in this case? I mean does it cache IP when we add this rule or not.

The reason it is critical for me since I am using nDPI on my server inside the network located between the router and all the devices inside local network so it is forwarding all the traffic from/to the Internet. I am curious if that would affect the detection in case the devices under the LAN/NAT have cached DNS with a different server IP from that domain?

**Comment by IvanNardi** [comment]
@vshuper1298
* with `ip:mydomain.com@CustomProtocolName` you match flow *ip* (DNS resolver is triggered at startup, i.e. when the rule is loaded)
 * with `host:"api-global.netflix.com"@Netflix` you match hostnames/SNI (in DNS, HTTP, TLS, QUIC...) without any DNS involvements

I stress that out, because your initial message was about "add custom protocol based on the domain" which I think is the second case

In any cases, these rules are loaded always at startup (without changing the code / rebuild the library); you can't change/add/remove them later

**Comment by vshuper1298** [comment]
Yeah, sorry I misunderstood that, you actually meant that I can add proto without rebuilding but before the ndpi initialization and I can see that from reader example. But what if I would re-init ndpi struct every time I need to add the rule at runtime?

**Comment by IvanNardi** [comment]
Custom rules are loaded exactly during "ndpi struct" initialization! So if you free the old structure and create a new one, you can load another custom rules list.
Pseudocode
```
//Init
ndpi_str = ndpi_init_detection_module(NULL);
NDPI_BITMASK_SET_ALL(all);
 ndpi_set_protocol_detection_bitmask2(ndpi_str, &all);

ndpi_load_protocols_file(ndpi_str, _protoFilePath);  <-----

ndpi_finalize_initialization(ndpi_str);
// Init done
```

**Comment by vshuper1298** [comment]
Thanks a lot!

And the last question, I know it is kind of a separate topic but still related to adding custom protocol, I also use ndpi_netfilter to block traffic based on protocol using iptables.

Do you still support your custom netfilter module and is it possible to block the traffic by the same custom rules with ndpi_netfilter?
It would require adding a separate hook for that but since it run the same nNDPI I assume that might work.

**Comment by IvanNardi** [comment]
Netfilter stuff is not integrated in upstream nDPI... I think the best place to ask about that is https://github.com/vel21ripn/nDPI/issues

**Comment by vshuper1298** [comment]
I see. But looks like I have found exactly what I need using another ntop project: PF_RING FT seems to have all the features I need.
