### ISSUE TITLE
*** ndpi library version mismatch, expected API rev.11086 (4.10.0) found rev.9581 (4.10.0) ***

### ISSUE THREAD

**Issue by nhatlequang102** [ntop/nDPI#2574]
I have installed the following versions :
Latest nDPI from git 4.10.0-stable.
Latest PF_RING FT from git 8.8.0-stable.

It seems that these 2 versions of pf_ring ft and ndpi are not compatible with each other.
When I run the application in the /PF_RING/userland/examples_ft using the following command, the above error appeared :
sudo ./ftflow_dpdk -c 1 --vdev=net_pcap0,iface=ens33 -- -v -7

And here is the error message:
*** ndpi library version mismatch, expected API rev.11086 (4.10.0) found rev.9581 (4.10.0) ***
pfring_ft_create_table error
![image](https://github.com/user-attachments/assets/15d5e73c-ea2f-44df-b1c5-28683bbbf8ce)

**Comment by IvanNardi** [comment]
I think it is more likely that you get an answer from the same issue you opened on PF_RING repository

**Comment by nhatlequang102** [comment]
I have seen this in the issue section and tried reinstalling pfrinng and
ndpi older versions on another machine but the result is almost the same.
Do you have any version of pfring that works or any solution that can help
me?

Vào 21:16 Th 2, 30 thg 9, 2024 Ivan Nardi ***@***.***> đã
viết:

**Comment by cardigliano** [comment]
@nhatlequang102 I pushed an FT update to make sure it is compiled against latest nDPI 4.10.0 stable. Please update both nDPI (install the .so with make install) and FT. In case you still experience the same problem please open an issue in the PF_RING repo. Thank you.
