### ISSUE TITLE
How to detect TLDs ?

### ISSUE THREAD

**Issue by UnveilTech** [ntop/nDPI#2584]
Hello,

we would like to know how to detect some TLDs like *.top, *.xyz, etc...
we tried with the protos.txt but it seems not working:
host:"*.top"@SUSPICIOUS
host:"*.xyz"@SUSPICIOUS

any tips ?

thanks,
Bye Fred

**Comment by IvanNardi** [comment]
@UnveilTech , could you take a look at `-r ./example/risky_domains.txt" option?

**Comment by UnveilTech** [comment]
Hi Ivan,
I'll kave a look, thanks :o)

bye Fred

**Comment by UnveilTech** [comment]
Ivan,

we made some tests, it works fine, results:
- risk: "**Risky Domain Name**"
- we get severity and risk_score
- but the proto is DNS or HTTP, etc...

do you think it's possible to define the **risky_domains.txt** similar to the **protos.txt**, something like that:
.top@suspicious
.xyz@suspicious
.xxx@porn
etc...

the proto ("suspicious") could enrich the final proto info:
DNS.SUSPICIOUS
HTTP.SUSPICIOUS
etc...

thanks,
bye Fred

**Comment by UnveilTech** [comment]
hi,
any update ?

bye Fred

**Comment by IvanNardi** [comment]
AFAIK with TLD you can have only a flow risk, not a protocol.

**Comment by IvanNardi** [comment]
@UnveilTech, I doulbe checked and it should work with protos file using:
```
host:"top"@suspicious
```
Keep in mind that domain matching uses a longest-prefix matching like algorithm, so this rule works only if you don't have anything more precise

**Comment by UnveilTech** [comment]
Ivan,
are you sure it could work with that:
host:".top"@suspicious

**Comment by IvanNardi** [comment]
> Ivan, are you sure it could work with that: host:".top"@Suspicious

pay attention: not trailing dot in my example

**Comment by UnveilTech** [comment]
we got what you indicate, but it means it detects all ending by "top", right ?
sorry but that's not what we would like.

actualy, the best way would that the function "**ndpi_load_risky_domain(struct ndpi_detection_module_struct *ndpi_str, char* domain_name)**" could act the same like the function "**ndpi_handle_rule(struct ndpi_detection_module_struct *ndpi_str, char *rule)**" with at least taking into account the "@" for the proto.

I know we ask a lot here, defining a risky TLD only could not be enough, it should be better to define a proto too.

bye Fred

**Comment by IvanNardi** [comment]
> we got what you indicate, but it means it detects all ending by "top", right ?

No. It detects all domains with "top" as TLD. Give it a try....

**Comment by UnveilTech** [comment]
Ivan,
it looks good, thanks
keep you posted if we face any issues...

bye Fred
