### ISSUE TITLE
Questions on string based service classification (hostnames, IPs)

### ISSUE THREAD

**Issue by dgeorgakakis** [ntop/nDPI#262]
```
We are using nDPI in our customer's field extended by few custom rules containing both IPs and hostnames. Regarding these rules, here are some questions:
```

1) If there are more than one ovelapping hostnames for the same service ID, does nDPI stop on the first match? E.g. if we have 
           a) www.google.games.*  and  
           b) www.google.games.europe.*

will the matching algorithm stop on a?

2) Similarly, is it possible to classify ranges of IPs before applying any rules related to the host name? 
E.g. 172.15.xx.xx – 172.32.xx.xx classified as private with no further lookups.

3) Does the same behavior apply for both the native nDPI and custom classification rules?

**Comment by kYroL01** [comment]
Hello!

Question 1) Yes, it stops on a as you can see [here](https://github.com/ntop/nDPI/blob/dev/src/lib/ndpi_content_match.c.inc#L7291) 
when a string is found it will check if there is a match with one of these entries.

Question 2) nDPI cannot classify a range of IP as private. This feature is not yet present (maybe we have to introduce it).
If you need to classify an IPs range as private I think you can try to workaround, but I have to try before tell you something.
For now on nDPI you can do this for port-based protocol detection using a standard format (read the doc for this if u need).

Question 3) If you you refer to point 1, yes.

**Comment by dgeorgakakis** [comment]
Hi again,

  Thanks a lot for your answers! Some follow-up:

4) Answer 2 above is understood. In general, is it possible to configure IP ranges for matching, such as 172.15.15/24?
5) Is it possible to have multiple keywords in a wildcard pattern, eg. “KPN*LOTTE””that would match “KPN-A-LOTTE”? Or combinations, like "poke && NOT poker"?
6) Are the patterns case sensitive?
7) Can they use regular expressions?

Thanks in advance

**Comment by lucaderi** [comment]
We currently use substring matching (no patterns). Yes you can configure range match (See https://github.com/ntop/nDPI/blob/dev/example/protos.txt)
