### ISSUE TITLE
nDPI-Wireshark real-time

### ISSUE THREAD

**Issue by mlmartinez87** [ntop/nDPI#2624]
Hello,
I am trying to make ndpiReader display the traffic and protocols it is analyzing in real-time, similar to how tcpdump works. I have tried integrating ndpiReader with Wireshark and using tshark, but when I run the command, it shows the following:

tshark -i ndpi
Capturing on 'nDPI interface: ndpi'
tshark: There is no device named "/tmp/wireshark_extcap_ndpi_C4A1W2/fifo".
(No such device exists)
0 packets captured.

Do you know how I can solve this issue or if there is any way to display packets in real-time?

Thank you

**Comment by IvanNardi** [comment]
If you set up ndpiReader as an extcap for wireshark, it works out of the box:
```
0 packets captured
ivan@ivan-Precision-3591:~/svnrepos/nDPI(rtp-payload-type)$ sudo ~/svnrepos/wireshark/wireshark-master/run/tshark -i ndpi -o extcap.ndpi.i:enx109819c03690 -Y "ndpi.protocol.name contains DNS"
[sudo] password for ivan: 
Running as user "root" and group "root". This could be dangerous.
Capturing on 'nDPI interface: ndpi'
  286   3.349293 192.168.1.125 → 192.168.1.253 DNS.Dropbox 447 Standard query 0x500f A d.dropbox.com OPT
  287   3.349402 192.168.1.125 → 192.168.1.253 DNS.Dropbox 447 Standard query 0x46f3 AAAA d.dropbox.com OPT
  288   3.383151 192.168.1.253 → 192.168.1.125 DNS.Dropbox 574 Standard query response 0x500f A d.dropbox.com CNAME d.v.dropbox.com CNAME d-edge.v.dropbox.com A 162.125.8.20 OPT
  289   3.395317 192.168.1.253 → 192.168.1.125 DNS.Dropbox 635 Standard query response 0x46f3 AAAA d.dropbox.com CNAME d.v.dropbox.com CNAME d-edge.v.dropbox.com SOA ns-773.awsdns-32.net OPT
  290   3.395790 192.168.1.125 → 192.168.1.253 DNS.Dropbox 454 Standard query 0x680d AAAA d-edge.v.dropbox.com OPT
  291   3.396406 192.168.1.253 → 192.168.1.125 DNS.Dropbox 551 Standard query response 0x680d AAAA d-edge.v.dropbox.com SOA ns-773.awsdns-32.net OPT
```

**Comment by mlmartinez87** [comment]
Thank you for your response. 
I have tried running the suggested commands, but I encountered the following issue: 

sudo /usr/bin/tshark -i ndpi -o extcap.ndpi.i:enx109819c03690 -Y "ndpi.protocol.name contains DNS"
Running as user "root" and group "root". This could be dangerous.
tshark: "ndpi.protocol.name" is not a valid protocol or protocol field.
    ndpi.protocol.name contains DNS

even if I remove the -Y option, I still get the same error indicating that no interface is found because the FIFO queue is not created:
sudo /usr/bin/tshark -i ndpi -o extcap.ndpi.i:enx109819c03690
Running as user "root" and group "root". This could be dangerous.
Capturing on 'nDPI interface: ndpi'
tshark: There is no device named "/tmp/wireshark_extcap_ndpi_TTJLX2/fifo".
(No such device exists)
0 packets captured

**Comment by IvanNardi** [comment]
`enx109819c03690` is the name of MY interface I was capturing traffic from; you need to use the name of your interface or, if you are reading from a file, the file name itself (something like `-o extcap.ndpi.i:/home/ivan/svnrepos/nDPI/tests/pcap/anydesk.pcapng`)
Please, double check that you set up the extcap and the lua plugin correctly (see `wireshark/README.md`)

**Comment by mlmartinez87** [comment]
It still doesn't work for me. I have uninstalled and reinstalled Wireshark, but without success. I have also followed the guidelines in wireshark/README.md with the following:
cp ~/nDPI/example/ndpiReader ~/.local/lib/wireshark/extcap/
cp ~/nDPI/wireshark/ndpi.lua ~/.local/lib/wireshark/plugins/

as it's shown in wireshark menu: 

![Captura de pantalla de 2024-11-19 16-25-06](https://github.com/user-attachments/assets/de14ec5f-4a82-4b29-8110-b9d6ffa5122e)

As you can see on the wiresharks home screen, the interface ndpi appears but no data can be captured on it:

![Captura de pantalla de 2024-11-19 16-24-41](https://github.com/user-attachments/assets/2e78a95f-8a14-47d2-ad03-fb7bb712af6c)

Versions that I am using are 4.4.0 for wireshark and the last one for nDPI.

Could there be any incompatibility?

**Comment by IvanNardi** [comment]
Are you able, from Wireshark, to use nDPI interface to open a file (i.e. not an interface)?

**Comment by mlmartinez87** [comment]
Yes, I opened a pcap file using ndpi interface:
![Captura de pantalla de 2024-11-19 18-56-57](https://github.com/user-attachments/assets/0f92c06c-0944-418d-b4d4-0e6e8e691d52)

**Comment by IvanNardi** [comment]
@mlmartinez87,
* what about opening a real interface from the nDPI interface? (using wireshark)
* which OS are you using?

**Comment by mlmartinez87** [comment]
Opening a real interface from the nDPI interface, using wireshark:
![Captura de pantalla de 2024-11-19 19-51-15](https://github.com/user-attachments/assets/b32491ed-dbdc-4695-ade2-97a282a80c0c)
It seems that it is not recognizing nDPI (QUIC IETF)

I am using Ubuntu 20.04.6 LTS

**Comment by IvanNardi** [comment]
Let's try:
* could you report the complete output of `sudo tshark -i ndpi -o extcap.ndpi.i:wlp2s0` (if I am not wrong, that should be your interface)
* are you able to open a pcap file using tshark (via ndpi interface)?
* which exact version of nDPI are you using? You said ` the last one for nDPI`.. do you mean 4.10 or latest dev? If you are using 4.10, could you try with current dev from github, please?

**Comment by mlmartinez87** [comment]
- I attach the output of sudo tshark -i ndpi -o extcap.ndpi.i:wlp2s0
[pruebandpi.txt](https://github.com/user-attachments/files/17820388/pruebandpi.txt)

- I can open a pcap file using thsark via ndpi interface but it seems that doesn't recognize the protocols:

tshark -i ndpi -r intagram.pcap 

 3688   7.815913 157.240.5.174 → 192.168.1.39 QUIC 90 Protected Payload (KP0), DCID=851f11
 3689   8.638295 192.168.1.39 → 157.240.5.174 QUIC 1294 Protected Payload (KP0), DCID=b02d0172121e43b9
 3690   8.638345 192.168.1.39 → 157.240.5.174 QUIC 615 Protected Payload (KP0), DCID=b02d0172121e43b9
 3691   8.652313 157.240.5.174 → 192.168.1.39 QUIC 90 Protected Payload (KP0), DCID=851f11
 3692   8.652492 192.168.1.39 → 157.240.5.174 QUIC 77 Protected Payload (KP0), DCID=b02d0172121e43b9
 3693   8.666626 157.240.5.174 → 192.168.1.39 QUIC 90 Protected Payload (KP0), DCID=851f11
 3694   8.744302 157.240.5.174 → 192.168.1.39 QUIC 794 Protected Payload (KP0), DCID=851f11
 3695   8.744869 192.168.1.39 → 157.240.5.174 QUIC 82 Protected Payload (KP0), DCID=b02d0172121e43b9
 3696   8.780114 157.240.5.174 → 192.168.1.39 QUIC 90 Protected Payload (KP0), DCID=851f11

I am using nDPI 4.11.0: AC_INIT([libndpi],[4.11.0])

**Comment by IvanNardi** [comment]
Let's take a step back, because I am a little confused right now...
1) You are now able to use tshark + ndpi interface + real interface. Is that correct? I am asking because in your initial message there was an error and now I see the packets...
2) If yes, the problem is now that you can't see a proper "DPI classification". Correct?
3) If yes, keep in mind that nDPI need the first packets of each flow. The easiest way to test it is to launch first tshark + ndpi and only at that point, open the broswer and surfing on some sites

**Comment by mlmartinez87** [comment]
Yes I can execute sudo tshark -i ndpi -o extcap.ndpi.i:wlp2s0
 Using sudo. I was trying without it before, sorry.
The problem is that I cannot see a proper DPI classification. I tried starting the capture at first, and after that open a browser but the result is the pcap that I attached in my previous message

**Comment by IvanNardi** [comment]
Try capturing the traffic with tcpdump, save the pcap, and process it
offline with ndpiReader. Does that work?

**Comment by mlmartinez87** [comment]
Yes it works fine:

sudo tcpdump -i wlp2s0 -w packet_capture.pcap

./ndpiReader -i packet_capture.pcap 

-----------------------------------------------------------
* NOTE: This is demo app to show *some* nDPI features.
* In this demo we have implemented only some basic features
* just to show you what you can do with the library. Feel 
* free to extend it and send us the patches for inclusion
------------------------------------------------------------

Using nDPI (4.11.0-4976-59ee1fe) [1 thread(s)]
Using libgcrypt version 1.8.6internal
Reading packets from pcap file packet_capture.pcap...
Running thread 0...

nDPI Memory statistics:
	nDPI Memory (once):      38.29 KB     
	Flow Memory (per flow):  1.16 KB      
	Actual Memory:           14.26 MB     
	Peak Memory:             14.26 MB     
	Setup Time:              24 msec
	Packet Processing Time:  36 msec

Traffic statistics:
	Ethernet bytes:        4380141       (includes ethernet CRC/IFC/trailer)
	Discarded bytes:       0            
	IP packets:            4499          of 4797 packets total
	IP bytes:              4272165       (avg pkt size 890 bytes)
	Unique flows:          266          
	TCP Packets:           1386         
	UDP Packets:           3110         
	VLAN Packets:          0            
	MPLS Packets:          0            
	PPPoE Packets:         0            
	Fragmented Packets:    0            
	Max Packet size:       60232        
	Packet Len < 64:       1542         
	Packet Len 64-128:     339          
	Packet Len 128-256:    255          
	Packet Len 256-1024:   406          
	Packet Len 1024-1500:  1778         
	Packet Len > 1500:     179          
	nDPI throughput:       124.47 K pps / 924.55 Mb/sec
	Analysis begin:        19/Nov/2024 22:32:41
	Analysis end:          19/Nov/2024 22:33:12
	Traffic throughput:    148.14 pps / 1.10 Mb/sec
	Traffic duration:      30.369 sec
	DPI Packets (TCP):     253           (7.44 pkts/flow)
	DPI Packets (UDP):     422           (1.83 pkts/flow)
	DPI Packets (other):   2             (1.00 pkts/flow)
	Confidence: DPI        266           (flows)


Detected protocols:
	DNS                  packets: 182           bytes: 24801         flows: 90           
	OCSP                 packets: 125           bytes: 37519         flows: 5            
	IGMP                 packets: 3             bytes: 162           flows: 2            
	TLS                  packets: 127           bytes: 46849         flows: 5            
	Facebook             packets: 19            bytes: 8159          flows: 4            
	YouTube              packets: 1388          bytes: 2167620       flows: 37           
	Google               packets: 2099          bytes: 1612665       flows: 87           
	UbuntuONE            packets: 26            bytes: 7838          flows: 4            
	Amazon               packets: 6             bytes: 1078          flows: 3            
	QUIC                 packets: 24            bytes: 12140         flows: 1            
	Github               packets: 2             bytes: 273           flows: 1            
	Instagram            packets: 265           bytes: 210526        flows: 6            
	GoogleServices       packets: 217           bytes: 140029        flows: 13           
	AmazonAWS            packets: 16            bytes: 2506          flows: 8            


Protocol statistics:
	Safe                 packets: 252           bytes: 84368         flows: 10           
	Acceptable           packets: 2575          bytes: 1801492       flows: 209          
	Fun                  packets: 1672          bytes: 2386305       flows: 47    


Thank you very much for your help :)
If you reply, I will see your message tomorrow.

**Comment by IvanNardi** [comment]
> * I attach the output of sudo tshark -i ndpi -o extcap.ndpi.i:wlp2s0
>       [pruebandpi.txt](https://github.com/user-attachments/files/17820388/pruebandpi.txt)
> 
In this file there is TCP traffic but no SYN packets -> you didn't capture the beginning of the flows
Could you try again:
* close your broswer
*  start tshark + nDPI
*  open the broswer
*  go to youtube.com and instagram.com
*  you should find packets classified as QUIC|TLS/Youtube or  QUIC|TLS/Instagram

**Comment by mlmartinez87** [comment]
I captured again from the beginning:
[pruebandpi.txt](https://github.com/user-attachments/files/17834735/pruebandpi.txt)

**Comment by IvanNardi** [comment]
ok, something doesn't work as expected...
Which version of Wireshark are you using? Any chance that you can use something like >=4.4.0? [ on ubuntu 20.04 you might have 3.6...]

**Comment by mlmartinez87** [comment]
I am using wireshark 4.4.0 and ubuntu 20.04.
I have also installed another host to test in Ubuntu 24.04, using wireshark 4.2.2 at first and wireshark 4.4.0 after that, and there is the same error.
Is there any other configuration that can be done and that I might have missed, apart from copying ndpiReader and ndpi.lua to Wireshark's paths?

**Comment by IvanNardi** [comment]
@mlmartinez87, I think I figured out the issue!
Copy `ndpiReader` and `ndpi.lua` on Wireshark **GLOBAL** folders (and not in the personal ones) and try again... let me know, please!

**Comment by mlmartinez87** [comment]
Now its working!
thank you very much for your kind support @IvanNardi !!
