### ISSUE TITLE
Unable to detect the protocols

### ISSUE THREAD

**Issue by shailendra-patil** [ntop/nDPI#2632]
Below is the code i am using to detect the protocols, but even 1 is not getting detected. I tried TLS, DNS, QUIC..but nothing worked:

#include <iostream>
#include <unordered_map>
#include <pcap.h>
#include <ndpi/ndpi_api.h>
#include <cstring>
#include <arpa/inet.h> // For ntohs()
#include <netinet/ip.h> // For IP header
#include <netinet/tcp.h> // For TCP header
#include <netinet/udp.h> // For UDP header

extern "C" {
    #include <ndpi/ndpi_api.h>
}
int pkt = 0;
#define NDPI_FLOW_STRUCT_SIZE sizeof(struct ndpi_flow_struct)

// Function to print IP address
void print_ip(uint32_t ip) {
    std::cout << ((ip >> 24) & 0xFF) << "."
              << ((ip >> 16) & 0xFF) << "."
              << ((ip >> 8) & 0xFF) << "."
              << (ip & 0xFF);
}

// Structure to hold flow information
struct Flow {
    struct ndpi_flow_struct *ndpi_flow;
    uint32_t src_ip;
    uint32_t dst_ip;
    uint16_t src_port;
    uint16_t dst_port;
};

// Hash function for flow keys
struct FlowKeyHash {
    std::size_t operator()(const std::tuple<uint32_t, uint32_t, uint16_t, uint16_t>& key) const {
        return std::get<0>(key) ^ std::get<1>(key) ^ std::get<2>(key) ^ std::get<3>(key);
    }
};

// Function to process packets
void process_packet(struct ndpi_detection_module_struct *ndpi, std::unordered_map<std::tuple<uint32_t, uint32_t, uint16_t, uint16_t>, Flow, FlowKeyHash>& flows, const uint8_t *packet_data, uint16_t packet_len, uint64_t timestamp) {
    // Extract IP header
    const struct ip *ip_header = (struct ip *)(packet_data + 14); // Assuming Ethernet header is 14 bytes
    uint32_t src_ip = ntohl(ip_header->ip_src.s_addr);
    uint32_t dst_ip = ntohl(ip_header->ip_dst.s_addr);

    // Extract transport layer header
    uint16_t src_port, dst_port;
    if (ip_header->ip_p == IPPROTO_UDP) {
        const struct udphdr *udp_header = (struct udphdr *)(packet_data + 14 + (ip_header->ip_hl * 4));
        src_port = ntohs(udp_header->source);
        dst_port = ntohs(udp_header->dest);
    } else if (ip_header->ip_p == IPPROTO_TCP) {
        const struct tcphdr *tcp_header = (struct tcphdr *)(packet_data + 14 + (ip_header->ip_hl * 4));
        src_port = ntohs(tcp_header->source);
        dst_port = ntohs(tcp_header->dest);
    } else {
        std::cout << "Non-TCP/UDP packet" << std::endl;
        return; // Not a TCP/UDP packet
    }

    // Create flow key
    auto flow_key = std::make_tuple(src_ip, dst_ip, src_port, dst_port);

    // Find or create flow
    Flow& flow = flows[flow_key];
    if (!flow.ndpi_flow) {
        flow.ndpi_flow = (struct ndpi_flow_struct *)ndpi_flow_malloc(NDPI_FLOW_STRUCT_SIZE);
        memset(flow.ndpi_flow, 0, NDPI_FLOW_STRUCT_SIZE);
        /*flow.src_ip = src_ip;
        flow.dst_ip = dst_ip;
        flow.src_port = src_port;
        flow.dst_port = dst_port;*/
    }

// Process packet
    std::cout << "Packet No: " << ++pkt << std::endl;
ndpi_protocol proto = ndpi_detection_process_packet(ndpi, flow.ndpi_flow, (packet_data + 14), packet_len - 14, timestamp, NULL);

    // Check if QUIC protocol is detected
    if(proto.proto.master_protocol == NDPI_PROTOCOL_DNS) 
    {
        std::cout << "Detected DNS protocol" << std::endl;
        std::cout << "Source IP: ";
        print_ip(src_ip);
        std::cout << "\nDestination IP: ";
        print_ip(dst_ip);
        std::cout << "\nSource Port: " << src_port << "\nDestination Port: " << dst_port << std::endl;

        // Extract and print SNI
        if(flow.ndpi_flow->host_server_name != NULL) 
        {
            std::cout << "SNI: " << flow.ndpi_flow->host_server_name << std::endl;
        } 
    }
}

int main(int argc, char *argv[]) {
    if (argc != 2) {
        std::cerr << "Usage: " << argv[0] << " <pcap file>" << std::endl;
        return 1;
    }

    // Open pcap file
    char errbuf[PCAP_ERRBUF_SIZE];
    pcap_t *handle = pcap_open_offline(argv[1], errbuf);
    if (!handle) {
        std::cerr << "Error opening pcap file: " << errbuf << std::endl;
        return 1;
    }

    // Initialize nDPI
    //struct ndpi_global_context *ndpi_global = ndpi_init_detection_module();
    struct ndpi_detection_module_struct *ndpi = ndpi_init_detection_module(nullptr);
    NDPI_PROTOCOL_BITMASK protocols;
    //NDPI_BITMASK_RESET(protocols);

    // Enable QUIC detection
    //NDPI_BITMASK_ADD(protocols, NDPI_PROTOCOL_DNS);
    NDPI_BITMASK_SET_ALL(protocols);
    ndpi_set_protocol_detection_bitmask2(ndpi, &protocols);
    ndpi_finalize_initialization(ndpi);
    // Flow map
    std::unordered_map<std::tuple<uint32_t, uint32_t, uint16_t, uint16_t>, Flow, FlowKeyHash> flows;

    // Process packets
    // Process packets
    struct pcap_pkthdr *header;
    const uint8_t *packet_data;
    while (pcap_next_ex(handle, &header, &packet_data) >= 0) {
        process_packet(ndpi, flows, packet_data, header->caplen, header->ts.tv_sec * 1000 + header->ts.tv_usec / 1000);
    }

    // Cleanup
    for (auto& entry : flows) {
        ndpi_flow_free(entry.second.ndpi_flow);
    }
    ndpi_exit_detection_module(ndpi);
    pcap_close(handle);

    return 0;
}

Please someone guide me, what wrong am i doing here, I have also attached the pcap files.
![image](https://github.com/user-attachments/assets/929975ac-c012-4191-af73-24967ceb7f9a)
![image](https://github.com/user-attachments/assets/9586ac3c-06a2-4335-a0df-9b6fd6955665)
![image](https://github.com/user-attachments/assets/5b4966ff-553a-459f-9825-8a9581e60269)

**Comment by IvanNardi** [comment]
Could you:
* properly format your code
* attach the real pcap

please?

**Comment by shailendra-patil** [comment]
@IvanNardi , I have the .pdf containing code in structured form
[code.pdf](https://github.com/user-attachments/files/17942003/code.pdf)

[dns.zip](https://github.com/user-attachments/files/17942015/dns.zip)

This zip contains the pcaps for DNS, QUIC and TLS.

Please help.

**Comment by IvanNardi** [comment]
I compiled your code as-is, run with dns.pcap and I got exactly what I was expecting
```
ivan@ivan-Precision-3591:~/svnrepos/nDPI(dev)$ ./a ~/Downloads/dns/dns.pcap 
Packet No: 1
Detected DNS protocol
Source IP: 192.168.137.253
Destination IP: 192.168.137.1
Source Port: 63153
Destination Port: 53
SNI: edge-stun.facebook.com
Packet No: 2
Detected DNS protocol
Source IP: 192.168.137.253
Destination IP: 192.168.137.1
Source Port: 64456
Destination Port: 53
SNI: graph.facebook.com
Packet No: 3
Detected DNS protocol
Source IP: 192.168.137.1
Destination IP: 192.168.137.253
Source Port: 53
Destination Port: 63153
SNI: edge-stun.facebook.com
Packet No: 4
Detected DNS protocol
Source IP: 192.168.137.1
Destination IP: 192.168.137.253
Source Port: 53
Destination Port: 64456
SNI: graph.facebook.com
Packet No: 5
Detected DNS protocol
Source IP: 192.168.137.253
Destination IP: 192.168.137.1
Source Port: 56832
Destination Port: 53
SNI: b-graph.facebook.com
Packet No: 6
Detected DNS protocol
Source IP: 192.168.137.1
Destination IP: 192.168.137.253
Source Port: 53
Destination Port: 56832
SNI: b-graph.facebook.com
Packet No: 7
Detected DNS protocol
Source IP: 192.168.137.253
Destination IP: 192.168.137.1
Source Port: 64405
Destination Port: 53
SNI: edge-mqtt.facebook.com
Packet No: 8
Detected DNS protocol
Source IP: 192.168.137.1
Destination IP: 192.168.137.253
Source Port: 53
Destination Port: 64405
SNI: edge-mqtt.facebook.com
Packet No: 9
Detected DNS protocol
Source IP: 192.168.137.253
Destination IP: 192.168.137.1
Source Port: 56782
Destination Port: 53
SNI: pubsub.googleapis.com
Packet No: 10
Detected DNS protocol
Source IP: 192.168.137.1
Destination IP: 192.168.137.253
Source Port: 53
Destination Port: 56782
SNI: pubsub.googleapis.com
Packet No: 11
Detected DNS protocol
Source IP: 192.168.137.253
Destination IP: 192.168.137.1
Source Port: 17496
Destination Port: 53
SNI: edge-mqtt.facebook.com
Packet No: 12
Detected DNS protocol
Source IP: 192.168.137.253
Destination IP: 192.168.137.1
Source Port: 1838
Destination Port: 53
SNI: graph.facebook.com
Packet No: 13
Detected DNS protocol
Source IP: 192.168.137.1
Destination IP: 192.168.137.253
Source Port: 53
Destination Port: 17496
SNI: edge-mqtt.facebook.com
Packet No: 14
Detected DNS protocol
Source IP: 192.168.137.1
Destination IP: 192.168.137.253
Source Port: 53
Destination Port: 1838
SNI: graph.facebook.com
```

**Comment by shailendra-patil** [comment]
Ya, @IvanNardi I also realized it afterwards....Thanks for your support....
