### ISSUE TITLE
Error may exist

### ISSUE THREAD

**Issue by tianzhishuizhu** [ntop/nDPI#264]
Error may exist in the code below

**Question1:**
(file in nDPI/src/lib/protocols/**mssql.c line 43~49**), but I don't know how to modify it. Firstly, it checks the beginning **four bytes**, == 0x1201. But then, it checks the third and forth bytes to be payload_packet_len. I think that may be an error.

```
if (packet->payload_packet_len > 51 && ntohs(get_u_int32_t(packet->payload, 0)) == 0x1201
      && ntohs(get_u_int16_t(packet->payload, 2)) == packet->payload_packet_len
      && ntohl(get_u_int32_t(packet->payload, 4)) == 0x00000100 && memcmp(&packet->payload[41], "sqlexpress", 10) == 0) {
    NDPI_LOG(NDPI_PROTOCOL_MSSQL, ndpi_struct, NDPI_LOG_DEBUG, "found mssql.\n");
    ndpi_int_mssql_add_connection(ndpi_struct, flow);
    return;
  }
```

**Question2:**
(file in nDPI/src/lib/protocols/**rsync.c line 40~47**)
Comment shows it should match "@RSYN NCD: 28", but the code matchs "@RSYNCD:"

```
    /*
     * Should match: memcmp(packet->payload, "@RSYN NCD: 28", 14) == 0)
     */
    if (packet->payload_packet_len == 12 && packet->payload[0] == 0x40 &&
    packet->payload[1] == 0x52 && packet->payload[2] == 0x53 &&
    packet->payload[3] == 0x59 && packet->payload[4] == 0x4e &&
    packet->payload[5] == 0x43 && packet->payload[6] == 0x44 &&
    packet->payload[7] == 0x3a ) {
```

**Comment by kYroL01** [comment]
Question 1: https://github.com/ntop/nDPI/commit/dbb3d8280ea2a5a5697ad8133973838451ef1d6d

Question 2: The comment is wrong, the dissector match correctly as u can see [here](https://www.wireshark.org/docs/dfref/r/rsync.html)
