### ISSUE TITLE
Priorities among Hostname rules

### ISSUE THREAD

**Issue by dgeorgakakis** [ntop/nDPI#268]
1) Let's assume one nDPI user adds a new sub-protocol with the rule:
      host:"nfl"@NFL

This rule seems to overlap to the nDPI rules for netflix:

_{ "nflxext.com",           "NetFlix",      NDPI_SERVICE_NETFLIX, NDPI_PROTOCOL_FUN },
{ "nflximg.com",            "NetFlix",      NDPI_SERVICE_NETFLIX, NDPI_PROTOCOL_FUN },_

The question is, a packet with hostname "nflxext.com" will match to NetFlix or to the custom protocol NFL.?In  other words, do custom rules take priority over the native nDPI rules, or?

2) Similarly, let's assume we have 2 conflicting rules for 2 different sub-protocols in a configuration file:

 host:"mobile"@MobileApp
 host:"bank"@Banking

In this case,  a packet with hostname "mobile.bank" will match to MobileApp OR to Banking?
Does the order in the configuration file matter?

Thanks,
D.

**Comment by kYroL01** [comment]
@dgeorgakakis 

Yes, for **point 1)** this overlap the nDPI rules (in this case for Netflix) and shows NFL. This is because if you specify a personal file, it takes priority over native nDPI rules.

For **point 2)** it will match with **MobileApp** in case of the string is _mobile.bank_. Instead with **Banking** if the string found is _bank.mobile_

What do you think about all ? Do you think is necessary modify something ?
Maybe point 1) could be re-think better...

**Comment by dgeorgakakis** [comment]
Hi,

  for **point 1)** We think you have implemented it correctly because one nDPI user who adds a personal file should add more specialized rules which override the more general native nDPI rules.

  for **point 2)** would it be possible to allow defining priority of custom rules (i.e. according to the order inside the personal file)? Would this affect performance and if yes, could this priority be enabled on demand (via configuration switch)?

**Comment by kYroL01** [comment]
for **point 2)** I don't think this affect on the performance, but I have to think a good way to implement it.
I think a nice idea could be definining priorities (maybe by default _no priorities_ but a user could specified it).
i.e. :
host:"mobile"@**MobileApp** [1]
host:"bank"@**Banking** [2]

So name with 1 has more priority than 2. Are u saying similar thing ?

**Comment by am107** [comment]
Hello,
I think that is a good idea. Allowing the user to set priorities would introduce more granularity in defining sub-protocol rules. I will try to see if I can introduce priorities.

**Comment by kYroL01** [comment]
Duplicate issue of https://github.com/ntop/nDPI/issues/146
