### ISSUE TITLE
MS_OneDrive Traffic Detected as SSL

### ISSUE THREAD

**Issue by smomojo** [ntop/nDPI#269]
Version 1.8.0

The rule for MS_OneDrive is:

Microsoft Corporation (MS One Drive)
204.79.195.0/24
204.79.196.0/23
134.170.0.0/16
131.253.12.0/22
131.253.16.0/23
131.253.18.0/24
65.54.191.0/24 

I can see that my connection to MS servers is using the IP address: 204.79.197.213. It should match the second subnet in this rule definition.

However, nDPI classifies the connection as SSL rather than MS_OneDrive.

**Comment by kYroL01** [comment]
Can you pass me the pcap with MS connection ? It seems that there a wrong match with ip address.
Thanks

**Comment by smomojo** [comment]
Here you go. Thanks for your help.

[onedrive.zip](https://github.com/ntop/nDPI/files/478565/onedrive.zip)

**Comment by kYroL01** [comment]
@smomojo Sorry for answer in late.
I try your pcap and I correctly detect it as MS OneDrive.

Are u sure you're using the latest version of nDPI ?

![drive](https://cloud.githubusercontent.com/assets/7222956/18616602/229045ec-7dbf-11e6-8656-0101388501b4.png)

**Comment by smomojo** [comment]
@kYroL01 thank you. I successfully reproduced your result with ndpiReader version 1.8 (I hadn't used ndpiReader before - it is great for this!) I have my own app that uses the API, and I confirmed that the app loads version 1.8 of the shared library. I guess I must be using the API incorrectly in some way. I'll investigate that by comparing with how ndpiReader works.

**Comment by kYroL01** [comment]
Ok. I close this issue as it's not a nDPI issue.
