### ISSUE TITLE
Add nDPI support for windowsupdate

### ISSUE THREAD

**Issue by Mile-Lile** [ntop/nDPI#27]
I remember there was windows update protocol in the old days. What happened to it? Lots of people will migrate from windows 7, 8, 8.1 to windows 10... it will be 3GB update that will run in background. It will be handy to have WSUS filter to put it to low priority...

**Comment by Mile-Lile** [comment]
http://www.computerworld.com/article/2929024/microsoft-windows/microsoft-triggers-windows-10-nag-campaign-on-windows-7-8-1-devices.html

**Comment by lucaderi** [comment]
@Mile-Lile Please provide a pcap file.

**Comment by Mile-Lile** [comment]
I can't do it right now 'cause I'm in process of migration to windows 10. My PC machines don't do update anymore (manually)... They do it "silently" (when they are in "idle") in the background and I don't know when to capture pcap... So, please don't close ticket for now, lets wait for july 29th and then I provide pcap for WSUS... Thx

**Comment by Mile-Lile** [comment]
here is file https://drive.google.com/file/d/0B0SCwy1irn3qZlhPTW1RdVlFdEU/view?usp=sharing
let me know if it is valid for WSUS detection or I will provide soon another one... Thx for your work.

**Comment by Mile-Lile** [comment]
and this one https://drive.google.com/file/d/0B0SCwy1irn3qNVZDb0xxekR6MGs/view?usp=sharing

**Comment by lucaderi** [comment]
Fixed in https://github.com/ntop/nDPI/commit/0b7af2dbbc5b6ee6480ab3022a1e1e4695a916bd
