### ISSUE TITLE
Does every protocol file need to be executed to detect any protocol

### ISSUE THREAD

**Issue by tianzhishuizhu** [ntop/nDPI#270]
I've read protocol files in nDPI/src/lib/protocols. Because there are more than 100 files, for detecting a protocol , does it need to compare all the 100 files every time, or history detection is uesd for detection? If so, the process would be very slow, I think. Thanks.

**Comment by kYroL01** [comment]
No. nDPI return the first protocol matched with the file.
First of all it search for hostname or ip address protocol matching [(1)](https://github.com/ntop/nDPI/blob/dev/src/lib/ndpi_content_match.c.inc), then every data is passed to the dissectors and the first who matched is the result.
Unfortunately this could cause false positive, so if you are thinking something new for contribution, ideas are well accepted.

**Comment by tianzhishuizhu** [comment]
I don't know whether my understanding is right after your explanation:  

There are more than 100 dissectiors, from dissector 1, dissector 2,dissector 3...
For every protocol and application detection, the process is :
1. Step1: match hostname or ip address.  and this step would filter only a few dissectors for example dissector 1 and dissector 2 from those dissectors.
2. Step2: and then data would only be only passed to dissector 1 and dissector 2 for detection, not all the dissectors.

Am I right? I will learn the source code more deeply. Thanks.
