### ISSUE TITLE
Feature Request: Expanding ndpiReader

### ISSUE THREAD

**Issue by DigiAngel** [ntop/nDPI#271]
So ok....I suspect this will get shot down, but I'm going to try any way :)  I LOVE ndpi's protocol detection.  LOVE IT.  Combining ntop/ndpi/ElasticSearch has been amazing.  What I'm trying to do now, is to remove the ntop layer.  I would love to see ndpiReader have a feature which would be able to listen to an interface and dump the flow/protocol information to ElasticSearch..just like the below:

```
{
  "_index": "ntopng-2016.09.21",
  "_type": "ntopng",
  "_id": "AVdOVxHbkT04DqG1f-ro",
  "_score": null,
  "_source": {
    "@timestamp": "2016-09-21T20:01:49.0Z",
    "type": "ntopng",
    "IN_SRC_MAC": "00:90:4C:C5:12:38",
    "OUT_DST_MAC": "00:22:41:33:12:B2",
    "IPV4_SRC_ADDR": "192.168.1.101",
    "IPV4_DST_ADDR": "208.67.222.222",
    "L4_SRC_PORT": 13170,
    "L4_DST_PORT": 53,
    "PROTOCOL": 17,
    "L7_PROTO": 126,
    "L7_PROTO_NAME": "DNS.Google",
    "IN_PKTS": 1,
    "IN_BYTES": 84,
    "OUT_PKTS": 1,
    "OUT_BYTES": 100,
    "FIRST_SWITCHED": 1474488109,
    "LAST_SWITCHED": 1474488109,
    "DST_IP_COUNTRY": "US",
    "DST_IP_LOCATION": [
      -122.393303,
      37.769699
    ],
    "NTOPNG_INSTANCE_NAME": "tester",
    "INTERFACE": "eth0",
    "DNS_QUERY": "ssl.google-analytics.com",
    "PASS_VERDICT": true
  },
  "fields": {
    "@timestamp": [
      1474488109000
    ]
  },
  "sort": [
    1474488109000
  ]
}
```

I realize that yes....ntop does this command line, but I'm hoping for something that's leaner than ntop, and my hope is that ndpiReader can be expanded to to just that.  I'm not a programmer...I script a little bit, but that's about it...I've looked at the ndpiReader source code and it's daunting to me.  Thank you.

**Comment by kYroL01** [comment]
Hi @DigiAngel I think this is a feature that need time and we first have a discussion if it's usefull to expand ndpiReader in this way.
We'll let you know but thanks for asking and proposing it.

**Comment by DigiAngel** [comment]
I appreciate it!

**Comment by leveryd** [comment]
it will be nice feature.

**Comment by sologub** [comment]
Taking into consideration that ndpiReader is an example app with the main purpose of showing how to use the nDPI lib to new developers, I'd like to suggest to not implement this feature nor any other integrations with 3rd party tools.
In my opinion complicating ndpiReader will make it harder for new devs to understand nDPI in the first place, and will only harm the adoption of nDPI project as a whole and hence less new contributors will come.

This, of course, doesn't prevent anyone to create a new separate repository for a more advanced reader with specialized integrations.

**Comment by kYroL01** [comment]
Sorry for late answer, but I'm agree with @sologub . 
ndpiReader is a demo to show how to use nDPI and what nDPI does, concerning the most important feature of the whole things: detectiong protocols.
After internal discussion, we need to keep the demo easy.
If you need to create your application with other features, don't have fear to do it, also because it could be usefull for us to understand if some basic parts are correctly implemented.
