### ISSUE TITLE
comments spelling mistake on dev master

### ISSUE THREAD

**Issue by JeanKerr** [ntop/nDPI#273]
ndpi_main.c, line:2198, /\* Stracraft _/
should be /_ Starcraft */

**Comment by kYroL01** [comment]
Are u sure ? What do you mean about "_master_" ? We have **dev** or one of the officials (**1.6** - **1.7** - **1.8**)

dev: https://github.com/ntop/nDPI/blob/dev/src/lib/ndpi_main.c#L2198

**Comment by JeanKerr** [comment]
I mean dev branch:
dev: https://github.com/ntop/nDPI/blob/dev/src/lib/ndpi_main.c#L2193
`/\* Stracraft /

**Comment by kYroL01** [comment]
https://github.com/ntop/nDPI/commit/bf778d6df11231df78e2015aac87b47c2f04756e
