### ISSUE TITLE
SSL Session re-use identified as ssl_no_cert

### ISSUE THREAD

**Issue by DigiAngel** [ntop/nDPI#274]
So I guess technically on the wire indeed there was no cert during the session, however after capturing these are actually ssl session reuse:
![2016-09-30 14_27_33-ssl-session-reuse pcapng wireshark 2 2 0 v2 2 0-0-g5368c50 from master-2 2](https://cloud.githubusercontent.com/assets/947191/19005862/0ecc5910-871a-11e6-8ad1-b543ae8cbc68.jpg)

wondering if this should be re-labeled?  Thank you.

**Comment by kYroL01** [comment]
@DigiAngel Can u send me the pcap for this behaviour ?
Thanks

**Comment by kYroL01** [comment]
@DigiAngel Closed for inactivity. Re-open if u need.
Thanks

**Comment by DigiAngel** [comment]
Ah poop...sorry..I don't think I got the notification for this :(  Anyway thank you.

**Comment by kYroL01** [comment]
No problem. Re-open if u need with the proper pcap. Thanks
