### ISSUE TITLE
realvnc decoded as skype

### ISSUE THREAD

**Issue by fabix71** [ntop/nDPI#275]
[realvnc_ex.zip](https://github.com/ntop/nDPI/files/519790/realvnc_ex.zip)

**Comment by kYroL01** [comment]
Thanks for reporting. I'll check asap

Il 10/ott/2016 17:30, "fabix71" notifications@github.com ha scritto:

**Comment by kYroL01** [comment]
fixed by https://github.com/ntop/nDPI/commit/3b95cd9a1133071ebf475c58aa830f83965bb889
