### ISSUE TITLE
Debugging flags

### ISSUE THREAD

**Issue by spellgen** [ntop/nDPI#277]
I'm looking to get a little more insight into where the go-wrapper I'm working on is failing. 

I can get some debugging with `./configure "-D DEBUG"` but I wanted to define the symbol `NDPI_ENABLE_DEBUG_MESSAGES` as well. 

This seems to be broken. It breaks in the code below. `ndpi_str` is missing. Could be it was intended to be a global, or more likely, would need to have a detection struct passed in.

```
void set_ndpi_malloc(void* (*__ndpi_malloc)(size_t size)) { _ndpi_malloc = __ndpi_malloc; }

void set_ndpi_free(void  (*__ndpi_free)(void *ptr))       { _ndpi_free = __ndpi_free; }

void set_ndpi_debug_function(ndpi_debug_function_ptr ndpi_debug_printf) {
#ifdef NDPI_ENABLE_DEBUG_MESSAGES
  ndpi_str->ndpi_debug_printf = ndpi_debug_printf;
#endif
```

**Comment by kYroL01** [comment]
Maybe this https://github.com/ntop/nDPI/commit/df6b71c5ea03485949f896036881fdbf6ae9f6b7 fix the problem. 
Re-open in case this does not solve all. Thanks
