### ISSUE TITLE
Number of packets needed for classification

### ISSUE THREAD

**Issue by stathisgotsis** [ntop/nDPI#283]
What would you expect as a reasonable number of packets needed for the classification of a flow ? I am referring to "typical" internet traffic. 

I have seen around 70pkts which seems too much to me.

**Comment by Skryabind** [comment]
As of my experience it's 20-30 packets enough to classify a flow. I tested it in version 1.7.0.

**Comment by kYroL01** [comment]
@stathisgotsis actually it depends on the application or protocol that u need to classify.
70 pkts is too much for sure and nDPI spend much less. For many application the avg is ~10 and it depends also if application is UDP or TCP.
