### ISSUE TITLE
How to extract hostname for HTTP/HTTPS

### ISSUE THREAD

**Issue by stathisgotsis** [ntop/nDPI#284]
What is the proper way to extract the hostname for HTTP/HTTPS?

I see that it is sometimes filled in ndpi_flow_struct.host_server_name or ndpi_flow_struct.protos.ssl.client_certificate[0] after calling ndpi_detection_process_packet(). But what would be the proper way to extract it when available? Does ndpi_detection_process_packet() always force such extraction?

**Comment by kYroL01** [comment]
The extraction is made by inside the http dissector (for http) and ssl dissector (for https).
1. https://github.com/ntop/nDPI/blob/dev/src/lib/protocols/http.c#L314
2. https://github.com/ntop/nDPI/blob/dev/src/lib/protocols/ssl.c#L313

Then the extracted information are saved in the main flow data structure to properly detect the subprotocol (i.e. if an HTTP packet has hostname for google, it's detected as HTTP.Google)
