### ISSUE TITLE
testing pcap range extension

### ISSUE THREAD

**Issue by waqas-latif** [ntop/nDPI#287]
Hi,

This is an awesome DPI project and servers the purpose with quite an accuracy. I would love to see the updated test pcap file with which we can trigger/detect all supported protocols.

Thanks

**Comment by kYroL01** [comment]
If you want to see the test pcaps look [here](https://github.com/ntop/nDPI/tree/dev/tests).
[Here](https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_protocol_ids.h) you can see all the protocols and services detected.
