### ISSUE TITLE
Strange call of printf

### ISSUE THREAD

**Issue by mkfsn** [ntop/nDPI#291]
I found a strange call of `printf` in `src/lib/ndpi_main.c:1750`:

```c
#ifdef NDPI_ENABLE_DEBUG_MESSAGES
  printf(0, NULL, NDPI_LOG_DEBUG, "ndpi_init_detection_module initial malloc failed\n");
#endif
```

I'm wondering if it should be changed to `NDPI_LOG` ?

**Comment by kYroL01** [comment]
You're right.
Fixed by https://github.com/ntop/nDPI/commit/61c8dca469b7129731d91da842e9ae4ad6dcd782
