### ISSUE TITLE
How does array ndpi_ndpi_mask fds_bits works in nDPI

### ISSUE THREAD

**Issue by tianzhishuizhu** [ntop/nDPI#293]
I have read deeply about ndpiReader.c. But I still can't understand how `ndpi_ndpi_mask fds_bits[NDPI_NUM_FDS_BITS]`  works. Are there any images to illustrate how the specific bitmask is set or clear in the detection for a specific protocol? Thanks for the whole project and I hope I could do something for this project one day.

**Comment by kYroL01** [comment]
If you see [here](https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_define.h#L224) you can see theat _fds_bits_ is an array of `u_int32_t ndpi_ndpi_mask` of size `NDPI_NUM_FDS_BITS` defined in the structure to managed the [protocol bitmask](https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_typedefs.h#L61).

So, it is kinda a mask of bits to remember the protocols. For example if you see [this](https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_define.h#L218) all of these macros use the _fds_bits_ array to do its work.
You have to imagine an array of n elements and every elements represent a protocol.

You understand better if you see the struct container of _fds_bits_ `ndpi_protocol_bitmask_struct_t`.
This struct is used to define the important macro [NDPI_PROTOCOL_BITMASK](NDPI_PROTOCOL_BITMASK) used in every **protocol init dissector** to mark a protocol detected
See the signature of init functions for all the dissectors: https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_protocols.h#L53
