### ISSUE TITLE
nDPI code has changed but nDPI_quickstart guide has description according to previous API.

### ISSUE THREAD

**Issue by p2yogi** [ntop/nDPI#297]
Hi,

I am working on a solution where I need to use nDPI library to get application ID of an incoming packet.
So my query is how to start  nDPI engine and what is needed for the API to give the application ID.

As in quickstart guide API has been changed.
For eg. in quick start guide:

NDPI_PROTOCOL_BITMASK all;
ndpi_struct = ndpi_init_detection_module(
detection_ticks_resolution,
malloc_wrapper,
free_wrapper,
debug_printf);

whereas in example with the source code:

struct ndpi_detection_module_struct * module = ndpi_init_detection_module();

That is in new code no arguments are passed with it, for initialization. 
So how to initialise the engine and use it to get application ID.

Gratitude for your help.

**Comment by kYroL01** [comment]
@p2yogi You are right. nDPI documentation about API must be rewrite properly to help anyone who wanna use the API.

For the example you mentioned, the signature is changed as you correctly say, so to create a new module for the detection, you just call that function without any params. See [here](https://github.com/ntop/nDPI/blob/e9f00a4e8a6995ffb79e7efbe1f183cb7a833632/src/include/ndpi_api.h#L125)

See also the implementation of that function in [ndpi_main.c](https://github.com/ntop/nDPI/blob/1e19b689c4b50c69239bb207951a42b8a2ae8d45/src/lib/ndpi_main.c#L1750)

So, you're right: API documentation must be upgrade.
Thanks

**Comment by clauderobi** [comment]
Any progress on updating the documentation? 

Beside de API, a description of the life cycle of the a detection instance, a flow and other objects would be really useful. A definition of odd terms, such as subscriber would be welcomed.

Finally, the example code variable and function names should be changed to better reflect what comes the library and what is internal code to the example. Starting everything with ndpi_ is confusing.

**Comment by kYroL01** [comment]
@clauderobi Please be patient till the next week. I'm start working on it in the next week for sure.
Thanks

**Comment by clauderobi** [comment]
If you need early feedback let me know.

**Comment by kYroL01** [comment]
@clauderobi Yes sure, thanks

**Comment by subritm** [comment]
any update on this ?
I am also implementing similar stuff, where I use ndpi to detect the application and just print the application name. 
I went through the example ndpiReader.c to get the info related to the changes in the init.
Also I added a function to pass on the skb to a function which will call ndpi_detection_process_packet function to find the protocol.
with this, I cannot detect any customized application,. But sure of getting it added properly with ndpi_handle_rule().

**Comment by kYroL01** [comment]
@subritm I don't know how you implement properly your code, but the detection is done by dissectors, not by a single function

**Comment by elrawy** [comment]
@kYroL01 I want to ask something, when i change in the ndpiReader.c for example to just print something extra only, then recompile it the new line I added doesn't appear. I tried to delete the whole library and re-install it with modifications and it also doesn't appear anything, can you help with it ?

**Comment by Tomasz158** [comment]
I found an error connected with the new API.
`struct ndpi_detection_module_struct *ndpi_module(void);`

and in the main function:
`ndpi_set_protocol_detection_bitmask2(ndpi_module, &all);`

I receive an error:

error: cannot convert ‘ndpi_detection_module_struct* (*)()’ to ‘ndpi_detection_module_struct*’
