### ISSUE TITLE
 ndpi_main.h: No such file or directory

### ISSUE THREAD

**Issue by p2yogi** [ntop/nDPI#304]
Hi All,

  I am new to using nDPI library and facing a problem.

I am using nDPI APIs and structures defined in ndpi_main.h and hence including ndpi_main.h in my file.
i have downloaded the ndpi source code and followed below mentioned steps.
./configure
make
make install

And after following these steps I am getting above mentioned error.

Thanks for helping me.

**Comment by p2yogi** [comment]
In quickguide, it says we can directly include "ndpi_main.h" to our application code. but then while compiling it is giving error as mentioned in this issue subject...

Thanks

**Comment by kYroL01** [comment]
Hi @p2yogi .
Can you post exactly what your compiler says ?
It's strange because ndpi_main.h is in the library.

**Comment by p2yogi** [comment]
Hi @kYroL01,

   Actually while compiling my code, I have added ndpi_main.h as header filesimilar to quickguide. But compiler is throwing error as given below:

In file included from /home/user/yog/vs/VFP/ctrl_sync/vs_ds/src/vs_ds.c:1:0:
/home/user/yog/vs/VFP/ctrl_sync/vs_ds/inc/vs_ds.h:2:23: fatal error: ndpi_main.h: No such file or directory
 #include "ndpi_main.h"
                       ^
So I think its not able to locate the header file. So is the library placed in any specific location whose path I need to add my makefile. 
But that should not be the case as in quickguide example:
 #include "ndpi_main.h"

Thanks...

**Comment by kYroL01** [comment]
Are u sure you put correctly the library in the correct place (same folder) of your project ? Because it seems that when you want to include ndpi_main.h in your vs_ds.h, compiler not able to find it.
Check correctly the path

**Comment by p2yogi** [comment]
nDPI library folder is placed in /home/user/yog/nDPI right now.

I will place it in /home/user/yog/vs/VFP or else I can give the path of libarary in my makefile as 
   /home/user/yog/nDPI/src/include   

I would try with these and compile again. It should work. 

Thanks for your reply. I would update you with the result after my iteration.

**Comment by p2yogi** [comment]
hi @kYroL01.

  I did above mentioned iterations, and it is getting compiled. 

Thanks

**Comment by kYroL01** [comment]
You're welcome
