### ISSUE TITLE
undefined reference to 'ndpi_set_detected_protocol'

### ISSUE THREAD

**Issue by kyunghopark** [ntop/nDPI#305]
I wan to change the ndpiReader.c  using the dynamic library(libndpi.so) instead of static library(libndpi.a).
After changing the makefile, i compiled the source, 
but the compile is failed with the following reasons.
(I used the version 1.7 and 1.8 but the result is same.)
"undefined reference to 'ndpi_set_detected_protocol' and 'ndpi_protocol2name'.

i copyed the libndpi.so to /usr/local/lib. 
export LD_LIBRARY_PATH=/usr/local/lib

**Comment by kYroL01** [comment]
How did you change the Makefile ?
It seems you miss the reference to ndpi_main.h (where is the prototype of that two functions).

**Comment by kyunghopark** [comment]
The ndpReader.c file includes the ndpi_api.h which including the ndpi_main.h.

I changed the Makefile like the following.(Makefile in example directory)
 (Of course, i copyed the libnpid.so file to /usr/local/lib)
1) 110 line : ndpiReader_DEPENDENCIES = $(top_builddir)/src/lib/libndpi.la
   ==> ndpiReader_DEPENDENCIES = $(top_builddir)
2) 305 line : LDADD = $(top_builddir)/src/lib/libndpi.la -lpcap
   ==> LDADD = -lndpi -lpcap

**Comment by lucaderi** [comment]
$ grep ndpi_set_detected_protocol libndpi.sym 
ndpi_set_detected_protocol

Problem solved
