### ISSUE TITLE
undefined reference to many api like "ndpi_set_protocol_detection_bitmask2"

### ISSUE THREAD

**Issue by p2yogi** [ntop/nDPI#307]
Hi,

  After restarting my machine. I have starting to face this issue,

My project has two folders one which is ndpi library and other is my project related files.
I am using ndpi api for application identification. Hence I have included 'ndpi_main.h' in my project file. I have given the path of ndpi library as well for compilation and linking in my make file as shown below:

:   CFLAGS += -I/home/user/yog/vs/nDPI/src/include
:   LDFLAGS += -L/home/user/yog/vs/nDPI/src/lib/libndpi.la

But while linking of my project it is unable to detect the API symbols, that's why I am getting errors such as:

(.text+0xe87): undefined reference to `set_ndpi_malloc'
(.text+0xe91): undefined reference to `set_ndpi_free'
(.text+0xe98): undefined reference to `ndpi_init_detection_module'
(.text+0xeaa): undefined reference to `ndpi_calloc'
(.text+0xee7): undefined reference to `ndpi_calloc'
(.text+0xf2a): undefined reference to `ndpi_set_protocol_detection_bitmask2'

I am unable to see above mentioned API symbols which is because it is not getting linked.
I have tried few iterations of placing the library to different location as well, but unable to resolve the issue. 

Thanks for your help.

**Comment by p2yogi** [comment]
Dynamic linking is working..

**Comment by cicciob95** [comment]
> Dynamic linking is working..

I have same issue. How did you solve?

**Comment by utoni** [comment]
You should probably open a new issue with a precise description what happens and what was the expected result.

**Comment by cicciob95** [comment]
I solved it by adding the option:
`-L $ (NDPI_PATH) -l: libndpi.so`
Thanks
