### ISSUE TITLE
Capture Plex Traffic

### ISSUE THREAD

**Issue by depraved22** [ntop/nDPI#309]
I have a pretty simple config yet I seem to be missing something kinda easy.

I'm trying to capture plex traffic. It runs on TCP port 32400 and is accessible via a port map to the internet and folks can connect to that port to play content.

My custom proto looks simple:

tcp:32400@Plex

I can get it to match if my server initiates the connection but if it comes the other way, it is marked SSL instead of Plex.

http://imgur.com/a/xk9P8

I tested with a traffic profile and you can see that works without an issue and maps it to Plex by using a simple filter:

ip host 192.168.1.31 and port 32400

Do I just have a misconfig or do I need to set something else setup?

Thanks.

**Comment by kYroL01** [comment]
Simple: Plex is not classified service in nDPI.
It is not your fault.
So, if u provide a pcap I'll see on how to put plex inside the library.
Thanks

**Comment by depraved22** [comment]
What's the best way to provide that (I'm good with the actual command to capture the traffic)?

**Comment by kYroL01** [comment]
Did you try to put **tcp:32400@Plex** in a file .txt and pass to the library with option -p ?
If u did this and nDPI does not show Plex I think there is a bug to solve in the library.

**Comment by depraved22** [comment]
Yep:

```
cat custom.protos
#  Format:
#  <tcp|udp>:<port>,<tcp|udp>:<port>,.....@<proto>

tcp:32400@Plex
```

`Startup Line	ntopng --interface "p3p1" --http-port "3000" --dns-mode "1" --local-networks "192.168.1.0/24" --data-dir "/var/tmp/ntopng" --disable-autologout "" --ndpi-protocols "/etc/ntopng/custom.protos" --http-prefix "/ntopng" --daemon "" --disable-login "1" --dump-flows "mysql;localhost;ntopng;flows;ntopng;xxxxx"`

**Comment by kYroL01** [comment]
Can u provide me this pcap to do a test ? I tried with another pcap and works.
Thanks

**Comment by depraved22** [comment]
Here is the packet capture as well.

[capture.pcap.zip](https://github.com/ntop/nDPI/files/622271/capture.pcap.zip)

**Comment by kYroL01** [comment]
I tested and I realized that is **not** a nDPI issue.
If you try the ndpiReader with _-p custom.protos_ you see that _Plex_ is correctly identified.
So I think there's a bug in ntopng side.
Open an issue on ntopng repo and refer to this issue.
Please specify also how you start ntopng.
Thanks
