### ISSUE TITLE
Add nDPI support for icmp and icmpv6

### ISSUE THREAD

**Issue by Mile-Lile** [ntop/nDPI#31]
I don't see it in /src/lib/protocols. Is it detected in some other way? Just in case pcap files for icmp and icmpv6 added... Thx

https://drive.google.com/file/d/0B0SCwy1irn3qTDlMVGhSUXc1dU0/view?usp=sharing

https://drive.google.com/file/d/0B0SCwy1irn3qZVJVRjd3X0x0Tm8/view?usp=sharing

**Comment by lucaderi** [comment]
Fixed in https://github.com/ntop/nDPI/commit/1d711d849d4cc1350ede04b4f5e0911ac59e88fa
