### ISSUE TITLE
iis.net and g2a.com detects as TOR

### ISSUE THREAD

**Issue by a7lan** [ntop/nDPI#310]

**Comment by kYroL01** [comment]
Can u provide a pcap for this issue ? Thanks

**Comment by a7lan** [comment]
Yes, but not today. Maybe tomorrow

**Comment by kYroL01** [comment]
@a7lan any news ?

**Comment by a7lan** [comment]
Yes. Sorry to keep you waiting. 2 pcap file. iis.net. 
First file without tor block rule and second file with tor block rule
[pcap.zip](https://github.com/ntop/nDPI/files/639272/pcap.zip)

**Comment by kYroL01** [comment]
Thanks. I'll see it

**Comment by kYroL01** [comment]
I pass pcap to ndpiReader but they're both detected as SSL, not TOR.
Are u sure to use the latest version of nDPI ?

**Comment by a7lan** [comment]
I have not tested the latest version. I'll try to test
Maybe ndpi detects it as https and tor, too? because when I add a rule to block tor, iis and g2a not openned. Other https sites work.

**Comment by kYroL01** [comment]
If you see the result with last version of nDPI, it detect your pcaps as SSL.
![img](https://cloud.githubusercontent.com/assets/7222956/21052268/63b0ee32-be24-11e6-9788-a50cb8256abb.png).

So the thing that I can do is add the detection of **iis.net** as Microsoft, if you think is a good idea.
Let me know about it
