### ISSUE TITLE
QUIC is only detected

### ISSUE THREAD

**Issue by p2yogi** [ntop/nDPI#311]
Hi 
 
   I have used nDPI api for application identification in my solution. It is detecting applications like bit-torrent and skype.

But when I am opening any application like facebook, twitter etc on google chromium browser. My application is only detecting ap id as 188 (Quic) and nothing else. whereas in ndpiReader example it is detecting quic and other thing as well like http.

So I had a query does nDPI library maintains flow per session internally or that has to maintained by the user using the api.....??

**Comment by kYroL01** [comment]
I'm not sure if I understand.
It is a fault of nDPI or the application you're using ? 
Of course nDPI has the concept of flows for sessions, it is not a packet sniffer (like Wireshark).
I.e. this is flow struct for a [tcp session](https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_typedefs.h#L447)

So, if nDPI detect protos correctly, I close this issue.
