### ISSUE TITLE
IPVERSION definition missing

### ISSUE THREAD

**Issue by sologub** [ntop/nDPI#313]
I see constant IPVERSION is used in a few places but I can't find its definition and get a compilation error.
Is this a bug or am I missing something?

**Comment by mkfsn** [comment]
I found the include here https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_includes.h#L45 :

```c
#include <netinet/ip.h>
```

and found  `IPVERSION` is defined in `netinet/ip.h`:

```
#define IPVERSION       4               /* IP version number */
#define IP_MAXPACKET    65535           /* maximum packet size */
```

**Comment by kYroL01** [comment]
Yes is like @mkfsn says, so you have compilation error if you don't include **netinet/ip.h**

**Comment by kYroL01** [comment]
Look here http://unix.superglobalmegacorp.com/Net2/newsrc/netinet/ip.h.html
