### ISSUE TITLE
confused about tcp retransmission in  function ndpi_connection_tracking

### ISSUE THREAD

**Issue by tianzhishuizhu** [ntop/nDPI#315]
How does variable `ndpi_struct->tcp_max_retransmission_window_size`  work in tcp retransmission checking? Its value is 65536 in decimal.
In ndpi_main.c from line 3055, function  ndpi_connection_tracking():
```
else if(packet->payload_packet_len > 0) {
      /* check tcp sequence counters */
      if(((u_int32_t)(ntohl(tcph->seq) - flow->next_tcp_seq_nr[packet->packet_direction])) >
	 ndpi_struct->tcp_max_retransmission_window_size) {

	packet->tcp_retransmission = 1;
```

My understanding: 
// for simplification
```
(u_int32_t)a1 = ntohl(tcph->seq)  
(u_int32_t)a2 = flow->next_tcp_seq_nr[packet->packet_direction]
```
I would think that if a1 < a2, that means retransmission happens. **Because a1 and a2 are u_int32_t, a1-a2 would be very large when a1 < a2, and maybe larger than 65536**. Thanks for you work.

**Comment by kYroL01** [comment]
Retransmission happens exactly as the code says:

```
else if(packet->payload_packet_len > 0) {
      /* check tcp sequence counters */
      if(((u_int32_t)(ntohl(tcph->seq) - flow->next_tcp_seq_nr[packet->packet_direction])) >
	 ndpi_struct->tcp_max_retransmission_window_size) {

	packet->tcp_retransmission = 1;
```

So if the difference between the actual pkt seq number and the next pkt seq number is bigger than the maximum dimension of the window size, that means you have a retrasmission of a tcp packet, and _packet->tcp_retransmission_ is set to 1.

**Comment by tianzhishuizhu** [comment]
I debug with following code:
```
else if(packet->payload_packet_len > 0) {
      /* check tcp sequence counters */
      if(((u_int32_t)(ntohl(tcph->seq) - flow->next_tcp_seq_nr[packet->packet_direction])) >
	 ndpi_struct->tcp_max_retransmission_window_size) {
          
             // added for debugging
             if(ntohl(tcph->seq) < flow->next_tcp_seq_nr[packet->packet_direction]) 
	        printf("real seq less than expected \n");
             else if  (ntohl(tcph->seq) > flow->next_tcp_seq_nr[packet->packet_direction])
               printf("real seq larger than expected \n");

	packet->tcp_retransmission = 1;
```

Only "real seq less than expected"  outputs.

**Comment by kYroL01** [comment]
Correct: **123456789** > **65536**  --> retrasmission
