### ISSUE TITLE
ndpi-netfilter for 1.8 or dev

### ISSUE THREAD

**Issue by TTpartizan** [ntop/nDPI#316]
Hi
For 1.8 or dev (kernel 4.4 iptables-1.4.21) not compile ndpi-netfilter
Maybe someone make the a working fork? 
https://github.com/ewildgoose/ndpi-netfilter

**Comment by kYroL01** [comment]
nDPI don't support anymore netfilter, so if you need to use it , look at any fork project that still maintain the netfliter support.

Maybe the upgratest work is this https://github.com/vel21ripn/nDPI
