### ISSUE TITLE
unable to detect applications

### ISSUE THREAD

**Issue by p2yogi** [ntop/nDPI#318]
Hi, 
 In my code I am not capturing live packets and giving it to nDPI. I am using DPDK and DPDK mbuf is passed to "**ndpi_detection_process_packet()**" API. 

So in my case I am able to get master_protocol but unable to get applications like facebook, twitter etc...instead I am only getting ID as 188 (i.e. of QUIC)

I debugged it with GDB and In ndpiReader application packet size is much longer then what I am having. So is it the reason my application is unable to detect applications such as facebook, because complete packet size is not being received by the API.....??

Thanks for the help....!!

**Comment by kYroL01** [comment]
I answered you privately to the mail you sent me.

**Comment by 490** [comment]
@p2yogi hello,did you capture packets by DPDK and analyse them by nDPI?
such as
```
packet = rte_pktmbuf_mtod(rte_mbuf *m, u_char * );//in DPDK
pcap_packet_callback_checked(u_char *args,const struct pcap_pkthdr *header, const u_char *packet)//int nDPI
```
how to implement it?could you please give me  some advice ?could you please share your code on github?
Thank you very much!!!
