### ISSUE TITLE
Add WeChat application protocol

### ISSUE THREAD

**Issue by kYroL01** [ntop/nDPI#323]
Missing WeChat recognition. See link for infos

 https://en.wikipedia.org/wiki/WeChat

http://www.cse.cuhk.edu.hk/~pclee/www/pubs/iwqos15chatdissect.pdf

**Comment by swtar** [comment]
Do you have any good ideas?

**Comment by kYroL01** [comment]
Hi @swtar I need a good pcap that I'm going to do in the following days and then I can try to put inside nDPI

**Comment by 490** [comment]
I'm looking forward to this!!  thank you

**Comment by kYroL01** [comment]
Today I'm going to have a couple of good pcap and I'm working on it.
If you have other pcap to send, please, shared.

Thank you

**Comment by kYroL01** [comment]
first commit
b97e3ee51a9a17b837a2ed8c30e5ddabbf2d7140

**Comment by feriel-ux** [comment]
I want to add a new custom protocol on nDPI ( e.g : shahid.mbc.net ) , but I want ndpi detect the protocol when I build and add a source code for this protocol ( not in protos.txt with the host )

**Comment by feriel-ux** [comment]
how can I capture a pcap file for a specific protocol application , do I have to user wireshark ? any help please
