### ISSUE TITLE
debugging problem

### ISSUE THREAD

**Issue by tianzhishuizhu** [ntop/nDPI#324]
When debugging ndpiReader, I set breakpoint to make gdb stop at specific line,but gdb doesn't do that. I think it's inlining and optimisation in gcc. How can I fix this problem? Thanks.

**Comment by kYroL01** [comment]
@tianzhishuizhu this is not a nDPI issue, and the only optimization of gcc is about the visibility of something variables.
So, this is a problem on your machine, or, as I think, you put a breakpoint on a line that cannot be reached in that moment.

**Comment by tianzhishuizhu** [comment]
Thanks. I try it with `./autogen.sh ./configure make` and then `gdb ndpiReader`. Is it the right process for debugging?

I set breakpoint at **line 3281**

>  b ndpi_main.c:3281
Breakpoint 1 at 0x40fb30: file ndpi_main.c, line 3281.

> info breakpoint
Num     Type           Disp Enb Address            What
1       breakpoint     keep y   0x000000000040fb30 in check_ndpi_tcp_flow_func at ndpi_main.c:3281
        breakpoint already hit 1 time

But when hiting the breakpoint, it's line **3331**:

> Breakpoint 1, check_ndpi_tcp_flow_func (ndpi_struct=ndpi_struct@entry=0x67f6a0, flow=flow@entry=0x7ffff0000b40,
    ndpi_selection_packet=ndpi_selection_packet@entry=0x7ffff75b7a28) at ndpi_main.c:3331
3331                                  NDPI_SELECTION_BITMASK_PROTOCOL_SIZE *ndpi_selection_packet) {

**Comment by tianzhishuizhu** [comment]
I change `gcc -g -O2` to `gcc -g -O0` in all Makefiles, and then it works.

**Comment by kYroL01** [comment]
As i told you before, is a problem of visibility. Now you put more visibility on what gdb can show you.
If u want the maximum, try gcc -g3 .

**Comment by tianzhishuizhu** [comment]
Thanks.
