### ISSUE TITLE
Skype detection

### ISSUE THREAD

**Issue by shivanikhosa** [ntop/nDPI#325]
I was testing Skype detection and I see now, that most of the call traffic is either classified as RTCP or is unkown. Only the tcp connections get recognized as Skype. The udp session carrying the voice data isn't recognized.

**Comment by kYroL01** [comment]
Can u provide a pcap of your skype traffic so i can see the bug and going to fix ? 
Thanks

**Comment by shivanikhosa** [comment]
[skype.zip](https://github.com/ntop/nDPI/files/707114/skype.zip)

**Comment by shivanikhosa** [comment]
I was just trying the Skype test call. I see a lot of tcp udp connections getting recognized as either skype or stun but the main voice call udp connection was Unknown. Are there any recent enhancements to skype dissector other than addition of new host name matching that could help me recognize the skype voice call?

**Comment by kYroL01** [comment]
I have to check. Thanks for the pcap

**Comment by shivanikhosa** [comment]
Thanks. I will wait for your reply.

**Comment by shivanikhosa** [comment]
Wanted to mention that the skype version that I'm using is 7.30.0.105. I was looking at the dissector and I saw that the Skype dissector mostly was looking for the third byte of the payload to be 0x02 in case of UDP packets to classify as skype. When I make a test call, my payload 3rd byte isn't 0x02.
But I did notice another pattern when I see packets in wireshark.
 payload[0] = 0x80, payload[1]=09,c8 or c9.
Wireshark seems to classify these packets as GigE Vision Streaming Protocol.

**Comment by kYroL01** [comment]
I'm watching all and try to understand better.

**Comment by kYroL01** [comment]
@shivanikhosa Actually the traffic classified as GigE Vision Streaming Protocol has the same two bytes as RTP payload[0] = 0x80 && payload[1] = 0x08. I extracted GVSP packet from your pcap and nDPI detect it as RTP for this reason. So I have to find a way to detect GVSP as Skype but ONLY for real skype traffic.
Are u agree with me ?

**Comment by kYroL01** [comment]
I'm doing some changes because I need to see deeper the question. Please be patient.
Thanks

**Comment by shivanikhosa** [comment]
👍 Thanks for your efforts :)

**Comment by alagoutte** [comment]
> @shivanikhosa Actually the traffic classified as GigE Vision Streaming Protocol has the same two bytes as RTP payload[0] = 0x80 && payload[1] = 0x08. I extracted GVSP packet from your pcap and nDPI detect it as RTP for this reason. So I have to find a way to detect GVSP as Skype but ONLY for real skype traffic

There is a false postive with GigE Vision Streaming dissector on Wireshark 2.2.x
the heuristic is now disable

**Comment by kYroL01** [comment]
@alagoutte Thanks for the clarification. So is correct if nDPI detect GVSP as RTP ?

**Comment by shivanikhosa** [comment]
Yes I see that. I updated my wireshark  and the GVSP detection went away.

**Comment by kYroL01** [comment]
Do some test after [this](https://github.com/ntop/nDPI/commit/eb92c6b676064ef7bd642f43eae3136e7db4737e)
and let me know

**Comment by kYroL01** [comment]
@shivanikhosa any update ?

**Comment by shivanikhosa** [comment]
I tested it with skype test call but I still see the same results. I see that in this patch you have added extra skype related ip ranges.
In my setup I still see the connection related to the skype call as being unclassified. The destination ip address matching probably won't be foolproof as I see different dst ip everytime. Were you able to identify any skype protocol related heuristics, that we could use to improve detection?

**Comment by shivanikhosa** [comment]
I re-tested with skype-to-skype call and still the call packets are unclassified.
udp      17 179 src=192.168.1.10 dst=104.44.201.157 sport=11228 dport=3480 packets=8070 bytes=899637
Another call yields this connection:
udp      17 179 src=192.168.1.10 dst=104.44.201.173 sport=9182 dport=3480 packets=1637 bytes=182668 

My recognized skype connections are as follows :
tcp      6 86387 ESTABLISHED src=192.168.1.10 dst=111.221.90.252 sport=54183 dport=50003 packets=179 bytes=9533
tcp      6 85995 ESTABLISHED src=192.168.1.10 dst=91.190.218.58 sport=53992 dport=443 packets=22 bytes=2948
tcp      6 86365 ESTABLISHED src=192.168.1.10 dst=111.221.77.165 sport=53995 dport=40030 packets=401 bytes=44556
tcp      6 86342 ESTABLISHED src=192.168.1.10 dst=23.99.97.116 sport=54222 dport=443 packets=15 bytes=16344
tcp      6 85 TIME_WAIT src=192.168.1.10 dst=104.211.162.124 sport=54191 dport=50004 packets=114 bytes=6090
tcp      6 85 TIME_WAIT src=192.168.1.10 dst=104.211.164.75 sport=54189 dport=50007 packets=131 bytes=8292 src=104.211.164.75
tcp      6 86390 ESTABLISHED src=192.168.1.10 dst=168.63.207.197 sport=54185 dport=50006 packets=174 bytes=8336

udp      17 6 src=192.168.1.10 dst=157.56.52.39 sport=2454 dport=40022 packets=1 bytes=76
udp      17 66 src=192.168.1.10 dst=49.240.38.181 sport=2454 dport=43369 packets=2 bytes=85
udp      17 57 src=192.168.1.10 dst=157.55.130.159 sport=2454 dport=40033 packets=3 bytes=400
udp      17 6 src=192.168.1.10 dst=157.56.52.24 sport=2454 dport=40023 packets=1 bytes=76
udp      17 66 src=192.168.1.10 dst=202.165.93.87 sport=2454 dport=35024 packets=2 bytes=85
udp      17 108 src=192.168.1.10 dst=111.221.90.252 sport=2454 dport=50003 packets=119 bytes=6683
udp      17 20 src=192.168.1.10 dst=157.55.235.159 sport=2454 dport=40001 packets=2 bytes=351
udp      17 107 src=192.168.1.10 dst=111.221.77.157 sport=2454 dport=40028 packets=12 bytes=1490
udp      17 93 src=192.168.1.10 dst=111.221.77.150 sport=2454 dport=40022 packets=15 bytes=770
udp      17 68 src=192.168.1.10 dst=157.56.52.43 sport=2454 dport=40027 packets=4 bytes=189
udp      17 117 src=192.168.1.10 dst=168.63.207.197 sport=2454 dport=50006 packets=93 bytes=6878
udp      17 156 src=192.168.1.10 dst=157.55.235.167 sport=2454 dport=40022 packets=2 bytes=157
udp      17 66 src=192.168.1.10 dst=49.194.31.166 sport=2454 dport=1732 packets=2 bytes=85
udp      17 6 src=192.168.1.10 dst=157.55.130.142 sport=2454 dport=40007 packets=1 bytes=76
udp      17 42 src=192.168.1.10 dst=111.221.77.140 sport=2454 dport=40033 packets=3 bytes=150
udp      17 92 src=192.168.1.10 dst=58.0.66.104 sport=2454 dport=16045 packets=2 bytes=97
udp      17 156 src=192.168.1.10 dst=64.4.23.145 sport=2454 dport=40035 packets=2 bytes=157
udp      17 93 src=192.168.1.10 dst=157.56.52.43 sport=2454 dport=40028 packets=11 bytes=527
udp      17 66 src=192.168.1.10 dst=174.101.107.5 sport=2454 dport=4458 packets=2 bytes=85
udp      17 92 src=192.168.1.10 dst=61.143.129.74 sport=2454 dport=36378 packets=2 bytes=97
udp      17 156 src=192.168.1.10 dst=65.55.223.39 sport=2454 dport=40022 packets=2 bytes=157
udp      17 81 src=192.168.1.10 dst=157.55.130.161 sport=2454 dport=40023 packets=2 bytes=365
udp      17 93 src=192.168.1.10 dst=201.165.197.87 sport=2454 dport=16990 packets=2 bytes=97
udp      17 20 src=192.168.1.10 dst=157.56.52.12 sport=2454 dport=40031 packets=2 bytes=125
udp      17 81 src=192.168.1.10 dst=111.221.77.165 sport=2454 dport=40011 packets=3 bytes=406
udp      17 6 src=192.168.1.10 dst=65.55.223.24 sport=2454 dport=40023 packets=1 bytes=76
udp      17 81 src=192.168.1.10 dst=157.56.52.17 sport=2454 dport=40033 packets=2 bytes=363
udp      17 6 src=192.168.1.10 dst=64.4.23.159 sport=2454 dport=40027 packets=1 bytes=76
udp      17 44 src=192.168.1.10 dst=157.56.52.34 sport=2454 dport=40030 packets=2 bytes=129
udp      17 50 src=192.168.1.10 dst=111.119.215.66 sport=2454 dport=63319 packets=120 bytes=5729
udp      17 92 src=192.168.1.10 dst=203.106.119.45 sport=2454 dport=59451 packets=2 bytes=97

**Comment by kYroL01** [comment]
@shivanikhosa Find heuristics we could use to improve detection is the challenge to make best dissectors for every protocol that doesn't have free and open documentation. This is the problem

**Comment by kYroL01** [comment]
Fix by https://github.com/ntop/nDPI/commit/5de6a96af5754c13846883b556f58fc79831c61d
