### ISSUE TITLE
Cento-bridge still downloads torrent

### ISSUE THREAD

**Issue by izzie88** [ntop/nDPI#326]
Hello Luca ,
Please find attached the zip file for packet capture.
I was still able to download torrents after applying the policy on the cento-bridge.
[torrent2.pcapng.zip](https://github.com/ntop/nDPI/files/707466/torrent2.pcapng.zip)
[torrent.pcapng.zip](https://github.com/ntop/nDPI/files/707468/torrent.pcapng.zip)

**Comment by kYroL01** [comment]
Hi @izzie88 let me understand better: the problem is that there is a false positive on torrent traffic or anyway that traffic is real torrent traffic ?
if it's the second option this is not an nDPI issue.

**Comment by lucaderi** [comment]
Please make sure that you use nDPI (and non unDPI) in cento and it should work.
