### ISSUE TITLE
Add nDPI support for HOOQ application

### ISSUE THREAD

**Issue by tomerto** [ntop/nDPI#33]
Add nDPI support for HOOQ application. HOOQ is a Video Streaming service. https://www.hooq.tv/
Traces will be sent separately.

**Comment by lucaderi** [comment]
@tomerto See https://github.com/ntop/nDPI/commit/2be84d4d644cd6122d9328a5619d1f1168bda03f
Note that as HOOQ is apparently a customer of Quickplay, the protocol is set to quickplay
