### ISSUE TITLE
ndpiReader.c:40:18: fatal error: pcap.h: No such file or directory

### ISSUE THREAD

**Issue by ghost** [ntop/nDPI#331]
Unable to compile. No results on google. Already tried libcap-dev, libcapnp-dev
Ubuntu 16.04

**Comment by kYroL01** [comment]
I'm going to see and fix, thanks.

**Comment by alagoutte** [comment]
@ajzimme it is lipcap-dev (and no libcap-dev)... can you try ?

**Comment by kYroL01** [comment]
@ajzimme are u refer to this [line](https://github.com/ntop/nDPI/blob/dev/example/ndpiReader.c#L40) ?
You must install libpcap. For example http://stackoverflow.com/a/5779827
