### ISSUE TITLE
Include file installation path issue

### ISSUE THREAD

**Issue by clauderobi** [ntop/nDPI#333]
First of all, I am cross compiling so the issue may not be present when compiling native.

But first, before going to my issue, I found this small glitch in src/include/Makefile.am
library_includedir=$(includedir)/libndpi-1.4/libndpi   
I guess it should be libndpi-@VERSION@, not libndpi-1.4 since I am using version 1.8

My main problem is that the path for the include files includes the library version. This is not typical; I am using many open source librariesy and none do that. It forces the makefile file to include a specific -I for nDPI or to write the #include statements with a version, both of which are cumbersome.

**Comment by alagoutte** [comment]
Thanks claude for report

**Comment by kYroL01** [comment]
Thanks to both

**Comment by clauderobi** [comment]
Thanks,

but this only solves the lesser issue. The main issue of having the version in the include pathname, forcing to have it in the source #include pragma or in the Makefile (-I) is not addressed. It is not common to have the version in the path name but I understand that when an API is not stable that may be necessary. But may be adding a soft link is acceptable; this is what is done for the .so itself. Can this is added to the configure process?

**Comment by kYroL01** [comment]
@clauderobi does your problem related with the installation of the lib ? I mean (if I understand well) you say that every time we put a new version, if you use the lib you have to change makefile, isn't it ?

**Comment by kYroL01** [comment]
I close for inactivity. Reopen if necessary
