### ISSUE TITLE
no PCAP

### ISSUE THREAD

**Issue by clauderobi** [ntop/nDPI#336]
Is it possible to compile the library without pcap support? I do not need it nor want it on the platform I target.

Also, it is possible to skip building the example application?

**Comment by kYroL01** [comment]
1. There is no flag to disable the pcap support at compiling time. To do this you have to modify the code (at your risk).

2. If you want to exclude the example directory you have to modifiy this [Makefile.am](https://github.com/ntop/nDPI/blob/dev/Makefile.am) excluding the _example_ in SUBDIRS and then recompile all.

**Comment by clauderobi** [comment]
But, how does the code is compiled inside the kernel? Surely libpcap is not capable of executing in the kernel. My use of the nDPI library is not inside the kernel.

**Comment by kYroL01** [comment]
nDPI does not have anymore the kernel support.
