### ISSUE TITLE
ndpi_flow_struct life cycle

### ISSUE THREAD

**Issue by clauderobi** [ntop/nDPI#338]
I am not sure if this place (issues) is the right place to ask question or discuss about topics since a group is better suited but I fail to find one.

I would like to understand better the life cycle of a single ndpi_flow_struct instance. What I am trying to do is to keep malloc and free to a minimum. Since I am already maintaining a high-up flow object, into which I would like to instantiate a ndpi_flow_struct instance, I would like to understand if I can simply wipe (memset) the ndpi_flow_struct object when a flow is not needed anymore. Looking at the code (ndpi_free_flow) I see that there are 2 subobjects that are freed so if I simply memset ndpi_flow_struct I will endup with memory leaks. Not good!!
I can may be keep the 2 subobjects, memset them and add them back into the ndpi_flow_struct instance but would that work?

I know that I can use malloc and free wrapper to help better manage the memory but the best thing is also to avoid that completely OR include that into a high up object management. I am doing this in order to improve as much as I can the efficiency for the purpose of high packet rate.

**Comment by kYroL01** [comment]
@clauderobi It's always difficult to give a good exhaustive answer in this case.

> Looking at the code (ndpi_free_flow) I see that there are 2 subobjects that are freed so if I simply memset ndpi_flow_struct I will endup with memory leaks. Not good!!

Correct: if u memset without correctly free the two subobject, you lost them and have mem leaks.
But the two subobjects in the `ndpi_flow_struct` are strictly correlated with the main object, so i don't know how much sense have keep them when the flow change. Can you explain better this point ?
