### ISSUE TITLE
Is nDPI a thread-safe?

### ISSUE THREAD

**Issue by Skryabind** [ntop/nDPI#34]
To work with >10Gps traffic I want to share the traffic detection in different threads. Shall I use one detection module for all threads or own detection module for each thread?

**Comment by lucaderi** [comment]
Each instance returned by ndpi_init_detection_module() is lock-less but not thread safe if shared across threads. Please create one instance per thread as we do in https://github.com/ntop/nDPI/blob/dev/example/ndpiReader.c
