### ISSUE TITLE
What's the meanning of NDPI_SELECTION_BITMASK_PROTOCOL_COMPLETE_TRAFFIC?

### ISSUE THREAD

**Issue by HaochuanXJTU** [ntop/nDPI#340]
I think this bitmask is to distinguish the packet, like tcp or udp. So I can't understand NDPI_SELECTION_BITMASK_PROTOCOL_COMPLETE_TRAFFIC, please tell me the function of this bitmask. Thanks ~

**Comment by lucaderi** [comment]
I think this is old stuff from OpenDPI we could remove. @kYroL01 What do you think?

**Comment by kYroL01** [comment]
@HaochuanXJTU @lucaderi  I suppose this Bitmask is never used in the actual code, so, yes, I think we could remove.

**Comment by kYroL01** [comment]
Actually this bitmask is used and cannot delete without a good fix before, but it's an old stuff so I have understand the real use of it.
I look in the code it is a macro for a left shift of 8 bit and set the value of `ndpi_selection_packet` to 256 ( https://github.com/ntop/nDPI/blob/dev/src/lib/ndpi_main.c#L3356 )

**Comment by HaochuanXJTU** [comment]
@kYroL01@luacaderi thanks for your help~
