### ISSUE TITLE
netflix isn't detected very well

### ISSUE THREAD

**Issue by gabeblack** [ntop/nDPI#342]
I have a capture that is a majority of netflix traffic, but it is showing up as mostly HTTPDownload. I looked at some of the IPs and it appears that they may be from Amazon's cloud services. How would I go about modifying the code to follow that as my guess is that the amazon cloud services that are providing the streaming don't have hard-coded ip ranges assigned specifically for netflix...

**Comment by kYroL01** [comment]
Netflix uses Amazon's cloud service and servers. So, we have to see if the ip-range is modified to add properly server names. Can u pass me the pcap with this traffic ?
Thanks

**Comment by kYroL01** [comment]
Check after this update https://github.com/ntop/nDPI/commit/af04f78bd783a18593fb9a1320bfc430ae8af0bc

**Comment by gabeblack** [comment]
I tried your patch and unfortunately no additional traffic was detected as
netflix. I sent you a message to your profile email about the traffic I
have.

Thanks,
Gabe

**Comment by kYroL01** [comment]
https://github.com/ntop/nDPI/commit/fd93036b792bc33a81cb46164b7a3184d8723fd6
Now is fixed and improved netflix detection IMHO.
I close this issue. If needed reopen
