### ISSUE TITLE
question about dns dissector

### ISSUE THREAD

**Issue by tianzhishuizhu** [ntop/nDPI#345]
In protocols/dns.c:
`	/* DNS Request */
	if((dns_header.num_queries > 0) && (dns_header.num_queries <= NDPI_MAX_DNS_REQUESTS)
	   && (((dns_header.flags & 0x2800) == 0x2800 /* Dynamic DNS Update */)
	       || ((dns_header.num_answers == 0) && (dns_header.authority_rrs == 0)))) {`

What's the use for checking **(dns_header.flags & 0x2800) == 0x2800**?It checks dns flag at postion 3 and 5 in 16 bit range 0010 1000 0000 0000. I've searched DNS protocol format, but haven't found the answer. Thanks!.

**Comment by kYroL01** [comment]
For example read this http://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-12
"**In DNS query header there is a flag field in the second 16 bit word in 
query from bit 5 through bit 11**"
