### ISSUE TITLE
free expiring flow struct

### ISSUE THREAD

**Issue by tianzhishuizhu** [ntop/nDPI#346]
4-tuple <src_ip, src_port, dst_ip, dst_port> indentifies unique connection. But it may be reused by another protocol after a long time. Does nDPI free flow struct if flow expires?

**Comment by kYroL01** [comment]
Flows are not free automatically.
nDPI provides many free function to do that, for example
https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_api.h#L133
https://github.com/ntop/nDPI/blob/dev/src/lib/ndpi_main.c#L4795
https://github.com/ntop/nDPI/blob/dev/src/lib/ndpi_main.c#L331

If you want to free a flow you have to use it. C does not have garbage collector so the flows must be explicity free.
