### ISSUE TITLE
unbind nDPI from ntop, aka use as a system library

### ISSUE THREAD

**Issue by blshkv** [ntop/nDPI#353]
I have reported this issue in an old bug tracking system but it is gone.

ntop building system is a mess right now. it downloads nDPI during build and trying to compile even if nDPI is already installed in the system.

There are also other tools which are using nDPI like xplico.

The following patch allows to install include files so that they could be found during ntop build:
https://github.com/pentoo/pentoo-overlay/blob/master/net-libs/libndpi/files/libndpi-1.5.0-system.patch

**Comment by blshkv** [comment]
https://github.com/pentoo/pentoo-overlay/blob/master/net-analyzer/ntop/files/ntop-5.0.1-system-ndpi.patch

**Comment by alagoutte** [comment]
Hi,

Please push directly your patch a Push Request (on ndpi and ntop repo)

**Comment by kYroL01** [comment]
@blshkv I have to try the patch locally before push into official repository. 
Thanks for it.

**Comment by blshkv** [comment]
sorry, the patches are for the previous version.

**Comment by kYroL01** [comment]
Ok, so i can close this issue ?

**Comment by blshkv** [comment]
no, please port it to the latest ntopng

**Comment by kYroL01** [comment]
@lucaderi what do u think about this ?

**Comment by kYroL01** [comment]
@blshkv I don't understand why the `-@VERSION@` in the Makefile should be a problem for nDPI.
I don't know if is a good thing to avoid this check.

For the second patch, please, open an inssue or (better) send a pull request directly into ntopng repository.

**Comment by blshkv** [comment]
I'm not an automake expert so feel free to adjust it properly
The only reason why I removed version from the include path is that it would be possible to specify it in the configure script of ntop (see NDPI_INC variable) in the second patch.

**Comment by kYroL01** [comment]
In the beginning I don't understand what you mean, but now I think you're right. We have to modify this thing properly. I'm working on it.
Thank you

**Comment by kYroL01** [comment]
@blshkv this link https://github.com/pentoo/pentoo-overlay/blob/master/net-libs/libndpi/files/libndpi-1.5.0-system.patch is outdate.

**Comment by blshkv** [comment]
you can still find it in the previous revision. However, Gentoo guys seems pushed it to the main tree so I deleted it. Please see the following patches:

https://github.com/LordVeovis/gentoo/blob/master/net-analyzer/ntopng/files/ntopng-2.4-no-ndpi.patch
https://github.com/LordVeovis/gentoo/blob/master/net-analyzer/ntopng/files/ntopng-2.0-dont-build-ndpi.patch

They patched it differently (it's your call anyway) and no nDPI changes are required

**Comment by lucaderi** [comment]
nDPI is now packaged on a separate package form both ntop, brew.sh and other distributions. i think we can close this issue
