### ISSUE TITLE
Need help of capturing https traffic.

### ISSUE THREAD

**Issue by subhedarnikhil** [ntop/nDPI#356]
Hi All,

i am interested to understand the the capturing of https traffic. What i know is we are determing the server name from ssl ceritificate. but  this is happening at the  initial level i.e. at handshaking level. But i want to know how we can  map the  this actual data to this server name..???

Regards,
Nikhil

**Comment by kYroL01** [comment]
Duiring the handshake exchange, the [ssl dissector ](https://github.com/ntop/nDPI/blob/dev/src/lib/protocols/ssl.c) catch the server name from a field in Client Hello packet, and match it with a list of possible server names kept by nDPI internally ([here](https://github.com/ntop/nDPI/blob/dev/src/lib/ndpi_content_match.c.inc)).

A function to do this is https://github.com/ntop/nDPI/blob/dev/src/lib/ndpi_main.c#L4641 for example.
