### ISSUE TITLE
Need help on https  flow tracking...

### ISSUE THREAD

**Issue by subhedarnikhil** [ntop/nDPI#359]
Hi ,

Want to know how we can track the HTTPS flow. What i know is  we are  getting the server name from the SSL certificate. But this is at handshaking level. Once connection is established then how we are obtain the flow information corresponding to that connection. Are we storing this information i.e. 5 tuples..? ??
 and comparing each flow corresponding to it..???

Regards,
Nikhil

**Comment by kYroL01** [comment]
@subhedarnikhil I understand you need explanation on what the dissector does and the behaviour inside nDPI, but I answered on a similar question in your latest issue related to HTTPS, and this is not a FAQ session, this is an issue session.
I cannot "teach" you on how to do a thing.
If I answer to all these kind of questions, everyone could open hundreds of issues like this, and this is not right, IMHO.
Please to understand us and keep the behaviour of this section.
If you need a consultant, write us privately and we get a paid full assistant.
Thank you.

p.s. BTW nDPI parse and extract information on SSL packet similar to [this](http://stackoverflow.com/questions/17832592/extract-server-name-indication-sni-from-tls-client-hello)
