### ISSUE TITLE
ERROR: could not open pcap file or playlist: ens802f1: No such file or directory

### ISSUE THREAD

**Issue by 490** [ntop/nDPI#361]
Hi,
1、I can see ens802f1(a 10G intel nic)by ifconfig,but when I execute ./ndpiReader -i ens802f1 -s 30 it says ERROR.. and I can use ndpiReader to read a pcap file correctly.
2、If I want to combine Intel DPDK with nDPI, use nDPI to analyse the packet captured by DPDK ,could you give me some advice?
Thank you very much!

**Comment by kYroL01** [comment]
>  it says ERROR

Can u specify little bit more about this ?

**Comment by 490** [comment]
my input is :   ./ndpiReader -i ens802f1 -s 30
and then:
Using nDPI (1.8.0) [1 thread(s)]
ERROR: could not open pcap file or playlist: ens802f1: No such file or directory
(I can see this ens802f1 device by "ifconfig")
I have read the source code:
` if((pcap_handle = pcap_open_live((char*)pcap_file, snaplen, promisc, 500, pcap_error_buffer)) == NULL) 
    {
        capture_for = capture_until = 0;
        live_capture = 0;
        num_threads = 1; /* Open pcap files in single threads mode */
        /* trying to open a pcap file */
        if((pcap_handle = pcap_open_offline((char*)pcap_file, pcap_error_buffer)) == NULL) 
        {
            char filename[256];
        /* trying to open a pcap playlist */
            if(getNextPcapFileFromPlaylist(thread_id, filename, sizeof(filename)) != 0 ||
                (pcap_handle = pcap_open_offline(filename, pcap_error_buffer)) == NULL) 
            {
                printf("ERROR: could not open pcap file or playlist: %s\n", pcap_error_buffer);
                exit(-1);
            } 
            else 
            {
                if((!json_flag) && (!quiet_mode)) 
                    printf("Reading packets from playlist %s...\n", pcap_file);
            }
        } 
        else 
        {
            if((!json_flag) && (!quiet_mode)) 
                printf("Reading packets from pcap file %s...\n", pcap_file);
        }
    } 
   else 
    {
        live_capture = 1;
        if((!json_flag) && (!quiet_mode)) 
            printf("Capturing live traffic from device %s...\n", pcap_file);
    }`
but I dont understand why ,HOW CAN I CAPTURE LIVE TRAFFIC FROM DEVICE?could you please help me?Thank you!

**Comment by kYroL01** [comment]
nDPI use the pcap library to manage how to open a device, so `pcap_open_live` and `pcap_open_offline` are under the control of the **libpcap** library.
It seems that the pcap library does not recognize **ens802f1** as a network device, and this is why you have no handle on it.
Which kind of device is it ? What _ifconfig_ says about it ?

**Comment by 490** [comment]
ens802f1 is a `Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)`,eno1 is a `Intel Corporation I210 Gigabit Network Connection (rev 03)`.I tried both of them and "No such file or directory"
$ **ifconfig**
`eno1`: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.254.13.19  netmask 255.0.0.0  broadcast 10.255.255.255
        inet6 fe80::b83e:65b7:80fd:f900  prefixlen 64  scopeid 0x20<link>
        ether a4:bf:01:0f:d3:09  txqueuelen 1000  (Ethernet)
        RX packets 856855  bytes 301551852 (287.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 869873  bytes 282663871 (269.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xd1c00000-d1c7ffff
`ens802f1`: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::65a0:f65e:6c13:e16c  prefixlen 64  scopeid 0x20<link>
        ether 90:e2:ba:32:c1:a1  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 23600  bytes 1840800 (1.7 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by kYroL01** [comment]
Hi @490 
Unfortunately this is not a nDPI issue. It seems that your device `ens802f1` has some problem with _libpcap_ but I don't know how to help you from my side.
Have you tried if there's something in your configuration that avoid the correct work with the library ?
Try **ethtool** to see config
Look also [here](https://communities.intel.com/message/431540#431540)

For your second question, why don't you use PF_RING instead of DPDK ? http://www.ntop.org/pf_ring/pf_ring-dnalibzero-vs-intel-dpdk/
Btw I don't know how DPDK is structured, but I think you need to create a boundary from pkts receiving from your NIC and the nDPI library to analize and detect pkts.

**Comment by 490** [comment]
thank you !

**Comment by rameesnajeeb** [comment]
using sudo before the ./ndpiReader -i enp0s3 -s 20 worked for me..!!
