### ISSUE TITLE
unable to detect bittorrent (upto 50% loss)

### ISSUE THREAD

**Issue by JeevanNailwal** [ntop/nDPI#362]
Hi All,
I was using ndpi_1.8-stable binary for my bittorrent data etection and figured almost 50% loss. Please find the attached logs, pcap file for your reference. Please let me know if you need any more information from my setup.

ndpiReader version:
jeevan@lap-jeevan:~/CODE/ndpi_1.8/nDPI$ ndpiReader -r
ndpiReader - nDPI (1.8.0-1.8-stable-467-6450ae2)
jeevan@lap-jeevan:~/CODE/ndpi_1.8/nDPI$ 

pcap files are in google drive:
https://drive.google.com/open?id=0B4M_moAIGLMSdVNhUW1sZzR1WU0
https://drive.google.com/open?id=0B4M_moAIGLMSaGt5SXhuUl9lZEU

[snapshot_ndpiReader.txt](https://github.com/ntop/nDPI/files/929855/snapshot_ndpiReader.txt)

**Comment by kYroL01** [comment]
Thanks for reporting. I'm going to investigate on it.

Thank you

**Comment by JeevanNailwal** [comment]
Hi Michele,
Did you get time to look at this issue?

**Comment by vel21ripn** [comment]
**download_bittorrent_3.pcapng**
IMHO This is encrypted BT. Cannot detect by content.

**Comment by kYroL01** [comment]
Yes I'm going to see now. I'll answer asap.
