### ISSUE TITLE
Invalid code in ndpi_util.c

### ISSUE THREAD

**Issue by Ravi-t** [ntop/nDPI#364]
In function named "packet_processing" line number 546, it will result in a crash 

 if(flow != NULL) {
    workflow->stats.ip_packet_count++;
    workflow->stats.total_wire_bytes += rawsize + 24 /* CRC etc */,
      workflow->stats.total_ip_bytes += rawsize;
    ndpi_flow = flow->ndpi_flow;
    flow->packets++, flow->bytes += rawsize;
    flow->last_seen = time;
  } else {
    return(flow->detected_protocol); **// This line will result in a crash as flow is NULL**
  }

**Comment by Ravi-t** [comment]
The function get_ndpi_flow_info always returns NULL value for fragmented packets because of following code at line 222 in ndpi_util.c

 if((iph->ihl * 4) > ipsize || ipsize < ntohs(iph->tot_len)
       || **(iph->frag_off & htons(0x1FFF)) != 0)**
      return NULL;

**Comment by kYroL01** [comment]
@Ravi-t I think you're right but i can fix later.
Please be patient, but thank you so much for this reporting.

**Comment by Ravi-t** [comment]
I think either ndpiReader should support fragments else in function "packet_processing" we should declare a new variable called nproto as
**struct ndpi_proto nproto = { NDPI_PROTOCOL_UNKNOWN, NDPI_PROTOCOL_UNKNOWN };**
and on line 546 return **nproto** instead of **flow->detected_protocol** to avoid the crash
so that it looks as

if(flow != NULL) {
    workflow->stats.ip_packet_count++;
    workflow->stats.total_wire_bytes += rawsize + 24 /* CRC etc */,
      workflow->stats.total_ip_bytes += rawsize;
    ndpi_flow = flow->ndpi_flow;
    flow->packets++, flow->bytes += rawsize;
    flow->last_seen = time;
  } else {
    **//return(flow->detected_protocol);
    return nproto;**
  }

**Comment by kYroL01** [comment]
You can also send a pull request if you prefer.
I'm watching later. Thanks
