### ISSUE TITLE
Protocols are not shown 

### ISSUE THREAD

**Issue by rubencitroxs** [ntop/nDPI#367]
Dear:
 
Protocols are not shown in the "Recent active flows" tab.
Are shown as unknown
 
Versions:
NProbe v.7.5.170330
Ntopng x86_64 v.2.5.170330

The problem is with nDPI, when viewing reports via ntopng, all protocols are not displayed.
-example:
Youtube
Whatsapp
Instagram

I attach the catch because it was not possible by this means
https://we.tl/pUAuyKxeNn

![image](https://cloud.githubusercontent.com/assets/27857718/25287972/e372a98e-2699-11e7-9a17-64d32e8d76fa.png)

![image](https://cloud.githubusercontent.com/assets/27857718/25288002/fb1dd6da-2699-11e7-8bf8-71ebb94bc2c6.png)

**Comment by kYroL01** [comment]
Hi @rubencitroxs . I tried your pcap but it seems corrupted and I cannot open it both ndpiReader and Wireshark.
Can you send again please ?
So, you told us in your traffic there are flows of Youtube Whatsapp and Instagram that are not show because are you sure the traffic of these protocols **are** present, right ?
I need a good pcap to fix the problem.
Thanks.

**Comment by rubencitroxs** [comment]
Hello

If I am sure that the traffic of these protocols is present.
I attach the new catch.
I have another query, how are web pages visited by a host?
example:
![image](https://cloud.githubusercontent.com/assets/27857718/25535050/34c901f8-2c0c-11e7-8adf-62381a133883.png)



-Do you have to buy another license? DNS plugins?

-I attach the catch because it was not possible by this means
https://wetransfer.com/downloads/86b47d36d611aaf50d1e8da25995374f20170428151937/2db1c6

**Comment by kYroL01** [comment]
@rubencitroxs For every question concerning ntopng, open issue on ntopng issue page.
From you screenshot i just give you one error about the github.com not detected well, but is impossibile to detect correctly ALL the DNS query.
After checking your pcap I can understand better, anyway.

**Comment by rubencitroxs** [comment]
Did you see the catch?
Any solution?

**Comment by kYroL01** [comment]
Yes I saw the pcap and IMHO there is nothing strange.
I saw different detection from your screenshot; are u sure you have upgrade nDPI and ntopng correctly ?
Look:

![img](https://cloud.githubusercontent.com/assets/7222956/25621855/eb0fe744-2f52-11e7-9f29-d609f6462980.png)

**Comment by rubencitroxs** [comment]
Yes, follow the steps that show me emanuel

I strongly suggest you to upgrade to the nightly builds of ntopng and nProbe, which will likely solve your issues.

For the update you will need to flush your existing ntopng data. If you accept this, please follow these steps for the update:

1) stop ntopng: systemctl stop ntopng
2) stop nprobe
3) flush data: sudo rm -rf /var/tmp/ntopng && redis-cli flushall
4) update ntopng and nprobe to the nightly versions using the instructions at this link http://packages.ntop.org/
5) start nprobe and ntopng

![image](https://cloud.githubusercontent.com/assets/27857718/25622273/497e3110-2f2a-11e7-9054-6f07be5d6eab.png)

These data do not appear to me

![image](https://cloud.githubusercontent.com/assets/27857718/25622357/847cdd34-2f2a-11e7-8b45-099e47e724f1.png)

any ideas ?

**Comment by kYroL01** [comment]
Look at the result, there is a lot of **Unknown** pkts because I think you are under a VLAN and there are lots of broadcast messages (255.255.255.255) and all of these pkts cannot be detected different from **Unknown**.
Another thing: there are hundreds of **HTTP**, but with private IP adresses (_192.168.0.33_ or _192.168.0.25_) and examining the flows, this is only generic pkts so nDPI correctly detect as HTTP but there is no other informations.

**Comment by kYroL01** [comment]
Are u using a VLAN ? If yes, How can u use it with nProbe ?

**Comment by rubencitroxs** [comment]
We actually have a VLAN segment, but it is not published in NTOP. Should not be seen.
Private addresses 0.25 (server ntop, nprobe), and 0.33 is my computer on which I work.

**Comment by kYroL01** [comment]
IMHO the pcap you sent us is different from the traffic you show in the screenshot (i.e. I can't see any ip addr == `138.255.97.14` while in yours it's show).
So maybe is a different pcap or you catch the traffic in a different way.

**Comment by rubencitroxs** [comment]
Traffic capture with tcpdump, from ntop
Tcpdump -i eth0 -w /tmp/ntop.pcap

**Comment by kYroL01** [comment]
Can you pass the screenshot of the traffic detected by ndpiReader ?

**Comment by rubencitroxs** [comment]
![image](https://cloud.githubusercontent.com/assets/27857718/25624006/8e45eb4a-2f2e-11e7-865c-c3124687c562.png)
![image](https://cloud.githubusercontent.com/assets/27857718/25624053/af29ec3a-2f2e-11e7-8172-761407a76e1c.png)
![image](https://cloud.githubusercontent.com/assets/27857718/25624167/f3bfd080-2f2e-11e7-9480-f6a83c0b0d8f.png)

**Comment by kYroL01** [comment]
So, what's the problem with this detection ? It seems that the traffic detection  is correct, isn't it ?

**Comment by rubencitroxs** [comment]
Sure, but the main problem is that it does not recognize YOUTUBE traffic.
Never shown. en la pestaña FLOW/Application

**Comment by rubencitroxs** [comment]
And neither the "URLs" that enter the HOST

**Comment by kYroL01** [comment]
Do me a big favour: provide a pcap with **ONLY** a good **Youtube** traffic, so I could understand better. 
Thanks

**Comment by rubencitroxs** [comment]
Dear
Does it serve you if you are a specific host to have only youtube traffic?

example
Tcpdump -i eth0 src 192.168.0.X -w /tmp/ntop.pcap

**Comment by kYroL01** [comment]
Tcpdump cannot filter by application. Is like Wireshark, is a packet analyzer.
Filter for private ip address doesn't mean anything in this case.
So, if you wanna catch only Youtube traffic, launch tcpdup on your `eth0` and generate YouTube traffic opening ONLY YouTube (no other pages or torrent or anything could be mix the traffic).

**Comment by rubencitroxs** [comment]
If I understand, I attach the catch

https://wetransfer.com/downloads/1c276d57dc1397920d53014fc56b51ff20170502154439/75bf556f61238cbd8a4b039f6ab024cb20170502154439/0aafdd?utm_campaign=WT_email_tracking&utm_content=general&utm_medium=download_button&utm_source=notify_recipient_email

**Comment by kYroL01** [comment]
It's _impossibile_ to detect YouTube with these kind of pcap.
Seeing your results, every "server" IP address is Multicast address (in the range `224.0.0.0 - 239.255.255.255`) so it's impossible to have any hostname match with the real server of YT (because YT could be detected by IP address or host name).
I think the problem is not the nDPI detection but your nProbe/ntop environment. At this point I think you need a plugin for nProbe but I'm not so sure.
