### ISSUE TITLE
View pages visited by a host

### ISSUE THREAD

**Issue by rubencitroxs** [ntop/nDPI#369]
How can I view pages visited by a host? 
example
![image](https://cloud.githubusercontent.com/assets/27857718/25540842/d6069e3e-2c22-11e7-9eaa-2ecc1f304e37.png)

My ntop does not show me that information.

**Comment by kYroL01** [comment]
You open again in nDPI. Open here https://github.com/ntop/ntopng/issues

**Comment by rubencitroxs** [comment]
Dear 

 

 

Because they closed the subject?

 

Saludos cordiales:

Rubén Sáez
Ingeniero de Proyectos
Axia Tecnología Limitada
San Diego 630 Oficina 42
Santiago Centro – Chile
56-2- 5626735  -  9-73928636
 <mailto:rsaez@axia.cl> rsaez@axia.cl
 <blocked::blocked::blocked::http://www.axia.cl/> www.axia.cl

 

De: Michele Campus [mailto:notifications@github.com] 
Enviado el: viernes, 28 de abril de 2017 15:31
Para: ntop/nDPI
CC: rubencitroxs; Author
Asunto: Re: [ntop/nDPI] View pages visited by a host (#369)

 

Closed #369 <https://github.com/ntop/nDPI/issues/369> .

**Comment by kYroL01** [comment]
Because this is a question for **ntopng**, not **nDPI**.
Open this issue HERE https://github.com/ntop/ntopng/issues

Thank you
