### ISSUE TITLE
Need help on SSL certificate

### ISSUE THREAD

**Issue by subhedarnikhil** [ntop/nDPI#373]
Hi All,

I  need a small information  to take the host name from SSL certificate.

Currently we are reading the SSL certificate and from that we are extracting the host name.

I  have a access point on which i am trying to port the nDPI library.
Below  is the topology.

Wireless client -------- Access point-------- External network

If the SSL certificate is coming for the Wireless client then , can nDPI library on Access point will be able to read the SSL certificate to  extract the host name ....????

Regards,
Nikhil

**Comment by kYroL01** [comment]
Hi @subhedarnikhil 
Yes, why not ? nDPI could extract host name from certificate thanks to **SSL dissector**.
I think you have no problem in this environment.

Regards
