### ISSUE TITLE
Do you have any options to detect nDPI version from source code?

### ISSUE THREAD

**Issue by pavel-odintsov** [ntop/nDPI#376]
Hello!

I just discovered that you changed API and my code:
```
    struct ndpi_detection_module_struct* my_ndpi_struct =
        ndpi_init_detection_module(detection_tick_resolution, malloc, free, debug_printf);
```

Is not working anymore.

So I have a question. How could I detect nDPI version to use a different syntax from some recent version and prefer to use old syntax for old versions?

I'm looking for something like:
```

#define NDPI_MAJOR 1
#define NDPI_MINOR 8
#define NDPI_PATCH 0
```

**Comment by kYroL01** [comment]
Hi @pavel-odintsov .

Actually I think you refering to a very old API. I checked where that function is changed but I think the old API is in 1.7 or older, isn't it ?

What is in this [implementation](https://github.com/ntop/nDPI/blob/442adce51db0b3fd9fdfe9f80df9e3cb767414c1/src/lib/ndpi_main.c#L1809) that break your code ?
I think the params passed to the old function now are inside the new API.

Can u address me to an old commit where the function is called in the way you show ?

Thanks

**Comment by pavel-odintsov** [comment]
Hello!

I think I have actual commit number: https://github.com/ntop/nDPI/commit/22e03ee98a07cce4a58b38b97860f56541ab82d9 

My tools work in a very wide range of distros and I would like to use ifdef to support old 1.7 version because old centos/debian distros use it but I also want to support new version with new API and I looking for options to implement it.

**Comment by kYroL01** [comment]
We have to discuss about it.

**Comment by pavel-odintsov** [comment]
Hello!

Do you have some updates about it?

**Comment by kYroL01** [comment]
Hi @pavel-odintsov . Actually we are very busy and we don't have discussed about it yet.
Hope to do asap.
Thanks

**Comment by subritm** [comment]
Hello, 

Executing ndpiReader, it gives some version number. I think @pavel-odintsov wants something similar.

./ndpiReader 
Welcome to nDPI 2.1.0-922-1a605e2

**Comment by subritm** [comment]
or ./ndpiReader -r also gives the ndpi version and git revision number

**Comment by kYroL01** [comment]
@lucaderi What do u think about this ?

**Comment by bdrung** [comment]
That doesn't really help. The version information is needed on compile time in a deterministic way. Having a header that defines the major and minor version number is much more usable than needing to run a shell command, parse the output to extract the major and minor and then set a flag for compilation.

**Comment by pavel-odintsov** [comment]
Yes, indeed. We need version in geaders to use it in ifdef constructions

**Comment by lucaderi** [comment]
@pavel-odintsov Sorry for taking so long, however what you asked has been implemented.

**Comment by pavel-odintsov** [comment]
Thanks!
