### ISSUE TITLE
Snapchat detection

### ISSUE THREAD

**Issue by stathisgotsis** [ntop/nDPI#378]
Hi,

Snapchat does not seem to be properly detected using the latest version of ndpi. I suppose this is related to QUIC protocol now being used by snapchat.
[Snapchat_1_anon.zip](https://github.com/ntop/nDPI/files/1007452/Snapchat_1_anon.zip)
[Snapchat_2_anon.zip](https://github.com/ntop/nDPI/files/1007455/Snapchat_2_anon.zip)

BR,
Stathis

**Comment by kYroL01** [comment]
I'll check.
Thanks

**Comment by kYroL01** [comment]
Fixed https://github.com/ntop/nDPI/commit/ebb6d4499ae2ab9f474318fca08326609440e91c
Thanks
