### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by HaochuanXJTU** [ntop/nDPI#384]
How can I test the accuracy of ndpi, do you have some benchmark?

**Comment by kYroL01** [comment]
Hello @HaochuanXJTU .
We don't have special benchmark.
I think the best way is created a properly environmet and test result on any protocols you want to verify.
Do you thought about it ?

**Comment by kYroL01** [comment]
If your doubt is about the performance between nDPI and other tools for packet inspection, I suggest you to read [this](http://vbn.aau.dk/files/179043085/TBU_Extended_dpi_report.pdf).
You can see nDPI obtains the best score ;)
