### ISSUE TITLE
Office 365 detection- Added changes for detection

### ISSUE THREAD

**Issue by subritm** [ntop/nDPI#387]
FYI
While testing office 365, found that its not getting detected.

I added these domins and I can see its getting detected properly
src/lib/ndpi_content_match.c.inc

> +   { ".microsoftonline.com",           "OFFICE_365",           NDPI_SERVICE_OFFICE_365, NDPI_PROTOCOL_ACCEPTABLE },
> +   { ".office365.com",                 "OFFICE_365",           NDPI_SERVICE_OFFICE_365, NDPI_PROTOCOL_ACCEPTABLE },
> +   { ".office.com",                    "OFFICE_365",           NDPI_SERVICE_OFFICE_365, NDPI_PROTOCOL_ACCEPTABLE },
> +   { ".msocsp.com",                    "OFFICE_365",           NDPI_SERVICE_OFFICE_365, NDPI_PROTOCOL_ACCEPTABLE },
> +   { ".msocdn.com",                    "OFFICE_365",           NDPI_SERVICE_OFFICE_365, NDPI_PROTOCOL_ACCEPTABLE },

Thanks

**Comment by kYroL01** [comment]
Hi @subritm Thanks for reporting this!
I'll update asap.
Thank you

**Comment by kYroL01** [comment]
https://github.com/ntop/nDPI/commit/d17ea73273eacf4044759fe4e563e96a8195ffdd
