### ISSUE TITLE
nDPI hangs in some packets

### ISSUE THREAD

**Issue by Skryabind** [ntop/nDPI#39]
Function ndpi_detection_process_packet hangs when process the packet mpegts.
Captured packet:
https://dl.dropboxusercontent.com/u/5135944/Github/mpegts.cap
This problem occur in version 1.6.1. Version 1.5.1 works normally.

**Comment by lucaderi** [comment]
@Skryabind See https://github.com/ntop/nDPI/commit/7e28cc0981dfcbbea9a08fd622a408f16184347a
Don't forget to star nDPI on github :-)
