### ISSUE TITLE
Data analysis in different packets.

### ISSUE THREAD

**Issue by max197616** [ntop/nDPI#392]
Hi,

Can the nDPI extract data (for example http) from different packets within the same tcp session?
For example, in the first packet:
GET /test.html HTTP1/1\r
In the second packet:
\nHost: example.com\r\n\r\n

Thanks.

**Comment by kYroL01** [comment]
Every packet is analyzed regardless the other, but two packets could belong to the same flow.
So, if we have two HTTP packets, nDPI extract all possibile information from both pkts.
You cannot choose "from this pkt i want to extract only URL and from the other Host".
