### ISSUE TITLE
Google Drive is detected

### ISSUE THREAD

**Issue by subhedarnikhil** [ntop/nDPI#393]
Hi I have seen that Google drive traffic is not detected by nDPI.

Do we need to implement the supoort for the same..???

Regards,
Nikhil

**Comment by kYroL01** [comment]
Hi @subhedarnikhil . Provide a pcap with Google Drive traffic and share with us.

Thanks

**Comment by kYroL01** [comment]
This issue refers to this https://github.com/ntop/nDPI/issues/126
