### ISSUE TITLE
need to extract linkedin,Soundcloud and google photo.

### ISSUE THREAD

**Issue by subhedarnikhil** [ntop/nDPI#396]
Hi 
Looks like we need to classify the https  flows such as Linkedin ,google photo .
Since both of them uses dst port as 443 . 
Currently i am working on that  and just wanted to check that currently Linkedin and google photo are part of SSL flows..????

Regards,
Nikhil

**Comment by kYroL01** [comment]
As for all the Google "suite" we need just to add the server name of their services [here](https://github.com/ntop/nDPI/blob/dev/src/lib/ndpi_content_match.c.inc) to perform pattern matching string. nDPI already etract server name (and in general host name) from SSL or HTTPS in order to classify encripted protocol flows.

For Linkedln I think is the same things, but I need to check. I catch a pcap to see it.
Thanks.

**Comment by subhedarnikhil** [comment]
So can i add one more TCP handler for linkedin and soundcloud..????

**Comment by kYroL01** [comment]
Sure, look at https://github.com/ntop/nDPI/blob/dev/src/lib/ndpi_content_match.c.inc to put string refers to a server name or ip-range address. Then send a pull request and I'll check it correctness.

**Comment by subhedarnikhil** [comment]
In this scenario do i need to add only servername or do i need to add the ip address as well..????

**Comment by kYroL01** [comment]
You can add both if you are sure that also IP-address i for that domain.
For Drive I already do this https://github.com/ntop/nDPI/commit/39dc99443cf60c2daa859d77c59b811a4aad4243

**Comment by subhedarnikhil** [comment]
Okay , tell me one thing how i can send you a git pull request..????

**Comment by kYroL01** [comment]
Read this https://help.github.com/articles/creating-a-pull-request/
When you send I'll check if everything is ok.

**Comment by subhedarnikhil** [comment]
Hi,

I have sent an pull request please check the code and proceed further.

**Comment by subhedarnikhil** [comment]
Hi  kYroL01 ,
Looks  like i am confused in the git pull request.
Just now i  have checked out the latest code and merged my changes .

Please find attached zip  files with this comment .
Please  let me know which branch
[soundclound.zip](https://github.com/ntop/nDPI/files/1070343/soundclound.zip)
 should i mention in my next pull request.

**Comment by subhedarnikhil** [comment]
Hi kYroL01,
When my code will get added to the dev branch????

Regards,
Nikhil

**Comment by kYroL01** [comment]
Hello. Please be patient for a day. I'll do the work asap.
Thanks

**Comment by kYroL01** [comment]
LinkedIn here https://github.com/ntop/nDPI/commit/5e2f75f5f02efcaac4aca57c40fb838ddd45df68#diff-37f0ad94bbd32b9fbff7d75f1307c652R8294
