### ISSUE TITLE
nDPI does not work at all with iptables while ndpiReader works?

### ISSUE THREAD

**Issue by hrhasani** [ntop/nDPI#397]
I compiled ndpi_netfilter and made it's kernel module(and load it!). When I add some simple filter to drop ftp, http it doesn't work, but when I run ndpiReader it's detect everything correctly! What is the problem? I add an iptables rule like this:
`
iptables -I FORWARD -m ndpi --http -j DROP
`

also I add another simple rules in POSTROUTING but it didn't work too!

**Comment by kYroL01** [comment]
Hi @hrhasani . I think the problem is just because nDPI does not have the kernel support anymore. If you wanna continue to use it, looking for parallel fork project that continue in that direction.
https://github.com/betolj/ndpi-netfilter

**Comment by hrhasani** [comment]
Hi @kYroL01. I exactly used that project to use nDPI in iptables. But the problem is that the ndpiReader worked fine for me, but the ndpi-netfilter didn't!

**Comment by kYroL01** [comment]
I understand it and I'm sorry for it, but we don't provide to keep the netfilter part anymore. I think you have to speak with the developer who continue to works with netfilter. If ndpiReader works fine, the problem is on the netfilter side.

**Comment by hrhasani** [comment]
Ok, thanks

**Comment by kYroL01** [comment]
You're welcome
