### ISSUE TITLE
Add a way to properly check IPv6 address to classify protocols

### ISSUE THREAD

**Issue by kYroL01** [ntop/nDPI#399]
Recently I see that an increasing number of protocols don't match the IPv6 range that could allow to classify applications.
The best way is to implement a similar things as https://github.com/ntop/nDPI/blob/dev/src/lib/ndpi_content_match.c.inc#L23, but with only IPv6 addresses to keep things clear and sorted.
For example `2a00:1450:400d:806::2001` is a Google server address but nDPI classify it just as SSL.

**Comment by IvanNardi** [comment]
Done
