### ISSUE TITLE
Whatsapp detection doesn't work

### ISSUE THREAD

**Issue by pechy** [ntop/nDPI#400]
Whatsapp (mobile Android APP) is not detected in recent nDPI version.

I see several reasons for this:
- WhatsApp uses more IP adresses and ranges then stated in [ndpi_content_match.c.inc](https://github.com/ntop/nDPI/blob/dev/src/lib/ndpi_content_match.c.inc#L80). The IP used in my case (169.55.67.244) isn't catched by this filter. See that the DNS query before, it returns more IP addresses, so there is more that is used by WA. There is a lot of IP ranges assigned to WA looking into RIPE database.
- WA protocol changed. The detection here: [src/lib/protocols/ssl.c#L590](https://github.com/ntop/nDPI/blob/cd26942edf5686455f051205e5c3454588d7409a/src/lib/protocols/ssl.c#L590) doesn't catch it. In pcap/wireshark I'm seeing that the payload of the initial WA packets is just 4 bytes long, and it is 'WA\0x02\0x00'. The numbers after 'WA' part might vary I guess (depending on version).

See attached recorded initiation of WA. I didn't know how to anonymize pcap file, so I exported dissection from wireshark (with bytes) into text file, I hope you won't mind. I can provide the pcap file if needed.
[WA_pcap.tar.gz](https://github.com/ntop/nDPI/files/1060608/WA_pcap.tar.gz)

**Comment by kYroL01** [comment]
Thank you very much. I'm look at it asap!
Provide a pcap it will be always the best way.

**Comment by pechy** [comment]
Hello,
attached you can find pcap file.
[wa_anon.zip](https://github.com/ntop/nDPI/files/1061108/wa_anon.zip)

**Comment by kYroL01** [comment]
first commit https://github.com/ntop/nDPI/commit/e0366a99653debd29d57aae3ac81a0559a5434fb

**Comment by kYroL01** [comment]
second commit https://github.com/ntop/nDPI/commit/af3086fb82e4c4622e10370ab092822e55fb6716

Please check if now WA is correctly detected.
Thanks

**Comment by kYroL01** [comment]
Other tests show the issue seems to be solved. Reopen if necessary

**Comment by SoftnauticsLtf** [comment]
Looks like something is changed again and detection is not working properly.
I captured pcap and used in reader and seems some of packets are categorized as unknown which belongs to whatsapp.

@kYroL01 can you please have a look into this.
Let me know if anything needed more.
@pechy can you please re-open this issue.
[whatsapp.zip](https://github.com/ntop/nDPI/files/1302080/whatsapp.zip)

**Comment by SoftnauticsLtf** [comment]
@kYroL01 @pechy can you please look into it.

**Comment by kYroL01** [comment]
@kishan-sib Sorry, I didn't see the comment. Of course, I'll check asap

**Comment by SoftnauticsLtf** [comment]
Hi @kYroL01 , 
Any updates?
