### ISSUE TITLE
Does Lync with TLS detection support？

### ISSUE THREAD

**Issue by YumingMa** [ntop/nDPI#401]
the lync with TLS detection doesn't  work via my test.there is the code about lync in the source code, but there is not LYNC protocols in the supported list. could you help me confirm the question，please?  I will upload the packets tomorrow. 
Thanks in advance!

**Comment by kYroL01** [comment]
Hi @YumingMa I checked and yes, Lync is present in the list of protocols but it seems a proper detection is missing. Maybe is an old protocol deleted not correctly.
If you share a pcap we provide to put inside in the best way.
Thanks

**Comment by YumingMa** [comment]
[lyn.zip](https://github.com/ntop/nDPI/files/1062796/lyn.zip)
I uploaded the lync pcap. Thanks. If any questions, please contact me.

**Comment by kYroL01** [comment]
Thank you!

**Comment by YumingMa** [comment]
Any updates?
Could you provide the best way to support Lync detection. Though it is an old protocol, but many people use it. so I think we should support it ASAP. I can try to code.

**Comment by kYroL01** [comment]
Hi @YumingMa I ask you to be patient but in a couple of day I'll provide the code. No problem if it's an old protocol. If people use its usefull.

**Comment by kYroL01** [comment]
HI @YumingMa . Check your pcap I see many traffic on many ports, but the only things I can understand looking on Internet about Lync is that it use for sure the `TCP port 5061` for Skype; the others are variables.
Again, extract server name from TLS certificate does not give us much information. I need more informations or additional hints to have a good classification of this protocol. Can you give me any support on this ?
Thanks

**Comment by YumingMa** [comment]
I am so sorry.  I can't have other support. I only uploaded another pcap. I think we can have a good classification of this protocol based on port 5061 and  matching "lync"  in server name field now.  If we meet new detection missing of this in the future, we could add new code to fix it.
Thanks

**Comment by YumingMa** [comment]
[lync2.zip](https://github.com/ntop/nDPI/files/1066584/lync2.zip)

**Comment by kYroL01** [comment]
Ok thanks. I'll see what shall I do as better as I can.

**Comment by YumingMa** [comment]
I found we should parse data pactet to detect lync data stream. so the prot shouldn't  be  5061. We should check other prots stream.

**Comment by kYroL01** [comment]
Which kind of data packets ? We just parse not encrypted payload.

**Comment by YumingMa** [comment]
I want to detect data stream over lync.  For example, I chats by lync, we could detect the chat stream as lync . It seems more difficult.

**Comment by kYroL01** [comment]
I'm trying to see if it's possibile

**Comment by kYroL01** [comment]
I think the detection could be improved. I'm going to see deeply.

**Comment by YumingMa** [comment]
I think you are right. the old code doesn't support it over tcp and can't detect it over udp. I only fix them. you can check  the document named MS-ICE2. So I also think my patch could merge.
[[MS-ICE2].pdf](https://github.com/ntop/nDPI/files/1086687/MS-ICE2.pdf)

**Comment by YumingMa** [comment]
Thanks. I still work on this case in the furture.

**Comment by kYroL01** [comment]
You're welcome.
