### ISSUE TITLE
Different results from linking with apt package lib / compiled lib

### ISSUE THREAD

**Issue by nikofil** [ntop/nDPI#403]
Hello!
I am writing some code that uses nDPI. It's based on https://github.com/caesar0301/pcapdpi/blob/master/pcapReader.c and I've noticed the behavior changes depending on how I link the nDPI library. The file I'm compiling is the same as the one above, but I removed the linux_compat.h include and I changed the ndpi_main.h include to ``#include <libndpi-1.7.1/libndpi/ndpi_main.h>``. You can see the difference below: if I link with the library from the apt package (I've tried this on Ubuntu Zesty and Yakkety) then one flow from the http.cap file (downloaded from the Wireshark site) goes undetected. If however I compile the library myself and link with it then that flow gets detected. I've tried compiling it at the tags 1.8 and 1.7 and this difference in behavior between the package and source is consistent.
Maybe there is another change that I'm not aware of? This seems very strange to me.
Thanks!

```
~/w/dpitest ❯ gcc pcapReader.c -lndpi -lpcap
pcapReader.c: In function ‘packet_processing’:
pcapReader.c:536:5: warning: ‘return’ with no value, in function returning non-void
     return;
     ^
pcapReader.c:541:33: warning: ‘return’ with no value, in function returning non-void
   if(flow->detection_completed) return;
                                 ^
~/w/dpitest ❯ ./a.out -i /tmp/http.cap
Reading packets from pcap file /tmp/http.cap...

pcap file contains
	ip packets:   43            of 43 packets total
	ip bytes:     25091        
	unique flows: 3            
	guessed flow protocols: 0            


detected protocols:
	Unknown              packets: 34            bytes: 20695         flows: 1            
	DNS                  packets: 2             bytes: 277           flows: 1            
	HTTP                 packets: 7             bytes: 4119          flows: 1            


~/w/dpitest ❯ gcc pcapReader.c ../nDPI/lib/libndpi.a -lpcap
pcapReader.c: In function ‘packet_processing’:
pcapReader.c:536:5: warning: ‘return’ with no value, in function returning non-void
     return;
     ^
pcapReader.c:541:33: warning: ‘return’ with no value, in function returning non-void
   if(flow->detection_completed) return;
                                 ^
~/w/dpitest ❯ ./a.out -i /tmp/http.cap
Reading packets from pcap file /tmp/http.cap...

pcap file contains
	ip packets:   43            of 43 packets total
	ip bytes:     25091        
	unique flows: 3            
	guessed flow protocols: 0            


detected protocols:
	DNS                  packets: 2             bytes: 277           flows: 1            
	HTTP                 packets: 41            bytes: 24814         flows: 2
```

**Comment by kYroL01** [comment]
HI @nikofil
First of all, which version are you including with `-lndpi` ? Did you try to remove and recompile all after upgrade to the version `1.8` ?

**Comment by nikofil** [comment]
Hey!
I've tried the packages libndpi3 (on Ubuntu Yak) and libndpi4 (on Zesty) which, according to https://launchpad.net/ubuntu/+source/ndpi, contain versions 1.7.1 and 1.8.1. I've also tried compiling many different versions, and I've tried doing everything in containers to make sure there is no interference, but the same thing happens.

**Comment by kYroL01** [comment]
It seems the apt package are out of sync. Maybe there was additional fixes added later not include in the package from Ubuntu.
BTW the last stable version is `2.0` (see the branches).

**Comment by kYroL01** [comment]
Just a thing look at your code:
https://github.com/caesar0301/pcapdpi/blob/master/pcapReader.c#L536
i suggest you to to `return -1` (or other number different from `0`) to avoid warning.

**Comment by nikofil** [comment]
So turns out you were right, I was actually not compiling the older versions somehow, only >=2.0, while the packages were <=1.8. I have no idea how I missed it, I was 100% sure that I had tried older versions, but apparently it is version 2.0 that makes the difference, which isn't in any package yet.
Thank you for your time! I'm closing this issue now.

**Comment by kYroL01** [comment]
You're welcome!
