### ISSUE TITLE
No 2.0 tag

### ISSUE THREAD

**Issue by mamash** [ntop/nDPI#407]
Can you tag 2.0, please, so that source for 2.0 can be downloaded?

**Comment by kYroL01** [comment]
Did it.

Thanks

**Comment by mamash** [comment]
Thanks!

**Comment by mamash** [comment]
Actually, you seem to have tagged the latest commit as 2.0, but the codebase already references 2.1.0. Assuming 2.1.0 is not released yet, can you, please, re-tag with the specific commit that marked the 2.0 "release"?

Sorry to be such a drag. To paraphrase a well known quote, you keep using the 'tag' word, I do not think it means what you think it means. ;)

**Comment by mamash** [comment]
Looking at the history of configure.ac, it doesn't seem that you ever actually published a 2.0 release (that the changelog suggests), because the file went from 1.8.0 straight to 2.1.0.

Is 2.1.0 released then? I'm looking for a reliably tagged released nDPI that I can package to build ntopng-3.0 against. What do you suggest I use?

**Comment by kYroL01** [comment]
@mamash I think I fixed, look now I tagged the 2.0-stable (https://github.com/ntop/nDPI/commit/09c176576697f5dc8fc4c6340ba57127399c3eac) as u expected.
The 2.1.0 release is for the `dev` branch, but you can use it without problem with ntop 3.0

**Comment by dangbert** [comment]
@kYroL01  Why is 1.6 tagged as the latest release?
https://github.com/ntop/nDPI/releases

**Comment by kYroL01** [comment]
@danielengbert because nobody do that thing again. I have to do but not immediately.
