### ISSUE TITLE
make error while installing nDPI for ntop

### ISSUE THREAD

**Issue by ayeshabasit** [ntop/nDPI#411]
Here is my output, I installed pfring already as per instructions here http://www.ntop.org/get-started/download/

make all-recursive
make[1]: Entering directory '/root/nDPI'
Making all in src/lib
make[2]: Entering directory '/root/nDPI/src/lib'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/root/nDPI/src/lib'
Making all in example
make[2]: Entering directory '/root/nDPI/example'
/bin/bash ../libtool --tag=CC --mode=link gcc -pthread -g -O2 -static -ldl -o ndpiReader ndpiReader.o ndpi_util.o ../src/lib/libndpi.la /root/PF_RING/userland/libpcap/libpcap.a /root/PF_RING/userland/lib/libpfring.a -lnuma -lrt -ldl -lrt -ldl -lm
libtool: link: gcc -pthread -g -O2 -o ndpiReader ndpiReader.o ndpi_util.o ../src/lib/.libs/libndpi.a /root/PF_RING/userland/libpcap/libpcap.a /root/PF_RING/userland/lib/libpfring.a -lnuma -lrt -ldl -lm -pthread
/usr/bin/ld: cannot find -lnuma
collect2: error: ld returned 1 exit status
Makefile:393: recipe for target 'ndpiReader' failed
make[2]: *** [ndpiReader] Error 1
make[2]: Leaving directory '/root/nDPI/example'
Makefile:462: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/nDPI'
Makefile:371: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by kYroL01** [comment]
@ayeshabasit It seems very strange that does not find ndpiReader.
Are u sure you did all steps correctly ?
Try do re-do all doing `./autogen.sh` before `./configure` if you didn't do it.

**Comment by kYroL01** [comment]
Any news ?

**Comment by kYroL01** [comment]
I closed now. Open if necessary

**Comment by ayeshabasit** [comment]
Hi, I did ./autogen.sh and ./configure but the results are the same :( 

Also, what directory should I git clone all of these (pf ring, dpi, etc)? I did them at root, but that does not feel right.

**Comment by kYroL01** [comment]
I think the problem is the **root** directory. Why you placed there ? Try to do all in a different folder.
If you install these libraries from source code I suggest you to do under your home space.
Try to install correctly nDPI in a different place:

1. `git clone https://github.com/ntop/nDPI.git` (on the branch you prefer, i suggest dev that is the upgradest)
2. `./autogen.sh`
3. `./configure`
4. `make`

**Comment by ZeeshanSultan** [comment]
Didn't work tried doing this

**Comment by kYroL01** [comment]
@ZeeshanSultan this is the only way you can clone and compile nDPI succesfully.
What's your status if you do these commands ?
Thanks

**Comment by ZeeshanSultan** [comment]
The makefile was incomplete. i tried to remove all-am subsection and the example app compiled just fine.
Thanks

**Comment by dsokoloski** [comment]
Wasn't the initial error message simply stating that libnuma was not found on your system and so ndpiReader couldn't be linked?
