### ISSUE TITLE
How to extract mac address using nDPI?

### ISSUE THREAD

**Issue by ArslanSaleem** [ntop/nDPI#416]
Hi,
I am trying to find the mac address of source but i didn't find documentation or source code to extract mac address.Is it possible to get mac address using nDPI?

**Comment by kYroL01** [comment]
Actually the library don't use a specific API to do this. the MAC address is matched during the analysis of ethernet header in https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_typedefs.h#L121 you can see:

```
struct ndpi_ethhdr
{
  u_char h_dest[6];       /* destination eth addr */
  u_char h_source[6];     /* source ether addr    */
  u_int16_t h_proto;      /* data length (<= 1500) or type ID proto (>=1536) */
}
```

Do u think it could be a good feature to add ? How you use the MAC addresses extracted? 
Thanks

**Comment by ArslanSaleem** [comment]
Yes, i tried the above approach but getting unknown characters. Below is the code that i used alongwith the outputs.
1. 
`void packet_handler(u_char *args,const struct pcap_pkthdr* packet_header,const u_char* packet)
{
ethernet = (struct ndpi_ethhdr *) packet;
printf("Dest from ethHdrC: %s\n", ethernet->h_dest);
}`
output:
`Dest from ethHdrC: �������R��##`

Another i used another approach to parse it to character below is the source code and output of it.
2.
`void packet_handler(u_char *args,const struct pcap_pkthdr* packet_header,const u_char* packet)
{
ethernet = (struct ndpi_ethhdr *) packet;
char * eth_hdest= ether_ntoa(ethernet->h_dest);
printf("Dest from ethHdrC: %s\n", eth_hdest);
}`
output:
`Segmentation fault(core dumped)`

Any help related to this issue?

**Comment by kYroL01** [comment]
Hi @ArslanSaleem Your code is wrong. Try this:

```
void packet_handler(u_char *args, const struct pcap_pkthdr* packet_header, const u_char* packet) { 
       ethernet = (struct ndpi_ethhdr *) &packet;
       printf("Mac Address SRC: %s", ether_ntoa((struct ether_addr*) ethernet->h_source));
       printf("Mac Address DST: %s", ether_ntoa((struct ether_addr*) ethernet->h_dest));
}
```

I tested and it works.

**Comment by ArslanSaleem** [comment]
It worked thanks

**Comment by androuxx** [comment]
in which file and line i need to add this code to print the mac address ?
 and how i can print the timestamp of the packets  also?
