### ISSUE TITLE
Compile error on OpenBSD 6.1

### ISSUE THREAD

**Issue by kakadoo** [ntop/nDPI#417]
hi

i get this error 

`
Making all in example
depbase=`echo ndpiReader.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; gcc -DHAVE_CONFIG_H -I. -I..  -I../src/include    -pthread  -g -O2 -MT ndpiReader.o -MD -MP -MF $depbase.Tpo -c -o ndpiReader.o ndpiReader.c && mv -f $depbase.Tpo $depbase.Po
ndpiReader.c:65: error: '_bpf_filter' redeclared as different kind of symbol
/usr/include/net/bpf.h:301: error: previous declaration of '_bpf_filter' was here
*** Error 1 in example (Makefile:406 'ndpiReader.o')
*** Error 1 in . (Makefile:485 'all-recursive')
*** Error 1 in /usr/src/nDPI (Makefile:369 'all')
`

it is possible to fix ?

holger

**Comment by kYroL01** [comment]
Test if this solved the problem, thanks

**Comment by kakadoo** [comment]
hi

now i get
`
Making all in example
depbase=`echo ndpiReader.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; gcc -DHAVE_CONFIG_H -I. -I..  -I../src/include    -pthread  -g -O2 -MT ndpiReader.o -MD -MP -MF $depbase.Tpo -c -o ndpiReader.o ndpiReader.c && mv -f $depbase.Tpo $depbase.Po
ndpiReader.c: In function 'parseOptions':
ndpiReader.c:452: error: lvalue required as left operand of assignment
ndpiReader.c: In function 'configurePcapHandle':
ndpiReader.c:1950: warning: passing argument 3 of 'pcap_compile' from incompatible pointer type
*** Error 1 in example (Makefile:406 'ndpiReader.o')
*** Error 1 in . (Makefile:485 'all-recursive')
*** Error 1 in /usr/src/nDPI (Makefile:369 'all')
`
holger

**Comment by kYroL01** [comment]
What about after this https://github.com/ntop/nDPI/commit/c5bc91145f9ce6553678b1ea3a6c0ddc1e6afdfb ?

**Comment by kakadoo** [comment]
hi

next new error after git pull,

`
Making all in example
depbase=`echo ndpiReader.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; gcc -DHAVE_CONFIG_H -I. -I..  -I../src/include    -pthread  -g -O2 -MT ndpiReader.o -MD -MP -MF $depbase.Tpo -c -o ndpiReader.o ndpiReader.c && mv -f $depbase.Tpo $depbase.Po
ndpiReader.c: In function 'parseOptions':
ndpiReader.c:452: error: lvalue required as left operand of assignment
ndpiReader.c: In function 'configurePcapHandle':
ndpiReader.c:1950: warning: passing argument 3 of 'pcap_compile' from incompatible pointer type
*** Error 1 in example (Makefile:406 'ndpiReader.o')
*** Error 1 in . (Makefile:485 'all-recursive')
*** Error 1 in /usr/src/nDPI (Makefile:369 'all')

`

holger

**Comment by kYroL01** [comment]
Can you please told me the version of the compiler you used in OpenBSD ?

**Comment by kYroL01** [comment]
Nevermind the compiler question. I think I fixed.

https://github.com/ntop/nDPI/commit/6d7f5552de5cf88a6dc994b0d2a93dadbbe23509

**Comment by kakadoo** [comment]
hi
make  are now successful just some warning
` warning: sprintf() is often misused, please use snprintf()`

thanks you .

i will now start the installation and test on a active openbsd firewall

holger
