### ISSUE TITLE
Getting error after installing.

### ISSUE THREAD

**Issue by GMarciales** [ntop/nDPI#418]
I am running WireShark 2.2.6 on Ubuntu 16.04 LTS and OS-X 10.12.5, both systems disabled the plugin due to a error when opening.

![screenshot from 2017-07-09 10-14-40](https://user-images.githubusercontent.com/15690019/27994739-48d4e37a-6491-11e7-9220-5c91a1dcc51d.png)
<img width="451" alt="screen shot 2017-07-09 at 10 15 12 am" src="https://user-images.githubusercontent.com/15690019/27994741-4cbe0dfe-6491-11e7-941c-518aa77c8b04.png">

**Comment by lucaderi** [comment]
@GMarciales Line 7 of ndpi.lua does not contain < that looks to me a git merge issue. Please clone nDPI again and it will work
