### ISSUE TITLE
L7 Apple detection (Protocol 140)

### ISSUE THREAD

**Issue by flepti** [ntop/nDPI#419]
On ntop flows, everything is associated with apple,
e.g.
Application: Skype.Apple
Dropbox.Apple
HTTP.Apple
SSL.Apple
DNS.Apple
And... on ndpi_content_match.c.inc, is it really 17.0.0.0/8?

**Comment by kYroL01** [comment]
Hi @flepti Can you provide a pcap to see this issue ?
Yes, the CIDR 17.0.0.0/8 is associated with Apple name server. We need to see deeply with a pcap.
this is what `whois` return:

> NetRange:       17.0.0.0 - 17.255.255.255
> CIDR:           17.0.0.0/8
> NetName:        APPLE-WWNET
> NetHandle:      NET-17-0-0-0-1
> Parent:          ()
> NetType:        Direct Assignment
> OriginAS:       
> Organization:   Apple Inc. (APPLEC-1-Z)

Thanks

**Comment by flepti** [comment]
Try this.
[dropbox.zip](https://github.com/ntop/nDPI/files/1140401/dropbox.zip)

**Comment by kYroL01** [comment]
Thanks. I'll let u know asap

**Comment by kYroL01** [comment]
Hi @flepti . Are u sure you sent me the correct pcap to investigate ? Because from this pcap I just see DropBox flows correctly detected by nDPI.

**Comment by flepti** [comment]
HI @kYroL01 . Setup is okay now, I tried reinstall ntopng the past few weeks and still apple protocol is everywhere. I tried to reinstall it again yesterday and everything is fine now.

**Comment by kYroL01** [comment]
Good to know! Thanks
