### ISSUE TITLE
Feature request: Add Plex Media Server traffic to nDPI 

### ISSUE THREAD

**Issue by Kazz3r24** [ntop/nDPI#420]
As requested I am adding a feature request to have Plex Media Server traffic added to nDPI.

Pcap file link is below, Pcap files are not supported to upload to github, so I have placed a link to a secure location where it can be downloaded from.

https://kkazienko.dattodrive.com/index.php/s/vw0JUITiJbziwvg
MD5: 0261101f9f51995e48713933dee81a1f
SHA1: d2f53ed7472deae791874b9c610e4b3a1221a5f9
SHA256: c0f5e9cec3a18bf1755d576bcc04f251fe4caf74d2ad91976b6806c5cf93f8c7

If you prefer another method of upload for the pcap please let me know.

Thanks!

**Comment by kYroL01** [comment]
Thanks for sharing pcap.
The work will be done asap.

**Comment by lucaderi** [comment]
The pcap file is gone, so I have no way to implement it. Please reopen this issue attaching a pcap to it

**Comment by Kazz3r24** [comment]
The pcap was originally uploaded over a year ago, I'll upload a new pcap asap.
