### ISSUE TITLE
SSL client vs. server certificate possible issue

### ISSUE THREAD

**Issue by MicahLyle** [ntop/nDPI#421]
Using the latest development version (also occurs on the 2.0 stable branch), with the https google request in the pcap below (there is a DNS lookup and then an HTTPS google request in the PCAP file), the SSL flow classifies the `client_certificate` as `www.google.com` but `server_certificate` is empty. Shouldn't it be `client_certificate` empty and `server_certificate` `www.google.com`?

[google_https_request_1.pcap.zip](https://github.com/ntop/nDPI/files/1146067/google_https_request_1.pcap.zip)

**Comment by kYroL01** [comment]
Thanks for reporting. I'll check asap.

**Comment by MicahLyle** [comment]
@kYroL01 you're welcome. When I looked into it and stepped through the debugger, I think I've found at least some of what's happening. I attached two screenshots below.
<img width="1113" alt="screen shot 2017-07-14 at 11 49 27 am" src="https://user-images.githubusercontent.com/10660805/28226351-a591d012-688a-11e7-93ea-fc5e900b6107.png">
![screen shot 2017-07-14 at 11 49 58 am](https://user-images.githubusercontent.com/10660805/28226352-a5962806-688a-11e7-90eb-778539228fd1.png)

Basically, if you look at the wireshark picture, along with the code, what ends up happening is that the client hello contains the server name extension with www.google.com as the Server Name. The code gets that far, and sets www.google.com as the client certificate, and says *We're happy now* in the code comment. Then in ssl.c it does this:

```
      rc = getSSLcertificate(ndpi_struct, flow, certificate, sizeof(certificate));
      packet->ssl_certificate_num_checks++;

      if(rc > 0) {
	packet->ssl_certificate_detected++;
#ifdef CERTIFICATE_DEBUG
	printf("***** [SSL] %s\n", certificate);
#endif
	u_int32_t subproto = ndpi_match_host_subprotocol(ndpi_struct, flow, certificate, 
							 strlen(certificate), NDPI_PROTOCOL_SSL);
  
	if(subproto != NDPI_PROTOCOL_UNKNOWN) {
	  ndpi_set_detected_protocol(ndpi_struct, flow, subproto,
				     ndpi_ssl_refine_master_protocol(ndpi_struct, flow, NDPI_PROTOCOL_SSL));
	  return(rc); /* Fix courtesy of Gianluca Costa <g.costa@xplico.org> */
```

Hence, since the return code was 2, and we called `ndpi_set_detected_protocol` and returned 2 again, then go through the return stack, in `ndpi_util.c` we have now set `flow->detection_completed.` Hence, the ssl.c code never gets to see the server hello, or certificate packets, so it never classifies the server certificate.

Hope this helps! I noticed in the ssl.c code we have:

```
      if(((packet->ssl_certificate_num_checks >= 2)
	  && flow->l4.tcp.seen_syn
	  && flow->l4.tcp.seen_syn_ack
	  && flow->l4.tcp.seen_ack /* We have seen the 3-way handshake */)
	 || (flow->protos.ssl.server_certificate[0] != '\0')
```

This code never gets called though because of a return code of 2 from the client certificate. Maybe we should check and make sure we've seen at least a certain number of packets or that before we return from client only that we've seen the server one too, something like that.

**Comment by MicahLyle** [comment]
@kYroL01 I'll submit a pull request later today, I think I know how to fix it.

**Comment by MicahLyle** [comment]
@kYroL01 Here's my progress so far (I have to head home for the weekend soon, based out of California here).

https://github.com/MicahLyle/nDPI/tree/ssl-certificate-fix

It's a quick and simple fix, but I'd possibly like to enhance it. I've modified the tests that were clearly still passing and just had an extra server certificate attached to the SSL output. However, there are now some tests where it doesn't classify SSL "as quickly" (because it might wait for a few more packets now), and those tests obviously aren't passing. I could probably just naively assume it's going to be fine, but I would prefer if maybe a more robust implementation could come about.

Is there a way to say that the "detection is complete" but "I want to keep processing packets until a certain point?" Because that would make this SSL detection even better. I want to know what it is as soon as I can (I.E. with the client certificate), but I also want to be able to process enough packets to get the server certificate and any other information we might want (say with other protocols). Maybe have a variable that gets reset to 0 each time we call packet processing, and if it's set to 1 we keep processing packets until it sets it to 0. That way SSL for example could wait until it has seen enough packets for getting all the valuable data out of there.

Hopefully I'm making some sense.

Anyways, thanks so much for your time on this and I'm happy to help next week starting Monday if you have any suggestions or would like me to change anything.

Best,

Micah

**Comment by kYroL01** [comment]
Hi @MicahLyle .
Really thanks for ALL.
I think you're right about the server name, and I appreciate the test you did to see the improvement of your work.
SSL dissector is old and sometimes not easy to understand where improve, so everything new to fix some issues are welcome.

> Is there a way to say that the "detection is complete" but "I want to keep processing packets until a certain point?"
> ....
> Maybe have a variable that gets reset to 0 each time we call packet processing, and if it's set to 1 we keep processing packets until it sets it to 0.

This is also my idea, so correctly, we can have a variable to differenziate the need. The only problem is where and how to put that. Maybe as a new command user option, i don't know. I think we can think about it.
Also I think it is a good idea give the possibility to keep the behaviour where a flow is detected only by client server, just because other users could be not interest to wait time for server certificate.
IMHO I think we have integrate your work with the existent to improve ssl detection.

What do u think about it ?

**Comment by MicahLyle** [comment]
@kYroL01 here is my current approach, I will test it tomorrow:

https://github.com/MicahLyle/nDPI/commit/6e85b9344298dbba49d06951360c5e3c464d92ba

Basically if the nDPI users want to check for extra packet detection in their code, they are welcome to. Protocol detectors can now also specify if they want to check for extra packets and how many extra packets they want to check for (and what the callback function is, etc.)
