### ISSUE TITLE
nDPI is taking SSL.Telegram traffic for SSL.Amazon's

### ISSUE THREAD

**Issue by ingria** [ntop/nDPI#424]
I'm using nDPI with ntopng. 

nDPI v. 2.0.0-836-3cfcc05

**Comment by kYroL01** [comment]
Hi @codefuhrer please provide us a pcap to see the issue.

THanks

**Comment by kYroL01** [comment]
@codefuhrer any news ? I need a pcap to understand what's wrong

**Comment by ingria** [comment]
@kYroL01 I'm still not sure what's the root of the problem - nDPI or ntopng.

Sometimes it shows the correct values, but sometimes it shows Amazon instead of Telegram.

**Comment by kYroL01** [comment]
Well, how can we understand if the detection is correct, without a pcap to see the issue ?
Any other idea ?

**Comment by kYroL01** [comment]
Close for inactivity. If you send us a good pcap we can inspect better. Thanks
