### ISSUE TITLE
nDPI v2.1.0 crashing with large trace 

### ISSUE THREAD

**Issue by sferlin** [ntop/nDPI#426]
Hi, I have large (few GB) trace files, and I am using ndpi with -v 2 option to get the output and parse it. At some point, while reading the trace, nDPI crashes. I haven't used a profiler, just observing that some of my trace files do not go through. Any thoughts?

**Comment by kYroL01** [comment]
Hi @sferlin . Are u understand the part of the trace could cause the crash ? Maybe you can share us that part to understand better.

**Comment by kYroL01** [comment]
Close for inactivity. Open if necessary and possibily with pcap that cause crash. Thanks
