### ISSUE TITLE
Add Signal application protocol

### ISSUE THREAD

**Issue by kYroL01** [ntop/nDPI#429]
https://en.wikipedia.org/wiki/Signal_(software)

https://security.stackexchange.com/questions/121304/how-does-the-signal-protocol-used-by-whatsapp-work

https://eprint.iacr.org/2016/1013.pdf

**Comment by elrawy** [comment]
Hello, Does the nDPI read the content of the payload and extract it ?? @kYroL01

**Comment by kYroL01** [comment]
@elrawy Of course nDPI read the content of payload to process a packet and get a classification

**Comment by elrawy** [comment]
@kYroL01 could you tell me what command make the nDPI read the content of payload and extract it in a file please ?

**Comment by kYroL01** [comment]
@elrawy There isn't a command, it is an internal process made by code we have programmed. I really don't understand your question. nDPI is not a "program for users", is a library.

**Comment by elrawy** [comment]
@kYroL01 yes i knew all of it but I'm asking if there is a command like ndpiReader -i that show detailed content ?

**Comment by kYroL01** [comment]
If u type ./ndpiReader without command u can see a list of options, maybe the one you look for is 
**-j <file.json>            | Specify a file to write the content of packets in .json format**

**Comment by IvanNardi** [comment]
Signal support has been added starting from  54deb130. Closing
