### ISSUE TITLE
Integrating Tshark with nDPI

### ISSUE THREAD

**Issue by smirAnton** [ntop/nDPI#432]
Guys, is it possible to integrate tshark with nDPI? 
I wanna use deep packet inspection in tshark console.
Thanks for help!

**Comment by VitalyKushnir** [comment]
@smirAnton Ye, it would be great to have this integration

**Comment by lucaderi** [comment]
Did you see https://github.com/ntop/nDPI/tree/dev/wireshark ?

**Comment by scroopyn00pers** [comment]
After reading the link, I was left a little confused about tshark integration. If I wanted to capture all Linkedin traffic on a wired interface (say, eth0), and I had an ndpi interface, would I need to do something like:

tshark -i ndpi -i eth0 -Y "ndpi.name.protocol == SSL.Linkedin" 

or would I need to pipe the pcap output of one tshark command into the other, such as:

tshark -i eth0 -F pcap -w - | tshark -i ndpi -Y "ndpi.name.protocol == SSL.Linkedin"

obviously, on my system (Mac OS X El Capitan), neither of the above commands work. I put the lua script in the global plugin directory and the ndpiReader binary in the extcap path.

Thanks for your help
