### ISSUE TITLE
Code formatting (indentation, etc.)

### ISSUE THREAD

**Issue by pauloangelo** [ntop/nDPI#433]
Hi all,

Are there default basic instructions for code formatting in nDPI? Such as indentation, function names, etc.

Thank you in advance.

regards,

Paulo Angelo

**Comment by kYroL01** [comment]
Hi.
Well, there aren't special rules for code formatting. I think you can follow the code indentation and tab you can see.
For function names, you can see [this](https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_api.h) for example.

If you have questions like this you can also write me privately, thanks!

Regards

**Comment by alagoutte** [comment]
Yes, it will be a good idea to add indent modelines (file) for editconfig for example :)
