### ISSUE TITLE
Improvements on HTTP dissection

### ISSUE THREAD

**Issue by pauloangelo** [ntop/nDPI#434]
Hi all,

I'm needing some features on the HTTP dissection module, which are useful for intrusion detection. Currently, we have the following for HTTP:
- OS detection (caught in the user-agent header);
- HTTP request method;
- URL; and 
- content type.

I suggest the addition of:
- Number of headers in the request (actually the number of lines in the request header);
- The HTTP protocol version in the request (1.0 or 1.1);
- The response status code (200, 404, etc.);

For this, we would have the following changes on [src/include/ndpi_typedefs.h](https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_typedefs.h#L958):

```C
  struct {
    ndpi_http_method method;
    char *url, *content_type;
    u_int8_t  num_requested_headers, request_version; /* 0=1.0 and 1=1.1. Create an enum for this? */
    u_int16_t response_status_code;  /* 200, 404, etc. */
  } http;
```
and some implementation on [src/lib/protocols/http.c](https://github.com/ntop/nDPI/blob/dev/src/lib/protocols/http.c) .

What do you think about it?  May I propose a pull for this?

regards,

Paulo Angelo

**Comment by kYroL01** [comment]
Hi @pauloangelo . I think these features could be helpfull, so I'm agree with you.

If you can provide a pull request, feel free to do it and I'm testing and we can dissuss on it.

Thank you!
