### ISSUE TITLE
telegram protocol doesn't detect

### ISSUE THREAD

**Issue by TaranehKhalili** [ntop/nDPI#441]
telegram does not detect by ndpi

**Comment by kYroL01** [comment]
Hi @taranehk Provide a pcap so we can see the problem.

**Comment by TaranehKhalili** [comment]
Hi @kYroL01 
I provide two pcap, one for web based telegram and one for its desktop application.

[telegram desktop](https://expirebox.com/download/cfd4986694058af8221cb97f197698bb.html)
[telegram web](https://expirebox.com/download/19281bb1bac8367c1961acf9d2772f8a.html)

**Comment by kYroL01** [comment]
FIxed by https://github.com/ntop/nDPI/commit/8e8445e02f9190c9fb12b01c097dda68a4c88856

**Comment by TaranehKhalili** [comment]
thanx @kYroL01 
but it doesn't work. still http_download is the protocol which is detected by ndpi.
