### ISSUE TITLE
The migration of the names of the protocols

### ISSUE THREAD

**Issue by spinenkoia** [ntop/nDPI#443]
Good afternoon. I updated the version of the library from 1.8 to 2.0, but the protocols has changed. For example, 217(Ubntac2) is now 31 and number 31(Imesh) has deleted. How can I do the migration?

**Comment by spinenkoia** [comment]
We use this library in production, and we can't afford to delete the created rules, which are linked to id protocols.

**Comment by kYroL01** [comment]
Yes, from 1.8 to 2.0 there were some changes in the names cause by deleting any old protocols. Later we decide to don't change this behaviour to avoid create problem like the one you report.
Unfortunately users reports this later, and some of the number changed. With 2.0 you don't have this issue anymore. Are there any chance to update directly to 2.0 and accept these changes ? Maybe you have just to chande few link to ID protos.

**Comment by spinenkoia** [comment]
Thank you very much for the reply, now the problem is solved, we removed the protocols. We are more concerned about the constant changes in the protocols, if in the next version of such changes will not, it is very good.

**Comment by kYroL01** [comment]
@spinenkoia Yes we introduct some "empty" lines in case a protocol is removed.
BR
