### ISSUE TITLE
Was 2.0 retagged?

### ISSUE THREAD

**Issue by ilovezfs** [ntop/nDPI#446]
Currently the SHA-256 checksum for https://github.com/ntop/nDPI/archive/2.0.tar.gz is a42a60ebd64bc8606f780204222893027f6dce0e3b460d7be655e5e065f5f3fa.

Originally it was 90ae6e4de83bda5bb7405207020c1e0be364841510fdf5f0a2d48974e1a3fbcb. See https://github.com/Homebrew/homebrew-core/pull/14632.

Was 2.0 retagged at some point?

**Comment by ilovezfs** [comment]
@lucaderi @kYroL01 any idea what happened here?

**Comment by kYroL01** [comment]
Yes, it was retagged from here https://github.com/ntop/nDPI/commit/09c176576697f5dc8fc4c6340ba57127399c3eac

**Comment by ilovezfs** [comment]
@kYroL01 thanks for confirming!
