### ISSUE TITLE
As a rookie.....

### ISSUE THREAD

**Issue by EBWi11** [ntop/nDPI#448]
I would like to ask in addition to the 2013 documents, there is no updated more detailed documentation for reference?
I would like to use nDpi traffic analysis and https analysis, Google does not have any relevant documents, I am very depressed.
so,If have any demo or documentation,Please provide me, thx!

**Comment by kYroL01** [comment]
Yes, the pdf in the `doc ` section is from 2016
https://github.com/ntop/nDPI/blob/dev/doc/nDPI_QuickStartGuide.pdf

As demo I suggest you to use the ndpiReader test program
https://github.com/ntop/nDPI/tree/dev/example

If you need a fast introduction, you could write me in private for questions, If I could answer you.

**Comment by EBWi11** [comment]
thx!
