### ISSUE TITLE
Detect Call direction in Whatsapp Voice

### ISSUE THREAD

**Issue by mhdtbc** [ntop/nDPI#458]
Dear all,

Is there any way to implement in ndpi whatsapp voice call direction detection (incoming or outgoing) depending on the capture. I was wondering if this can be done only by finding out if the first packet even cyphered is in incoming or outgoing direction.

Thanks.

**Comment by kYroL01** [comment]
IMHO the best way is to understand who begin the conversation, so, in a cyphered comunication, who send the Client hello, and consequently, mark it as the one who "outgoing" the call.
Thanks to you
