### ISSUE TITLE
Some of the API functions in the shared library are private

### ISSUE THREAD

**Issue by dangbert** [ntop/nDPI#459]
See the stackoverflow thread [here ](https://stackoverflow.com/questions/46393154/c-code-undefined-reference-to-function-when-using-shared-library/46416892#46416892) for details about the problem.

In summary: there are some API functions that are inaccessible when using the shared library, libndpi.so,
 (they are treated as local symbols for some reason).
* set_ndpi_flow_free
* set_ndpi_flow_malloc
The only way you use these functions is to compile with the static library.  I am using the NDPI-2.0 release which I compiled from the github release download.

ndpiReader itself uses these functions in ndpi_util.c but doesn't seem to run into this problem because it is compiled using the static library instead of linking to the shared library (libndpi.so).  (I believe a static library automatically exports all symbols).

**Comment by kYroL01** [comment]
I think you're right... I have to think about it deeply. Thanks.

**Comment by dangbert** [comment]
Someone on stackoverflow helped identify the fix: https://stackoverflow.com/a/46416892/5500073

Now I see that there are other functions that have this problem as well such as (ndpi_workflow_process_packet).

I will try to identify all the functions where this is a problem and possibly submit a pull request.

**Comment by dangbert** [comment]
Ok so I was wrong about ndpi_workflow_process_packet being a missing symbol (it turns out I was using that function wrong).

However, the following functions were missing symbols:
* set_ndpi_flow_malloc
* set_ndpi_flow_free
* ndpi_flow_free

after adding them to libndpi.sym I was able to compile my program (a modified version of ndpiReader) using the nDPI-2.0 shared library.

Pull request submitted: https://github.com/ntop/nDPI/pull/468
