### ISSUE TITLE
Use nDPI to extract or mark packets in PCAP

### ISSUE THREAD

**Issue by mhdtbc** [ntop/nDPI#461]
Dear All,

I would like to use nDPI to extract from a large pcap, a file with only Whatsappvoice recognised packets.

Is there a way to do it with example nDPIReader ? 

Thank you.

**Comment by kYroL01** [comment]
nDPI is not an extractor. you can use it to evidence which packets are WhatsApp voice and then you have to use an application to extract only that packet.
You can use nDPI as a "filter" for your application.

Cheers
