### ISSUE TITLE
trace flow to the end 

### ISSUE THREAD

**Issue by NatashaR4in** [ntop/nDPI#470]
hi all , i want to trace a tcp flow that labeled with specific signature to the end .how can i do that ?
thanks in advance

**Comment by kYroL01** [comment]
I think this question is too generic and maybe is different from the behaviour of nDPI.
How you use nDPI ? How you sign a flow ? the end of a single flow or the flows or single protocol ?

**Comment by TaranehKhalili** [comment]
End of TCP flow is marked by the fin or rst flags in the tcp header.

**Comment by NatashaR4in** [comment]
when i am searching  , i see that whatsapp server on port 443 send a static packet to client directly afler client send a chat to server (like an ACK say that server received what client send ) , so i want to count those packet  just in this flow  , so i added an array in `ndpi_flow_struct` and a flag ,and in ssl.c i set the flag to 1 when flow accepted as whatsapp flow . 
i tried to change the max extra packet ,but while debugging the flow does not return to ssl.c  file after few packets .
where should i set that flow need to check all of its packets ?how can i do that ?
thanks for your time.

**Comment by kYroL01** [comment]
@taranehk I know that the end of the flow is a packet like that in general, but I want to understand in this scenario...
@NatashaR4in later I'm watching better andtry to help u, thanks.

**Comment by kYroL01** [comment]
@NatashaR4in do u have your modified code so I can take a look and try ? 
I think the problem is that when a flow is marked for a proto (i.e. Whatsapp), the following pkts in that flow are considered WA. I think there is a function do this work, to avoid to enter in the dissector every time the lib process another pkt of the same flow.
Can u tell me that is that packet or if u have a pcap represent this scenario ?

**Comment by NatashaR4in** [comment]
ok, first of all , i found that whatsapp has a new signature , start with first packet of 1 byte contains 'E' ,and the second packet in flow will contain a WA at payload [8]and [9] , later in flow a packet with size payload_packet_len==67  and start with 0x00 0x00 0x40 appears after sending a chat message , i added those to function `ndpi_search_ssl_tcp` . 
[w_chat1.zip](https://github.com/ntop/nDPI/files/1358409/w_chat1.zip).

[ssl.zip](https://github.com/ntop/nDPI/files/1358426/ssl.zip)

**Comment by kYroL01** [comment]
Thanks!

**Comment by androuxx** [comment]
I think that this is a great idea to track a specific flow to the end or to the specific number of packets , packet by packet so we can labeling multi sub-services in the same flow if exists like whatsapp and messenger like[Whatsapp.chat.send_photo] or by using a custom array like @NatashaR4in doing
this is very helpful @kYroL01 for deep network monitor

**Comment by taranehk** [comment]
@kYroL01 I thought the matter is tracing a flow. I add some codes to ndpi_process_packet function to trace the flow to the end.  I can send a pull request if u want.
(I also consider some other options for osdpi_flow_node such as packet and bytes to have informations  about the flow.)
`
static u32 ndpi_process_packet(struct nf_conn * ct, const uint64_t time,
		const struct iphdr *iph, uint16_t ipsize, const struct tcphdr *tcph , const char * in,
		const char * out) {
	u32 proto = NDPI_PROTOCOL_UNKNOWN;
	union nf_inet_addr *ipsrc, *ipdst;
	struct osdpi_id_node *src, *dst;
	struct osdpi_flow_node *flow, *curflow;
	u8 exist_flow = 0;
	u64 t1;
	struct timeval tv;
	spin_lock_bh(&flow_lock);
	ipsrc = &ct->tuplehash[IP_CT_DIR_ORIGINAL].tuple.src.u3;
	ipdst = &ct->tuplehash[IP_CT_DIR_ORIGINAL].tuple.dst.u3;
	flow = ndpi_flow_search(&osdpi_flow_root, ct);
	if (iph->protocol == IPPROTO_TCP) {
		if (tcph->syn) {
			spin_unlock_bh(&flow_lock);
			return proto;
		}
		else if ((tcph->fin || tcph->rst) && flow != NULL) {
			flow->end_of_flow = 1;
			flow->sport = ntohs(tcph->source), flow->dport = ntohs(tcph->dest);
			if (l7_log && flow->end_of_flow)
				pr_info("xt_ndpi:End of TCP flow %s dst %pI4: %u <-> src %pI4: %u  [pkts: %u][bytes: %u][ct:%u][time:%u][IN_int=%s][OUT_int=%s] \n",
						prot_long_str[flow->detected_protocol.protocol], ipdst,
						flow->dport, ipsrc, flow->sport , flow->packets, flow->bytes,  (long)flow->ct , flow->ndpi_timeout , flow->in_interface , flow->out_interface);
			ndpi_kill_flow(ct, ipsrc, ipdst);
			spin_unlock_bh(&flow_lock);
			return proto;
		}
	} else if (iph->protocol == IPPROTO_ICMP) {
		spin_unlock_bh(&flow_lock);
		return NDPI_PROTOCOL_IP_ICMP;
	}
	else {
		if (nf_ct_is_dying(ct)) {
			ndpi_kill_flow(ct, ipsrc, ipdst);
			spin_unlock_bh(&flow_lock);
			return proto;
		}
	}
	do_gettimeofday(&tv);
	t1 = (uint64_t) tv.tv_sec;
    //every interval seconds !!
	if(!interval){
		interval =t1;
	}else{
		if(t1-interval >= interval_time){
			ndpi_end_of_udp_flows();
			interval = t1;
		}
	}
	if (flow == NULL) {
		if (!gc_interval_timeout)
			gc_interval_timeout = t1;
		else {
			if (t1 - gc_interval_timeout > 59) {
				ndpi_gc_flow();
				gc_interval_timeout = t1;
			}
		}
		flow = ndpi_alloc_flow(ct);
		if (flow == NULL) {
			spin_unlock_bh(&flow_lock);
			return NDPI_PROTOCOL_UNKNOWN;
		} else {
			/* Include flow timeouts */
			flow->ndpi_timeout = t1; // 30s for DPI timeout  and 180 for connection
			flow->detected_protocol.protocol = NDPI_PROTOCOL_UNKNOWN;
			flow->detection_completed = 0;
			flow->flow_logged = 0;
		}
	} else {
		/* Update timeouts */
		exist_flow = 1;
		if (tcph)
			flow->sport = ntohs(tcph->source), flow->dport = ntohs(tcph->dest);
		else if (flow->ndpi_flow->packet.udp)
			flow->sport = ntohs(flow->ndpi_flow->packet.udp->source), flow->dport = ntohs(
					flow->ndpi_flow->packet.udp->dest);
		else
			flow->sport = flow->dport = 0;
		flow->bytes = flow->bytes + ipsize;
		++flow->packets;
		flow->in_interface = in;
		flow->out_interface = out;
		if (flow->detected_protocol.protocol) {
			proto = flow->detected_protocol.protocol;
			if (debug_dpi
					&& flow->detected_protocol.protocol <= NDPI_LAST_NFPROTO)
				pr_info(
						"xt_ndpi: flow detected %s dst %pI4: %u <-> src %pI4: %u \n",
						prot_long_str[flow->detected_protocol.protocol], ipdst,
						flow->dport, ipsrc, flow->sport);
			if (l7_log && flow->detected_protocol.protocol <= NDPI_LAST_NFPROTO
					&& !flow->flow_logged && !flow->end_of_flow)
			{

				flow->flow_logged = 1;
				pr_info(
						"xt_ndpi: flow detected %s dst %pI4: %u <-> src %pI4: %u  [pkts: %u][bytes: %u][ct:%u][time:%u][IN_int=%s][OUT_int=%s] \n",
						prot_long_str[flow->detected_protocol.protocol], ipdst,
						flow->dport, ipsrc, flow->sport , flow->packets, flow->bytes, (long)flow->ct ,flow->ndpi_timeout , flow->in_interface , flow->out_interface);
			}else if (l7_log && flow->detected_protocol.protocol == NDPI_PROTOCOL_UNKNOWN
				&& !flow->flow_logged && !flow->end_of_flow)
			{
				flow->flow_logged = 1;
				pr_info("xt_ndpi:  flow detected %s dst %pI4: %u <-> src %pI4: %u  [pkts: %u][bytes: %u][ct:%u][time:%u][IN_int=%s][OUT_int=%s]\n",
									prot_long_str[NDPI_PROTOCOL_UNKNOWN], ipdst, flow->dport,
									ipsrc, flow->sport, flow->packets	, flow->bytes ,  (long)flow->ct, flow->ndpi_timeout, flow->in_interface , flow->out_interface);
			}
			flow->ndpi_timeout = t1;
			spin_unlock_bh(&flow_lock);
			return proto;
		} else if (!flow->detected_protocol.protocol
				&& (t1 - flow->ndpi_timeout > 30)) {
			if (debug_dpi)
				pr_info("xt_ndpi: dst %pI4 expired\n", ipdst);

			spin_unlock_bh(&flow_lock);
			return NDPI_PROTOCOL_UNKNOWN;
		}
	}
	/* Invalid DPI flow */
	if (flow->ndpi_flow == NULL) {
		if (debug_dpi)
			pr_info("xt_ndpi: dst %pI4 invalid\n", ipdst);
		ndpi_kill_flow(ct, ipsrc, ipdst);
		spin_unlock_bh(&flow_lock);
		return proto;
	}
	flow->ndpi_timeout = t1;
	/* Set current flow for temporary dump */
	curflow = kmem_cache_zalloc(osdpi_flow_cache, GFP_ATOMIC);
	curflow->ndpi_flow =
			(struct ndpi_flow_struct *) ((char*) &curflow->ndpi_flow
					+ sizeof(curflow->ndpi_flow));
	curflow->detected_protocol.protocol = NDPI_PROTOCOL_UNKNOWN;
	curflow->ndpi_flow = flow->ndpi_flow;
	spin_unlock_bh(&flow_lock);

	/* control the src or dst id into flow spinlock */
	spin_lock_bh(&flow_lock);
	src = ndpi_id_search(&osdpi_id_root, ipsrc);
	if (src == NULL) {
		src = ndpi_alloc_id(ipsrc);
		if (src == NULL) {
			kmem_cache_free(osdpi_flow_cache, curflow);
			spin_unlock_bh(&flow_lock);
			return proto;
		}
	} else if (!exist_flow)
		kref_get(&src->refcnt);
	dst = ndpi_id_search(&osdpi_id_root, ipdst);
	if (dst == NULL) {
		dst = ndpi_alloc_id(ipdst);
		if (dst == NULL) {
			kmem_cache_free(osdpi_flow_cache, curflow);
			spin_unlock_bh(&flow_lock);
			return proto;
		}
	} else if (!exist_flow)
		kref_get(&dst->refcnt);
	spin_unlock_bh(&flow_lock);
	/* here the actual detection is performed */
	spin_lock_bh(&ipq_lock);
	curflow->detected_protocol = ndpi_detection_process_packet(ndpi_struct,
			curflow->ndpi_flow, (uint8_t *) iph, ipsize, time, src->ndpi_id,
			dst->ndpi_id);
	spin_unlock_bh(&ipq_lock);
	/* set detected protocol */
	spin_lock_bh(&flow_lock);
	if (flow != NULL) {
		proto = curflow->detected_protocol.protocol;
		flow->detected_protocol = curflow->detected_protocol;
		if (tcph)
			flow->sport = ntohs(tcph->source), flow->dport = ntohs(tcph->dest);
		else if (flow->ndpi_flow->packet.udp)
			flow->sport = ntohs(flow->ndpi_flow->packet.udp->source), flow->dport = ntohs(
					flow->ndpi_flow->packet.udp->dest);
		else
			flow->sport = flow->dport = 0;

		flow->bytes = flow->bytes + ipsize;
		++flow->packets;
	        flow->in_interface = in;
		flow->out_interface = out;
		if (proto > NDPI_LAST_IMPLEMENTED_PROTOCOL) {
			proto = NDPI_PROTOCOL_UNKNOWN;
			if (l7_log && flow->detected_protocol.protocol == NDPI_PROTOCOL_UNKNOWN
							&& !flow->flow_logged && !flow->end_of_flow)
			{
				flow->flow_logged = 1;
				pr_info("xt_ndpi: protocol detected %s  dst %pI4: %u <-> src %pI4: %u [host: %s][bytes: %u][ct:%u][time:%u][IN_int=%s][OUT_int=%s]\n",
									prot_long_str[NDPI_PROTOCOL_UNKNOWN], ipdst, flow->dport,
									ipsrc, flow->sport, flow->ndpi_flow->host_server_name, flow->bytes , (long)flow->ct, flow->ndpi_timeout, flow->in_interface , flow->out_interface);
			}
		} else {
			if (flow->detected_protocol.protocol != NDPI_PROTOCOL_UNKNOWN) {
				/* update timeouts */
				if (debug_dpi && proto <= NDPI_LAST_NFPROTO)
					pr_info(
							"xt_ndpi: protocol detected %s  dst %pI4: %u <-> src %pI4: %u\n",
							prot_long_str[proto], ipdst, flow->dport, ipsrc, flow->sport );
				if (l7_log && proto <= NDPI_LAST_NFPROTO
						&& !flow->flow_logged && !flow->end_of_flow)
				{

					flow->flow_logged = 1;
					pr_info(
							"xt_ndpi: protocol detected %s  dst %pI4: %u <-> src %pI4: %u [host: %s][bytes: %u][ct:%u][time:%u][IN_int=%s][OUT_int=%s]\n",
							prot_long_str[flow->detected_protocol.protocol],
							ipdst, flow->dport, ipsrc, flow->sport , flow->ndpi_flow->host_server_name, flow->bytes , (long)flow->ct , flow->ndpi_timeout, flow->in_interface , flow->out_interface);
				}
				flow->ndpi_timeout = t1;
				flow->detection_completed = 1;
				/* reset detection */
				if (flow->ndpi_flow)
					memset(flow->ndpi_flow, 0, sizeof(*(flow->ndpi_flow)));
			}
		}
	}
	kmem_cache_free(osdpi_flow_cache, curflow);
	spin_unlock_bh(&flow_lock);
	return proto;
}
`

**Comment by TaranehKhalili** [comment]
@kYroL01 I thought the matter is tracing a flow. I add some codes to ndpi_process_packet function of  in ndpi-netfilter to trace the flow to the end.  I can share it if u want.

**Comment by NatashaR4in** [comment]
@taranehk  , yes please share it ,i may try to adapt the same modification to my nDPI , and if there is an updated version of netfilter and you could share ,that 's will be great.
thanks.

**Comment by TaranehKhalili** [comment]
@NatashaR4in  I'll send a pull request for betolj/ndpi-netfilter as soon as possible.
[https://github.com/betolj/ndpi-netfilter](url)

**Comment by kYroL01** [comment]
@NatashaR4in @taranehk If you want to contribute for this task, please, send a pull request and we can integrate inside (after checking it's correctness).

**Comment by NatashaR4in** [comment]
@taranehk ,we are waiting for your pull, and by the way is there a netfilter project run with the latest nDpi ? https://github.com/betolj/ndpi-netfilter seem outdated

**Comment by TaranehKhalili** [comment]
I am trying to solve a bug and then I send the pull request. I am trying to solve this bug asap.

**Comment by TaranehKhalili** [comment]
@kYroL01 I made my changes on ndpi-netfilter and it doesn't let me to send a pull request. what should I do now?

**Comment by kYroL01** [comment]
Of course, because you have to do that changes to a fork of nDPI, not ndpi-netfilter.
Fork nDPI, make your changes and send a pull request.

**Comment by TaranehKhalili** [comment]
I'm sorry about my delay. I send the pull request on ndpi-netfilter. this is my commit. my fork name is taranehk.
[https://github.com/betolj/ndpi-netfilter/pull/60/commits/436f68ec1dffd3873919b6dfc11151082c0f9492](url)

**Comment by kYroL01** [comment]
@taranehk The link is dead. But if you want to contribute, why don't you send a pull request to this repository ? We have many differences from ndpi-netfilter repo, and it's easier if you send a pull request here. Please, respect this policy.
Thank you

**Comment by TaranehKhalili** [comment]
ok. I'm trying...:)
here is the commit:
(open a new tab and paste the address bellow!!)
[https://github.com/ntop/nDPI/pull/475/commits/d02a6daece4562eea01ae22f4e80165f24542e39](url)

**Comment by androuxx** [comment]
@taranehk i tried to install your netfilter version, from your fork https://github.com/taranehk/nDPI/ and when i run the ./autogen.sh script i get `config.status: error: cannot find input file: `Makefile.in'`

**Comment by androuxx** [comment]
what i need to setup ndpi-netfilter in inline-mode for control my network traffic?
i setup ndpi-netfilter on ubuntu 16.04.1 with two network interface, so how i can pass my network traffic to ndpi-netfilter machine ?
what iptabes need to setup for that ?

**Comment by TaranehKhalili** [comment]
@androuxx  you should install ndpi-netfilter. (instructions are in README file of these project)

after installation you can use it by for example:

> iptables -I FORWARD -mndpi --google -j DROP

**Comment by taranehk** [comment]
@kYroL01 did you check the pull request?

**Comment by androuxx** [comment]
@taranehk did you test the the installation of your ndpi-netfilter code ?
i tried to install your netfilter but i get an error
```
git clone https://github.com/taranehk/nDPI.git
cd nDPI/nDPI
./autogen.sh
configure.ac:103: error: required file 'libndpi.pc.in' not found
configure.ac:103: error: required file 'src/include/ndpi_define.h.in' not found
```

then i get those file from ntop/nDPI
and when i tried to make the code i get the following:
```
make  all-recursive
make[1]: Entering directory '/home/ubt/taranehk/nDPI/nDPI'
Making all in src/lib
make[2]: Entering directory '/home/ubt/taranehk/nDPI/nDPI/src/lib'
/bin/bash ../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../..  -I../../src/include/  -I../../src/lib/third_party/include/   -g -O2 -fPIC -DPIC  -MT libndpi_la-ndpi_main.lo -MD -MP -MF .deps/libndpi_la-ndpi_main.Tpo -c -o libndpi_la-ndpi_main.lo `test -f 'ndpi_main.c' || echo './'`ndpi_main.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../.. -I../../src/include/ -I../../src/lib/third_party/include/ -g -O2 -fPIC -DPIC -MT libndpi_la-ndpi_main.lo -MD -MP -MF .deps/libndpi_la-ndpi_main.Tpo -c ndpi_main.c  -fPIC -DPIC -o .libs/libndpi_la-ndpi_main.o
ndpi_main.c: In function ‘ndpi_detection_process_packet’:
ndpi_main.c:3580:67: error: ‘ndpi_protocol {aka struct ndpi_proto}’ has no member named ‘protocol’
          ret.master_protocol = flow->guessed_host_protocol_id, ret.protocol = flow->guessed_host_protocol_id;
                                                                   ^
ndpi_main.c:3587:55: error: ‘ndpi_protocol {aka struct ndpi_proto}’ has no member named ‘protocol’
       ret.master_protocol = NDPI_PROTOCOL_UNKNOWN, ret.protocol = flow->guessed_protocol_id;
                                                       ^
Makefile:1183: recipe for target 'libndpi_la-ndpi_main.lo' failed
make[2]: *** [libndpi_la-ndpi_main.lo] Error 1
make[2]: Leaving directory '/home/ubt/taranehk/nDPI/nDPI/src/lib'
Makefile:468: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ubt/taranehk/nDPI/nDPI'
Makefile:375: recipe for target 'all' failed
make: *** [all] Error 2
```
