### ISSUE TITLE
RFC: Debug output

### ISSUE THREAD

**Issue by vel21ripn** [ntop/nDPI#471]
We have 3 levels of debug printing: NDPI_LOG_ERROR, NDPI_LOG_TRACE, NDPI_LOG_DEBUG
Now part of the protocol uses only _LOG_DEBUG, the other part uses only _LOG_TRACE.

IMHO We need to define the rules for using _LOG_TRACE and _LOG_DEBUG. 
I propose to introduce the following rules:
The debug level _LOG_TRACE should be used when the protocol is successfully detected and at the beginning of processing the data packet.
In the ideal case, the trace should output two lines per packet of data: information about the data packet and the result of the detection.
The debug level _LOG_DEBUG must always be used at the beginning of each protocol detection procedure and to display the phase / state of the protocol detection.
It is necessary to add the level of debug printing _LOG_DEBUG_EXTRA which should be used only in detailing the operation of the protocols.
You need to add a set for selective debug output of the protocols, which must be used for the _LOG_DEBUG and _LOG_DEBUG_EXTRA levels.

Are there any other ideas for increasing the usefulness of debug output in nDPI?

**Comment by kYroL01** [comment]
I'm agree with you for this scenario.

**Comment by vel21ripn** [comment]
Please see commit https://github.com/vel21ripn/nDPI/commit/3eb7b6760c669626c0046b2bd3c40a7c3ab2d957

This is big commit!  155 files changed, 2662 insertions(+), 2463 deletions(-)
I will do the PR after your approval.

**Comment by kYroL01** [comment]
@vel21ripn I have to check these modification and let u know. Thanks

**Comment by vel21ripn** [comment]
Small fix after refatcoring https://github.com/vel21ripn/nDPI/commit/63969935bc8798fb1b29ce470acfa3ec0301071a

**Comment by kYroL01** [comment]
@vel21ripn IMHO your pull request could be sent and check.
I prefer wait the opinion of @lucaderi on this modification about LOG stuff.

**Comment by kYroL01** [comment]
I close this because refers to the pull request you sent us.
Thanks

**Comment by qianguozheng** [comment]
@vel21ripn  have test this deeply ? is this problem related to this  #512 ?
