### ISSUE TITLE
What is diffrence between http and ssl detection and other protocols?

### ISSUE THREAD

**Issue by TaranehKhalili** [ntop/nDPI#474]
can anyone explain me how http and ssl is detected in ndpi completely? I want the process of detection of these protos step by step. :D

**Comment by kYroL01** [comment]
@taranehk What is your doubt ? We cannot do an how-to here.

**Comment by TaranehKhalili** [comment]
well I want to get LOG for every flow which is specified in iptables with "-j LOG". I made some changes in ndpi-netfilter for this purpose. I can get flows of every application except http, ssl and ftp. I thought it may concern to way of detection of these protocols.

**Comment by kYroL01** [comment]
@taranehk this repository DOES NOT support netfilter with iptables. If you ask me "what is the difference between http and ssl detection and other protocols" I can just answer that the difference is inside the payload at application level, that is used by specific dissector to parse and classify a protocol properly.
If you ask me something more for netfilter, I can't help you.
