### ISSUE TITLE
nDPI-netfilter inline mode 

### ISSUE THREAD

**Issue by androuxx** [ntop/nDPI#479]
i'm trying to setup lasted version of ndpi-netfilter inline mode with Bypass NICs network card to control my network traffic with ndpi-netfilter machine.
the aim for that is to save accessing the network when ndpi-netfilter machine take down.(Bypass NICs)
i installed last version of ndpi-netfilter and it's work fine, but how can i setup the machine for inline mode ?
i tried to create basic bridge between the two interface then forced all bridged traffic into the iptables mangle+filter forward tables with etables rules but it did not work. (connection lost)
any help please ??
![netfilter](https://user-images.githubusercontent.com/18631976/31794928-9401df74-b52c-11e7-84ce-7f4c4727c377.PNG)

**Comment by kYroL01** [comment]
@androuxx This is not the repo of ndpi-netfilter. Please open this issue in that repo (that is not our).
We delete the ndpi-netfilter kernel mode, but soon We will introduce a solution for this by combining netfilter, efficiency, and user-space. Thanks
