### ISSUE TITLE
ndpiReader pcap_loop() in multithread issue

### ISSUE THREAD

**Issue by qianguozheng** [ntop/nDPI#480]
Hi guys:
I don't understand how the multithread work when call pcap_loop.
For example if I enable 2 thread in parameter, the it will have 2 pcap_loop API call. and then it will analyze the packet received one by one, while 2 pcap_loop will have the same data read from network device. Though the ndpiReader will find the hash in tree storage structure, I still think it is not quick enough.

Anyone have test multi-thread is faster than one thread in pcap_loop() API been used ?
I would like to know much more about that, thanks a lot.

**Comment by kYroL01** [comment]
HI @qianguozheng , did u do any specific test for this behaviour. It will be nice to understand better the environment you test on it.

**Comment by qianguozheng** [comment]
@kYroL01 Not really, am I right about logic of pcap_loop do and ndpiReader process?

**Comment by kYroL01** [comment]
@qianguozheng I actually never see before this part of ndpiReader. I inherited this part of the code. So maybe you're right about this. What u think about that ?

**Comment by lucaderi** [comment]
Each thread must have a private copy of the ndpi_mod, so there are never classes, or you need to lock ndpi (bad) to avoid concurrent calls on the same share ndpi_mod pointer

**Comment by dsokoloski** [comment]
@qianguozheng To more directly answer your question:  If you start ndpiReader with two or more threads, then they run concurrently on their own private handle of the nDPI module (as @lucaderi mentioned).  Multiple pcap_loops run concurrently from within their respective threads.  There is no contention between running threads for any resource (other than memory allocation) as implemented by ndpiReader.

As an aside, I mentioned memory allocation being a point of contention.  I have found that this can be significantly improved when running nDPI simultaneously across many interfaces by linking against tcmalloc (thread caching malloc) which is part of the Google Performance Tools library.
