### ISSUE TITLE
ndpiReader crash for long time testing

### ISSUE THREAD

**Issue by dugugang** [ntop/nDPI#481]
munmap_chunk(): invalid pointer: 0x000000fff01a076e ***
======= Backtrace: =========
/lib64/libc.so.6(+0xa11b4)[0xfff13761b4]
bwtrackeruser[0x1006e824]
bwtrackeruser(ndpi_free_flow_info_half+0x68)[0x1006f148]
bwtrackeruser[0x10066388]
bwtrackeruser[0x10013898]
bwtrackeruser[0x100138b8]
bwtrackeruser[0x1006d80c]
bwtrackeruser[0x1006da68]
/lib64/libpthread.so.0(+0xb9ec)[0xfff17469ec]
/lib64/libc.so.6(+0x10ba4c)[0xfff13e0a4c]
======= Memory map: ========
10000000-100a3000 r-xp 00000000 b3:02 4254                               /usr/bin/bwtrackeruser
100b2000-100c8000 rw-p 000a2000 b3:02 4254                               /usr/bin/bwtrackeruser
100c8000-100ea000 rwxp 00000000 00:00 0 
1e5e3000-1e89a000 rwxp 00000000 00:00 0                                  [heap]
ffe8000000-ffe820d000 rw-p 00000000 00:00 0 
ffe820d000-ffec000000 ---p 00000000 00:00 0 
ffef9a4000-ffef9a5000 ---p 00000000 00:00 0 
ffef9a5000-fff01a4000 rw-p 00000000 00:00 0                              [stack:13609]
fff01a4000-fff12a4000 rw-s 00000000 00:05 23596                          socket:[23596]
fff12a4000-fff12c5000 r-xp 00000000 b3:02 747                            /lib/libgcc_s.so.1
fff12c5000-fff12d4000 ---p 00021000 b3:02 747                            /lib/libgcc_s.so.1
fff12d4000-fff12d5000 rw-p 00020000 b3:02 747                            /lib/libgcc_s.so.1
fff12d5000-fff147e000 r-xp 00000000 b3:02 738                            /lib/libc-2.16.so
fff147e000-fff148f000 ---p 001a9000 b3:02 738                            /lib/libc-2.16.so
fff148f000-fff1495000 r--p 001aa000 b3:02 738                            /lib/libc-2.16.so
fff1495000-fff149a000 rw-p 001b0000 b3:02 738                            /lib/libc-2.16.so
fff149a000-fff149e000 rw-p 00000000 00:00 0 
fff149e000-fff1580000 r-xp 00000000 b3:02 749                            /lib/libm-2.16.so
fff1580000-fff159d000 ---p 000e2000 b3:02 749                            /lib/libm-2.16.so
fff159d000-fff159e000 r--p 000ef000 b3:02 749                            /lib/libm-2.16.so
fff159e000-fff159f000 rw-p 000f0000 b3:02 749                            /lib/libm-2.16.so
fff159f000-fff15bf000 r-xp 00000000 b3:02 2020                           /usr/lib/libz.so.1.2.8
fff15bf000-fff15c0000 rw-p 00020000 b3:02 2020                           /usr/lib/libz.so.1.2.8
fff15c0000-fff15c3000 r-xp 00000000 b3:02 744                            /lib/libdl-2.16.so
fff15c3000-fff15df000 ---p 00003000 b3:02 744                            /lib/libdl-2.16.so
fff15df000-fff15e0000 r--p 0000f000 b3:02 744                            /lib/libdl-2.16.so
fff15e0000-fff15e1000 rw-p 00010000 b3:02 744                            /lib/libdl-2.16.so
fff15e1000-fff16e8000 r-xp 00000000 b3:02 774                            /lib/libstdc++.so.6.0.17
fff16e8000-fff16f6000 ---p 00107000 b3:02 774                            /lib/libstdc++.so.6.0.17
fff16f6000-fff1701000 r--p 00115000 b3:02 774                            /lib/libstdc++.so.6.0.17
fff1701000-fff1706000 rw-p 00120000 b3:02 774                            /lib/libstdc++.so.6.0.17
fff1706000-fff171a000 rw-p 00000000 00:00 0 
fff171a000-fff1723000 r-xp 00000000 b3:02 770                            /lib/librt-2.16.so
fff1723000-fff1739000 ---p 00009000 b3:02 770                            /lib/librt-2.16.so
fff1739000-fff173a000 r--p 0000f000 b3:02 770                            /lib/librt-2.16.so
fff173a000-fff173b000 rw-p 00010000 b3:02 770                            /lib/librt-2.16.so
fff173b000-fff1759000 r-xp 00000000 b3:02 766                            /lib/libpthread-2.16.so
fff1759000-fff176a000 ---p 0001e000 b3:02 766                            /lib/libpthread-2.16.so
fff176a000-fff176b000 r--p 0001f000 b3:02 766                            /lib/libpthread-2.16.so
fff176b000-fff176c000 rw-p 00020000 b3:02 766                            /lib/libpthread-2.16.so
fff176c000-fff1770000 rw-p 00000000 00:00 0 
fff1770000-fff1796000 r-xp 00000000 b3:02 731                            /lib/ld-2.16.so

**Comment by kYroL01** [comment]
@dugugang How can I reproduce this issue to understand where is the crash ?

**Comment by kYroL01** [comment]
More information needed. Re-open if necessary. In this way is a useless issue.

Thanks
