### ISSUE TITLE
nDPI 2.0 detects some https sites as TOR traffic

### ISSUE THREAD

**Issue by rudigital** [ntop/nDPI#485]
Greetings.

It looks like TOR detection rules have some false positives yet.
Here is a small list of domain names, returning _ERR_CONNECTION_RESET_, when attempting to connect via https:

- https://www.gazneftetorg.ru/ 
- https://www.skydns.ru/
- https://www.kavkazr.com/

This list will be supplemented as soon as I find new non-working sites.

CAP files with a couple of connection attempts for each site are provided in the following attachment:
[pcap.zip](https://github.com/ntop/nDPI/files/1421043/pcap.zip)

**Comment by rudigital** [comment]
- https://vtb24.ru
[vtb24-ru.cap.zip](https://github.com/ntop/nDPI/files/1421085/vtb24-ru.cap.zip)

**Comment by kYroL01** [comment]
Yes, you're right. I have to understand why.

**Comment by spinenkoia** [comment]
I applied this patch to version 2.0 and everything is working except the web site https://www.kavkazr.com/ it still is blocked as Tor

**Comment by kYroL01** [comment]
Try after [this](https://github.com/ntop/nDPI/commit/3caac691d5640c505f03ae98fc187e019cb91d3d)

Thanks

**Comment by spinenkoia** [comment]
Yes, thank you, everything works

**Comment by kYroL01** [comment]
Great!
