### ISSUE TITLE
youtube traffic not detected

### ISSUE THREAD

**Issue by dillinger79** [ntop/nDPI#487]
These 2 pcaps have youtube traffic, but ndpiReader classifies it  only as QUIC
[youtube.zip](https://github.com/ntop/nDPI/files/1438038/youtube.zip)

**Comment by kYroL01** [comment]
I'm checking, thanks

**Comment by kYroL01** [comment]
@dillinger79 nDPI detect this traffic as QUIC because there is no information on the host name server knows to identify YT. The only way to detect this traffic as YouTube is to associate the ip address. Can u confirm  it ?

**Comment by alagoutte** [comment]
Missing some part of packet

because it is possible on (G)QUIC Client Hello to have a SNI

**Comment by dillinger79** [comment]
thanks to both, yes as i see know there are missing packets, michele the ip
can not be associated with youtube, please close the issue.
I will try to get a different trace with all the packets and check the
classification.

BR

2017-11-02 16:54 GMT+02:00 Alexis La Goutte <notifications@github.com>:

**Comment by kYroL01** [comment]
Perfect
