### ISSUE TITLE
block Telegram app

### ISSUE THREAD

**Issue by remort** [ntop/nDPI#489]
Signing in and messaging via Telegram are not being blocked with nDPI 2.0. File transfers are blocked within the lib only.
Traffic dump, containing the successful signing in and sending a couple of messages is attached below.
[telegram.pcapng.zip](https://github.com/ntop/nDPI/files/1461586/telegram.pcapng.zip)

**Comment by kYroL01** [comment]
Thanks for the pcap. I'm going to investigate

**Comment by spinenkoia** [comment]
Here's another tcpdump icq, over TLS
[icq.zip](https://github.com/ntop/nDPI/files/1463572/icq.zip)

**Comment by kYroL01** [comment]
Updated
https://github.com/ntop/nDPI/commit/a4532a49997ae185de393699e4b61c7d673fb78a

**Comment by spinenkoia** [comment]
Hello, I have applied these patches 8e8445e02f9190c9fb12b01c097dda68a4c88856 a4532a49997ae185de393699e4b61c7d673fb78a for nDPI 2.0, does not work. Tried the version from the dev branch, it works. Tell me, what is not enough to work in version 2.0?

**Comment by lucaderi** [comment]
You need to move to the development version

**Comment by spinenkoia** [comment]
Okay, thanks

**Comment by spinenkoia** [comment]
Another question, how stable is the dev branch? Can it be used in production?

**Comment by lucaderi** [comment]
Yes it can be used

**Comment by spinenkoia** [comment]
Okay, thanks
