### ISSUE TITLE
Is there a list of master protocols

### ISSUE THREAD

**Issue by dangbert** [ntop/nDPI#500]
While testing nDPI I saw that the master_protocols field is (at times) set to these values:

- SSL
- DNS
- HTTP
- (or unknown)

My question is, is there a list of all the possible values that master_protocol can take on?  Clearly app_protocol can take on any value from ndpi_protocol_ids.h, but master_protocol seems to only be from a subset of that list.

Also why do you set app_protocol to DNS or HTTP sometimes and leave master_protocol as unknown (rather than setting master_protocol to DNS or HTTP and app_protocol to unknown)?  Is there any reason for this or is it arbitrary?

**Comment by kYroL01** [comment]
`master_protocol` is set to _real_ protocols, not applications (that is considered like protocols in nDPI), and is set just when there is a an application and a protocol "under the hood" of application (for example **Facebook.SSL**). In other cases we consider just the `app_protocol` as important, and we set that.
Is just a choice, also becase is more correct call app_protocol both Facebook or HTTP than called tham master_protocol.
Anyway, is just an implementative choice, nothing more.

The list in `ndpi_protocol_ids` mixed master and app protocols. Maybe we could re-organize that for a better understanding.

**Comment by dangbert** [comment]
@kYroL01  Thanks for the info!  Do you know if the master_protocol would ever be set to anything other than SSL, DNS, or HTTP (or unknown)?  Or is that the extent of the possible values it could be set to?

**Comment by kYroL01** [comment]
master protocol is considered a protocol of that family, so for example also RTP, RTCP, SIP, etc.. If nDPI detect an application, the protocol behind that application is the master protocol
