### ISSUE TITLE
BitCoin protocol

### ISSUE THREAD

**Issue by spinenkoia** [ntop/nDPI#503]
Good day, our company has a task to block Blockchain mining. If someone knows how to add, maybe at least the bitcoin protocol?
I would be very grateful.

**Comment by kYroL01** [comment]
I think this could be very usefull for the future, but to do this we need to study deeply blockchain and begin with a pcap of real traffic.

**Comment by spinenkoia** [comment]
Okay.
I'll tryed sniffing to pcap file.

**Comment by kYroL01** [comment]
Thanks

**Comment by kYroL01** [comment]
Any News about the pcap @spinenkoia ?

**Comment by spinenkoia** [comment]
Hello, unfortunately there's nothing yet, no time, I hope soon something to send.

**Comment by spinenkoia** [comment]
@kYroL01 I hurried a bit with the answer, recently received several pcap files, which protocols I find a bit later.


[pcap.zip](https://github.com/ntop/nDPI/files/1613836/pcap.zip)

**Comment by spinenkoia** [comment]
there in the archive 3 file
1 - ethereum
2 - zcash
3 - monero

**Comment by spinenkoia** [comment]
Oh, Yes, the port number is random

**Comment by spinenkoia** [comment]
this is the 3 most popular currency for home mining

**Comment by mhdtbc** [comment]
Dear All,

Two ideas here : 

> The three traces seems to have a kind of "JSON" discussion between a peer and a server. the remote port is either 3333 or 4444 depending on the trace.
> I don't really know how mining works, but the exchanges here are clear, at least in the structure, maybe this can be signed.

Also i found that wireshark has a "dissector" called "bitcoin", maybe it's worth something that we take a look at it.

thank you.

**Comment by kYroL01** [comment]
Thanks @mehdi-erroussafi . I'm kinda busy but I'm agree and I'll do the dissection asap.

**Comment by lucaderi** [comment]
@spinenkoia Sorry for taking so long. Please verify the implementation and let me know
