### ISSUE TITLE
Compilation issues on Mageia Cauldron using gcc 7.3.0

### ISSUE THREAD

**Issue by kekePower** [ntop/nDPI#511]
System: Mageia Cauldron x86_64 in a VM.
Compiler: gcc 7.3.0
Build chroot: mock

I've uploaded a build log.
https://github.com/kekePower/mmbl/blob/master/ndpi/2018/01/27-210652/mock/build.log#L1183

Thanks for your time.

Cheers,
kekePower

**Comment by kYroL01** [comment]
Hi! I have to check better, thanks

**Comment by kekePower** [comment]
Hi.

I had to use --enable-shared and --enable-static to get it to build successfully and could then use it to compile ntopng.

Case closed.
