### ISSUE TITLE
How to open dissect debug message ?

### ISSUE THREAD

**Issue by qianguozheng** [ntop/nDPI#512]
I want to know down to detail of http dissector implementation, but I don't know how to open the log message of this module only, please  tell me how to do that ? 
Thanks

**Comment by qianguozheng** [comment]
I define macro `NDPI_ENABLE_DEBUG_MESSAGES` in ndpi_define.h, but it only print message in ndpi_main.c, no debug message of specified protocol like http and so on. While do the same thing nDPI 2.0 can print specified protocol debug message, I believe there is something error in there

**Comment by vel21ripn** [comment]
Look at the source of any protocol.There are 4 required lines
```
#include "ndpi_protocol_ids.h"
#ifdef NDPI_PROTOCOL_XXXXXXX
#define NDPI_CURRENT_PROTO NDPI_PROTOCOL_XXXXXXX
#include "ndpi_api.h"
```
Macros NDPI_LOG_DBG2,NDPI_LOG_DBG,NDPI_LOG_INFO use NDPI_CURRENT_PROTO as name of protocol.

To output debugging information, you need to use the macro NDPI_LOG_DBG2().
A debug message about the start of processing a packet and exclusion of the protocol from the processing should be output using the NDPI_LOG_DBG() macro.
A debug message about successful protocol detection should be displayed using the NDPI_LOG_INFO() macro.

**Comment by qianguozheng** [comment]
@vel21ripn , I know that's the defination of the debug macro usage.
My problem is that I use the latest code without modification of debug log, and define macro in `NDPI_ENABLE_DEBUG_MESSAGES` in ndpi_define.h, there can print the log of  `NDPI_LOG` and `NDPI_LOG_DBG2` in ndpi_main.c file, but don't print any debug or log info in http.c, I am sure there http request. 

Even debug below not printed ` NDPI_LOG_DBG2(ndpi_struct, "HTTP stage %d: \n", flow->l4.tcp.http_stage);`.
But, when I add printf("xxxx test"); just at the start of the function `ndpi_check_http_tcp`, I can see the output `xxxx test` printed. Why ? after all, we define the all the macro with macro `NDPI_ENABLE_DEBUG_MESSAGES`

some debug message
```
ndpi_main.c:ndpi_detection_process_packet:3699 - [Unknown]: START packet processing
ndpi_main.c:ndpi_init_packet_header:3210 - [Unknown]: ipv4 header
ndpi_main.c:ndpi_detection_get_l4_internal:3092 - [Unknown]: ipv4 header
ndpi_main.c:ndpi_detection_process_packet:3699 - [Unknown]: START packet processing
ndpi_main.c:ndpi_init_packet_header:3210 - [Unknown]: ipv4 header
ndpi_main.c:ndpi_detection_get_l4_internal:3092 - [Unknown]: ipv4 header
ndpi_main.c:ndpi_detection_process_packet:3699 - [Unknown]: START packet processing
ndpi_main.c:ndpi_init_packet_header:3210 - [Unknown]: ipv4 header
ndpi_main.c:ndpi_detection_get_l4_internal:3092 - [Unknown]: ipv4 header
ndpi_main.c:ndpi_detection_process_packet:3699 - [Unknown]: START packet processing
ndpi_main.c:ndpi_init_packet_header:3210 - [Unknown]: ipv4 header
ndpi_main.c:ndpi_detection_get_l4_internal:3092 - [Unknown]: ipv4 header
ndpi_main.c:ndpi_parse_packet_line_info:4053 - [Unknown]: ndpi_parse_packet_line_info: HTTP response parsed: "200 OK"
ndpi_main.c:ndpi_detection_process_packet:3699 - [Unknown]: START packet processing
ndpi_main.c:ndpi_init_packet_header:3210 - [Unknown]: ipv4 header
ndpi_main.c:ndpi_detection_get_l4_internal:3092 - [Unknown]: ipv4 header
ndpi_main.c:ndpi_detection_process_packet:3699 - [Unknown]: START packet processing
ndpi_main.c:ndpi_init_packet_header:3210 - [Unknown]: ipv4 header
ndpi_main.c:ndpi_detection_get_l4_internal:3092 - [Unknown]: ipv4 header
ndpi_main.c:ndpi_detection_process_packet:3699 - [Unknown]: START packet processing
ndpi_main.c:ndpi_init_packet_header:3210 - [Unknown]: ipv4 header
ndpi_main.c:ndpi_detection_get_l4_internal:3092 - [Unknown]: ipv4 header

```

**Comment by vel21ripn** [comment]
NDPI_LOG_DBG2 () will print messages only if (struct ndpi_detection_module_struct).ndpi_log_level >= NDPI_LOG_DEBUG_EXTRA and only for those protocols that are specified in (struct ndpi_detection_module_struct).debug_bitmask.
NDPI_LOG () will output messages only for those protocols that are specified in debug_bitmask.

```ndpiReader -V 4``` set ndpi_log_level=NDPI_LOG_DEBUG_EXTRA and all protocols in debug_bitmask.

**Comment by qianguozheng** [comment]
@vel21ripn  My fault, only set ndpi_log_level = NDPI_LOG_DEBUG_EXTRA without set debug_bitmask.
But don't you think this is too confused ? can we do some thing to make it simpler ?

**Comment by vel21ripn** [comment]
@qianguozheng Running ndpiReader with "-V 4" option is not difficult.
You can make your own implementation of the function ndpi_debug_printf() without check debug_bitmask.

**Comment by qianguozheng** [comment]
Thanks
