### ISSUE TITLE
How to write a dissector module of desired protocol ?

### ISSUE THREAD

**Issue by qianguozheng** [ntop/nDPI#513]
I want to implement a specific procotol of game inspection, but I don't know how to write a dissector, please tell me , thanks a lot.

**Comment by kYroL01** [comment]
Hi @qianguozheng .
Please read [here](https://github.com/ntop/nDPI#how-to-add-a-new-protocol-dissector) and follow instructions.
Thanks

P.s. I suggest you also to add a test pcap to verify the work
