### ISSUE TITLE
marking flows as local flows 

### ISSUE THREAD

**Issue by zaylon** [ntop/nDPI#514]
Dears nDPI developers,
thanks for this great work.
i have a question about detection local flows which created by 2 hosts on same network (192.168.1.15<->192.168.1.16). Or any two private ip in Bogon IP lists 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 169.254.0.0/16 ...
is there a way to say that this flow is a local flow ?
can we add a flag to mark this case?
i may try to help and develop some code, just please tell me what to do.

**Comment by kYroL01** [comment]
Hi @zaylon .
Actually for now there is no solution for consider Bogon IP list as "local".
As u correctly said, one idea could be mark these flows with a `flag`.
The process should be like this:

1. Scan IP addresses
2. If the IP is a Bogon -> mark as local
3. else -> do nothing

I think the work could be done here https://github.com/ntop/nDPI/blob/dev/example/ndpi_util.c#L275 .

Feel free to send a pull request and we can discuss togheter.
Thanks

**Comment by zaylon** [comment]
Dear @kYroL01,
thanks for your response, i tried a way to do that : 
```
if(((ntohl(flow->src_ip)>=3232235520)&&(ntohl(flow->src_ip)<=3232301055)) //192.168.0.0<>192.168.255.255
    &&((ntohl(flow->dst_ip)>=3232235520)&&(ntohl(flow->dst_ip)<=3232301055))
    )
    {
      printf("\n local ip detected +++++++++++++++ %u %u",ntohl(flow->src_ip),ntohl(flow->dst_ip));
    
    } 
```
it works fine on test pcap, but what about performance? is it a good idea to compare like this ,or should we try with something like ndpi_network host_protocol_list[] (ndpi_content_match.c.inc)

**Comment by kYroL01** [comment]
@zaylon Maybe to keep things clean and in order is better to put that list in `host_protocol_list[]` and check from there, even if I don't know about the performance.

**Comment by zaylon** [comment]
@kYroL01 , adding this  list to  host_protocol_list[],will return all flows as local (at least for my network),because all flows in my network are from public to private and vice-versa,and the fnx that check  host_protocol_list[] return positive if any of 2 flows ip(source or destination) appears,but in my case i need to check the 2 ips and see if they are both private or not.

**Comment by kYroL01** [comment]
It's okay. So take the first way
