### ISSUE TITLE
nDPI code Documentation

### ISSUE THREAD

**Issue by zablah** [ntop/nDPI#516]
Why nDPI project was not contains a code Documentation to help the developer for understanding the structure of the project and the codes
like linux kernel documentation that contains a lot of information about the kernel code.

**Comment by qianguozheng** [comment]
Yeah, that's a MUST, I think.

**Comment by kYroL01** [comment]
Yes, it's a must-to-do thing we should do in the next feature.
We will do.

Thanks so much
