### ISSUE TITLE
Question about ndpiReader  ndpi_flows_root and idle_flows  

### ISSUE THREAD

**Issue by qianguozheng** [ntop/nDPI#517]
I saw ndpiReader use `ndpi_thread_info[thread_id].workflow->ndpi_flows_root[ndpi_thread_info[thread_id].idle_scan_idx]` to store the flow captured, and somehow, will put outdated flow into idle_flows.  and eventually will delete idle_flows.  I don't understand this procedure. and have some questions below:

1. What is idle_flows ? 
2. Under what's circumatance will a flow be put into idle_flow ?
   My Answer: when meet this judgement: ` if(flow->last_seen + MAX_IDLE_TIME < ndpi_thread_info[thread_id].workflow->last_time) `

3. Will delete idle_flows affect statistics of the each ip's request ?
  My Answer: looks idle flow is not a real flow ?  by this code : `ndpi_thread_info[thread_id].workflow->stats.ndpi_flow_count--;`

4. will ndpiReader store all the flow into `ndpi_flows_root`, then will ndpiReader occupy too much memory ？ since normal flows will not be deleted from this `ndpi_flows_root` ?

Am I right about above 2, 3 answer ? and what about other questions ?

**Comment by kYroL01** [comment]
@qianguozheng IDLE FLOW is just outdated flow, so after a certain time, a flow must be considered old and must be deleted (as you correctly say in 2 and 3).
One time that you have to understand is that ndpiReader is kust a **demo** to see if the detection of an application is correct or not. It's not a full-standalone-perfect program.
The library is made to be used by ntopng, and all the optimization is made there.
The implementation of the flows is inherited by old code, so feel free to change ndpiReader in the best way if you found something wrong.

Thanks

**Comment by qianguozheng** [comment]
@kYroL01  There is still something confuse me.
Then idle flow is the outdated, what can be think of OUTDATED ? flows that exceed 30 seonds without following packets coming or both side of the flow close the connection ? I have test the flow added and API `node_idle_scan_walker` called times, found that there is only about 150 flows left, BUT, when I shutdown the process, the statistics show that the overall flow is same as added into `ndpi_flows_root`, This confuse me, since flows statistics by walk the ndpi_flows_root, but this flow storage have been delete, why looks none of them have been deleted ?  
I just want to know the logic of this.

**Comment by qianguozheng** [comment]
@kYroL01  Got that, before move the flow into idle flow, it statistics the data
