### ISSUE TITLE
Possibile bug about not extraction of server name with custom protocols

### ISSUE THREAD

**Issue by dillinger79** [ntop/nDPI#526]
with commit c115903fbb4df21c489226900a739cccd3f8f057, if a custom protocol is identified ndpi immediately returns. That has some changes to previous functionality, one i identified when updating to latest ndpi is that the host server name is not extracted.
Is that a bug or is it a desired functionality?

**Comment by kYroL01** [comment]
Hi @dillinger79 .

Can u specify better the problem and in wich case you see this ? Actually host name should not be compromised with that patch.
Did u see a different behaviour from latest ndpi than an old you say it work ?

Thanks

**Comment by dillinger79** [comment]
Hi Michele, 

i think that the host server name is extracted in the check_ndpi_flow_func function which is called in the ndpi_detection_process_packet function, due to the check for custom protocols , if a custom protocol is detected the check_ndpi_flow_func  function is never called, therefore the host server name is not extracted.
I recently updated ndpi from 1.8 to 2.2 and saw that there were cases that the app protocol is identified, but there is no host server name.

**Comment by kYroL01** [comment]
Does in 1.8 version the behaviour was correct for the extraction ?

**Comment by dillinger79** [comment]
yes

**Comment by kYroL01** [comment]
Ok so we'll have to check better.
If you already have idea how to fix, feel free to send us a Pull request and then I'll check.

Thanks

**Comment by dillinger79** [comment]
i made a pull request and will check further about it
