### ISSUE TITLE
How to save the UNKNOWN traffic into a standalone file for later analysis ?

### ISSUE THREAD

**Issue by qianguozheng** [ntop/nDPI#528]
Recently I use ndpiReader to analyze the traffic to see what traffic is have, but there some traffic not recoginzed but I don't know where it is, so I want to save it seperately and to analyze it, anyone can provide help ? thanks .
```
Protocol statistics:
	Safe                      57775363 bytes
	Acceptable                 3341353 bytes
	Fun                          54480 bytes
	Unrated                       3430 bytes
	Unrated                      55993 bytes
```

**Comment by qianguozheng** [comment]
I remember that ntopng may can save the traffic of UNKNOWN into a standalone fine @kYroL01

**Comment by kYroL01** [comment]
Hi @qianguozheng .
ndpiReader is just a demo for the traffic classification, is not like ntopng.
The feature you're asking cannot be satisfy here, unless you implemented for your own business.
