### ISSUE TITLE
error offset in protocol dhcp.c 

### ISSUE THREAD

**Issue by blacktrain** [ntop/nDPI#532]
file:src/lib/protocols/dhcp.c,line:75:
 if((packet->payload_packet_len >= 244 /* 244 is the offset of options[0] in dhcp_packet_t */)
the comment /* 244 is the offset of options[0] in dhcp_packet_t */) is incorrect

**Comment by kYroL01** [comment]
Hi @blacktrain what should be the correct comment ? _options_ ?

**Comment by kYroL01** [comment]
Any news ?

**Comment by dsokoloski** [comment]
In the GitHub notice email I received regarding this bug report, @blacktrain said:

> should be：
> if((packet->payload_packet_len >= 240 / 240 is the offset of options[0] in dhcp_packet_t */)

...but I believe that **244** is the correct value:
```
+   8 octets IP UDP header
+ 236 octets DHCPDISCOVER packet header + payload (w/no options)
  ---
= 244 octet offset to DHCP options
```
References:
[https://en.wikipedia.org/wiki/User_Datagram_Protocol](url)
[https://en.wikipedia.org/wiki/Dynamic_Host_Configuration_Protocol#DHCP_discovery](url)

**Comment by kYroL01** [comment]
Exactly. This is why I'm asking more explanation about that.

**Comment by kYroL01** [comment]
Close for inactivity. I think there is no issue
