### ISSUE TITLE
Bandwidth Control on Microsoft Edge for Youtube

### ISSUE THREAD

**Issue by faizatahir94** [ntop/nDPI#533]
Hi 
I am not able to control bandwidth of YouTube on Microsoft Edge.
After adding drop rules for QUIC protocol, I was able to achieve specified YouTube's bandwidth on chrome successfully. But this does not work for Microsoft Edge browser. Can you please suggest me any possible solution? Below are the rules for shaping the YouTube traffic.

sudo iptables -I FORWARD -m ndpi --quic -j DROP
tc qdisc del dev $PPP_IFACE root
tc qdisc add dev $PPP_IFACE root handle 1: htb default 30
tc class add dev $PPP_IFACE parent 1: classid 1:1 htb rate 8mbit burst 15k
tc class add dev $PPP_IFACE parent 1:1 classid 1:10 htb rate 1mbit burst 15k
tc qdisc add dev $PPP_IFACE parent 1:10 handle 10: sfq perturb 10
tc filter add dev $PPP_IFACE parent 1:0 protocol ip prio 1 handle 1 fw classid 1:10
iptables -t mangle -A POSTROUTING -m ndpi --youtube -j MARK --set-mark 0x1

**Comment by kYroL01** [comment]
@faizatahir94 How this issue could be related with nDPI ?
Sorry but this is out of the nDPI behaviour.
I think maybe you refer to the ndpi-netfilter project ( a fork of this repo ).
