### ISSUE TITLE
Dynamic addition for the website detection

### ISSUE THREAD

**Issue by faizatahir94** [ntop/nDPI#534]
Hi 
I want to add a support for the detection of a website whose URL is for example " www.myexample.com" based on this URL I want to take a specific action e.g block or assigning bandwidth. I have a concern. In real time scenario for the ISP's there may be many websites that need to be detected. If I am using nDPI library for detection, I need to change the some "c" files for the detection of that particular website and me may also introduce a new file. My question is if there is a automated way of introducing a website url instead of introducing the protocols in code ?

**Comment by kYroL01** [comment]
Yes, you can use [protos.txt](the https://github.com/ntop/nDPI/blob/dev/example/protos.txt) example, where you can label traffic detected from a URL.
See the **host** example in the link. I think is what u need
