### ISSUE TITLE
How to use nDPI in linux kernel as one .ko file

### ISSUE THREAD

**Issue by ydy1234** [ntop/nDPI#540]
Project neet to ues DPI as protocol filter and forward packets to controlers, ndpiReader is just one APP for packet filerter, how to process packet in linuxe kernel not in APP level?

**Comment by vel21ripn** [comment]
See fork https://github.com/vel21ripn/nDPI

**Comment by kYroL01** [comment]
@ydy1234 nDPI has no support for kernel. Follow the fork of @vel21ripn 
Thank you
