### ISSUE TITLE
ndpiReader SEGFault when defined NDPI_ENABLE_DEBUG_MESSAGES

### ISSUE THREAD

**Issue by Dipet** [ntop/nDPI#541]
Hi!
When I compile ndpiReader with NDPI_ENABLE_DEBUG_MESSAGES it is crashes with SEGV error.

**Comment by kYroL01** [comment]
Have to check, thanks !

**Comment by vel21ripn** [comment]
What branch of the project are you builded (dev or stable)?
With which options did you run ndpiReader?
The nDPI project can not be compiled with "CFLAGS=-DNDPI_ENABLE_DEBUG_MESSAGES ./configure ". 
You must use  **./configure --enable-debug-messages**

**Comment by Dipet** [comment]
Stable version.
With option "-i pcap_file"
Yes I did not compile nDPI with this options, my fail, sorry. Thanks for explanations.
