### ISSUE TITLE
Hosts by Operating System

### ISSUE THREAD

**Issue by slylander** [ntop/nDPI#542]
Hi,

I am new to ntopng, I read the bug/issues report but didn't see this appear in the v.3.3.x code.  I encounter "No results found" when accessing "Hosts by Operating System".  Any pointers where do I start troubleshooting?  I was running v.3.3.180328, updating to v.3.3.180329 didn't seem to help.

Thank you,

Willie

**Comment by kYroL01** [comment]
Hi @slylander this is not a nDPI issue. I think you have to open this issu on https://github.com/ntop/ntopng

Thanks
