### ISSUE TITLE
Using protocol file for host based protocols

### ISSUE THREAD

**Issue by zxyz** [ntop/nDPI#546]
Hello,
I'm trying to add custom protocols based on port or host for unknow 
traffic. An example for tcpdump pcap output is the following:

`12:28:04.970411 IP esp01.example.net.52376 > audio1b.example.net.dc: Flags [.], seq 191932:193392, ack 97, win 251, length 1460`

The classification using the port works:

`tcp:2001@audiox`

`./ndpiReader -p custom.protos -i ~/tcpdump.pcap` returns

> Detected protocols:
>       audiox              packets: 470           bytes: 679192 flows: 7

using

`host:"audio1a.example.net"@audiox` or `host:"esp01.example.net"@audiox` returns

> Detected protocols:
>       Unknown              packets: 470           bytes: 679192 flows: 7

nDPI is current Master.

Any help would be much appreciated! Thanks!

**Comment by kYroL01** [comment]
@zxyz Thanks for reporting. Need to investigate.

**Comment by zxyz** [comment]
hello @kYroL01, I'd just like to know, if there are any news on this issue.

Thanks!

**Comment by kYroL01** [comment]
Hi @zxyz . Sorry I was too busy. Hope to see asap!

**Comment by zxyz** [comment]
I know it's summer (at least on the side of the globe where I reside), but I'd be still really interested in turning my `unknown` protocols into some with cute names :)
please let me now if I can be of any further assistance and thanks a lot!

**Comment by dsokoloski** [comment]
@zxyz You've instructed the nDPI engine to do hostname matching for `audio1a.example.net` or `esp01.example.net`, which would work, but only for protocols that include hostnames, such as SSL (matches SNI or CN from certificate), or DNS query, or HTTP request (matches the "`Host: xyx`" directive in the header).  It doesn't look like the traffic you want to classify is a protocol that contains a hostname.

To do what you want, add "**ip:**" directives (that do IP matching), for example:
```
# Assuming that esp01.example.net resolves to one address: 192.168.0.1
ip:192.168.0.1/32@audiox
# ... or: esp01.example.net resolves to two addresses: 192.168.0.1, 10.1.0.1
ip:192.168.0.1/32,10.1.0.1/32@audiox
# ... or: *.example.net covers an entire class-C IP block: 192.168.0.0/24
ip:192.168.0.0/24@audiox
```

**Comment by zxyz** [comment]
dear @dsokoloski, thanks for explaining the problem, this clarifies a lot for me. 
I tried using `ip:` and sometimes it works, sometimes not. May this be dependent on the direction of the traffic? If I have a look at the `active unknown flows` in the ntopng web-gui, I see:

> Appliation: unknown, Client: 192.168.1.65:25198 Server:somename.example.net:41682

somename.example.net resolves to 10.128.66.23. my `custom.protocols` includes the line

`ip:192.168.2.15/32,192.168.66.123/32,10.128.66.23/32@XFTP`

therefore I'd expected the traffic to be calssified as `XFTP`

thanks for you help!

**Comment by dsokoloski** [comment]
@zxyz Yes you're right, however...

The problem is that you have to specify the directive `ip:` for each entry even when you fold several entries into a single comma-delimited line.  So your configuration line should be written like this (notice the multiple `ip:...` entries):
```
ip:192.168.2.15/32,ip:192.168.66.123/32,ip:10.128.66.23/32@XFTP
```
If you don't do this, then what I've experienced is that the nDPI engine will still parse such lines but will skip entries without a directive (`ip:` in this case).  So in your case, the first IP was being designated as XFTP, but the two IPs after were ignored.

The [./example/protos.txt](../blob/dev/example/protos.txt) from the nDPI source provides a pretty comprehensive list of example custom-protocol directives.

**Comment by zxyz** [comment]
@dsokoloski thanks a lot. That did the trick! :)
