### ISSUE TITLE
Fix memory leaks on shutdown

### ISSUE THREAD

**Issue by lucaderi** [ntop/nDPI#548]
==19665== 606,976 bytes in 4,742 blocks are still reachable in loss record 1,476 of 1,492
==19665==    at 0x4C29BE3: malloc (vg_replace_malloc.c:299)
==19665==    by 0x51ABE2: node_init (node.c:65)
==19665==    by 0x51AEB5: node_create (node.c:50)
==19665==    by 0x51AEED: node_create_next (node.c:167)
==19665==    by 0x51A61A: ac_automata_add (ahocorasick.c:100)
==19665==    by 0x4EE50C: ndpi_string_to_automa.isra.2 (ndpi_main.c:660)
==19665==    by 0x4F030D: ndpi_add_host_url_subprotocol (ndpi_main.c:675)
==19665==    by 0x4F030D: ndpi_init_protocol_match (ndpi_main.c:712)
==19665==    by 0x4F4A06: init_string_based_protocols (ndpi_main.c:739)
==19665==    by 0x4F4A06: ndpi_init_protocol_defaults (ndpi_main.c:1702)
==19665==    by 0x4F4A06: ndpi_init_detection_module (ndpi_main.c:1943)
==19665==    by 0x469A6C: NetworkInterface::NetworkInterface(char const*, char const*) (NetworkInterface.cpp:156)
==19665==    by 0x44BD01: PcapInterface::PcapInterface(char const*) (PcapInterface.cpp:32)
==19665==    by 0x44371E: main (main.cpp:237)
==19665==
==19665== 841,600 bytes in 1 blocks are still reachable in loss record 1,477 of 1,492
==19665==    at 0x4C29BE3: malloc (vg_replace_malloc.c:299)
==19665==    by 0x4EFF71: ndpi_realloc (ndpi_main.c:346)
==19665==    by 0x51A45A: ac_automata_register_nodeptr (ahocorasick.c:308)
==19665==    by 0x51A636: ac_automata_add (ahocorasick.c:103)
==19665==    by 0x4F4B2C: ndpi_add_string_value_to_automa (ndpi_main.c:1968)
==19665==    by 0x4B975E: Ntop::loadTrackers() (Ntop.cpp:1740)
==19665==    by 0x443B72: main (main.cpp:327)
==19665==
==19665== 863,856 bytes in 15,426 blocks are still reachable in loss record 1,478 of 1,492
==19665==    at 0x4C29BE3: malloc (vg_replace_malloc.c:299)
==19665==    by 0x4EF6A4: ndpi_calloc (ndpi_main.c:329)
==19665==    by 0x4EFBE1: ndpi_patricia_lookup (ndpi_patricia.c:824)
==19665==    by 0x4F0574: add_to_ptree (ndpi_main.c:1804)
==19665==    by 0x4F0574: ndpi_init_ptree_ipv4 (ndpi_main.c:1819)
==19665==    by 0x4F0574: ndpi_init_detection_module (ndpi_main.c:1907)
==19665==    by 0x469A6C: NetworkInterface::NetworkInterface(char const*, char const*) (NetworkInterface.cpp:156)
==19665==    by 0x44BD01: PcapInterface::PcapInterface(char const*) (PcapInterface.cpp:32)
==19665==    by 0x44371E: main (main.cpp:237)
==19665==
==19665== 870,912 bytes in 15,552 blocks are still reachable in loss record 1,479 of 1,492
==19665==    at 0x4C29BE3: malloc (vg_replace_malloc.c:299)
==19665==    by 0x4EF6A4: ndpi_calloc (ndpi_main.c:329)
==19665==    by 0x4EFB76: ndpi_patricia_lookup (ndpi_patricia.c:771)
==19665==    by 0x4F0574: add_to_ptree (ndpi_main.c:1804)
==19665==    by 0x4F0574: ndpi_init_ptree_ipv4 (ndpi_main.c:1819)
==19665==    by 0x4F0574: ndpi_init_detection_module (ndpi_main.c:1907)
==19665==    by 0x469A6C: NetworkInterface::NetworkInterface(char const*, char const*) (NetworkInterface.cpp:156)
==19665==    by 0x44BD01: PcapInterface::PcapInterface(char const*) (PcapInterface.cpp:32)
==19665==    by 0x44371E: main (main.cpp:237)
==19665==
==19665== 910,848 bytes in 4,744 blocks are still reachable in loss record 1,480 of 1,492
==19665==    at 0x4C29BE3: malloc (vg_replace_malloc.c:299)
==19665==    by 0x51ABF9: node_init (node.c:69)
==19665==    by 0x51AEB5: node_create (node.c:50)
==19665==    by 0x51AEED: node_create_next (node.c:167)
==19665==    by 0x51A61A: ac_automata_add (ahocorasick.c:100)
==19665==    by 0x4EE50C: ndpi_string_to_automa.isra.2 (ndpi_main.c:660)
==19665==    by 0x4F030D: ndpi_add_host_url_subprotocol (ndpi_main.c:675)
==19665==    by 0x4F030D: ndpi_init_protocol_match (ndpi_main.c:712)
==19665==    by 0x4F4A06: init_string_based_protocols (ndpi_main.c:739)
==19665==    by 0x4F4A06: ndpi_init_protocol_defaults (ndpi_main.c:1702)
==19665==    by 0x4F4A06: ndpi_init_detection_module (ndpi_main.c:1943)
==19665==    by 0x469A6C: NetworkInterface::NetworkInterface(char const*, char const*) (NetworkInterface.cpp:156)
==19665==    by 0x44BD01: PcapInterface::PcapInterface(char const*) (PcapInterface.cpp:32)

==19665==    by 0x44371E: main (main.cpp:237)

**Comment by IvanNardi** [comment]
No known memory leaks on current code. Closing

**Comment by IvanNardi** [comment]
No known memory leaks on current code. Closing
