### ISSUE TITLE
Live Capture On pcapReader Sample

### ISSUE THREAD

**Issue by Ahmed-Mabrouck** [ntop/nDPI#549]
Hello,

I want to live capture the traffic from Ethernet interface on Linux machine.

I have compiled both the library and the sample and run the example using command: 
./ndpiReader -i ens33
and also
./ndpiReader -i /sys/class/net/ens33

but the application responds: ERROR: could not open playlist : error reading dump file: Is a directory.

Any valid clarification for this scenario please.

**Comment by kYroL01** [comment]
Hi @AhmedMabrouck .
The answer is given by the compiler:

> error reading dump file: Is a directory.

Are u sure you open a valid file or device ? Be sure on this and try again.
try `ifconfig -a ` to see all your network devices.

**Comment by DD152** [comment]
same problem and i just add sudo.
