### ISSUE TITLE
No way to log packets in ndpiReader ?

### ISSUE THREAD

**Issue by fazega** [ntop/nDPI#550]
Hello,
Is there an option to log the packets with ndpiReader ? Something like this https://github.com/caesar0301/pcapdpi, but working (this repo is too old and do not compile anymore).
If it does not exist, do you see a simple way to do that ? I don't want to spend hours understanding the whole code in C.
Thank you,

**Comment by kYroL01** [comment]
hI @fazega .
There is no log file as u said, because ndpiReader is just a demo to test protocols, and we prefer to take it slim, but maybe could be usefull to do it.
I put it into to-do feature list and we'll see if develop or not.

Thanks.

**Comment by fazega** [comment]
Thank you for your answer.
Finally I'm using tshark (pyshark actually) to log packets and ndpi to analyze them.
