### ISSUE TITLE
instagram flow classified as facebook

### ISSUE THREAD

**Issue by dillinger79** [ntop/nDPI#560]
this is an instagram flow that ndpi classifies as facebook, my guess is that this is due to the fact that the in the client hello packet the Server Name is "instagram.fath3-4.fna.fbcdn.net" and ndpi checks for the "fbcdn.net" first and classifies this as facebook before checking for "instagram."
[instagram.zip](https://github.com/ntop/nDPI/files/1987661/instagram.zip)

**Comment by kYroL01** [comment]
@dillinger79 It should be as u said. I have to investigate better.
Thanks for reporting.
