### ISSUE TITLE
Classification based on properties

### ISSUE THREAD

**Issue by rizwankh** [ntop/nDPI#574]
This is an enhancement request where we can have a high level file to classify based on lets say ssl properties that are already been extracted in ssl.c like certificate CN or hostname from Client Hello etc.

So i could write cn=="xyz.com" is "XYZ"

**Comment by dsokoloski** [comment]
@rizwankh You can do this already by defining your own "custom match" configuration file and defining your own application names.  We do this in Netify so for example, if we see an SSL connection with a CN/SNI matching google.com, the detected application name would be something like: SSL.netify.google

You can do this with the ndpiReader example code by using a command-line parameter to load in a custom "protos" file.

**Comment by kYroL01** [comment]
@rizwankh what @dsokoloski says is correct. Follow the instruction in nDPI documentation for this part on how to define your own personal detection and you have the answer.
Read also [this](https://www.ntop.org/ndpi/configuring-ndpi-for-custom-protocol-detection/)
