### ISSUE TITLE
Get time ip flow

### ISSUE THREAD

**Issue by agularrom** [ntop/nDPI#579]
Hi @lucaderi 

I'm using ndpireader for a project and i'm interested export the information in format IPFIX.
Can you get initial time and end time of an ip flow?

Thanks!!

**Comment by utoni** [comment]
Yes, you can. But this is basically part of your own implementation although `example/ndpiReader` or more precise `example/reader_util.c` and `example/reader_util.h` make use of such features. Take a look at `struct ndpi_entropy`. All timestamps there are from `libpcap`'s packet timestamp.
