### ISSUE TITLE
compile ndpi with -g

### ISSUE THREAD

**Issue by CharlesJu1** [ntop/nDPI#580]
I could not figure out how to compile the ndpi library with -g option so that I can use gdb to trace the code. Could you help out?

**Comment by dsokoloski** [comment]
Pass the compiler flags you want to use when you configure via CFLAGS.  Such as:
```
# ./autogen.sh
# CFLAGS='-g' ./configure
# make clean
# make
```

**Comment by CharlesJu1** [comment]
I followed your instruction. But the Makefile in src/lib is not auto generated and thus not changed. Make VERBOSE=1 shows that the lib is still compile without -g. 

MacBook-Pro:~/ndpi-new/nDPI $ make VERBOSE=1
Making all in src/lib
cc -fPIC -DPIC -I../include -Ithird_party/include -DNDPI_LIB_COMPILATION -c protocols/afp.c -o protocols/afp.o
cc -fPIC -DPIC -I../include -Ithird_party/include -DNDPI_LIB_COMPILATION -c protocols/aimini.c -o protocols/aimini.o
cc -fPIC -DPIC -I../include -Ithird_party/include -DNDPI_LIB_COMPILATION -c protocols/ajp.c -o protocols/ajp.o

So is there any other option other than manually change the makefile to add -g option when compiling the lib?

**Comment by dsokoloski** [comment]
@CharlesJu1 Oh right!  My mistake...  I forgot that @lucaderi has recently removed the Automake template from ./src/lib for some reason.

I've had to re-create my own... but in the interest of getting this working for you now, just edit the file:
./src/lib/Makefile

...and add -g to the CFLAGS line you see there.

If you wish to restore automake, you can use my template Makefile [here](https://gitlab.com/netify.ai/public/netify-agent-libs/ndpi/blob/c11a155fff4aa21260a010a4a45b040649c46a28/src/lib/Makefile.am).

You should remove '-static' from libndpi_la_LDFLAGS.  Also, you need to re-add an output directive to the configure.seed to generate the Makefile:

./configure.seed, ensure AC_CONFIG_FILES includes src/lib/Makefile.  Then re-generate everything:

`# ./autogen.sh`
