### ISSUE TITLE
nDPI internals

### ISSUE THREAD

**Issue by CharlesJu1** [ntop/nDPI#581]
Is there a document on how nDPI is implemented? I want to know more about the internal of nDPI such as how a packet is captured and inspected.

**Comment by dsokoloski** [comment]
There are two documents that you can find some relevant information in.

1. The nDPI [White Paper](http://luca.ntop.org/nDPI.pdf) by @lucaderi, and...
2. The nDPI [Quick Start Guide](https://www.ntop.org/wp-content/uploads/2013/12/nDPI_QuickStartGuide.pdf).

Both are informative but don't really describe the internals of how nDPI is built.  Studying the source is the best way to understand this.  However, in a nutshell, the engine is a state machine that passes incoming packets (it's up to you to feed in the packets, usually via libpcap), to protocol "dissectors" that, as efficiently as possible, look for matches to confidently detect a flow's protocol.  The engine, by default will only examine between 8 to 10 packets (depending on IP protocol), and if no dissector matches, then a "guess" is made based on IP or port.

That's the very simple overview -- there is obviously a lot more to how it works.  Is there anything more specific that you want to know about?

**Comment by lucaderi** [comment]
Auto* tools are a nightmare, that's why

**Comment by lucaderi** [comment]
If you have time to write docs please so, we'll make a wiki
