### ISSUE TITLE
Request for the detection of memcache

### ISSUE THREAD

**Issue by tianchao-haohan** [ntop/nDPI#583]
It seems that memcache is not supported now. Is that possible to add the detection of memcache?
Memcache is a kind of widely used distributed cache. It is valuable to do the enhancement.

**Comment by dsokoloski** [comment]
I agree.  I have submitted a PR https://github.com/ntop/nDPI/pull/584 containing a dissector for Memcached.  Please test and provide feedback.  If it fails to match Memcached traffic on your network, please provide a capture (from tcpdump) to refine the dissector.

**Comment by simonemainardi** [comment]
thanks for submitting the PR. Please, follow up on the nDPI PR thread as once in nDPI the detection will automatically be included in ntopng.
