### ISSUE TITLE
Mutliple matches with hyperscan

### ISSUE THREAD

**Issue by simonemainardi** [ntop/nDPI#587]
In hyperscan there is no concept of greedy/lazy regex matching. All the matches are always returned.

It is requested to handle multiple matches that can determine ambiguous protocol detection (e.g.g,  match for youtube.com and upload.youtube.com; match for apple.com and itunes.apple.com)

IMHO, we should define NON-overlapping regexs. That will also have a positive impact on the performances as there's no need to always match a string agains all the databases and we can stop at the first match.

**Comment by lucaderi** [comment]
This ticket is no longer relevant as Hyperscn support has been removed
