### ISSUE TITLE
Hyperscan 

### ISSUE THREAD

**Issue by marcopp2018** [ntop/nDPI#597]
Hi,

  It's not clear how to compile the nDPI with Hyperscan support and what type of protocols are using this feature.

Thanks.

**Comment by lucaderi** [comment]
Hyperscan is used only with string matching protocols such as DNS, HTTP/S sub-protocols. As hyper scan is Intel-specific it is not available on non-Intel platforms.

After you installed hyperscan do ./configure --with-hyperscan and it will work
