### ISSUE TITLE
RFC: spotify.c wrong network address or mask

### ISSUE THREAD

**Issue by vel21ripn** [ntop/nDPI#615]
```
((ntohl(packet->iph->saddr) & 0xFFFFFC00 /* 255.255.252.0 */) == 0xC284A200 /* 194.132.162.0 */)
((ntohl(packet->iph->daddr) & 0xFFFFFC00 /* 255.255.252.0 */) == 0xC284A200 /* 194.132.162.0 */)
```
0xC284A200 & FFFFFC00  != 0

Wrong network address or network mask?

**Comment by kYroL01** [comment]
@vel21ripn did u pull and recompile ? I think https://github.com/ntop/nDPI/pull/604/commits solved the issue

**Comment by vel21ripn** [comment]
This commit was added to the dev branch. Maybe you can apply it to the 2.4-stable branch?

**Comment by vel21ripn** [comment]
"git cherry-pick f48c7ab8e6b0a6848aaab28ec56212787b41defa" solves this problem for the 2.4-stable branch.

**Comment by IvanNardi** [comment]
Fixed. Closing
