### ISSUE TITLE
ggpht.com is YouTube or PlayStore

### ISSUE THREAD

**Issue by vel21ripn** [ntop/nDPI#617]
grep -n '"ggpht.com"' ndpi_content_match.c.inc 
Result:
```
8106:  { "ggpht.com", NULL, "ggpht" TLD,    "PlayStore",    NDPI_PROTOCOL_PLAYSTORE, NDPI_PROTOCOL_CATEGORY_SW_UPDATE, NDPI_PROTOCOL_SAFE },
8220:  { "ggpht.com", NULL, "ggpht" TLD,     "YouTube",     NDPI_PROTOCOL_YOUTUBE, NDPI_PROTOCOL_CATEGORY_MEDIA, NDPI_PROTOCOL_FUN },
```
grep -n '"docs.googleusercontent.com"' ndpi_content_match.c.inc 
Result:
```
8098:  { "docs.googleusercontent.com", NULL, "docs\\.googleusercontent" TLD, "GoogleDocs",     NDPI_PROTOCOL_GOOGLE_DOCS, NDPI_PROTOCOL_CATEGORY_MEDIA, NDPI_PROTOCOL_ACCEPTABLE },
8099:  { "docs.googleusercontent.com", NULL, "docs.googleusercontent" TLD,   "GoogleDocs",     NDPI_PROTOCOL_GOOGLE_DOCS, NDPI_PROTOCOL_CATEGORY_MEDIA, NDPI_PROTOCOL_ACCEPTABLE },
```
How to fix it?

**Comment by kYroL01** [comment]
`ggpht.com` is the domain name for _Google image hosting_ servers, so it is used in many cases.
IMHO it is not enough to classify it as PlayStore or YouTube, we need to have more specific domain, i.e `yt3.ggpht.com` = YouTube, that is already present in the list

**Comment by kYroL01** [comment]
https://github.com/ntop/nDPI/commit/a62f90073a01d953d64a49320ba54a2dfd8e987e
