### ISSUE TITLE
Absolute library symlink including DESTDIR breaks when DESTDIR is set

### ISSUE THREAD

**Issue by hlein** [ntop/nDPI#619]
DESTDIR is used, for instance, by distros to facilitate installing to a temp path.

In general nDPI supports DESTDIR (yay!), but there's a problem in src/lib/Makefile.in:

`ln -Fs $(DESTDIR)$(libdir)/$(NDPI_LIB_SHARED) $(DESTDIR)$(libdir)/$(NDPI_LIB_SHARED_BASE)`

If DESTDIR is set, then that ends up including it in the path in the target of the symlink.

I submitted #618 to fix this.

**Comment by kYroL01** [comment]
Thanks !
