### ISSUE TITLE
nDPI quick start guide is not in sync with the latest code.  

### ISSUE THREAD

**Issue by sudeepta-bhuyan** [ntop/nDPI#62]
For eg. It talks about using the demo pcapReader application, which is not present in the latest code.
Instead ndpiReader should be used.

**Comment by lucaderi** [comment]
Can you please update it and send us the new version?

**Comment by sudeepta-bhuyan** [comment]
Sure. I'll  do that.

**Comment by sudeepta-bhuyan** [comment]
Hi Luca,
Unfortunately i don't have a Mac. So I am getting into a lot of ugly formatting issues when trying to edit the files using my word processor. Could you please send me the .pages file exported to either .doc or docx format, so that I can do  the necessary edits and send them to you.

Appreciate your help.

Thanks,
Sudeepta

**Comment by lucaderi** [comment]
Done. I have added a new Word version of the manual. Please enable "track changes" and mail me the new document for inclusion. Thanks.

**Comment by sudeepta-bhuyan** [comment]
I have sent you the new document. Thanks.
