### ISSUE TITLE
Hardcoded prefix= in src/lib/Makefile.in ignores configure --prefix=

### ISSUE THREAD

**Issue by hlein** [ntop/nDPI#620]
Building using autogen.sh + configure, --prefix is respected in general.

But not by src/lib/Makefile.in, which contains a hardcoded:

`prefix     = /usr/local`

This is used by both library and include-file installation.  So they will install into /usr/local/lib and /usr/local/include respectively, regardless of `./configure --prefix=/usr` , etc.

I don't know where the preferred place would be to set prefix=, since ./configure at the top level does not seem to (re)write the Makefile in src/lib/.  But hardcoding /usr/local surely does not seem right.

**Comment by utoni** [comment]
Fixed in 81649d9979d5069299500bc6d74fc9587cccee16.
