### ISSUE TITLE
Hardcoded libdir= in src/lib/Makefile.in means lib{32,64} is not correctly determined

### ISSUE THREAD

**Issue by hlein** [ntop/nDPI#623]
Note, this has some things in common with #620, but it is different.

Top-level 'configure' figures out the correct libdir to use - lib64 or lib32.  But src/lib/Makefile.in has a harcoded:

`libdir = ${prefix}/lib`

This has a couple of problems:

1) On a system with both 64bit and 32bit libs installed, one can't try installing nDPI built for each.

2) Although /usr/lib/ probably exists as either a dir or symlink, some distributions' packaging tools will refuse to build/install a package with a shared library that doesn't explicitly use lib32 or lib64.

As with #620, I don't know the preferred way to modify src/lib/Makefile.in to make it respect configure's arguments/choices.

**Comment by IvanNardi** [comment]
It is possible that this issue has been fixed by 780cbf5f760df3b52a62362d184b8d6df3eef2df.
@utoni , do you agree?

**Comment by utoni** [comment]
Should be fixed.
