### ISSUE TITLE
libndpi.pc.in and src/lib/Makefile.in disagree about include file path

### ISSUE THREAD

**Issue by hlein** [ntop/nDPI#625]
src/lib/Makefile.in installs headers under one path, and libndpi.pc.in (which gets cooked and installed as libndpi.pc) lists a different path.  Therefore, anything using pkg-config to get a suitable -I path will get a wrong answer, and compilation will fail.

PR #624 attempts to fix this.

**Comment by utoni** [comment]
Fixed with d31a29bf6a0c8efa11203badff3afe9f3b19ce08.
