### ISSUE TITLE
Do I need to recompile nDPI after adding IPs in  nDPI/src/lib/ndpi_content_match.c.inc?

### ISSUE THREAD

**Issue by Baymax254** [ntop/nDPI#626]
I have a running ntopng , every time I see a different IP I add it in the  nDPI/src/lib/ndpi_content_match.c.inc
 file and stop ntopng and recompile? Can I do it without recompiling?

**Comment by kYroL01** [comment]
Basically you need to recompile only nDPI library for sure. There is no way to do it without recompile.

**Comment by Baymax254** [comment]
Ok thankyou @kYroL01
