### ISSUE TITLE
youtube is not detected

### ISSUE THREAD

**Issue by romeor** [ntop/nDPI#633]
Hello,
I see the youtube app in the list, but as soon as I filter flows by app: youtube there are none. Any way to debug?
running latest nightly build installation.

**Comment by QbsuranAlang** [comment]
Due to GQUIC version, which is described in #634.

**Comment by Mile-Lile** [comment]
Here is pcap that is not recognized as youtube by ndpi... can you check it?
[yt_pcap.zip](https://github.com/ntop/nDPI/files/3586757/yt_pcap.zip)

**Comment by IvanNardi** [comment]
The provided trace is correctly decoded. Closing
