### ISSUE TITLE
QUIC version >= 39 detection failed

### ISSUE THREAD

**Issue by QbsuranAlang** [ntop/nDPI#634]
Hello, according to [dissectors of wireshark](https://github.com/wireshark/wireshark/blob/master/epan/dissectors/packet-gquic.c#L2108)
GQUIC version is greater or equal to `39` will change to "big endian", which causes the [`offset` and `prev_offset`](https://github.com/ntop/nDPI/blob/dev/src/lib/protocols/quic.c#L99) needs to swap bytes order.
At my platform(mips64 which is big endian) shows the bug.

**Comment by QbsuranAlang** [comment]
```
--- src/lib/protocols/quic.c	2018-08-22 14:29:35.000000000 +0800
+++ src/lib/protocols/quic.c	2018-10-31 20:53:58.000000000 +0800
@@ -27,6 +27,15 @@
 #define NDPI_CURRENT_PROTO NDPI_PROTOCOL_QUIC
 
 #include "ndpi_api.h"
+#include "ndpi_define.h"
+
+#if defined(__LITTLE_ENDIAN__)
+#define quic_ntohl(x) (x)
+#elif defined(__BIG_ENDIAN__)
+#define quic_ntohl(x) ((((x) & 0xff000000u) >> 24) | (((x) & 0x00ff0000u) >> 8) | (((x) & 0x0000ff00u) << 8) | (((x) & 0x000000ffu) << 24))
+#else
+#error "__BYTE_ORDER MUST BE DEFINED !"
+#endif
 
 static int quic_ports(u_int16_t sport, u_int16_t dport)
 {
@@ -96,8 +105,8 @@
 	     && (packet->payload[i+1] == 'N')
 	     && (packet->payload[i+2] == 'I')
 	     && (packet->payload[i+3] == 0)) {
-	    u_int32_t offset = *((u_int32_t*)&packet->payload[i+4]);
-	    u_int32_t prev_offset = *((u_int32_t*)&packet->payload[i-4]);
+	    u_int32_t offset = quic_ntohl(*((u_int32_t*)&packet->payload[i+4]));
+	    u_int32_t prev_offset = quic_ntohl(*((u_int32_t*)&packet->payload[i-4]));
 	    int len = offset-prev_offset;
 	    int sni_offset = i+prev_offset+1;
```

It should fixed the bug.

**Comment by QbsuranAlang** [comment]
Update here

The [doc](https://docs.google.com/document/d/1WJvyZflAO2pq77yOLbp9NsGjC1CHetAXV8I0fQe-B_U/) says:
> All integer values used in QUIC, including length, version, and type, are in **little-endian** byte order, and not in network byte order. QUIC does not enforce alignment of types in dynamically sized frames.

Which means [offset and prev_offset](https://github.com/ntop/nDPI/blob/dev/src/lib/protocols/quic.c#L99) works fine at little-endian, but big-endian.

And [dissectors of wireshark](https://github.com/wireshark/wireshark/blob/master/epan/dissectors/packet-gquic.c#L2108):
> /* After Q039, Integers and floating numbers are written in big endian*/

It definitely goes wrong someday.

**Comment by lucaderi** [comment]
@QbsuranAlang Do you have a pcap to use for testing?

**Comment by QbsuranAlang** [comment]
@lucaderi 
[GQUIC.zip](https://github.com/ntop/nDPI/files/2662812/GQUIC.zip)
There are three pcap files in attachment.
Q024.pcap(GMail), Q039.pcap(Youtube) and Q043.pcap(Youtube).

**Comment by QbsuranAlang** [comment]
Q044 has started the transition to IETF QUIC. I am not test yet, but I have a pcap sample.
[Q044.pcap.zip](https://github.com/ntop/nDPI/files/2686447/Q044.pcap.zip)

The latest wireshark can dissectors the pcap sample, it can be downloaded [here](https://www.wireshark.org/download/automated/)

**Comment by cavedon** [comment]
https://github.com/ntop/nDPI/pull/658 fixes this issue

**Comment by IvanNardi** [comment]
This (old) issue can be closed: nDPI detects all recent GQUIC versions (and some of the older versions).
To be fair, Q044 is not supported by current code (I am not sure if it was before 23ec82b5) but it is not supported anymore from Google/Chrome either, so you shouldn't find it on live traffic.
If someone is really, really interested in such a version they could open a dedicated issue
