### ISSUE TITLE
Current example/Makefile.in missing slash after path. Overwrites /usr/local/bin with the ndpiReader executable.

### ISSUE THREAD

**Issue by emarshswe** [ntop/nDPI#637]
https://github.com/ntop/nDPI/blob/71b2c19cf28f72ad2e876719af88c7841c2aea84/example/Makefile.in#L17

**Comment by kYroL01** [comment]
So , you say must be `cp ndpiReader $(DESTDIR)$(PREFIX)/bin/` , right ?

**Comment by emarshswe** [comment]
Yes, after testing, that last slash fixes the problem. The current code works on OSX if there is a bin folder present, but breaks on my fresh debian install. We should use full paths just to be sure. Maybe we need to make sure the path exists or is created, so we don't get an error if there's no bin folder?

is "mkdir -p /usr/local/bin" safe to run on existing folders? Works in both OSX and debian 9 for me but I could be mistaken about other variants.


Sorry for not making a PR. I messed up my local branch and need to do a fresh checkout :-)
