### ISSUE TITLE
Debug Xbox protocol dissector

### ISSUE THREAD

**Issue by rkerur** [ntop/nDPI#648]
(1) How to enable nDPI debugs. I tried './configure --enable-debug-message' followed by make and use ndpireader. I don't see any debugs on console or log file in /var/log? GDB on Apple MAC (my test platform) has some issues so I need debugs to work.

(2) I have a xbox game pcap which is classified as 'Unknown' by nDPI. In PCAP files most of the packets are UDP and on port 3076.  In src/lib/protocols/xbox.c I see dissector is initialized as follows which is only v4/v6+TCP and no UDP. I have modified code to accept UDP as well but it doesn't work. My hunch is 'ndpi_search_xbox' function is not getting called and I want to debug that. Also let me know where in the code 'ndpi_search_xbox' which is initialized as a function pointer gets invoked?

 ndpi_set_bitmask_protocol_detection("Xbox", ndpi_struct, detection_bitmask, *id,
                                      NDPI_PROTOCOL_XBOX,
                                      ndpi_search_xbox,
                                      NDPI_SELECTION_BITMASK_PROTOCOL_V4_V6_TCP_WITH_PAYLOAD,
                                      NO_SAVE_DETECTION_BITMASK_AS_UNKNOWN,
                                      ADD_TO_DETECTION_BITMASK);

**Comment by vel21ripn** [comment]
Use "ndpReader -V 4 ... " or "ndpiReader -V 3 -dbg-proto  Xbox ..." for output debug messages.

**Comment by kYroL01** [comment]
@rkerur well, actually if u look the dissector is the opposite of what u said.
https://github.com/ntop/nDPI/blob/dev/src/lib/protocols/xbox.c#L45
it looks ONLY UDP traffic, not TCP (there is a note you can read).

**Comment by rkerur** [comment]
Thanks, let me work on the debugs and get back to you if I have additional questions.

Regarding code, what you mentioned is correct i.e. it checks for 'packet->udp != NULL', however, when dissector is initialized via 'init_xbox_dissector' one of the function param to nDPI is 
NDPI_SELECTION_BITMASK_PROTOCOL_V4_V6_TCP_WITH_PAYLOAD
Doesn't it allow only v4/v6 TCP packets? if not, what is this bitmask used for?

**Comment by kYroL01** [comment]
@rkerur absolutely. I think your right.

**Comment by lucaderi** [comment]
@rkerur Can you please share a pcap for inspection?

**Comment by rkerur** [comment]
@lucaderi Will upload  pcap file this week.

**Comment by rkerur** [comment]
File size is the issue for Xbox pcap file, Kindly let me know other way I can send it.

**Comment by lucaderi** [comment]
Please let us know if xbox detection is now working and reopen this ticket if necessary
