### ISSUE TITLE
Query - enabling ndpi Debug 

### ISSUE THREAD

**Issue by mallesh-thotager** [ntop/nDPI#656]
Hi All,
Compiled the nDPI using the below commands

./autogen.sh
./configure    --enable-debug-messages 
make

But the still  the inclusion of ndpi_config.h is under HAVE_CONFIG_H (ndpi_main.c).

How to get his macro HAVE_CONFIG_H enabled during the compilation? 

Thanks.

**Comment by IvanNardi** [comment]
It should work as expected since 56d87186. Closing
