### ISSUE TITLE
the variable buf_len in function ac_match_handler() is always 0

### ISSUE THREAD

**Issue by hans2003** [ntop/nDPI#660]

**Comment by lucaderi** [comment]
Not sure you're right. Please explain more in detail

**Comment by hans2003** [comment]
static int ac_match_handler(AC_MATCH_t *m, AC_TEXT_t *txt, AC_REP_t *match) {
  int min_len = (txt->length < m->patterns->length) ? txt->length : m->patterns->length;
  **char buf[64] = { '\0' }; // initial buf here, the length of buf string is 0.**
  int min_buf_len = (txt->length > 63 /* sizeof(buf)-1 */) ? 63 : txt->length;
  **u_int buf_len = strlen(buf); // here，calculate buf_len by strlen；it is 0**   

  **strncpy(buf, txt->astring, min_buf_len);
  buf[min_buf_len] = '\0'; //here，reassign buf; not calculate buf_len，so buf_len is also 0**

#ifdef MATCH_DEBUG
  printf("Searching [to search: %s/%u][pattern: %s/%u] [len: %u][match_num: %u][%s]\n",
:    buf, txt->length, m->patterns->astring, m->patterns->length, min_len,
:    m->match_num, m->patterns->astring);
#endif

  /*
    Return 1 for stopping to the first match.
    We might consider searching for the more
    specific match, paying more cpu cycles.
  */

  memcpy(match, &m->patterns[0].rep, sizeof(AC_REP_t));

  if(((buf_len >= min_len) && (strncmp(&buf[buf_len-min_len], m->patterns->astring, min_len) == 0))
     || (strncmp(buf, m->patterns->astring, min_len) == 0) /* begins with */
     )
    {
#ifdef MATCH_DEBUG
      printf("Found match [%s][%s] [len: %u][proto_id: %u]\n",
:        buf, m->patterns->astring, min_len, *matching_protocol_id);
#endif
    return(1); /* If the pattern found matches the string at the beginning we stop here */
  } else
    return 0; /* 0 to continue searching, !0 to stop */
}

**Comment by utoni** [comment]
Not valid anymore after c418b7110b9385c5c3748c10e198df27ae0f7083 was merged.
