### ISSUE TITLE
Q on idle_flows and pcap_analysis_duration

### ISSUE THREAD

**Issue by rkerur** [ntop/nDPI#664]
nDPI team,

I am seeing an issue when 'pcap_analysis_duration' is given as an option to ndpiReader. By default 'pcap_analysis_duration = -1'. I understand 'ndpiReader' is just a sample application, would like to understand whether it is correct or a bug?

In function 'ndpi_process_packet' which is called by PCAP library or from while(dpdk_run_capture), a check is made 

       **if((pcap_end.tv_sec-pcap_start.tv_sec) > pcap_analysis_duration) {**
             ...
                printResults(processing_time_usec, setup_time_usec);

                for(i=0; i<ndpi_thread_info[thread_id].workflow->prefs.num_roots; i++) {
                         ndpi_tdestroy(ndpi_thread_info[thread_id].workflow->ndpi_flows_root[i], ndpi_flow_info_freer);
                        ndpi_thread_info[thread_id].workflow->ndpi_flows_root[i] = NULL;

                        memset(&ndpi_thread_info[thread_id].workflow->stats, 0, sizeof(struct ndpi_stats));
                }
        }

By default above code never gets executed so everything is ok. If 'pcap_analysis_duration = <some_val>', after printing results, code cleans up/destroys every flow. In my opinion it should just reset stats.  Any reason why flow clean up is done?

For example, my setup is Host-X-----DPI----Host-Y

Ping/iperf from Host-X to Host-Y, I do see for every 'pcap_analysis_duration', old flow is destroyed and a new flow is created.

**Comment by lucaderi** [comment]
This is done to check memory is properly allocated/freed
