### ISSUE TITLE
Inconsistent youtube detection

### ISSUE THREAD

**Issue by rkerur** [ntop/nDPI#668]
nDPI team,

I am using latest nDPI library code and doing some live traffic testing with different applications. Network traffic like ICMP, DHCP, DNS are consistently classified correctly. With Youtube traffic 3 out of   5 times it failed to classify correctly. I have tested Youtube traffic with both 'Chrome' and 'Firefox' browser and before I start traffic I clear browsing data on them. Unfortunately I cannot run tcpdump to capture packets from nDPI node as there are other users traffic going through that node. 

In function packet_processing from ndpiReader application, I changed following condition to check for 20 packets but it didn't help.

if((flow->detected_protocol.app_protocol != NDPI_PROTOCOL_UNKNOWN)
     || ((proto == IPPROTO_UDP) && ((flow->src2dst_packets + flow->dst2src_packets) > 8))
     || ((proto == IPPROTO_TCP) && ((flow->src2dst_packets + flow->dst2src_packets) > 10))) {

Inputs on how to debug this? Does 'Ntopng' which also used nDPI do differently?

**Comment by lucaderi** [comment]
You need to report with a pcap (you can do it on your PC) and explain how to reproduce it as otherwise I cannot help you

**Comment by Mile-Lile** [comment]
[yt_pcap.zip](https://github.com/ntop/nDPI/files/3586836/yt_pcap.zip)

**Comment by lucaderi** [comment]
seems to work reliably in the current version
