### ISSUE TITLE
CustomCategory File format

### ISSUE THREAD

**Issue by rkerur** [ntop/nDPI#669]
in nDPI there is a way to load/enable custom category files, however, Iam unable to find the format of entries to add to that file. For example following code snippets shows loading ip_category or host_name. Can someone point me to an example of custom category file?

if(_customCategoryFilePath) {
    FILE *fd = fopen(_customCategoryFilePath, "r");

    if(fd) {
      while(fd) {
        char buffer[512], *line, *name, *category;
        int i;

        if(!(line = fgets(buffer, sizeof(buffer), fd)))
          break;

        if(((i = strlen(line)) <= 1) || (line[0] == '#'))
          continue;
        else
          line[i-1] = '\0';

        name = strtok(line, "\t");
        if(name) {
          category = strtok(NULL, "\t");

          if(category) {
            int fields[4];

            // printf("Loading %s\t%s\n", name, category);

            if(sscanf(name, "%d.%d.%d.%d", &fields[0], &fields[1], &fields[2], &fields[3]) == 4)
              ndpi_load_ip_category(ndpi_thread_info[thread_id].workflow->ndpi_struct,
                                    name, (ndpi_protocol_category_t)atoi(category));
            else
              ndpi_load_hostname_category(ndpi_thread_info[thread_id].workflow->ndpi_struct,
                                          name, (ndpi_protocol_category_t)atoi(category));
          }
        }
      }

**Comment by rkerur** [comment]
Figured it out.

**Comment by maheeshap** [comment]
Hi, could you provide a sample of the format you ended up using?
Cheers
