### ISSUE TITLE
WhatsApp Detection 

### ISSUE THREAD

**Issue by alrferreira** [ntop/nDPI#67]
Hello guys. Congratulations for the work!
In my tests,  the version 1.6 is not properly detecting/blocking Whatsapp messages.
Can confirm me if I have done wrong?

**Comment by kYroL01** [comment]
Hello @alrferreira .
Can you detect a pcap of your Whatsapp session that is not properly detecting ?
Thank you

**Comment by alrferreira** [comment]
Hello @kYroL01.

Follows pcap files:
http://www.netdeep.com.br/tmp/whatsapp_with_ndpi_rule.pcap
http://www.netdeep.com.br/tmp/whatsapp_without_ndpi_rule.pcap

Thanks!

**Comment by kYroL01** [comment]
Thank you. 
We try to fix all in following days.

**Comment by alrferreira** [comment]
Any news? Did you detected the issue?

**Comment by lucaderi** [comment]
How did run your tests? Did you use ntopng in bridge mode?

**Comment by alrferreira** [comment]
I used tcpdump in my firewall. 

André Luiz R. Ferreira

-----Mensagem Original-----
De: "Luca Deri" notifications@github.com
Enviada em: ‎09/‎08/‎2015 04:42
Para: "ntop/nDPI" nDPI@noreply.github.com
Cc: "André L. R. Ferreira" alrferreira@netdeep.com.br
Assunto: Re: [nDPI] WhatsApp Detection  (#67)

How did run your tests? Did you use ntopng in bridge mode?
—
Reply to this email directly or view it on GitHub.
**\* Secured by Netdeep ClearMail ***

**Comment by lucaderi** [comment]
Ok but who is supposed to block you WhatsApp? You complain as there is an issue on nDPI but it is not clear why you think so and who should block this traffic.

**Comment by alrferreira** [comment]
I did a test with nDPI, integrated with iptables (version 1.6).
It worked with most applications, but with Whatsapp, is not blocking anymore. Before he could block.

See the used syntax:
iptables -I FORWARD -o eth1 -m ndpi --whatsapp -j DROP

So I captured traffic and send it to help me identify what happens.

**Comment by lucaderi** [comment]
We do not support this module, please contact its coder. We have asked several times to send us a patch so that we can update the code of this kernel module inside nDPI but nobody helped. Thus I cannot assist you unfortunately.
