### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [ntop/nDPI#670]
I would like to point out that an identifier like “[`__NDPI_API_H__`](https://github.com/ntop/nDPI/blob/efef99cbadc8ddd6f6743e04d184fe240d6eb334/src/include/ndpi_api.h#L25 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by lucaderi** [comment]
Please propose a fix via a pull request. Thanks
