### ISSUE TITLE
Add nDPI support for Evernote application

### ISSUE THREAD

**Issue by alrferreira** [ntop/nDPI#68]
Hello,
Please add nDPI support for Evernote (notes application generally in mobile devices) 

Follows trace (tested login, synchronization, and changing a note):
http://www.netdeep.com.br/tmp/evernote.pcap

Thanks!

**Comment by lmangani** [comment]
Have you tried using a protocol file definition, ie:

```
#  Subprotocols
#  Format:
#  host:"<value>",host:"<value>",.....@<subproto>
host:"evernote.com",host:"sandbox.evernote.com"@Evernote

#  IP based Subprotocols
#  Format:
#  ip:<value>,ip:<value>,.....@<subproto>
ip:204.154.94.81,ip:216.104.243.26@Evernote
```

**Comment by feriel-ux** [comment]
what is the other solution to add a custom protocol without this proto.txt file ( add a source code for that protocol ) any tips ? and thank you ?
