### ISSUE TITLE
Viber additional IPs

### ISSUE THREAD

**Issue by clebig** [ntop/nDPI#684]
Hi,

I don't know if this is relevant because it's maybe not enough generic (/32) to be put in ndpi code, but I have found a set of IPs that are not currently included in the Viber prefixes defined in ndpi_content_match.c.inc.

Those IP are : 
52.3.167.70/32
52.22.44.235/32
52.22.95.15/32
54.85.84.93/32
54.85.86.93/32

Clément

**Comment by dark-vex** [comment]
I have created a PR for these IPs, they don't appear from the whois data to be part of Viber but after trying to access via browser to the reported IPs you can clearly see that it's Viber

**Comment by emarshswe** [comment]
This should be closed.
