### ISSUE TITLE
Packets are not classfied or updated with correct category

### ISSUE THREAD

**Issue by rkerur** [ntop/nDPI#689]
Packets are not classified with correct category

**Comment by rkerur** [comment]
Hi Luca,

There is a possible regression with your recent changes where packets category is not updated correctly. Can you please check?

I had 03/30 repo and when I run ICMP traffic it used to classify as 'Network' Category. I updated to latest code which has your code changes for handling category and ICMP traffic are no longer classified as 'Network'.

Thanks.

**Comment by rkerur** [comment]
Hi Luca,

I have tracked down the changes which is causing the issue on my testbed to "Improved-flow-category-guess" patch. I made following changes in function 'ndpi_fill_protocol_category' by commenting new code and adding old code back and everything works fine. I am not sure about the difference in our testing as we are getting different results with the latest code. For me everything worked as expected in 03/30 and issue started after update. Please advise.

void ndpi_fill_protocol_category(struct ndpi_detection_module_struct *ndpi_struct,
                                 struct ndpi_flow_struct *flow,
                                 ndpi_protocol *ret) {
  if(ndpi_struct->custom_categories.categories_loaded) {
/* Add old code back */
    if(flow->packet.iph) {
      if(ndpi_fill_ip_protocol_category(ndpi_struct, flow->packet.iph->saddr, flow->packet.iph->daddr, ret)) {
        flow->category = ret->category;
        return;
      }
    }
#if 0 /* Comment new code */
    if(flow->guessed_header_category != NDPI_PROTOCOL_CATEGORY_UNSPECIFIED) {
      flow->category = flow->guessed_header_category;
      return;
    } 
#endif

Thanks,
Ravi

**Comment by utoni** [comment]
This issue was probably fixed with ca15e3295. Please open a new issue, if it still exists.
