### ISSUE TITLE
Add nDPI support for TED application

### ISSUE THREAD

**Issue by alrferreira** [ntop/nDPI#69]
Please add nDPI support for TED (video conference platform application). 

Trace is here:
http://www.netdeep.com.br/tmp/TED.pcap

Thanks!

**Comment by kYroL01** [comment]
Maybe we take more time to do all because we are busy. Be patience please.

Thank you

**Comment by alrferreira** [comment]
Ok. No problem. 
Meanwhile, I'm testing other commonly used applications (icq, snapchat, tinder, facebook messenger, play store, google plus, imo, dubsmash, 4shared, linkedin, etc) and will send the pcap file of the monitored traffic.

**Comment by lucaderi** [comment]
The pcap trace is gone, so I cannot implement this.

**Comment by feriel-ux** [comment]
I want to add a new custom protocol on nDPI ( e.g : shahid.mbc.net ) , but I want ndpi detect the protocol when I build and add a source code for this protocol ( not in protos.txt with the host )

**Comment by feriel-ux** [comment]
why do I need a pcap file to add a custom protocol ? for what purpose ?
