### ISSUE TITLE
nDPI and video games classification

### ISSUE THREAD

**Issue by rkerur** [ntop/nDPI#699]
Hi nDPI team,

I will be evaluating nDPI for video game classification and wanted to check with the team on testing/evaluation done so far. If yes, can you please share the information?

From the code I see following protocol files under src/lib/protocols 

(1) world_of_kungfu.c
(2) world_of_warcraft.c
(3) battlefield.c
(4) warcraft3.c
(5) Starcraft.c

so I am assuming those should be supported.

Thanks.

**Comment by mmanoj** [comment]
@rkerur 

If you have the latest pcap for above-mentioned applications, try the detection via nDPIReader app.

**Comment by emarshswe** [comment]
This should be closed. Also, this is a question not an issue.

**Comment by utoni** [comment]
Please open a new issue if protocol detection does not work as expected.
