### ISSUE TITLE
Kakao Talk

### ISSUE THREAD

**Issue by adamzvikler** [ntop/nDPI#7]
This App is very popular in the Far East. Can you support it? 

How can I send you traces for Kakao talk? I get a message 'unfortunately, we don't support that file type'

**Comment by lucaderi** [comment]
Please send a merge request for a file to put inside https://github.com/ntop/nDPI/tree/dev/tests/pcap

**Comment by adamzvikler** [comment]
How do I do that? I couldn't find a merge option

**Comment by lucaderi** [comment]
https://help.github.com/articles/creating-a-pull-request/

**Comment by lucaderi** [comment]
@adamzvikler We moved this issue to https://github.com/ntop/nDPI/issues/13.
Can you please send me a pcap file to reproduce the issue?
