### ISSUE TITLE
Perfromance debugging issue

### ISSUE THREAD

**Issue by pavel-odintsov** [ntop/nDPI#70]
Hello, folks!

Thanks for your brilliant work!

I have run nDPI on Network with 500 kpps load (per packet analitics mode) and expect significant performance issues, I can't achieve more than 250 kpps. Thus, I have tried to debug it but have some troubles with debugging symbols.

In perf top I saw:

```
Samples: 775K of event 'cycles', Event count (approx.): 49347133671
  19.00%  libc-2.19.so              [.] __memcmp_sse4_1
   4.31%  libc-2.19.so              [.] memset
   3.20%  libndpi.so.1.0.0          [.] 0x00000000000089ca
   3.20%  libndpi.so.1.0.0          [.] 0x00000000000089b0
   2.98%  libndpi.so.1.0.0          [.] 0x00000000000089c5
   2.58%  libndpi.so.1.0.0          [.] memcmp@plt
   1.81%  libndpi.so.1.0.0          [.] 0x00000000000089bf
   1.79%  libndpi.so.1.0.0          [.] 0x0000000000009d88
   1.75%  libc-2.19.so              [.] _int_free
   1.44%  libndpi.so.1.0.0          [.] ndpi_detection_process_packet
   1.39%  libc-2.19.so              [.] malloc
   1.34%  libndpi.so.1.0.0          [.] 0x0000000000009d98
   1.08%  libc-2.19.so              [.] _int_malloc
   0.96%  libndpi.so.1.0.0          [.] 0x000000000000a404
   0.90%  ndpicallback.so           [.] fastnetmon_parse_pkt
```

But my binary is not stripped:

``` bash
file /opt/ndpi/lib/libndpi.so.1.0.0 
/opt/ndpi/lib/libndpi.so.1.0.0: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=3fbf0ef7daee47da17d55984d3184baf414340a2, not stripped
```

And have all important symbols:

``` bash
nm /opt/ndpi/lib/libndpi.so.1.0.0 |grep process
000000000000fc10 T ndpi_detection_process_packet
0000000000007400 t ndpi_patricia_process
```

I have installed my nDPI binary with following reference:

```
cd /usr/src
git clone https://github.com/ntop/nDPI.git
cd nDPI/
./autogen.sh
./configure --prefix=/opt/ndpi
make install
echo "/opt/ndpi/lib" >  /etc/ld.so.conf.d/ndpi.conf
ldconfig
```

Maybe you could help me with this "unidentified" functions?

**Comment by lucaderi** [comment]
Pavel
first of all please disable -O2 and add -g for debugging.

This said, nDPI is a library, not a networking bridge as ntopng. So I am unable to assist as it is used inside your code. Please try to reproduce the issue with ndpiReader. Thanks.

**Comment by pavel-odintsov** [comment]
Luca, I speaking about another thing :)  

Perf top correctly show functions from my code (i.e. I have -g -O0). But I want to build nDPI itself with debug enabled and can't find any options in configure for this.

**Comment by lucaderi** [comment]
Edit src/lib/Makefile after configure and add your options

**Comment by pavel-odintsov** [comment]
What about nice option for configure?=) Folks from Debian have added -dbg package and it's very useful
