### ISSUE TITLE
Add TLS/SSL cipher suite dissection

### ISSUE THREAD

**Issue by simonemainardi** [ntop/nDPI#705]
It is request to extract the cipher suite for SSL flows and to make it available.

It is also desired to create a static method which maps cipher suites to their corresponding string descriptions so that one can easily convert the cipher suite byte to a meaningful description.

See https://github.com/wireshark/wireshark/blob/3a2e290c331f03b2467d49d5c04151aab9f1a4d9/epan/dissectors/packet-tls-utils.c#L119

**Comment by lucaderi** [comment]
In essence this issue boil down to find out whether used ciphers are safe or not.
