### ISSUE TITLE
Add TLS/SSL certificate expiration date

### ISSUE THREAD

**Issue by simonemainardi** [ntop/nDPI#706]
It is requested to dissect and make available the expiration date of the server and client (if present) certificates.

**Comment by jandersonbt** [comment]
I second this.  However, I would also like to have the not_before date from the certificate.  Attached is a screenshot from wireshark showing the not_before and not_after dates in the packet information.
![wireshare_certificate](https://user-images.githubusercontent.com/29073162/61651084-5b542080-ac72-11e9-937a-a4a72f3c34f1.png)

**Comment by jandersonbt** [comment]
Would it be possible to get some sort of timeline as to when this feature can be implemented in nDPI?  Thanks!

**Comment by emarshswe** [comment]
This is implemented now right? the issues should be closed.

**Comment by lucaderi** [comment]
Implemented
