### ISSUE TITLE
Function get_ndpi_flow_info6() does not handle extension headers correctly

### ISSUE THREAD

**Issue by jvgee** [ntop/nDPI#708]
Function get_ndpi_flow_info6() does not handle IPv6 extension headers correctly/completely.  As a result, when I run:
```
./ndpiReader -q -i icmpv6.pcap -v 1
```
the output is:
```
        1       0 [fe80::e2f8:47ff:fe21:c9d6]:0 -> [ff02::1:ff21:c9d6]:0 [proto: 102/ICMPV6][cat: Network/14][2 pkts/172 bytes -> 0 pkts/0 bytes]
```
instead of:
```
        1       ICMPV6 [fe80::e2f8:47ff:fe21:c9d6]:0 -> [ff02::1:ff21:c9d6]:0 [proto: 102/ICMPV6][cat: Network/14][2 pkts/172 bytes -> 0 pkts/0 bytes]
```

The icmpv6.pcap file used for this test can be obtained by downloading [bigFlows.pcap](https://s3.amazonaws.com/tcpreplay-pcap-files/bigFlows.pcap) and applying this wireshark filter:
```
ipv6.addr == fe80::e2f8:47ff:fe21:c9d6 and ipv6.addr == ff02::1:ff21:c9d6
```

**Comment by IvanNardi** [comment]
Fixed a long time ago. Closing
