### ISSUE TITLE
API for attribute extraction

### ISSUE THREAD

**Issue by ofercetown** [ntop/nDPI#709]
Hi,

I'd like to know if there is a kind of standard API to get all metadata/attributes from nDPI.
My understanding is that all attribute/metadata are stored in dedicated structures defined in src/include/ndpi_typedefs.h, am I correct ?

What I'm looking is an interface to get metadata from a flow without having to handle C struct.
Something like get_metadata(flow) which could return an array of generic stuct/TLV which describes the data.

Finally, do you have any idea of exact number of metadata/attribute in current nDPI project.

**Comment by utoni** [comment]
> I'd like to know if there is a kind of standard API to get all metadata/attributes from nDPI. My understanding is that all attribute/metadata are stored in dedicated structures defined in src/include/ndpi_typedefs.h, am I correct ?

Basically correct, yes.

> What I'm looking is an interface to get metadata from a flow without having to handle C struct. Something like get_metadata(flow) which could return an array of generic stuct/TLV which describes the data.

There is no such interface function in nDPI.
You can use the serialization interface, but this is not the same as it does not provide you with all information stored in those structs.
