### ISSUE TITLE
performing DPI for http pipeline

### ISSUE THREAD

**Issue by imvisiontech** [ntop/nDPI#71]
Hi,
Is it possible to work with ndpi to capture multiple requests and responses in a single http session (http pipeline support)?
The example code  demonstrates only single request-response detection.

thanks,
Shirley.

**Comment by lucaderi** [comment]
nDPI does not capture but analyzes traffic that has to be captured by other means (e.g. PF_RING). This said, pipeline or not, nDPI can be used to detect HTTP traffic and this is what it does.
