### ISSUE TITLE
Add Antimalware category

### ISSUE THREAD

**Issue by emanuele-f** [ntop/nDPI#710]
A new "Antimalware" category should be added for the reason described in https://github.com/ntop/ntopng/issues/2571

**Comment by lucaderi** [comment]
This feature opens up a new problem: sites falling under CUSTOM_CATEGORY_ANTIMALWARE must keep their original protocol (e.g. DNS) while having CUSTOM_CATEGORY_ANTIMALWARE as category.
Awaiting @zimbawe998 first to provide the sites list and then deciding what to do

**Comment by zimbawe998** [comment]
There arent a full list of Antivirus url called by dns query to verify live sha/md5 for an unknown files, so it will be smart to allow a new category and specify on it the last part of the query used by them, avoiding DNS alerting.
Some Example *.sophosxl.net, url.trendmicro.com, url.trendmicro.com.akadns.net

**Comment by emanuele-f** [comment]
This will be implemented in a simpler way as described into the ntopng issue
