### ISSUE TITLE
Compilation Error "fatal error: ndpi_api.h: No such file or directory"

### ISSUE THREAD

**Issue by shahzad46** [ntop/nDPI#712]
Hello Everyone!
Just cloned nDPI, followed all readme steps to setup nDPI.
Performed all the `tests`
Tested `ndpiReader` example with some pcap files. All good upto here.
Now i want to use nDPI in my own C program but when I try to compile the C code it gives the above error. here is the CLI log:
 `ubuntu@sdnhubvm:~/nDPI/example[00:40] (dev)$ gcc myfun.c -o exe 
ndpiReader.c:50:22: fatal error: ndpi_api.h: No such file or directory
 #include "ndpi_api.h"
                      ^
compilation terminated.
`

What am I missing here?
BDW my long term goal is to use nDPI's MQTT library to dissect incoming packets for MQTT payload. I have already dissect up tp TCP using "inet" libraries. I am already capturing packets with libpcap and extracting headers up to TCP.

**Comment by dsokoloski** [comment]
@shahzad46 ensure you compile the nDPI code as a library: -D NDPI_LIB_COMPILATION=1
