### ISSUE TITLE
C compiler cannot create executables

### ISSUE THREAD

**Issue by shahzad46** [ntop/nDPI#713]
Need Help!! When I execute `sudo ./autogen.sh` I get the following error.
`ubuntu@sdnhubvm:~/nDPI[21:56] (dev)$ sudo ./autogen.sh
autoreconf: Entering directory .
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
autoreconf: Leaving directory `.'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/ubuntu/nDPI':
configure: error: C compiler cannot create executables
See `config.log' for more details'`
And here is the config.log 
`This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by libndpi configure 2.9.0, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure 

## --------- ##

hostname = sdnhubvm
uname -m = x86_64
uname -r = 3.13.0-24-generic
uname -s = Linux
uname -v = #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /usr/sbin
PATH: /usr/bin
PATH: /sbin
PATH: /bin
PATH: /snap/bin

## ----------- ##

configure:2404: checking for a BSD-compatible install
configure:2472: result: /usr/bin/install -c
configure:2483: checking whether build environment is sane
configure:2538: result: yes
configure:2689: checking for a thread-safe mkdir -p
configure:2728: result: /bin/mkdir -p
configure:2735: checking for gawk
configure:2751: found /usr/bin/gawk
configure:2762: result: gawk
configure:2773: checking whether make sets $(MAKE)
configure:2795: result: yes
configure:2824: checking whether make supports nested variables
configure:2841: result: yes
configure:2996: checking build system type
configure:3010: result: x86_64-unknown-linux-gnu
configure:3030: checking host system type
configure:3043: result: x86_64-unknown-linux-gnu
configure:3084: checking how to print strings
configure:3111: result: printf
configure:3144: checking for style of include used by make
configure:3172: result: GNU
configure:3243: checking for gcc
configure:3259: found /usr/bin/gcc
configure:3270: result: gcc
configure:3499: checking for C compiler version
configure:3508: gcc --version >&5
gcc (Ubuntu 7.4.0-1ubuntu1~14.04~ppa1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:3519: $? = 0
configure:3508: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.4.0-1ubuntu1~14.04~ppa1' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=gcc4-compatible --disable-libstdcxx-dual-abi --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~14.04~ppa1) 
configure:3519: $? = 0
configure:3508: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3519: $? = 1
configure:3508: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'; did you mean '--version'?
gcc: fatal error: no input files
compilation terminated.
configure:3519: $? = 1
configure:3539: checking whether the C compiler works
configure:3561: gcc    conftest.c  >&5
collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
compilation terminated.
configure:3565: $? = 1
configure:3603: result: no
configure: failed program was:
| /* confdefs.h */
| #define NDPI_PACKAGE_NAME "libndpi"
| #define NDPI_PACKAGE_TARNAME "libndpi"
| #define NDPI_PACKAGE_VERSION "2.9.0"
| #define NDPI_PACKAGE_STRING "libndpi 2.9.0"
| #define NDPI_PACKAGE_BUGREPORT ""
| #define NDPI_PACKAGE_URL ""
| #define NDPI_PACKAGE "libndpi"
| #define NDPI_VERSION "2.9.0"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3608: error: in `/home/ubuntu/nDPI':
configure:3610: error: C compiler cannot create executables
See `config.log' for more details

## ---------------- ##

ac_cv_build=x86_64-unknown-linux-gnu
ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_CXXCPP_set=
ac_cv_env_CXXCPP_value=
ac_cv_env_CXXFLAGS_set=
ac_cv_env_CXXFLAGS_value=
ac_cv_env_CXX_set=
ac_cv_env_CXX_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=x86_64-unknown-linux-gnu
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/bin/mkdir
ac_cv_prog_AWK=gawk
ac_cv_prog_ac_ct_CC=gcc
ac_cv_prog_make_make_set=yes
am_cv_make_support_nested_variables=yes

## ----------------- ##

ACLOCAL='${SHELL} /home/ubuntu/nDPI/missing aclocal-1.14'
AMDEPBACKSLASH='\'
AMDEP_FALSE='#'
AMDEP_TRUE=''
AMTAR='$${TAR-tar}'
AM_BACKSLASH='\'
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='1'
AM_V='$(V)'
AR=''
AUTOCONF='${SHELL} /home/ubuntu/nDPI/missing autoconf'
AUTOHEADER='${SHELL} /home/ubuntu/nDPI/missing autoheader'
AUTOMAKE='${SHELL} /home/ubuntu/nDPI/missing automake-1.14'
AWK='gawk'
CC='gcc'
CCDEPMODE=''
CFLAGS=''
CPP=''
CPPFLAGS=''
CXX=''
CXXCPP=''
CXXDEPMODE=''
CXXFLAGS=''
CYGPATH_W='echo'
DEFS=''
DEPDIR='.deps'
DLLTOOL=''
DL_LIB=''
DPDK_TARGET=''
DSYMUTIL=''
DUMPBIN=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
EXEEXT=''
FGREP=''
GIT_RELEASE=''
GREP=''
HAVE_PTHREAD_SETAFFINITY_NP=''
HS_INC=''
HS_LIB=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
JSON_C_LIB=''
LD=''
LDFLAGS=''
LIBOBJS=''
LIBS=''
LIBTOOL=''
LIPO=''
LN_S=''
LTLIBOBJS=''
MAKEINFO='${SHELL} /home/ubuntu/nDPI/missing makeinfo'
MANIFEST_TOOL=''
MKDIR_P='/bin/mkdir -p'
NDPI_MAJOR=''
NDPI_MINOR=''
NDPI_PATCH=''
NDPI_VERSION_SHORT=''
NM=''
NMEDIT=''
OBJDUMP=''
OBJEXT=''
OTOOL64=''
OTOOL=''
PACKAGE='libndpi'
PACKAGE_BUGREPORT=''
PACKAGE_NAME='libndpi'
PACKAGE_STRING='libndpi 2.9.0'
PACKAGE_TARNAME='libndpi'
PACKAGE_URL=''
PACKAGE_VERSION='2.9.0'
PATH_SEPARATOR=':'
PCAP_INC=''
PCAP_LIB=''
PTHREAD_CC=''
PTHREAD_CFLAGS=''
PTHREAD_LIBS=''
RANLIB=''
SED=''
SET_MAKE=''
SHELL='/bin/bash'
STRIP=''
SVN_DATE=''
VERSION='2.9.0'
ac_ct_AR=''
ac_ct_CC='gcc'
ac_ct_CXX=''
ac_ct_DUMPBIN=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__fastdepCXX_FALSE=''
am__fastdepCXX_TRUE=''
am__include='include'
am__isrc=''
am__leading_dot='.'
am__nodep='_no'
am__quote=''
am__tar='$${TAR-tar} chof - "$$tardir"'
am__untar='$${TAR-tar} xf -'
ax_pthread_config=''
bindir='${exec_prefix}/bin'
build='x86_64-unknown-linux-gnu'
build_alias=''
build_cpu='x86_64'
build_os='linux-gnu'
build_vendor='unknown'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host='x86_64-unknown-linux-gnu'
host_alias=''
host_cpu='x86_64'
host_os='linux-gnu'
host_vendor='unknown'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /home/ubuntu/nDPI/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='$(MKDIR_P)'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='NONE'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##

/* confdefs.h */
#define NDPI_PACKAGE_NAME "libndpi"
#define NDPI_PACKAGE_TARNAME "libndpi"
#define NDPI_PACKAGE_VERSION "2.9.0"
#define NDPI_PACKAGE_STRING "libndpi 2.9.0"
#define NDPI_PACKAGE_BUGREPORT ""
#define NDPI_PACKAGE_URL ""
#define NDPI_PACKAGE "libndpi"
#define NDPI_VERSION "2.9.0"

configure: exit 77
`

**Comment by lucaderi** [comment]
Sorry this is a problem on your local system
