### ISSUE TITLE
HTTP flows show lock icon

### ISSUE THREAD

**Issue by emanuele-f** [ntop/nDPI#714]
The lock icon should not be present in HTTP flows. It seems like here nDPI only takes the application protocol into account

![2019-06-05_12-00_1](https://user-images.githubusercontent.com/5488003/58948036-cb691e80-8778-11e9-9847-6d73f2928979.png)

![2019-06-05_12-00](https://user-images.githubusercontent.com/5488003/58948054-cefca580-8778-11e9-8f8d-95cfc17a189d.png)

**Comment by lucaderi** [comment]
This seems to be a ticket for ntopng
