### ISSUE TITLE
False positive Skype detection

### ISSUE THREAD

**Issue by Gelob** [ntop/nDPI#718]
Running ntopng and ndpi-2.9.0-1596 i saw a surge in my network traffic of 4Gbps and 2-3Mpps. When looking at ntopng I see it shows this traffic spike as Skype traffic. Really this is just Azure blob storage endpoint traffic, and its not skype. I don't have a pcap because I do flow based capturing but it was all dst port 443 to a single IP in the 13.96.0.0/13, 13.104.0.0/14, 13.64.0.0/11 space. When looking at passive DNS that IP has a hostname like blob.*.store.core.windows.net where * is a wildcard and would be a unique ID from Azure.

**Comment by haroflow** [comment]
I've found this page from MS: https://www.microsoft.com/en-us/download/details.aspx?id=41653
It says "deprecated" but has links for weekly (apparently) updated Azure endpoints:
- Public: https://www.microsoft.com/en-us/download/details.aspx?id=56519
- US Gov: http://www.microsoft.com/en-us/download/details.aspx?id=57063
- Germany: http://www.microsoft.com/en-us/download/details.aspx?id=57064
- China: http://www.microsoft.com/en-us/download/details.aspx?id=57062

Maybe we could add these as NDPI_PROTOCOL_MICROSOFT or NDPI_PROTOCOL_AZURE?

**Comment by Gelob** [comment]
Closing this as #823 was merged
