### ISSUE TITLE
How to contribute my code？

### ISSUE THREAD

**Issue by lance-wyvern** [ntop/nDPI#722]
Hi, everyone

I found a new version of OICQ protocol in qq.c, and then I've made a change to the code.
Now, I have no idea to contribute my code.  Can someone tell me how to do it？

**Comment by kYroL01** [comment]
https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by lance-wyvern** [comment]
> https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

Thank you
