### ISSUE TITLE
nDPI fails to recognize some DNS traffic

### ISSUE THREAD

**Issue by mauropalumbo75** [ntop/nDPI#725]
I noticed that some DNS traffic is not filtered correctly by nDPI FT. 

I attach a pcap file containing one DNS packet which is correctly filtered and another one which is not.

[twopacketsanon.pcap.gz](https://github.com/ntop/nDPI/files/3311016/twopacketsanon.pcap.gz)

Thanks in advance for looking into this issue.

**Comment by cardigliano** [comment]
This has been fixed. Please update and let us know. Thank you.
