### ISSUE TITLE
Travis is not detecting test failures

### ISSUE THREAD

**Issue by nickbroon** [ntop/nDPI#733]
the call to do.sh script seems to always be successful despite the the output containing errors, so Travis does not report a failure. For example: https://travis-ci.org/ntop/nDPI/jobs/556912071

Should the failing tests be considered a failure?

"after_script:" in travis.ci is not considered part of the result.
https://docs.travis-ci.com/user/job-lifecycle/#breaking-the-build

Should the tests be moved to the scripts section so that they are checked as part of the result?

**Comment by lucaderi** [comment]
I have fixed it as you suggested
