### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by lijk8890** [ntop/nDPI#762]
ndpi will memory leak with custom proto: HTTPS
e.g.

tcp:443,tcp:8443@HTTPS

**Comment by themadprofessor** [comment]
Do you have some sample data, i.e. a pcap file? Is this leak in the example code or the library? If it was the example code, can you share how you were running it? If it was in the library, can you supply some same code which reproduces the leak? Which version of nDPI does this apply to?

In future, please follow [CONTRIBUTING.md](https://github.com/ntop/nDPI/blob/dev/CONTRIBUTING.md) when submitting a bug.

**Comment by lijk8890** [comment]
yes, ndpiReader also has memory leak;
nDPI version: 2.6

use valgrind:  ./bin/ndpiReader -i ssh.pcap -p protos.txt

==61495== Memcheck, a memory error detector
==61495== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==61495== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==61495== Command: ./bin/ndpiReader -i ssh.pcap -p protos.txt
==61495== Parent PID: 6207
==61495== 
==61495== 
==61495== HEAP SUMMARY:
==61495==     in use at exit: 5 bytes in 1 blocks
==61495==   total heap usage: 72,349 allocs, 72,348 frees, 5,931,760 bytes allocated
==61495== 
==61495== 5 bytes in 1 blocks are definitely lost in loss record 1 of 1
==61495==    at 0x4A069EE: malloc (vg_replace_malloc.c:270)
==61495==    by 0x413BC7: ndpi_strdup (ndpi_main.c:385)
==61495==    by 0x414268: ndpi_handle_rule (ndpi_main.c:2698)
==61495==    by 0x4146D3: ndpi_load_protocols_file (ndpi_main.c:2784)
==61495==    by 0x40554C: setupDetection (ndpiReader.c:1483)
==61495==    by 0x4097B4: test_lib (ndpiReader.c:2621)
==61495==    by 0x409BD9: main (ndpiReader.c:3309)
==61495== 
==61495== LEAK SUMMARY:
==61495==    definitely lost: 5 bytes in 1 blocks
==61495==    indirectly lost: 0 bytes in 0 blocks
==61495==      possibly lost: 0 bytes in 0 blocks
==61495==    still reachable: 0 bytes in 0 blocks
==61495==         suppressed: 0 bytes in 0 blocks
==61495== 
==61495== For counts of detected and suppressed errors, rerun with: -v
==61495== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 6 from 6)

**Comment by themadprofessor** [comment]
This has been fixed with 165decdf6c58f67a087c514a7fae58355a8272b4. Here is a patch for 2.6-stable which fixes it.
```
diff --git a/src/lib/ndpi_main.c b/src/lib/ndpi_main.c
index e882feaa..46afedec 100644
--- a/src/lib/ndpi_main.c
+++ b/src/lib/ndpi_main.c
@@ -2699,7 +2699,7 @@ int ndpi_handle_rule(struct ndpi_detection_module_struct *ndpi_mod,
 			      ndpi_mod->ndpi_num_supported_protocols,
 			      0 /* can_have_a_subprotocol */, no_master,
 			      no_master,
-			      ndpi_strdup(proto),
+			      proto,
 			      NDPI_PROTOCOL_CATEGORY_UNSPECIFIED, /* TODO add protocol category support in rules */
 			      ndpi_build_default_ports(ports_a, 0, 0, 0, 0, 0) /* TCP */,
 			      ndpi_build_default_ports(ports_b, 0, 0, 0, 0, 0) /* UDP */);

```

**Comment by lijk8890** [comment]
ok, thanks
i pull the latest version

**Comment by lijk8890** [comment]
sry, nDPI 2.8.0 still has this bug

**Comment by themadprofessor** [comment]
As per my previous comment, this has been fixed with 165decdf6c58f67a087c514a7fae58355a8272b4. This commit is not in a stable release as of yet, so its only available on the dev branch.

**Comment by lijk8890** [comment]
ok, i'll fix it as you say
thank you

**Comment by themadprofessor** [comment]
If the issue has been resolved, please close the issue.
