### ISSUE TITLE
Tor node classification

### ISSUE THREAD

**Issue by jandersonbt** [ntop/nDPI#766]
Looking through the nDPI code (src/lib/ndpi_content_match.c.inc) it appears that you have a static list of Tor node IP's from 2017.  Tor node IP's are constantly changing and this list is most likely yielding false positives.  It would be nice to have the ability to load a user-defined list of Tor node IP addresses that could override the default list provided by nTOP.

If you wanted to make updates to the list in your code the link below is a good resource from Palo Alto of Tor exit nodes.
https://panwdbl.appspot.com/lists/ettor.txt

**Comment by emarshswe** [comment]
This should be reclassified as enhancement or feature request. This is not an issue.
