### ISSUE TITLE
DHCP fingerprinting

### ISSUE THREAD

**Issue by shivanikhosa** [ntop/nDPI#768]
Hi,
I wanted to ask if there was any plan to do client classification based on DHCP fingerprinting e.g classification into desktop, mobile phones, network devices, game console etc.
I was trying myself and found that classification with just DHCP option 55 fingerprint wasn't accurate enough and had a lot of conflicts. I was wondering if team at nDPI had tried something like that or if there was another database apart from fingerbank which could help.

Thanks
Shivani

**Comment by lucaderi** [comment]
We have done some work in ntopng using the DHCP fingerprint combined with the ethernet address of the requestor but we have found more reliably to use network discovery or passive traffic fingerprint. I encourage you to study this code in https://github.com/ntop/ntopng
