### ISSUE TITLE
iptables: No chain/target/match by that name.

### ISSUE THREAD

**Issue by prozaklob** [ntop/nDPI#771]
iptables -A FORWARD -m ndpi --bittorrent -j DROP
iptables: No chain/target/match by that name.

Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-161-generic i686)
iptables v1.6.0
grep NF_CONNTRACK_LABELS /boot/config-`uname -r`
CONFIG_NF_CONNTRACK_LABELS=y

what wrong?

**Comment by utoni** [comment]
Not related to the core library.
