### ISSUE TITLE
ndpiReader (nDPI 2.9.0-1810-64ed0ac) - segmentation fault

### ISSUE THREAD

**Issue by a-czyrny** [ntop/nDPI#773]
Input:
`gdb --args ndpiReader -i demo.pcap` _//PCAP file is 691 MB_

Output:
_Thread 2 "ndpiReader" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff79a4700 (LWP 25867)]
getSSCertificateFingerprint (ndpi_struct=<optimized out>, flow=0x7ffff2386100) at protocols/tls.c:760
760	  if(packet->payload[flow->l4.tcp.tls_record_offset] == 0x15 /* Alert */) {_

nDPI Version 2.9.0-1735-1231b81 runs fine.

**Comment by lucaderi** [comment]
Please put the demo.pcap file somewhere for debugging

**Comment by a-czyrny** [comment]
Unfortunately I cannot provide the data. What I can already say is that in rare cases the "payload" length is smaller than the "flow->l4.tcp.tls_record_offset" which leads to the segmentation fault.

I use the following sollution:
`
if(strlen((char*)packet->payload) < flow->l4.tcp.tls_record_offset) {
  goto invalid_len;
}
`

**Comment by emanuele-f** [comment]
Closing as fixed in 4bdbf02c2d5eb871dca4ec620bb66fcc16a74af1
