### ISSUE TITLE
nDPI doesn't show live traffic on terminal

### ISSUE THREAD

**Issue by umairkhan10** [ntop/nDPI#774]
M using nDPi nDPI 2.9.0-1519-e99a0ab on cent OS 7.6.1810
M running following command 

**sudo /usr/local/bin/ndpiReader -i enp0s8 -v2**

When I run this command, it captures all traffic but it doesn't show me on my terminal as live. It gets stuck on these lines:
**Using nDPI (2.9.0-1519-e99a0ab) [1 thread(s)]
Capturing live traffic from device enp0s8...
Running thread 0...**

And then when I stops this (Ctrl + c), then it shows all the traffic in the whole time it ran. 
I need to capture live traffic like when I run it it, it should not stop at "Running thread 0.." rather it should show me live traffic on my terminal as I need to capture and see traffic whenever it captures

Can anyone help me ?

**Comment by aouinizied** [comment]
You can split analysis duration in DURATION max seconds (-m option). For example with the following command, ndpiReader will prints analysis statististics each 5 seconds.
sudo /usr/local/bin/ndpiReader -i enp0s8 -v 2 -m 5

**Comment by umairkhan10** [comment]
What if I want to process live data. Like Whenever nDPI captures traffic I need to filter something like some maching IPs from the captured data etc. 
So when I apply any of these filter, nDPI captures traffic sends it to my method and then my method processes the data and filter out some IPs (my own ), when my method is working on the data that nDPI captured, in the meantime nDPI is free and is not capturing the data so on my method processing, my network traffic data is missing. So need to capture and process the live traffic

**Comment by SarmadHanif** [comment]
> What if I want to process live data. Like Whenever nDPI captures traffic I need to filter something like some maching IPs from the captured data etc.
> So when I apply any of these filter, nDPI captures traffic sends it to my method and then my method processes the data and filter out some IPs (my own ), when my method is working on the data that nDPI captured, in the meantime nDPI is free and is not capturing the data so on my method processing, my network traffic data is missing. So need to capture and process the live traffic

Use nDPI with DPDK

**Comment by lucaderi** [comment]
nDPI is a library on top of which you need to write your own code. Please look at the ndpiExample and extend it as needed and don't forget to send back your contributions
