### ISSUE TITLE
make with Hyperscan

### ISSUE THREAD

**Issue by SarmadHanif** [ntop/nDPI#776]
after executing ./configure --with-hyperscan no error appears but with make following error appears.
g++ -g -I../src/include -g -O2 ndpiReader.o reader_util.o -o ndpiReader ../src/lib/libndpi.a -lpcap -lpthread
../src/lib/libndpi.a(ndpi_main.o): In function `free_hyperscan_memory':
/root/new/nDPI/src/lib/ndpi_main.c:635: undefined reference to `hs_free_scratch'
/root/new/nDPI/src/lib/ndpi_main.c:636: undefined reference to `hs_free_database'
../src/lib/libndpi.a(ndpi_main.o): In function `hyperscan_load_patterns':
/root/new/nDPI/src/lib/ndpi_main.c:531: undefined reference to `hs_compile_multi'
/root/new/nDPI/src/lib/ndpi_main.c:540: undefined reference to `hs_alloc_scratch'
/root/new/nDPI/src/lib/ndpi_main.c:535: undefined reference to `hs_free_compile_error'
/root/new/nDPI/src/lib/ndpi_main.c:542: undefined reference to `hs_free_database'
../src/lib/libndpi.a(ndpi_main.o): In function `ndpi_match_custom_category':
/root/new/nDPI/src/lib/ndpi_main.c:2280: undefined reference to `hs_scan'
../src/lib/libndpi.a(ndpi_main.o): In function `ndpi_automa_match_string_subprotocol':
/root/new/nDPI/src/lib/ndpi_main.c:5988: undefined reference to `hs_scan'
/root/new/nDPI/src/lib/ndpi_main.c:5988: undefined reference to `hs_scan'
collect2: error: ld returned 1 exit status
make[1]: *** [ndpiReader] Error 1
make[1]: *** Waiting for unfinished jobs....

**Comment by rkerur** [comment]
Do you see following output with './configure --with-hyperscan'
...
checking for hs_compile_multi in -lhs... yes
checking for pow in -lm... no
checking for main in -lstdc++... yes
checking for HS... yes
compiling with Intel Hyperscan
...

**Comment by SarmadHanif** [comment]
> Do you see following output with './configure --with-hyperscan'
> ...
> checking for hs_compile_multi in -lhs... yes
> checking for pow in -lm... no
> checking for main in -lstdc++... yes
> checking for HS... yes
> compiling with Intel Hyperscan
> ...

/it is unable to compile with -lhs that' why all the calls to hs show undefined any solution in your mind.
p.s: thanks for replying

**Comment by rashidali-net-sys** [comment]
@SarmadHanif Hope that you will be fine

> > Do you see following output with './configure --with-hyperscan'
> > ...
> > checking for hs_compile_multi in -lhs... yes
> > checking for pow in -lm... no
> > checking for main in -lstdc++... yes
> > checking for HS... yes
> > compiling with Intel Hyperscan
> > ...

I am facing this issue while integrating Hyperscan with the nDPI-3.2 version. Can someone help me in this regard? Moreover, can I make this integration with the latest version of nDPI-4.6/4.0.

My hyperscan user_prefix were /usr/local/

**Comment by utoni** [comment]
Hyperscan support was dropped some releases ago. I guess integration won't be trivial.
