### ISSUE TITLE
Python bindings not working

### ISSUE THREAD

**Issue by aouinizied** [ntop/nDPI#777]
Thanks for provinding the community with python bindings. However, when I tried to run the example, it doesn't work. 
Python3.6 and nDPI master cloned today.
I run make under /python/ directory after installing ndpi from scratch, and start example using python3.6 ndpi_example.py....

It seems that it crashed because of missing functions in ndpi_wrap.c

Traceback (most recent call last):
  File "ndpi_example.py", line 21, in <module>
    from ndpi_typestruct import *
  File "/home/sah0312/PycharmProjects/nDPI/python/ndpi_typestruct.py", line 759, in <module>
    ndpi.ndpi_tfind.restype = c_void_p
  File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: ./ndpi_wrap.so: undefined symbol: ndpi_tfind

Does the python bindings are work in progress or I'm missing something?

Thanks for help!

**Comment by sajukassim** [comment]
Same with me too..

**Comment by lucaderi** [comment]
On OSX (where I develop) everything seems to work

deri@Lucas-iMac.local 220> cd python/
total 112
 8 Makefile		 8 Makefile.in		 8 README		24 ndpi_example.py*	56 ndpi_typestruct.py	 8 ndpi_wrap.c
deri@Lucas-iMac.local 221> make
clang -I. -I../src/include -I./src/lib/third_party/include -shared -Wl,-install_name,ndpiReader.so -o ndpi_wrap.so -fPIC ndpi_wrap.c ../src/lib/libndpi.so.2.9.0 -lpcap
ln -s ../src/lib/libndpi.so.2.9.0 .
deri@Lucas-iMac.local 222> ./ndpi_example.py
Using nDPI b'2.9.0-1827-5c2e495'

Usage: ndpi_example.py <device>
deri@Lucas-iMac.local 223> ./ndpi_example.py en3
Using nDPI b'2.9.0-1827-5c2e495'
Capturing live traffic from device en3...
^C
number of anylized packet 14
number of flows 5

Detected protocols:
b'Unknown: 6'
b'DHCP: 1'
b'TLS: 4'
b'Spotify: 1'
b'Telegram: 

Are you using Linux ? Please investigate and report.
