### ISSUE TITLE
Viber protocol is not detected.

### ISSUE THREAD

**Issue by whoknowz** [ntop/nDPI#78]
Viber is no longer detected, identified as unknown. Will upload pcap file soon.

**Comment by lucaderi** [comment]
@whoknowz Please update a pcap

**Comment by rathnaTech** [comment]
*_@whoknowz *_
Please update the latest version library. It will detect all the protocols.

**Comment by whoknowz** [comment]
Thanks, works now

**Comment by feriel-ux** [comment]
I want to add a new custom protocol on nDPI ( e.g : shahid.mbc.net ) , but I want ndpi detect the protocol when I build and add a source code for this protocol ( not in protos.txt with the host )
