### ISSUE TITLE
NO nDPI interface 

### ISSUE THREAD

**Issue by Lizeth2989** [ntop/nDPI#785]
Hey guys, 

I installed nDPI in wireshark using this guide https://sharkfesteurope.wireshark.org/assets/presentations17eu/19.pdf

First, I did it in Windows (wireshark 3.5) and the nDPI interface never appeared. Only Lua menu.

Later, I used an ubuntu (wireshark 2.6) and the nDPI interface appeared. 

![Capture](https://user-images.githubusercontent.com/32398014/65752164-c7557800-e13e-11e9-8938-1562e34f65ba.PNG)

However, when I click on it, gives me this error instead of the nDPI interface.

"No packets captured.
 As no data was captured, closing the temporary capture file. 
Help about capturing can be found at 
https://wiki.wireshark.org/CaptureSetup"

![60a1f33a579636e81693ec10ff5343f](https://user-images.githubusercontent.com/32398014/65752136-bdcc1000-e13e-11e9-97df-2bdc530f06ff.jpg)

Of course I captured packets but I do not receive the nDPI interface options as shown in ppt page 33 (https://sharkfesteurope.wireshark.org/assets/presentations17eu/19.pdf). 

Could you help me with any idea?

Thank you

**Comment by lucaderi** [comment]
We have made some fixes for Wireshark. Please try again now and if still failing please reopen this ticket

**Comment by videvelop** [comment]
I get this error.  I use nrfsniffer.  It shows packets first.  When I stop and restart, it throws this error.  Only way out is to exit the wireshark and restart again.
