### ISSUE TITLE
ndpi_protocol2name() not exported

### ISSUE THREAD

**Issue by rs-natano** [ntop/nDPI#79]
The release notes for nDPI 1.6 mention "New API call for converting nDPI protocols IDs to names ndpi_protocol2name()", but the function name is not included in libndpi.sym and thus not exported in the resulting shared library.

<pre>
natano@ketzer:~$ nm /usr/lib/libndpi.so.1.0.0|grep protocol2name
000000000000efd0 t ndpi_protocol2name
</pre>

Notice the lower-case 't', which indicates that the symbol is local.

Is this on purpose?

**Comment by lucaderi** [comment]
Fixed
