### ISSUE TITLE
Skipping TCP handshake packets

### ISSUE THREAD

**Issue by shivanikhosa** [ntop/nDPI#793]
Hi,
I'm using nDPI integrated as a netfilter module into a router with iptables. I have seen an issue where if nmap command is being run, which sends hundreds of TCP connections in half open state, it can cause the system to go out of memory. Since only one packet is sent per session, these  connections stay unclassified in the system for quite sometime and the memory is held up until we force clean it. To avoid running into such OOM situations, I thought that we could hold on sending packets to the detection engine for TCP based connections until we see packets in either direction. So far I haven't seen any adverse side effect of this change on my classifications. Do you think this would effect any of the detectors in any way ?

Thanks
Shivani

**Comment by emarshswe** [comment]
I parse pcaps through nDPI and work from there. Scans are interesting for me and therefore I'm interested in flows where I don't see packets in either direction. A change in ntop does not bother me, but I don't want this functionality included in nDPI.

**Comment by utoni** [comment]
I agree with @emarshswe. Such functionality should be part of your nDPI integration.
