### ISSUE TITLE
noob question regarding traffic blocking

### ISSUE THREAD

**Issue by mrbluecoat** [ntop/nDPI#794]
Your readme says

> You can use nDPI to selectively block selected Internet traffic by embedding it onto an application

Do you have a doc or code sample to demonstrate that?  Something like "How to block YouTube using a Raspberry Pi" would be great!

**Comment by mmanoj** [comment]
Check below:
https://github.com/betolj/ndpi-netfilter

Now not much maintained.

**Comment by mrbluecoat** [comment]
Perfect, thanks!  https://thingsinlinux.blogspot.com/2016/02/installing-and-configuring-ndpi.html helped walk me through the install

**Comment by mmanoj** [comment]
The only thing you need to update the nDPI libs time to time with netfilter module. If the Original maintainer does not does so.

**Comment by mrbluecoat** [comment]
Any option that works with [nftables](https://linuxhandbook.com/iptables-vs-nftables/)?

**Comment by houmie** [comment]
@mrbluecoat I tried the same, but https://github.com/betolj/ndpi-netfilter is no longer compiling on latest Ubuntu 20.04.
Did you get it to work?

**Comment by mrbluecoat** [comment]
@houmie No, got interested in other things

**Comment by lucaderi** [comment]
We have written various tools on top of netfilter (user-space no kernel) and also our tools such as nEdge block traffic. it is a simple exercise on top of netfilter basically

**Comment by houmie** [comment]
Hi @lucaderi 
Thank for your comment. Sorry where do I find ```nEdge block traffic``` and has it documentation how to identify and block torrent packets?

Many Thanks
