### ISSUE TITLE
Is it possible to extract the Flow identificators and the Application protocol to a CSV File using the python bindings?

### ISSUE THREAD

**Issue by jsrojas** [ntop/nDPI#796]
Hello everyone

I've been looking to the python bindings example and trying to understand how it works with ctypes and everything (I'm new to combining C and python code).

After a lot of effort, I understand a bit how the provided python bindings example gets the application protocol so I was wondering if it is possible to get the application protocol (name and number ID) and the 4-tuple identificators (Src IP, Src Port, Dst Ip, Dst Port) of the flow it belongs to and create a CSV file with records for each flow. A record on CSV file like this:

Src IP         Src Port       Dst IP        Dst Port        Application Protocol ID     Application Protocol Name
2.2.2.2            443           1.1.1.1         5893                       211                                       Instagram
  
Please I've been trying a lot with this. Any help will be much appreciated!

**Comment by aouinizied** [comment]
Hi,
I already did it. in which part you are struggling so I can help?
br

**Comment by jsrojas** [comment]
Hi, thank you for responding

The thing is since I do not know the nDPI library on the inside I'm not sure what should I call and how.

I am working with a small pcap file that has **39 packets** all from **Instagram** and the CSV file is saving 39 rows with the IP identifiers and the application label, but nDPI says that from those 39 packets there are **4 flows** only. So, what I want is to store only 4 rows on the CSV file with all the information of each flow and their respective application label. How can I get only the flows information (not the packets) and their application label?

**Pcap file:** 
[Instagram packets.zip](https://github.com/ntop/nDPI/files/3740961/Instagram.packets.zip)

So far, I was able to create the CSV file but It seems that it is just saving the Header information of every packet. I did it with the following functions:

```
def getFlowIdentifiers(flow, flow_label, packet_count):
    global df
    src_ip = socket.inet_ntoa(struct.pack('!L',flow.contents.src_ip))
    src_port = flow.contents.src_port
    dst_ip = socket.inet_ntoa(struct.pack('!L',flow.contents.dst_ip))
    dst_port = flow.contents.dst_port
    app_number = flow_label.app_protocol
    app_protocol_name = cast(ndpi.ndpi_get_proto_name(ndpi_info_mod, flow_label.app_protocol), c_char_p).value


    df = df.append({'src_ip': src_ip, 'src_port': src_port, 'dst_ip': dst_ip,
                    'dst_port': dst_port, 'app_number': app_number,
                    'app_name': app_protocol_name}, ignore_index=True)
    
def writeCSV(df, process_finished):
    if process_finished:
        df.to_csv (r'/home/jsrojas/Juan/dataframe.csv', index = None, header=True)
```
After looking into it I understood that the Application label is obtained from the **packetcaptured** function, and this is where I call my function:

```
def packetcaptured(packet):
    global packet_number
    global start_time
    global ndpi_info_mod
    global packet_count

    flow = None
    h = pcap_pkthdr()

    #getting flow
    try:
        flow = get_flow(packet)
    except AttributeError:
        pass # ignore packet
    if flow is None: return

    #filling pcap_pkthdr
    h.len = h.caplen = len(packet)
    h.ts.tv_sec = int(packet["IP"].time/1000000)
    h.ts.tv_usec = int(packet["IP"].time)
    # real work
    if int(packet[1].frag) == 0:  # not fragmented packet
        flow.contents.packets += 1
        packet_number += 1
        # get ndpi_iphdr address
        iphdr_addr = cast(c_char_p(packet[1].build()), c_void_p)
        ndpi_flow = flow.contents.flow

        # Search for the Application protocol inside the packet
        if flow.contents.detection_completed is 0:
            flow.contents.detected_protocol = ndpi.ndpi_detection_process_packet(ndpi_info_mod, ndpi_flow, cast(iphdr_addr, POINTER(c_uint8)),
                    int(packet[1].len), h.ts.tv_usec, flow.contents.src_id, flow.contents.dst_id)

            flow_label = flow.contents.detected_protocol
            getFlowIdentifiers(flow, flow_label, packet_count)
            packet_count += 1

            valid = False

            if flow.contents.protocol == 6: valid = flow.contents.packets > max_num_tcp_dissected_pkts
            elif flow.contents.protocol == 17: valid = flow.contents.packets > max_num_udp_dissected_pkts

            #should we continue anylizing packet or not?
            if valid or flow_label.app_protocol is not 0:
                if valid or flow_label.master_protocol is not 91: #or # 91 is NDPI_PROTOCOL_TLS
                    flow.contents.detection_completed = 1 #protocol found
l.if flow_label.app_protocol is 0:
                        flow.contents.detected_protocol = ndpi.ndpi_detection_giveup(ndpi_info_mod, ndpi_flow, 1)
```
What should I be calling to get the flow information only (not the packets) and get those 4 rows on the CSV file (not 39 rows)?

Thanks in advance

Best regards.

**Comment by aouinizied** [comment]
HI,

You need to maintain a flow cache with entries and manage the expiration. nDPI is called just for detection.
I released nfstream (https://github.com/aouinizied/nfstream) that address what you want to do.
The main idea is to build a common framework for network data scientist community.
You are more than welcome to join the team and contribute in improving the project.

Zied

**Comment by jsrojas** [comment]
Oh great!!

I will definitely have a look to nfstream. It might solve what I need to do and for sure if I can provide any improvement to it and contribute I will do it

On the other hand yeah I do know I need to maintain a flow cache, however, since i do not know how ndpi is on the inside, I don't know how to obtain the flow identifiers in the example code. Right now I'm getting just packets and their application labels but I need to get the Flow Identifiers and their application label (not the packets). Could you maybe give me an example of how to obtain that?

**Comment by emarshswe** [comment]
This is not an issue and should be closed.

**Comment by jsrojas** [comment]
It was an issue considering that there is a lack of documentation regarding the python bindings of nDPI. However I was able to sort this out thanks to the help of aouinizied and will close it now. Thanks for the reminder
