### ISSUE TITLE
Tests output files corrupted

### ISSUE THREAD

**Issue by aouinizied** [ntop/nDPI#797]
Hi all,

Some of the tests are uncorrect and thus, raise unconsistent behavior of nDPIReader.
Example: wechat.pcap.out
When you look at this flow:
93	0 [fe80::842:a3f3:a286:6c5b]:0 -> [ff02::16]:0 [proto: 102/ICMPV6][cat: Network/14][1pkts/110 bytes -> 0 pkts/0 bytes]
protocol_id here are reported as 0 however, analysis using wireshark and other tools show that ip_proto is ICMPv6.

BR

**Comment by lucaderi** [comment]
0 is the port, the protocol is 102/ICMPV6. It works for me

**Comment by aouinizied** [comment]
H @lucaderi, there is a misunderstanding. I'm talking about the first 0 in this line which refer to ip_protocol. It must be 58.
