### ISSUE TITLE
Segmentation fault when running ndpi_example.py

### ISSUE THREAD

**Issue by RadionBik** [ntop/nDPI#798]
Hello!

I performed the following steps on the 3.0-stable and dev branches on both Ubuntu 16.04 and 18.04:
1. Build the project as per instructions in README
2. Performed `make` in the `python` folder
3. Installed scapy for python3 (also tried python2)
4. Launched `sudo python[23] ndpi_example.py ...` with either a `.pcap` or an interface arg.
As traffic started to flow, the script terminated and resulted in the segmentation fault error (optionally with `core dumped`)

I doubt this the expectable behavior, how can I resolve the issue? Are there any specific dependencies the bindings were written against?

**Comment by lucaderi** [comment]
Can you please try to debug the core dump checking where is the problem and pasting here the trace?

**Comment by RadionBik** [comment]
I launched the following cmd:
`sudo ~/Applications/VENVs/classifier/bin/python3 -q -X faulthandler ndpi_example.py wlp2s0`

That resulted in:
`Using nDPI b'3.1.0-1918-604abaf'
Capturing live traffic from device wlp2s0...
number of anylized packet 837
number of flows 78
Fatal Python error: Segmentation fault

Current thread 0x00007f381d9fd740 (most recent call first):
  File "ndpi_example.py", line 55 in node_proto_guess_walker
  File "ndpi_example.py", line 205 in result
  File "ndpi_example.py", line 251 in <module>
Segmentation fault`

If there are other possible ways to debug the issue in more details, please, suggest them.

**Comment by aouinizied** [comment]
In nDPI example, change the call the ndpi.give_up as follow: 
                            flow.detected_protocol = ndpi.ndpi_detection_giveup(ndpi_info_mod,
                                                                                flow.flow,
                                                                                1,
                                                                                cast(addressof(c_uint8(0)),
                                                                                     POINTER(c_uint8)))

It should solve it. As now the last parameter is pointer to guessed.

**Comment by RadionBik** [comment]
Thank you,  that solved the issue.
Also I had to change the arguments in the `packetcaptured` function.
