### ISSUE TITLE
New Amazon Video dissector

### ISSUE THREAD

**Issue by shivanikhosa** [ntop/nDPI#805]
Hi,
I see a new Amazon video dissector doing static classification based on payload values.
I've tried running videos in amazon prime to generate traffic from desktop as well as mobile phones but I do not see any classification happening using this dissector.  Mostly amazonvideo classification is happening via string match on SNI or IP address matching.  Could you help me to generate the sort of traffic that this dissector is classifying ?

**Comment by lucaderi** [comment]
Please provide the pcap with some example we can analyse

**Comment by lucaderi** [comment]
Closed for inactivity
