### ISSUE TITLE
how to decode HTTPS traffic with nDPI?

### ISSUE THREAD

**Issue by lua-study** [ntop/nDPI#812]
In the QuickStartGuide(https://www.ntop.org/wp-content/uploads/2013/12/nDPI_QuickStartGuide.pdf) of nDPI , nDPI support encrypted connections if adding a decoder for SSL certificates.

But I can't find how to add the decoder for https to get the plain HTTP data? 
Who can help me ? Thanks very much.
Note: I have the server certificate .

**Comment by aouinizied** [comment]
When nDPI is dissecting traffic, all extracted information could be found in ndpi_flow_struct (the flow pointer you give to process_packet API). When you look at this struct, you will find under protos, SSL information.

**Comment by lucaderi** [comment]
We do not plan to decode encrypted traffic, but to extract metadata such as signature, host names etc.
