### ISSUE TITLE
Memory consumption increasing when running ndpiReader with Split analysis duration

### ISSUE THREAD

**Issue by subritm** [ntop/nDPI#815]
I have cloned and compiled the ndpi latest git repository, and was testing the application detection in my linux desktop.
./ndpiReader -i eth0 -m 1
What I noticed is the memory consumption of the reader is constantly growing.
There is not much traffic going on hardly 10 browser sessions and ping etc.

This is when its started 
Using nDPI (3.1.0-2028-fbc59c5) [1 thread(s)]
Capturing live traffic from device eth0...
Running thread 0...

nDPI Memory statistics:
	nDPI Memory (once):      208.13 KB    
	Flow Memory (per flow):  2.20 KB      
	**Actual Memory:           3.66 MB**      
	Peak Memory:             3.66 MB      
	**Setup Time:              29 msec**
	Packet Processing Time:  1798 msec

After running for a few seconds

nDPI Memory statistics:
	nDPI Memory (once):      208.13 KB    
	Flow Memory (per flow):  2.20 KB      
	**Actual Memory:           7.60 MB**      
	Peak Memory:             7.60 MB      
	**Setup Time:              150281 msec**
	Packet Processing Time:  5752 msec

I checked the code, and found terminateDetection function is called, once we complete the detection. 
But how this can be used for live capture ?

**Comment by aouinizied** [comment]
In live capture mode, there is an idle flows walker that free idle flows memory space depending on your idle timeout.
See node_idle_scan_walker for more information.
Maybe increasing your split to 10 secs ans reducing idle_timeout to 5 secs would be a good option?

**Comment by subritm** [comment]
Hi @aouinizied 

I tried this, reduced the idle time from 30000 to 5.
#define MAX_IDLE_TIME           5,
also with -m 10, it only reduces the interval of memory allocation, still the overall size increases. 
TIA.

**Comment by aouinizied** [comment]
Just a note on how idle scan works (how I understand it at least :) ), each scan_period a root (from a total of 512) is scanned with a specific scan_budget.
So if you reduced your idle_time to 5 msecs, you should also reduce scan_period from 10 to something like 1 or even 0 ms  and enlarge your scan_budget from 1024 to a greater amount.
The idea is just to see if with such parameters a change in the memory allocation behavior.

**Comment by aouinizied** [comment]
Another note is regarding your used values, they seems quite small for a realistic scenario. You could try to split analysis by 10 seconds ans having a idle timeout of 1 sec. This would be more realistic as scenario. The problem you encountered is due to the fact that the idle scan period was greater than both idle_timeout and analysis duration (not logic parameters).
If you want memory to be freeed in live capture scenario, your split duration must enable at least a full idle scan walk.

**Comment by lucaderi** [comment]
This tool (ndpiReader) is just a demo tool not used for long term processing but only for demo purposes. If you believe this could be improved, please send a pull request
