### ISSUE TITLE
Without IPv4 Layer protocols

### ISSUE THREAD

**Issue by halidaltuner** [ntop/nDPI#818]
Hello,

I am working on ICS / SCADA protocols. However, some protocols do not use IPv4. Sample; GOOSE protocol works directly at Layer3 level.

Is there a solution for this?

Does the "packet-> payload [0]" object only return Layer4 application payloads?

For example: GOOSE protocol.
<img width="814" alt="Screen Shot 2019-12-05 at 21 53 19" src="https://user-images.githubusercontent.com/221467/70264564-b57cfa80-17a9-11ea-8d77-35501dab68b2.png">

Example pcap:
https://github.com/ITI/ICS-Security-Tools/blob/master/pcaps/IEC61850/GOOSE/GOOSE.pcap

Sources:
https://en.wikipedia.org/wiki/EtherType

**Comment by lucaderi** [comment]
nDPI currently works with IPv4 and v6. What you are asking requires some changes, doable but that  might need some work. Would you like to start this thread by sending un initial pull request?

**Comment by lucaderi** [comment]
Closed for inactivity
