### ISSUE TITLE
IPv6 Adresses are malformed/ivalid

### ISSUE THREAD

**Issue by a-czyrny** [ntop/nDPI#819]
Some IPv6 addresses are malformed after the analysis and therefore invalid for later processing.

e.g.: 

2a02:8100:0:32:9::145 becomes 2a02:8100::32:9::145

Tested with ndpiReader.

Example pcap: [ipv6_example_pcap.zip](https://github.com/ntop/nDPI/files/3950186/ipv6_example_pcap.zip)

**Comment by aouinizied** [comment]
It's a patch applied to ensure consistency across platforms if we rely on the comment in the code. It's performed using this function: https://github.com/ntop/nDPI/blob/65d526d8f6ae75f8d1a3f5c8dd19bf40ec03f320/src/lib/ndpi_utils.c#L744

**Comment by a-czyrny** [comment]
Thanks for pointing that out, i commented out the line. Elasticsearch (in this case) would not accept the values otherwise.

**Comment by lucaderi** [comment]
The problem is that inet_ntop() is not consistent across all the platforms. The function above is used to patch issues to make test produce the same results on all platforms I am not an IPv6 expert so you should instruct me how to address this issue.
