### ISSUE TITLE
ndpiReader detect incorrect

### ISSUE THREAD

**Issue by tuor4eg** [ntop/nDPI#822]
I use nDPI 3.0 and I try to detect skype/viber/whatsapp traffic. My system is FreeBSD 11.
So I use command  `ndpiReader -i vmx1 -f 'src net 192.168.199.0/24' -m 1 -v 2 -V 3`
But there is not many packets with codes of messengers, most of them have code 91 (TLS). Those packets, who was detected have no significant impact to app's working.
The typical output of ndpiReader looks like:
```
 1 TCP 192.168.199.30:58243 -> 104.236.74.212:443 [proto: 91/TLS][cat: Web/5][1 pkts/111 bytes -> 0 pkts/0 bytes]
 2 TCP 192.168.199.30:55812 -> 5.255.255.88:443 [proto: 91/TLS][cat: Web/5][1 pkts/60 bytes -> 0 pkts/0 bytes]
 3 TCP 192.168.199.30:56646 -> 104.236.74.212:443 [proto: 91/TLS][cat: Web/5][1 pkts/60 bytes -> 0 pkts/0 bytes]
 4 TCP 192.168.199.30:56893 -> 104.236.74.212:443 [proto: 91/TLS][cat: Web/5][1 pkts/60 bytes -> 0 pkts/0 bytes]
 5 TCP 192.168.199.30:56894 -> 104.236.74.212:443 [proto: 91/TLS][cat: Web/5][1 pkts/60 bytes -> 0 pkts/0 bytes]
 6 TCP 192.168.199.30:57906 -> 23.97.215.12:443 [proto: 91.125/TLS.Skype][cat: VoIP/10][1 pkts/60 bytes -> 0 pkts/0 bytes]
```
Is it possible to handle something with that?

**Comment by lucaderi** [comment]
Do you have a pcap file I can use to troubleshoot this issue?

**Comment by tuor4eg** [comment]
Sorry for the delay. Now, I've back to the problem. So, there're pcap from inner interface and output of ndpiReader attached.
[dump.zip](https://github.com/ntop/nDPI/files/4212948/dump.zip)

**Comment by lucaderi** [comment]
This is the current output

	1	TCP 192.168.199.30:52161 <-> 52.188.42.235:443 [proto: 91.125/TLS.Skype][cat: VoIP/10][12 pkts/3531 bytes <-> 9 pkts/6907 bytes][Goodput ratio: 80/93][0.54 sec][ALPN: h2,http/1.1][bytes ratio: -0.323 (Download)][IAT c2s/s2c min/avg/max/stddev: 0/0 45/38 134/129 62/57][Pkt Len c2s/s2c min/avg/max/stddev: 60/54 294/767 1494/1494 443/658][TLSv1.2][Client: client-s.gateway.messenger.live.com][JA3C: 10ee8d30a5d01c042afd7b2b205facc4][ServerNames: *.gateway.messenger.live.com,api.chat.skype.net,*.chat.skype.net,apis.skype.com,api.skype.net,df-api.skype.net,df-apis.skype.com,*.api.skype.net,*.apis.skype.com][JA3S: 986571066668055ae9481cb84fda634a][Certificate SHA-1: 8D:96:AF:F0:6B:3F:3D:F5:2F:95:D9:49:AC:7B:32:AE:91:95:81:91][Validity: 2020-01-23 11:06:51 - 2022-01-23 11:06:51][Cipher: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384]
	2	TCP 192.168.199.30:52160 <-> 52.7.135.84:443 [proto: 91.178/TLS.Amazon][cat: Web/5][12 pkts/3342 bytes <-> 11 pkts/5013 bytes][Goodput ratio: 79/88][0.81 sec][bytes ratio: -0.200 (Download)][IAT c2s/s2c min/avg/max/stddev: 0/0 60/50 137/129 63/62][Pkt Len c2s/s2c min/avg/max/stddev: 60/54 278/456 1494/1494 410/611][TLSv1.2][Client: river-mobile.data.ea.com][JA3C: 69415598724855f70b37da9f653ec421][ServerNames: *.data.ea.com][JA3S: 303951d4c50efb2e991652225a6f02b1][Organization: Electronic Arts, Inc.][Certificate SHA-1: 30:BD:7E:CB:DF:DC:B2:CA:D3:C7:6C:D7:33:A1:24:66:32:11:80:54][Validity: 2019-07-25 00:00:00 - 2020-08-19 12:00:00][Cipher: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256]
	3	UDP 192.168.199.30:57955 <-> 74.125.205.94:443 [proto: 188.126/QUIC.Google][cat: Web/5][4 pkts/1988 bytes <-> 4 pkts/1949 bytes][Goodput ratio: 92/91][0.02 sec][Host: ssl.gstatic.com][bytes ratio: 0.010 (Mixed)][IAT c2s/s2c min/avg/max/stddev: 0/0 8/0 23/0 11/0][Pkt Len c2s/s2c min/avg/max/stddev: 70/60 497/487 1392/1392 540/544][PLAIN TEXT (ssl.gstatic.com)]
	4	TCP 52.188.42.235:443 <-> 192.168.199.30:62512 [proto: 91/TLS][cat: Web/5][2 pkts/469 bytes <-> 2 pkts/2671 bytes][Goodput ratio: 77/96][0.14 sec]
	5	TCP 192.168.199.30:52151 <-> 52.86.93.8:443 [proto: 91.178/TLS.Amazon][cat: Web/5][5 pkts/2511 bytes <-> 5 pkts/597 bytes][Goodput ratio: 89/55][0.26 sec][bytes ratio: 0.616 (Upload)][IAT c2s/s2c min/avg/max/stddev: 130/0 65/32 131/90 65/37][Pkt Len c2s/s2c min/avg/max/stddev: 60/54 502/119 1494/347 524/115]
	6	TCP 52.188.42.235:443 <-> 192.168.199.30:62481 [proto: 91/TLS][cat: Web/5][2 pkts/469 bytes <-> 3 pkts/2538 bytes][Goodput ratio: 77/93][0.14 sec]
	7	TCP 192.168.199.30:52158 <-> 81.19.74.4:443 [proto: 91/TLS][cat: Web/5][2 pkts/818 bytes <-> 1 pkts/623 bytes][Goodput ratio: 86/91][0.08 sec]
	8	TCP 192.168.199.30:62578 <-> 35.154.102.71:443 [proto: 91.178/TLS.Amazon][cat: Web/5][5 pkts/455 bytes <-> 4 pkts/330 bytes][Goodput ratio: 38/34][10.22 sec][bytes ratio: 0.159 (Mixed)][IAT c2s/s2c min/avg/max/stddev: 215/0 2554/3334 8017/7989 3217/3392][Pkt Len c2s/s2c min/avg/max/stddev: 60/54 91/82 113/111 25/28]
	9	TCP 192.168.199.30:62579 <-> 35.154.102.71:443 [proto: 91.178/TLS.Amazon][cat: Web/5][5 pkts/455 bytes <-> 4 pkts/330 bytes][Goodput ratio: 38/34][10.23 sec][bytes ratio: 0.159 (Mixed)][IAT c2s/s2c min/avg/max/stddev: 219/9 2557/3336 8322/8289 3366/3570][Pkt Len c2s/s2c min/avg/max/stddev: 60/54 91/82 113/111 25/28]
	10	TCP 192.168.199.30:62580 <-> 35.154.102.71:443 [proto: 91.178/TLS.Amazon][cat: Web/5][5 pkts/455 bytes <-> 4 pkts/330 bytes][Goodput ratio: 38/34][10.22 sec][bytes ratio: 0.159 (Mixed)][IAT c2s/s2c min/avg/max/stddev: 215/0 2554/3333 8842/8799 3643/3896][Pkt Len c2s/s2c min/avg/max/stddev: 60/54 91/82 113/111 25/28]
	11	TCP 192.168.199.30:62568 <-> 35.154.102.71:443 [proto: 91.178/TLS.Amazon][cat: Web/5][3 pkts/284 bytes <-> 3 pkts/219 bytes][Goodput ratio: 41/26][6.38 sec][bytes ratio: 0.129 (Mixed)][IAT c2s/s2c min/avg/max/stddev: 211/0 3188/3062 6166/6125 2978/3062][Pkt Len c2s/s2c min/avg/max/stddev: 60/54 95/73 113/111 25/27]
	12	TCP 192.168.199.30:62569 <-> 35.154.102.71:443 [proto: 91.178/TLS.Amazon][cat: Web/5][3 pkts/284 bytes <-> 3 pkts/219 bytes][Goodput ratio: 41/26][6.92 sec][bytes ratio: 0.129 (Mixed)][IAT c2s/s2c min/avg/max/stddev: 214/0 3461/3334 6708/6668 3247/3334][Pkt Len c2s/s2c min/avg/max/stddev: 60/54 95/73 113/111 25/27]
	13	TCP 192.168.199.30:62570 <-> 35.154.102.71:443 [proto: 91.178/TLS.Amazon][cat: Web/5][3 pkts/284 bytes <-> 3 pkts/219 bytes][Goodput ratio: 41/26][7.46 sec][bytes ratio: 0.129 (Mixed)][IAT c2s/s2c min/avg/max/stddev: 212/0 3730/3600 7249/7199 3518/3600][Pkt Len c2s/s2c min/avg/max/stddev: 60/54 95/73 113/111 25/27]
	14	TCP 192.168.199.30:52146 <-> 52.188.42.235:443 [proto: 91/TLS][cat: Web/5][2 pkts/120 bytes <-> 1 pkts/54 bytes][Goodput ratio: 0/0][0.13 sec]
	15	UDP 173.194.73.189:443 <-> 192.168.199.30:57486 [proto: 126/Google][cat: Web/5][1 pkts/82 bytes <-> 1 pkts/70 bytes][Goodput ratio: 48/39][0.01 sec]
	16	TCP 192.168.199.30:51931 <-> 64.233.163.83:443 [proto: 91.126/TLS.Google][cat: Web/5][1 pkts/60 bytes <-> 1 pkts/66 bytes][Goodput ratio: 2/0][0.03 sec]
	17	TCP 192.168.199.30:52138 <-> 52.114.75.79:443 [proto: 91.125/TLS.Skype][cat: VoIP/10][1 pkts/60 bytes <-> 1 pkts/66 bytes][Goodput ratio: 2/0][0.06 sec]


Do you see any problem? If so, which one.

**Comment by tuor4eg** [comment]
At the line 1 we see correct detection (TLS/Skype)
But at the line 14 connection to the same address has only TLS detection, no skype. So, skype works fine and doesn't block.
The same thing happens with viber and whatsapp

**Comment by tuor4eg** [comment]
Good day! Is there anything I can do with this problem?

**Comment by lucaderi** [comment]
The line 14 has only 3 packets too little. I have tested nDPI (the dev version) in inline mode and it blocks skype for me
