### ISSUE TITLE
Sample files installed in sbin

### ISSUE THREAD

**Issue by EricFromCanada** [ntop/nDPI#826]
Is there a reason why [this commit](https://github.com/ntop/nDPI/commit/1ec160d4c99a8dc5b7117abb148f0f89403eab82) places sample files in `sbin` instead of something like `share`? 

I've done so in its Homebrew formula: https://github.com/Homebrew/homebrew-core/pull/48421

**Comment by lucaderi** [comment]
Thank you for reporting it
