### ISSUE TITLE
Whatsapp enhancement

### ISSUE THREAD

**Issue by ewildgoose** [ntop/nDPI#827]
Hi, I have previously been classifying whatsapp using a DNS based approach and looking in /src/lib/ndpi_content_match.c.inc I see:

  { "mmg.whatsapp.net", NULL, "mmg\\.whatsapp" TLD,                    "WhatsApp",         NDPI_PROTOCOL_WHATSAPP, NDPI_PROTOCOL_CATEGORY_CHAT, NDPI_PROTOCOL_ACCEPTABLE },

I think this DNS name should be classified as "WhatsAppFiles? At least on Android this is exclusively used for media

Additionally I see requests to "cdn.whatsapp.net" - these probably should be included in the files protocol match also?

**Comment by lucaderi** [comment]
Can you please send a pull request with your changes and include a pcap file so we can validate your approach?

**Comment by lucaderi** [comment]
Already in ndpi_content_match.c.inc
