### ISSUE TITLE
nDPI-dev is unable to classify Youtube Flows

### ISSUE THREAD

**Issue by SarmadHanif** [ntop/nDPI#834]
Currently Youtube is sending data over UDP.
nDPI is only able to classify DNS packets as Youtube it is unable to classify UDP packets that follow as Youtube Protocol. 
![image](https://user-images.githubusercontent.com/48462184/73154100-09e08e80-40f8-11ea-8b70-5c9c191e3cd4.png)

**Comment by lucaderi** [comment]
Can you please send a pcap file for testing?

**Comment by SarmadHanif** [comment]
Hi,
Sorry I couldn't find the pcap I ran the test on I will send as soon as I find it, In new tests udp packets are detected as quic which in turn is classified as Youtube packets. Its working fine I'm closing this issue for now.
 Thank you for replying
