### ISSUE TITLE
Bug in node_has_matchstr()

### ISSUE THREAD

**Issue by noureddin** [ntop/nDPI#837]
In `src/lib/third_party/src/node.c`, the function [`node_has_matchstr`](https://github.com/ntop/nDPI/blob/3e99b736358ca11c3ba3723a1282ffd3bfc760bd/src/lib/third_party/src/node.c#L140) is defined as:

```c
/******************************************************************************
 * FUNCTION: node_has_matchstr
 * Determine if a final node contains a pattern in its accepted pattern list
 * or not. return values: 1 = it has, 0 = it hasn't
 ******************************************************************************/
int node_has_matchstr (AC_NODE_t * thiz, AC_PATTERN_t * newstr)
{
  int i, j;
  AC_PATTERN_t * str;

  for (i=0; i < thiz->matched_patterns_num; i++)
    {
      str = &thiz->matched_patterns[i];

      if (str->length != newstr->length)
	continue;

      for (j=0; j<(int)str->length; j++)
	if(str->astring[j] != newstr->astring[j])
	  continue;

      if (j == str->length)
	return 1;
    }
  return 0;
}
```

I understand that it searches for the string `newstr->astring` in the (loosely speaking) array of strings `thiz->matched_patterns[]->astring`.

My problem is the [`continue`](https://github.com/ntop/nDPI/blob/3e99b736358ca11c3ba3723a1282ffd3bfc760bd/src/lib/third_party/src/node.c#L154) statement in the nested `for`-loop; I think it's intended to go to the next string if the current one has a diffrent character than `newstr`, but it continues the inner loop instead of the outer one.

I suggest changing that `continue` to `break`, or even better, changing that entire inner `for`-loop and the following `if` into a simple `if` with `strncmp`:

```c
if (strncmp(str->astring, newstr->astring, str->length) == 0)
    return 1;
```

So it becomes:

```c
  for (i=0; i < thiz->matched_patterns_num; i++)
    {
      str = &thiz->matched_patterns[i];

      if (str->length != newstr->length)
	continue;

      if (strncmp(str->astring, newstr->astring, str->length) == 0)
	return 1;
    }
  return 0;
```

**Comment by lucaderi** [comment]
Thanks
