### ISSUE TITLE
Low number of detected IP packets

### ISSUE THREAD

**Issue by linparkkin** [ntop/nDPI#847]
Hi everyone, I'm currently involved in a project where I need to use ndpiReader. As you can see from the attached image I have very few detected IP packets (just 452638 of 2231702). I noticed also that there are many VLAN packets to deal with, and it seems that nDPI is not able to dissect them or it does not recognize them as IP packets. What could be the reason? The packets are sFlow sampled and truncated at 128 bytes.

![immagine](https://user-images.githubusercontent.com/33873343/75090597-ae71b700-5564-11ea-9ac5-741aa43b61af.png)

**Comment by emarshswe** [comment]
You need to supply a pcap that recreates this particular problem so we can investigate this. Screenshots will not cut it I'm afraid.

In my experience, nDPI has no problems recognizing VLAN packages. However, nDPI creates a flow hash id that includes VLAN as a part of the hash and I have had problems when VLAN is used for parts of the flow (but not for both directions). This would lead to a problem where nDPI is splitting flows if VLAN is not set in both directions of the flow. Hope this helps.

**Comment by lucaderi** [comment]
@linparkkin Can you please provide a pcap for reproducing the issue?

**Comment by IvanNardi** [comment]
Missing traces. If you are still facing this problem, open a new issue and attached a full trace, please
