### ISSUE TITLE
DNS-over-HTTPS (DoH) and youtube traffic.

### ISSUE THREAD

**Issue by vitalivanov** [ntop/nDPI#851]
Is nDPI going to support DoH?
I think currently it will not handle youtube video recognition if DoH is used.

@lucaderi @cardigliano

**Comment by lucaderi** [comment]
We already support DoH and Youtube will be supported. Please try with firefox that uses DoH

**Comment by vitalivanov** [comment]
It's supported from what version of nDPI?
