### ISSUE TITLE
protocol_was_guessed Is never used 

### ISSUE THREAD

**Issue by leonn** [ntop/nDPI#852]
protocol_was_guessed Is never used at ndpi_detection_giveup() - ndpi_main.c
 
it should be set to 1 when the guess happens within ndpi_detection_giveup

**Comment by lucaderi** [comment]
Can you please tell me the file name and line?

**Comment by leonn** [comment]
src/lib/ndpi_main.c: L: 4259
function ndpi_detection_giveup

there are many situations in the function where the protocol is guessed but in none of them  the `protocol_was_guessed` is set to true.
