### ISSUE TITLE
False positive for Skype

### ISSUE THREAD

**Issue by bcronje** [ntop/nDPI#86]
I've uploaded 3 pcap files with false positives on Skype: https://github.com/bcronje/pcaps/tree/master/pcap-files

Capture taken from a brand new installed Windows 10 workstation with no applications except Wireshark and Bittorrent client.

I suspect the identification came from dst IP match, but in this case it was definitely not used for Skype.

**Comment by lmangani** [comment]
Please retest, this should have been fixed with https://github.com/ntop/nDPI/commit/a3d66b07778981d5abbf2d2525f83eb349e3a4f3

**Comment by bcronje** [comment]
Yep still false positive running on latest git code. At least one of those 3 examples has an IP Address that is associated to Skype as defined in `ndpi_content_match.c.inc`, see `false-skype3.pcap`

Server IP: 157.56.106.184

ndpi_content_match.c.inc:

```
/*
Skype (Microsoft CDN)
157.56.0.0/14, 157.60.0.0/16, 157.54.0.0/15
111.221.64.0 - 111.221.127.255
91.190.216.0/21 (AS198015 Skype Communications Sarl)
*/
```

However the traffic was not Skype, looks like Teredo IPv6 over UDP tunneling to Microsoft, it must be some internal Windows callback, as nothing was running on the PC at that stage.

`false-skype2.pcap` looks like standard HTTP to some Microsoft server. I suspect this server IP might also be statically defined in `ndpi_content_match.c.inc`

`false-skyp1.pcap` is another Teredo IPv6 over UDP tunneling to Microsoft

All three flows does seem to go to Microsoft based on reverse IP lookups, it's just not Skype.
