### ISSUE TITLE
[Question] Script to limit usage of signatures' library.

### ISSUE THREAD

**Issue by Stesnyaus** [ntop/nDPI#860]
Hello.

I'm working with small amount of protocols/services (e.g. YouTube, Twitch, Discord, Apple Music, Spotify). I don't wanna spend CPU processing power (so the time of processing will be less than usual) for analyzing my traffic with the hole library of signatures, just to use a tiny bit of it.

So, is there any way to make a simple script which will make nDPI (or just ndpiReader though) to use only few protocol dissectors, which I can point to use manually?

I'm speaking about some code which will be like:

```
local user_scripts = require("user_scripts")

-- #################################################################

local script = {
   hooks = {},

   gui = {
      i18n_title = "Script for limited protocols' library",
      i18n_description = "Limits the library of protocols' dissectors for better perfomance of nDPI",
   }
}

-- #################################################################

function script.hooks.protocolDetected()
   local proto = flow.getInfo()
   
   if proto["proto.l4"] == "TCP" then
      <function for using custom library of dissectors> = /path/to/custom/library/TCPprotos/
   elseif proto["proto.l4"] == "UDP" then
      <function for using custom library of dissectors> = /path/to/custom/library/UDPprotos/   
   elseif proto["ndpi_cat"] == "Streaming" then
      <function for using custom library of dissectors> = /path/to/custom/library/StreamingServices/
   else
      <function that sets flow to UNKNOWN>
   end
end

-- #################################################################

return(script)
```

Thanks in advance for your answers!

**Comment by lucaderi** [comment]
Sure this is possible. Instead of doing things like

 NDPI_BITMASK_SET_ALL(all);
 ndpi_set_protocol_detection_bitmask2(ndpi_info_mod, &all);

you can set only the bit for the protocols you want nDPI to decode and ignore the others.
