### ISSUE TITLE
Youtube Upload is not detected by nDPI.

### ISSUE THREAD

**Issue by vitalivanov** [ntop/nDPI#862]
Attached pcap.
[youtubeuploadlive.zip](https://github.com/ntop/nDPI/files/4382352/youtubeuploadlive.zip)

**Comment by vitalivanov** [comment]
@lucaderi hope you are doing well!
please check

**Comment by vitalivanov** [comment]
1. Youtube has "new beta studio 2020" to upload video and old "upload with classic". Both failed.
2. Analyzing my pcap and pcap from nDPI examples - I can see that failed traffic use TCP while pcap that works uses gquic (google quick UDP Internet Protocol).
3. Seems like nDPI is not supporting modern way of youtube upload video.

**Comment by lucaderi** [comment]
Not sure I understand.

$ ndpiReader -i ~/Downloads/youtubeuploadlive.pcapng -v 2
...
Detected protocols:
	YouTubeUpload        packets: 4285          bytes: 4455460       flows: 5            


Protocol statistics:
	Fun                        4455460 bytes

JA3 Host Stats: 
		 IP Address                  	 # JA3C     
	1	 10.20.1.117              	 2      


	1	TCP 10.20.1.117:56287 <-> 172.217.163.175:443 [proto: 91.136/TLS.YouTubeUpload][cat: Media/1][2043 pkts/4301486 bytes <-> 2180 pkts/139128 bytes][Goodput ratio: 97/5][1.45 sec][ALPN: h2,http/1.1][TLS Supported Versions: TLS (4A4A),TLSv1.3,TLSv1.2,TLSv1.1,TLSv1][bytes ratio: 0.937 (Upload)][IAT c2s/s2c min/avg/max/stddev: 0/0 0/1 109/737 3/18][Pkt Len c2s/s2c min/avg/max/stddev: 60/60 2105/64 7610/1314 916/53][TLSv1.3][Client: upload.youtube.com][JA3C: 66918128f1b9b03303d77c6f2eefd128][JA3S: eb1d94daa7e0344597e756a1fb6e7054][Cipher: TLS_AES_128_GCM_SHA256][PLAIN TEXT (eram/71ykutube.com)]
	2	TCP 10.20.1.117:56286 <-> 172.217.163.175:443 [proto: 91.136/TLS.YouTubeUpload][cat: Media/1][14 pkts/2426 bytes <-> 17 pkts/6571 bytes][Goodput ratio: 67/85][1.21 sec][ALPN: h2,http/1.1][TLS Supported Versions: TLS (DADA),TLSv1.3,TLSv1.2,TLSv1.1,TLSv1][bytes ratio: -0.461 (Download)][IAT c2s/s2c min/avg/max/stddev: 0/0 87/90 864/864 246/231][Pkt Len c2s/s2c min/avg/max/stddev: 60/60 173/387 577/2091 182/556][TLSv1.3][Client: upload.youtube.com][JA3C: 66918128f1b9b03303d77c6f2eefd128][JA3S: eb1d94daa7e0344597e756a1fb6e7054][Cipher: TLS_AES_128_GCM_SHA256]
	3	TCP 10.20.1.117:56381 <-> 172.217.160.143:443 [proto: 91.136/TLS.YouTubeUpload][cat: Media/1][11 pkts/2233 bytes <-> 14 pkts/2542 bytes][Goodput ratio: 73/69][1.04 sec][ALPN: h2,http/1.1][TLS Supported Versions: TLS (1A1A),TLSv1.3,TLSv1.2,TLSv1.1,TLSv1][bytes ratio: -0.065 (Mixed)][IAT c2s/s2c min/avg/max/stddev: 0/0 91/94 718/718 237/208][Pkt Len c2s/s2c min/avg/max/stddev: 60/60 203/182 642/710 195/209][TLSv1.3][Client: upload.youtube.com][JA3C: 554719594ba90b02ae410c297c6e50ad][JA3S: 2b0648ab686ee45e0e7c35fcfb0eea7e][Cipher: TLS_AES_128_GCM_SHA256]
	4	UDP 10.20.1.117:51181 <-> 103.249.80.100:53 [proto: 5.136/DNS.YouTubeUpload][cat: Media/1][2 pkts/156 bytes <-> 1 pkts/381 bytes][Goodput ratio: 46/89][0.27 sec][Host: upload.youtube.com][172.217.160.143][PLAIN TEXT (upload)]
	5	UDP 10.20.1.117:56658 <-> 103.249.80.100:53 [proto: 5.136/DNS.YouTubeUpload][cat: Media/1][2 pkts/156 bytes <-> 1 pkts/381 bytes][Goodput ratio: 46/89][0.07 sec][Host: upload.youtube.com][172.217.163.175][PLAIN TEXT (upload)]


What's wrong exactly?

**Comment by feriel-ux** [comment]
how can I added a new protocol in ndpi and detect it ?
