### ISSUE TITLE
wireshark interface problem ndpi3.2

### ISSUE THREAD

**Issue by 1160300131** [ntop/nDPI#864]
I've already compiled ndpi on linux successfully and as the wireshark readme talked to put the lua and ndpiReader under the  correct path. There has ndpiinterface on the interface list, but when I choose the  pcap I want it to analyze  and start it, the window is empty. no information and no package. What's the problem ? Can anyone help me?

**Comment by fifteenblade** [comment]
Same problem here

nDPI (3.3.0-2336-94eee66a) 
OS: Ubuntu 19.10 fresh install
nDPI compiled with hyperscan (incl. pcre)


./ndpiReader -i ~/Desktop/testfile.pcapng
using nDPI (3.3.0-2336-94eee66a) [1 thread(s)]
Reading packets from pcap file /home/markus/Desktop/testfile.pcapng...
Running thread 0...
nDPI Memory statistics:
	nDPI Memory (once):      209.63 KB    
	Flow Memory (per flow):  2.20 KB      
	Actual Memory:           4.50 MB      
	Peak Memory:             4.50 MB      
	Setup Time:              8 msec
	Packet Processing Time:  3 msec
Traffic statistics:
	Ethernet bytes:        3771183       (includes ethernet CRC/IFC/trailer)
	Discarded bytes:       120          
	IP packets:            3314          of 3316 packets total
	IP bytes:              3691647       (avg pkt size 1113 bytes)
	Unique flows:          10           
	TCP Packets:           3309         
	UDP Packets:           5            
	VLAN Packets:          0            
	MPLS Packets:          0            
	PPPoE Packets:         0            
	Fragmented Packets:    0            
	Max Packet size:       9888         
	Packet Len < 64:       1327         

![image](https://user-images.githubusercontent.com/8506026/80001487-b85d5b00-84be-11ea-8d9f-69526984ec24.png)

![image](https://user-images.githubusercontent.com/8506026/80001575-cf03b200-84be-11ea-9839-48d8413553b2.png)

![image](https://user-images.githubusercontent.com/8506026/80001606-d925b080-84be-11ea-8d6d-bc436f27e4b9.png)

compiled ndpireader binary standalone works
but not with wireshark (3.2.2) - no packets are displayed

**Comment by SurealCereal** [comment]
I hit the same problem with WireShark 3.2.3 on Ubuntu 20.04, Linux 5.4.0-28-generic
 `/home/user/.config/wireshark/extcap/ndpiReader` is a soft-link, and works well from the CLI.
![image](https://user-images.githubusercontent.com/6961673/80748458-9fdbe900-8b2d-11ea-810a-fff8a0ddb4ec.png)

**Comment by Keld-F** [comment]
I have the exact same problem on Ubuntu 18.04.4 LTS Wireshark Version 3.3.0.
I followed the instructions in _nDPI/wireshark/README.md_ to install nDPI with Wireshark. When opening Wireshark the nDPI interface is present as an option but I am presented with a blank screen if I try to capture on the interface or try to analyze a .pcap file. 

Furthermore, when using tshark it does not recognize ndpi as an interface but gives the following error message:
"tshark: The capture session could not be initiated on interface 'ndpi' (No such device exists)."
