### ISSUE TITLE
Office 365 URLs and IP address ranges

### ISSUE THREAD

**Issue by bcronje** [ntop/nDPI#87]
Just in case you haven't seen this document from Microsoft, it contains a significant list of URLs and IP address ranges for Office 365

https://support.office.com/en-us/article/Office-365-URLs-and-IP-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2?ui=en-US&rs=en-US&ad=US

Feel free to delete/close this issue if it's not applicable.

**Comment by lucaderi** [comment]
Hi, would you like to join the nDPI development team?

**Comment by bcronje** [comment]
Thanks for the invite Luca, but I'm stretched a bit thin at the moment. So best I can offer is to log issues and send patches through if I'm able to fix it myself. I have however just integrated nDPI in one of our projects, so I'll definitely be around.

**Comment by lucaderi** [comment]
Thank you. Looking forward hearing from you then

**Comment by kYroL01** [comment]
@bcronje I started to put urls and ip ranges as you suggested (see 3aa506eb1b6ddf629b6c7c4f74060c52da6768e0).
I close this issue but I'll continue the work. Thanks a lot for the link ;)
