### ISSUE TITLE
Missing new line in CSV file when using -v without -J

### ISSUE THREAD

**Issue by a-czyrny** [ntop/nDPI#871]
https://github.com/ntop/nDPI/blob/d665df64e297051cd5b48605974846fa7076d883/example/ndpiReader.c#L1148

The csv-file line break should be placed outside of the if condition, otherwise the -j argument is always required.

**Comment by lucaderi** [comment]
Hi I am not sure I understand. This is the code


  if(enable_joy_stats) {
    /* Print entropy values for monitored flows. */
    flowGetBDMeanandVariance(flow);
    if(csv_fp) fprintf(csv_fp, "\n");
    fflush(out);
    fprintf(out, "[score: %.4f]", flow->entropy.score);
  }

the if is necessary as if csv_fp is NULL we should not print to it. Can you please explain and if you have a fix to share send a pull request?

**Comment by a-czyrny** [comment]
> the if is necessary as if csv_fp is NULL we should not print to it. Can you please explain and if you have a fix to share send a pull request?

I mean the scope of_if(enable_joy_stats)_. The if condition for the csv_ftp remains. I will gladly send the change as a pull request.
