### ISSUE TITLE
Cisco Anyconnect not reconized

### ISSUE THREAD

**Issue by didgaudin** [ntop/nDPI#875]
Hello,
ndpiReader can't find cisco anyconnect VPN
the cisco anyconnect can do UDP/443 connection instead TCP/443.

The sequence are TCP/TLS for login/passowrd and after the vpn switch to UDP.
With a tcpdump when the switch is done, there are 3 sequences:
Client Hello - Hello Verify Request ( sequence 0 )
Client Hello - Server Hello Change cipher, Encrypted Handshake (sequence 1)
Change Cipher Spec (sequence 2)
Then application Data.

I have made some changes in ciscovpn.c and now ndpiReader detect the cisco VPN (only application Data detection)
[cisco.patch.gz](https://github.com/ntop/nDPI/files/4483682/cisco.patch.gz)

do you think it's ok ?

**Comment by lucaderi** [comment]
it works!
https://github.com/ntop/nDPI/commit/94eee66a7b49a32ff482ecee77fa7bb8534c5772

Thank you. Next time please send a pull request if possible
