### ISSUE TITLE
Definition mismatch between tagged branch and release

### ISSUE THREAD

**Issue by thespooler** [ntop/nDPI#885]
There seems to be a mismatch between the tagged branch for version 3.2 and the equivalent released archive. 
In `src/includes/ndpi_main.h` from the 3.2.tar.gz release archive and 3.2 tag:
```c
int ndpi_netbios_name_interpret(char *in, char *out, u_int out_len);
```
From the 3.2-stable branch:
```c
int ndpi_netbios_name_interpret(char *in, size_t inlen, char *out, u_int out_len);
```

Note that the implementations from `src/lib/protocols/netbios.c` matches their header definitions.

**Comment by lucaderi** [comment]
You're right. Now do you know how to reconcile the differences?

**Comment by thespooler** [comment]
Update the tag? Something like
```bash
git checkout 3.2-stable
git tag --force 3.2
git push --tag --force
```

Force pushing is not best practice I'll admit, but I think in this case it is the correct, legitimate thing to do. I'm unsure if a PR can update existing tags, but I would guess it can't.

**Comment by IvanNardi** [comment]
I don't know if this issue has been fixed.
Nowadays, 3.2 is an old, unsupported version so I think we can ignore the issue anyway
