### ISSUE TITLE
How can nDPI achieve 10 Gb wirerate 

### ISSUE THREAD

**Issue by Onotoko** [ntop/nDPI#886]
Hi all,
Have anybody achieved 10 Gb wirerate when testing with nDPI? if any, how can configure to achieve it.

Thank you in advance!

**Comment by Onepamopa** [comment]
I'd also like to know if it can achieve 40 / 40+ ?

**Comment by Onotoko** [comment]
@Onepamopa,

Have you got 10 Gb?

**Comment by Onepamopa** [comment]
@Onotoko got 10G and 40G nics and switch @ the lab.

**Comment by Onotoko** [comment]
I see, did you use ndpireader of pfring_ft?
