### ISSUE TITLE
Can the packet be freed after being fed to ndpi_detection_process_packet()?

### ISSUE THREAD

**Issue by rs-natano** [ntop/nDPI#89]
I can't seem to find this information in the documentation. What I have in mind is a usage like that:

<pre>
ndpi_detection_process_packet(..., packet, ...);
free(packet);
</pre>

This seemed to work with nDPI 1.5.1, but after upgrading to 1.7.0 that produces segfaults (to be investigated).

**Comment by bcronje** [comment]
I believe this is related to issue #77 The solution is to upgrade to the latest git source where a fix is implemented.

**Comment by natano** [comment]
Yes, on latest git the issue is far less severe. One segfault remains though, please see https://github.com/ntop/nDPI/pull/91.

**Comment by rs-natano** [comment]
#77 is closed and #91 has been merged. I believe this issue to be resolved.
