### ISSUE TITLE
FreeBSD / FreeNAS TCP protocol interpreted as What's App calls

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/nDPI#892]
Hi all,

I am seeing a lot of this:

STUN.WhatsAppCall UDP Proxmox VM :56113

This TCP port 56113 is used (also) for the FreeNAS / FreeBSD stuff we do, and is unfortunately confusing people

Is there a way to change this?

See here for details: 
https://www.adminsub.net/tcp-udp-port-finder/56113

Our ProxMox VMs aren't making What's App calls, as their not even mobile systems, their ProxMox server VMs, mostly doing stuff with FreeNAS

**Comment by utoni** [comment]
To reproduce this issue on my side, I would appreciate any kind of (anonymized) pcap.

**Comment by StewAlexander-com** [comment]
Ok...

How? The server is using a virtual bridge port as a KVM to the physica 10GB port channel trunk, so its not like I can tap the line and or mirror from the switch to get a decent PCAP via Wireshark

Here's what the GUI is telling me:

![image](https://user-images.githubusercontent.com/48565067/86633916-3ea61b00-bf9f-11ea-9831-c00899daaab0.png)

**Comment by utoni** [comment]
AFAIS the issue seems related to the stun protocol detection. But w/o any decent pcap, it is like searching a needle in a haystack.

**Comment by StewAlexander-com** [comment]
Fine, give me a way to capture it, like a command or a tool or something that will provide what you are looking for, again realizing this is a ProxMox KVM

**Comment by utoni** [comment]
If you have `tshark` available, you can use something like: `tshark -w /path/to/pcap/file -Y stun`.

**Comment by StewAlexander-com** [comment]
Will get back to this, truly odd issue 

I'll post the PCAP once I have it

**Comment by IvanNardi** [comment]
@StewAlexander-com : any chances to have a trace triggering the issue?

**Comment by utoni** [comment]
Any updates @StewAlexander-com ?

**Comment by StewAlexander-com** [comment]
Closing for now, will reopen if / when I can get back to this
