### ISSUE TITLE
Difference in flow packets counters when using -v 2 option versus csv

### ISSUE THREAD

**Issue by aouinizied** [ntop/nDPI#893]
Hi,

I observed a bug on ndpiReader export
Bug observed on capwap testing file.

* case1 : If you start nDPI as in do.sh (tests repo), it generates 5 flows. (-w rs_file.out -v 2)
* case2 : exporting to csv, 5 flows also. (-C rs_file.out)

However there is a difference in packet counters when reporting the following flow:

case 1: (from result file under test repo)
2	UDP 192.168.10.10:12380 <-> 192.168.10.9:5247 [proto: 247/CAPWAP][cat: Network/14][170 pkts/33465 bytes <-> 1 pkts/168 bytes][Goodput ratio: 79/75][157.99 sec][bytes ratio: 0.990 (Upload)][IAT c2s/s2c min/avg/max/stddev: 0/0 961/0 3999/0 859/0][Pkt Len c2s/s2c min/avg/max/stddev: 93/168 197/168 470/168 78/0]

In case 2, csv export counters are different as  they appears for the same flow as:
c_to_s_pkts: 170 | c_to_s_bytes: 33465 
s_to_c_pkts | 3 | s_to_c_bytes 437

So there is a 2 packets on s_to_c direction which I could not explain.
Note that this happens only on capwap pcap test file.

BR,
Zied

**Comment by IvanNardi** [comment]
Hi
a simple suggestion.
Since f965983c, do.sh script uses "-t" flag. Are you using it in your tests in case 2?
Its presence/absence may lead to different results
My 2 cents
Ivan

**Comment by aouinizied** [comment]
Thanks Ivan, I didn't notice that change. Now, solved.

BR,
Zied
