### ISSUE TITLE
How to get Mining and Malware Categories in nDPI during APP detection ?

### ISSUE THREAD

**Issue by wamannawathe** [ntop/nDPI#894]
Dear Sir/Madam,

I am in the processing of learning nDPI library.  I know nDPI uses 10/15 packets to detect APP. But in the list of the 245 APPs I did not see any Mining and Malware APP category as each APP name is strictly ties to an APP category.  How do we get that detected ?  Is it a third party Library that we need to buy ?

thanks,

-Waman Nawathe

**Comment by lucaderi** [comment]
You just need to load the files for malware and mining categories and nDPI will do that automatically. No third party library needed.

**Comment by wamannawathe** [comment]
Ok thanks Mr. Luca,
-Waman

    On Tuesday, July 7, 2020, 12:48:59 PM EDT, Luca Deri <notifications@github.com> wrote:  
 
 


You just need to load the files for malware and mining categories and nDPI will do that automatically. No third party library needed.
