### ISSUE TITLE
How to get each packet len and arrival time of a flow

### ISSUE THREAD

**Issue by XDDDDDG** [ntop/nDPI#895]
Hi,I want to get each packet len and arrival time of each flow
I use this: 'flow->last_entropy.dst2src_pkt_len[l]'  in function: printFlow()
But I found all the packet's len only in 'src2dst_pkt_len' but no one in 'dst2src_pkt_len'
could you tell me the reason and give me some suggestions?
Thank you very much

**Comment by lucaderi** [comment]
This is a testing function used by ndpiReader. You can access the time in ndpi_process_packet() using  const struct pcap_pkthdr *header
