### ISSUE TITLE
How to print mac address in ndpiReader ?

### ISSUE THREAD

**Issue by chirayu-patel** [ntop/nDPI#901]

**Comment by chirayu-patel** [comment]
Currently when we enable the csv output, we get the src_ip for each flow

Can we also print the src mac address for the flow. If yes, how to do it.

**Comment by llhfromgrxa** [comment]
you can find it  in ndpi_ethhdr and  ndpi_arphdr ,ndpiReader does not give,you have to  echo youself

**Comment by llhfromgrxa** [comment]
> Currently when we enable the csv output, we get the src_ip for each flow
> 
> Can we also print the src mac address for the flow. If yes, how to do it.

ndpi_arphdr

**Comment by llhfromgrxa** [comment]
you can find it in ndpi_ethhdr and ndpi_arphdr

**Comment by lennon-liu** [comment]
you can find it in ndpi_ethhdr and ndpi_arphdr

> Currently when we enable the csv output, we get the src_ip for each flow
> 
> Can we also print the src mac address for the flow. If yes, how to do it.

you can find it in ndpi_ethhdr and ndpi_arphdr
