### ISSUE TITLE
Improving TLS sni/cert identification

### ISSUE THREAD

**Issue by DigiAngel** [ntop/nDPI#904]
So...I'm sure I'm not wording this right but here goes.  Currently home.hulu.com is ID'd as TLS.Hulu.  Awesome.  However, http-e-darwin.hulustream.com is not...only seen as TLS.  How can I/we classify this as TLS.Hulu?  Thank you.
![Screenshot from 2020-05-15 03-06-09](https://user-images.githubusercontent.com/947191/82033716-5e355d00-965a-11ea-857f-546786d363bc.png)

**Comment by utoni** [comment]
FYI #926
