### ISSUE TITLE
ja3_client and ja3_server are not exported correctly

### ISSUE THREAD

**Issue by Marcuccio** [ntop/nDPI#906]
**Describe the bug**
The ja3 client and server fields are not always exported correctly. 
I double checked the results with [salesforce/ja3](https://github.com/salesforce/ja3). Running the before mentioned tool I manage to retrieve thousands of entries. nDPI with the same pcap export a column filled with NaNs

**To Reproduce**

1. Go to 'https://mcfp.felk.cvut.cz/publicDatasets/CTU-Malware-Capture-Botnet-243-1/' and dowload the pcap file

2. feed nDPI with the pcap

`ndpiReader -q -t -i 2017-04-12_win5.pcap -C 2017-04-12_win5.csv`

3. Install salesforce/ja3 and run:

`ja3 2017-04-12_win5.pcap`

4. Salesforce/ja3 is able to extract thousand of ja3

**Expected behavior**
The ja3 fields should be equivalent in number and value

**Additional context**
Sometimes a ja3_server is present but not the relative ja3_client. Is this even more atypical?

**Comment by lucaderi** [comment]
Please check if all issues have been fixed. If not please report a flow (or provide a BPF filter) for reproducing the issue as the pcap you highlighted was pretty large. Thanks for reporting it
