### ISSUE TITLE
Http response payload just show me  "HTTP/1.0 200 OK"

### ISSUE THREAD

**Issue by lennon-liu** [ntop/nDPI#910]
i guess that it's imcomplete
![image](https://user-images.githubusercontent.com/48307267/83106808-abe8a580-a0ef-11ea-99c0-a62a149f084b.png)
so how to get the whole response,waitting for answer

**Comment by lennon-liu** [comment]
beside ,the http  Server info hardly find

**Comment by lucaderi** [comment]
It is part of the HTTP header dissected by the HTTP plugins. You can search there
