### ISSUE TITLE
Anydesk protocol in ndpi

### ISSUE THREAD

**Issue by aliabidzaidi** [ntop/nDPI#916]
Have you guys looked into Anydesk? 
Can its packets be identified by ndpi as all of them go under TLS, Please find below the pcap dump I took and let me know...

https://drive.google.com/file/d/1a7QRVm1ajJSZvwurG02LpekBpwCOX9zl/view?usp=sharing

Thanks, Abid.

**Comment by utoni** [comment]
Looks like there is a stable pattern in there. But could you please provide a second pcap (new session) to verify that?

**Comment by aliabidzaidi** [comment]
@lnslbrty here you go
https://drive.google.com/file/d/1A4htMekxryCdenXtAV1hlGtxM0Lwa3mF/view?usp=sharing

**Comment by utoni** [comment]
> @lnslbrty here you go
> https://drive.google.com/file/d/1A4htMekxryCdenXtAV1hlGtxM0Lwa3mF/view?usp=sharing

Not public. ;)

**Comment by aliabidzaidi** [comment]
> > @lnslbrty here you go
> > https://drive.google.com/file/d/1A4htMekxryCdenXtAV1hlGtxM0Lwa3mF/view?usp=sharing
> 
> Not public. ;)

Sorry about that, please check again

**Comment by utoni** [comment]
Your second PCAP looks like a midstream capture. However I think that anydesk uses TLS over TCP 80 with a unique common name. So detection should be possible.

**Comment by utoni** [comment]
FYI #919
