### ISSUE TITLE
Lot's of false positive protocol detections after update

### ISSUE THREAD

**Issue by DigiAngel** [ntop/nDPI#917]
Wow....just updated to the latest git about 4 hours ago.  Now seeing things like:
~~~
Jun 11 09:48:00  ntopng: [11/06/2020 15:48:00][Warning][Known Application on Non-Standard Port][Flow][flow] Known application GoogleServices detected on non-standard port 5228 [Flow: Info 192.168.1.79:60622  74.125.199.188:5228 
~~~
And another:
~~~
Known application Zoom detected on non-standard port 3479 [Flow: 192.168.1.12:25390  50.239.204.19:3479] [UDP] [Application: STUN.Zoom] 
~~~
and the last:
~~~
Known application SMBv23 detected on non-standard port 445 [Flow: box1:52838  box2:445] [TCP] [Application: NetBIOS.SMBv23] 
~~~

is there something I can do to squelch these out?  Thank you.

**Comment by Onepamopa** [comment]
Are you sure all these are false-positives? What is the version you updated from?

**Comment by DigiAngel** [comment]
Yes...the above ports shown are all standard ports for the identified services.

**Comment by DigiAngel** [comment]
And another....clearly windows updates:
~~~
Detected suspicious file transfer [ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr/en/authrootstl.cab?1133428e46062b95] [Flow: x.x.x.x:50010  184.24.98.127:80] [TCP] [Application: HTTP.WindowsUpdate] [Info: ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr...] 
~~~

**Comment by DigiAngel** [comment]
Anything on this Devs?

**Comment by lucaderi** [comment]
@DigiAngel Please share a pcap file for debugging

**Comment by DigiAngel** [comment]
Sure...the most recent:
~~~
Jun 19 09:24:36 ntopng: [19/06/2020 15:24:35][Warning][Known Application on Non-Standard Port][Flow][flow] Known application GoogleServices detected on non-standard port 5228 [Flow: Info machine:50970 74.125.197.188:5228
~~~
Something to keep in mind here....I've been running ntopng since May 13...it was only after git pulling nDPI and ntopng on Jun 11th did I start to see these.  Thank you.

[5228-1.zip](https://github.com/ntop/nDPI/files/4805465/5228-1.zip)

**Comment by utoni** [comment]
Does not look like a false positive to me.
The 74.125.0.0/16 is part of Google.
And the SNI of the TLS1.3 client hello contains mtalk.google.com.
Both seems fine to me. Was that flow triggered by Google Hangouts?

**Comment by DigiAngel** [comment]
It is.  This is just one of many since the update.  Example:
~~~
Jun 24 15:39:33 ntopng: [24/06/2020 21:39:30][Warning][Known Application on Non-Standard Port][Flow][flow] Known application Tor detected on non-standard port 9001 
~~~
And per the FAQ:
![Screenshot from 2020-06-24 15-46-54](https://user-images.githubusercontent.com/947191/85631064-111db100-b632-11ea-8a17-c590bae79c0a.png)

5228 is standard Google play store port (a Google Service ;) ):
![Screenshot from 2020-06-24 15-52-01](https://user-images.githubusercontent.com/947191/85631420-ba64a700-b632-11ea-9036-9df5473dc6d8.png)

I could go on...something has changed with nDPI.

**Comment by utoni** [comment]
A tiny pcap file would be appreciated from my side.

**Comment by DigiAngel** [comment]
Already posted but here it is again:
[pcap](https://github.com/ntop/nDPI/files/4805465/5228-1.zip)

**Comment by utoni** [comment]
We're lost in `while(1)`.

This is what I get with ndpiReader (version `3.2`) using `5228-1.pcap`.

> -----------------------------------------------------------
>
> * NOTE: This is demo app to show *some* nDPI features.
> * In this demo we have implemented only some basic features
> * just to show you what you can do with the library. Feel 
> * free to extend it and send us the patches for inclusion
> ------------------------------------------------------------
>
> Using nDPI (3.3.0-2486-d9af1562) [1 thread(s)]
> Reading packets from pcap file 5228-1.pcap...
> Running thread 0...
>
> nDPI Memory statistics:
> 	nDPI Memory (once):      223.12 KB    
> 	Flow Memory (per flow):  2.19 KB      
> 	Actual Memory:           3.43 MB      
>	Peak Memory:             3.43 MB      
> 	Setup Time:              42 msec
> 	Packet Processing Time:  0 msec
>
> Traffic statistics:
> 	Ethernet bytes:        7128          (includes ethernet CRC/IFC/trailer)
> 	Discarded bytes:       0            
> 	IP packets:            21            of 21 packets total
> 	IP bytes:              6624          (avg pkt size 315 bytes)
> 	Unique flows:          1            
> 	TCP Packets:           21           
> 	UDP Packets:           0            
> 	VLAN Packets:          0            
>	MPLS Packets:          0            
> 	PPPoE Packets:         0            
> 	Fragmented Packets:    0            
> 	Max Packet size:       1450         
> 	Packet Len < 64:       12           
> 	Packet Len 64-128:     3            
> 	Packet Len 128-256:    1            
> 	Packet Len 256-1024:   3            
> 	Packet Len 1024-1500:  2            
> 	Packet Len > 1500:     0            
> 	nDPI throughput:       81.08 K pps / 209.97 Mb/sec
> 	Analysis begin:        19/Jun/2020 17:24:25
> 	Analysis end:          19/Jun/2020 17:25:10
> 	Traffic throughput:    0.46 pps / 1.22 Kb/sec
> 	Traffic duration:      45.675 sec
> 	Guessed flow protos:   0            
>
>
> Detected protocols:
> 	GoogleServices       packets: 21            bytes: 6624          flows: 1            
>
>
> Protocol statistics:
> 	Acceptable                    6624 bytes

What nDPI version you are using?
What is your expected protocol detection if not `GoogleServices` ?

**Comment by IvanNardi** [comment]
AFAIU @DigiAngel is not complaining about protocol classification; he is complaining about the "warning" :"Known Application on Non-Standard Port"
From e5e69d0f7  nDPI is able to detect when a known protocol is using a non-standard port, and it mark these sessions with NDPI_KNOWN_PROTOCOL_ON_NON_STANDARD_PORT flag. The algorithm may need some improvements, though.

**Comment by DigiAngel** [comment]
Thank you @IvanNardi that's exactly it.  Nothing has changed from a client/network side if that helps.

**Comment by utoni** [comment]
Now we're talking. But that isn't a false positive detection as @IvanNardi mentioned (thanks btw for `break`ing that `while(1)`).

**Comment by DigiAngel** [comment]
I guess that's a definition issue.  The protocol detection is accurate, the alerting on non-standard port is not..hence my "false positive" naming.  Hope that clears that up.

**Comment by IvanNardi** [comment]
With latest release, you can add exception to flow risks: see https://www.ntop.org/ndpi/howto-define-ndpi-risk-exceptions-for-networks-and-domains/
