### ISSUE TITLE
Protocol QUICKTIME not detect

### ISSUE THREAD

**Issue by a7lan** [ntop/nDPI#93]
Hello. I use ndpi together ndpi-netfilter. When I try to use the Protocol QUICKTIME to mp4 detection (e.g. youtube videos), ndpi it does not detect. 

Sorry for my English.

PCAP Files

mode html5
https://drive.google.com/file/d/0B9pJNOnHB-bkZmZIekN6WDJUMEU/view?usp=sharing
mode flash
https://drive.google.com/file/d/0B9pJNOnHB-bkTGczbEpBQUFCeXM/view?usp=sharing

**Comment by lmangani** [comment]
For both provided pcaps Youtube seems correctly detected. 

```
YouTube              packets: 8478          bytes: 7821912       flows: 13           
YouTube              packets: 17885         bytes: 17266713      flows: 9         
```

Please clarify the expected results in order to troubleshoot. Also providing a PCAP with only the protocols of interest is usually more suitable and appropriate for such reports.

**Comment by a7lan** [comment]
New pcap file html5
https://drive.google.com/file/d/0B9pJNOnHB-bkMWFCaldNbkNSNU0/view?usp=sharing

command was used
tcpdump -i ppp999 port 80  and src 74.125.110.57 -w /tmp/html5.pcap
where 74.125.110.57 is youtube ip when a watching  video.

I expect that will be detected by the resulting video from youtube

Other proto detected (eg http, ssh, icmp)

**Comment by lmangani** [comment]
Capture is missing the setup/establishment consequently the flow is not properly detected. The original files seems to produce the desired output in my tests.

**Comment by a7lan** [comment]
and now
https://drive.google.com/file/d/0B9pJNOnHB-bkZ0ZlNTJHbk1naTQ/view?usp=sharing

**Comment by kYroL01** [comment]
@lmangani : Inspecting the packets, i notice that in the payload is present the name of a web server used by youtube (gwiseguy - 2.0) used by many domains (https://seomon.com/website-technologies/web-servers/gwiseguy/2.0/).
But i think it's impossible to detect this as Quicktime protocol, just Youtube.

**Comment by lmangani** [comment]
@kYroL01 fully agree at this stage that is the case currently

**Comment by kYroL01** [comment]
@lmangani maybe we can add the name of that server for the youtube dissector ? what are thinking of it ?
