### ISSUE TITLE
add support of (IETF) QUIC

### ISSUE THREAD

**Issue by alagoutte** [ntop/nDPI#934]
There is now more on more IETF QUIC ( https://quicwg.org/ ) with client (Firefox Nighty, ntctp2) and server (nginx, picoquic...) (See [Implementation ](https://github.com/quicwg/base-drafts/wiki/Implementations)

it will be nice also to support IETF QUIC

You can found pcap (of last draft) on Wireshark [bug 13881](https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=13881)

**Comment by lucaderi** [comment]
Good idea, thank you. Sample pcap https://bugs.wireshark.org/bugzilla/attachment.cgi?id=17806

**Comment by alagoutte** [comment]
There is multiple draft release actually used, it is better to support multiple version...

You can use the A Guide to Parsing QUIC Client Hellos for Network Middlebox Vendors from #933, it is also explain for IETF QUIC
