### ISSUE TITLE
Unknown Protocol was detected (25GB) and its grows 

### ISSUE THREAD

**Issue by AlekMarkus** [ntop/nDPI#94]
Hey ,

i have dumped the Unkown Data to pcap file , and opened in Wireshark

i can see that all the Destination Ip is my Exchange server and Sometimes The Exchange Server is the Source and my Firewall become the Destination Host

So why ntopng is not detect this traffic as SMTP protcol ? 

 i have noticed that since i have updated ntopng to the latest version i can see that Protcol SMTP has only 1.63 GB 

and before i updated  ntopng , there was no problem with SMTP detection

pcap file : 

 https://www.dropbox.com/s/dlog8z83ine5aqz/Uknown%20Protocol.rar?dl=0

Best Regards,
Alek

**Comment by ValentinaViscarelli** [comment]
Alek,
if I open your pcap files with wireshark, I cannot find smtp traffic so I'm not able to verify the problem. If you still have the problem please attach correct pcap files.
Thanks

**Comment by AlekMarkus** [comment]
Hey Valentina,

ok i have uploaded new Pcap file .

https://www.dropbox.com/s/2elepircg2ahy0g/Unknown.rar?dl=0

you can exclude Source :10.1.1.200  ,    Destination : 10.1.1.20 on port 5002

this is my ElasticSearch Server(10.1.1.20) that receiving logs from some device on my network on port 5002 so that o.k.

but look for example at ip Source : 10.1.4.13 and Destination :  10.1.1.228

its sending data on Source port 50981 to Destination Port : 45241 that i dont know what are those ports. 

Best Regards,
Alek

**Comment by pauloangelo** [comment]
@AlekMarkus ,

There is no SMTP traffic in your second pcap. The communication between 10.1.4.13 and 10.1.1.228 is using the MSRPC protocol. The communication between Exchange and Outlook clients is based on MSRPC. Probably is the case. 

I believe that libnDPI should classify this communication as MAPI or at least as DCE_RPC.

It would classify as DCE_RPC if the src port or dst port was 135. But in your case, the ports are (45241,50981). 

In ./src/lib/protocols/dcerpc.c, line 35, we have:

>  void ndpi_search_dcerpc(struct ndpi_detection_module_struct *ndpi_struct, struct ndpi_flow_struct *flow)
>  {
>    struct ndpi_packet_struct *packet = &flow->packet;
> 
>  if((packet->tcp != NULL)
>     && (packet->payload_packet_len > 64)
>     && ((ntohs(packet->tcp->source) == 135) || (ntohs(packet->tcp->dest) == 135))
>     && (packet->payload[0] == 0x05) /\* version 5 _/
>     && (packet->payload[2] < 16) /_ Packet type */
>     ) {
>    NDPI_LOG(NDPI_PROTOCOL_DCERPC, ndpi_struct, NDPI_LOG_DEBUG, "DCERPC match\n");
>    ndpi_int_dcerpc_add_connection(ndpi_struct, flow);
>    return;
>  }
> 
>    NDPI_ADD_PROTOCOL_TO_BITMASK(flow->excluded_protocol_bitmask,      >NDPI_PROTOCOL_DCERPC);
>   }

I believe that some coding is needed to classify it, adding another protocol (MAPI?!) or adjusting DCERPC.

[]'s

PA

**Comment by ValentinaViscarelli** [comment]
DCE_RPC changed. Now the flows should be recognized.
Regards,
Valentina
