### ISSUE TITLE
Wrong networks in host_protocol_list

### ISSUE THREAD

**Issue by vel21ripn** [ntop/nDPI#944]
Need to fix invalid ip networks

* 52.82.0.0/14 NDPI_PROTOCOL_AMAZON
  may be 52.82.0.0/15 ?
* 141.101.88.0/19 NDPI_PROTOCOL_CLOUDFLARE
  may be 141.101.88.0/21 ?
* 209.148.214.135/21 NDPI_PROTOCOL_NETFLIX
  ?????????????
* 208.64.201.0/22 NDPI_PROTOCOL_STEAM
  may be 208.64.201.0/24
* ```
  /* Teamviewer 159.122.189.32-63 */
  { 0x9F7ABD30 /* 159.122.189.32 */, 21, NDPI_PROTOCOL_TEAMVIEWER },

The value 0x9F7ABD30 is 159.122.189.48 and it is not network /21. 
may be 159.122.189.32-63 is 159.122.189.32/27

**Comment by lucaderi** [comment]
How do you know that these networks are wrong?

**Comment by vel21ripn** [comment]
The rule for network addresses is violated: (network_address & network_mask) == network_address.
In all cases, the network mask is too short.

**Comment by utoni** [comment]
@vel21ripn seems right AFAIS. I did a (very) fast investigation:
`whois 159.122.189.48`

> inetnum:        159.122.189.32 - 159.122.189.63
> netname:        NETBLK-SOFTLAYER-RIPE-CUST-SS30638-RIPE
> descr:          TeamViewer GmbH
> country:        DE
> admin-c:        SS30638-RIPE
> tech-c:         SS30638-RIPE
> status:         LEGACY
> mnt-by:         MAINT-SOFTLAYER-RIPE
> created:        2016-11-21T22:19:03Z
> last-modified:  2016-11-21T22:19:03Z
> source:         RIPE

with a `159.122.189.32/27` CIDR.

**Comment by utoni** [comment]
(accidentally closed that issue, but there is probably more to do)

**Comment by utoni** [comment]
> Need to fix invalid ip networks
> 
>     * 52.82.0.0/14 NDPI_PROTOCOL_AMAZON
>       may be 52.82.0.0/15 ?
> 
>     * 141.101.88.0/19 NDPI_PROTOCOL_CLOUDFLARE
>       may be 141.101.88.0/21 ?
> 
>     * 209.148.214.135/21 NDPI_PROTOCOL_NETFLIX
>       ?????????????

These three above require a deeper investigation. Could you provide some more details, please?

> 
>     * 208.64.201.0/22 NDPI_PROTOCOL_STEAM
>       may be 208.64.201.0/24

208.64.201.0/22 seems correct AFAIS
