### ISSUE TITLE
Would it be possible to add gotoassist meetings?

### ISSUE THREAD

**Issue by elico** [ntop/nDPI#945]
They have pretty long document at:
* https://support.goto.com/webinar/help/optimal-firewall-configuration-g2w060025

**Comment by utoni** [comment]
Seems possible. Working on it.

**Comment by elico** [comment]
@lnslbrty  I just noticed that there is a comment on the "citrix" protocol that includes something for gotoassist.

**Comment by elico** [comment]
@lnslbrty @lucaderi  Thanks
