### ISSUE TITLE
Add radiotap to ndpiReader

### ISSUE THREAD

**Issue by maciej-bielski** [ntop/nDPI#95]
Hello,

please modify example code to recognise radio tap packets. I'm attaching 2 files: phone.cap - contains data sent from my phone, all.cap - contains all data collected in monitor mode. It would be very nice if there was pice of code which checks if packet contains data in order to skip e.g. beacon frames. I failed to write it by my own.

http://maciejbielski.pl/all.cap
http://maciejbielski.pl/phone.cap

Thank you,
Maciej Bielski

**Comment by maciej-bielski** [comment]
Hello,

alter a while I finally managed to deal with radio tap packets. Please leave this ticket for me. I'll share my code with you when my project will be done. 

Thanks!
Maciej Bielski

**Comment by kYroL01** [comment]
Fixed (improvement needed): 1dc03d574195ffdd94091e2f15a77358e1119a46
