### ISSUE TITLE
When to support mysql8

### ISSUE THREAD

**Issue by ssz25** [ntop/nDPI#962]
When to support mysql8

**Comment by lucaderi** [comment]
What do you mean?

**Comment by emarshswe** [comment]
> When to support mysql8

Are you interested if nDPI will support protocol detection for mysql8? Please provide a pcap file with isolated examples of mysql8 traffic.

**Comment by utoni** [comment]
@ssz25 Can you please verify that PR #987 is able to detect MySQL 8?
I do not have the time right now to setup a MySQL 8 instance, otherwise I would verify it myself.

**Comment by lucaderi** [comment]
@ssz25 Closed for inactivity
