### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by Tomasz158** [ntop/nDPI#969]
I would like to add nDPI library in my project (application to slow down/speed up) certain packets based on DPI. Can anyone help me by providing a tutorial or place where I can start from? Official documentation is not helpful.

**Comment by utoni** [comment]
The official documentation is unfortunately not up to date.

There is a nDPI integration example in `example/ndpiSimpleIntegration.c`. It is not well documented as well but at least a all-in-one C file intended to show basic API usage.

**Comment by Tomasz158** [comment]
Thanks. I will open an issue in case I have any further problems
