### ISSUE TITLE
Packet detecting as a function

### ISSUE THREAD

**Issue by Tomasz158** [ntop/nDPI#971]
Can anyone guide me on interpreting reader/simpleintegration? I am more into C++ than pure C and I would like to integrate a protocol detection on one or many interfaces. Reader.c seems "overfunctioned" and it is a bit complicated for me to just take out that certain fuctionality and enhance it for my purposes. If it is possible to simply call that function (e.g. reader eth0) and get some sort of list as a result(name, src, dst), it would be even better.

**Comment by utoni** [comment]
AFAIU you want a std::vector<result> where result has 3 members aka name, src, dst.
But what do you exactly mean with name, src and dst? Detected protocol name? source ip/port? dest ip/port?
Integrating nDPI won't be that easy, unfortunately.

At first you need a packet capture interface. I'm usually using `libpcap` for this purpose, but you could also use a raw socket if you do not want to replay captured files.
The nDPI library does protocol detection per packet with `ndpi_detection_process_packet`.
But your integration needs to keep track of active flows to pass the right flow memory to the aforementioned function.
You'll need a flow tracking mechanism. nDPI has builtin **binary tree** support functions which you could use.
Last but not least you'll need a reliable packet distribution if you want to go multi-threading. Or use slow mutex if you don't care about speed.

These are just a few things you have to consider.

**Comment by Tomasz158** [comment]
I meant source ip, destination ip
for packet capturing I have libtins that I can use, but I thought nDPI can also process capturing packets. I guess the packet itself will be a PDU object?

**Comment by utoni** [comment]
> for packet capturing I have libtins that I can use, but I thought nDPI can also process capturing packets. I guess the packet itself will be a PDU object?

The library itself does not know anything about packet capturing. Only the integration e.g. `ndpiReader` need to know such things.

The packet should be a PDU starting at layer3.
