### ISSUE TITLE
not defined issue

### ISSUE THREAD

**Issue by Tomasz158** [ntop/nDPI#972]
I am testing API in a project and when I use:
#include <iostream>
#include "main.hpp"
#include "ndpi/ndpi_api.h"
#include "ndpi/ndpi_main.h"

using namespace std;
int main(){
cout << ndpi_get_api_version();
} 
I get an error: ||=== Build: Debug in ... (compiler: GNU GCC Compiler) ===|
/usr/bin/ld: obj/Debug/main.o||in function `main':|
/usr/bin/ld: /.../main.cpp|20|undefined reference to `ndpi_get_api_version'|
||error: ld returned 1 exit status|
||=== Build failed: 4 error(s), 0 warning(s) (0 minute(s), 0 second(s)) ===|

ndpi is installed

**Comment by utoni** [comment]
Please provide the full command you've used to compile **and** link this piece of code.

**Comment by Tomasz158** [comment]
g++ -Wall -fexceptions -g  -.../main.cpp -o obj/Debug/main.o
g++  -o bin/Debug/ obj/Debug/main.o  
I compile it using Code::Blocks

**Comment by utoni** [comment]
You do not link against any nDPI library. See `-l` or just use the static code archive.

**Comment by Tomasz158** [comment]
adding -lndpi worked, thanks.
