### ISSUE TITLE
ndpi_detection_process_packet

### ISSUE THREAD

**Issue by Tomasz158** [ntop/nDPI#975]
Can anyone guide me through each parameter of ndpi_detection_process_packet?
I know that it is used in ndpiSimpleIntegration.c, but it is not documented very well and I just wanted to avoid simple copy and paste of most of the code.
I guess that in:
` workflow->pcap_handle = pcap_open_live(file_or_device, /* 1536 */ 65535, 1, 250, pcap_error_buffer);`
file_or_device points to eth interface I would like to capture packets from?

**Comment by utoni** [comment]
You are right. Indeed, `file_or_device` can be a network interface or just a pcap file.

**Comment by Tomasz158** [comment]
> You are right. Indeed, `file_or_device` can be a network interface or just a pcap file.

Thanks. How can I point it to, for example, eth0?
I will have to analyze example more deeply.

**Comment by utoni** [comment]
`ndpi_detection_process_packet`:

1st arg: pointer to an **initialized** detection module
2nd arg: pointer to the current flow memory the packet belongs to
3rd arg: pointer to the start of the layer3 header
4th arg: total size of the packet w/o any layer2 overhead
5th arg: tick resolution of libnDPI
6,7th arg: pointer to source/destination id struct

**Comment by utoni** [comment]
> Thanks. How can I point it to, for example, eth0?

Exactly.

**Comment by Tomasz158** [comment]
> > Thanks. How can I point it to, for example, eth0?
> 
> Exactly.

so just write "eth0"?

**Comment by utoni** [comment]
Just try it out. A string literal should work fine.

**Comment by Tomasz158** [comment]
> 
> 
> Just try it out. A string literal should work fine.

I will try and see if it works

**Comment by Tomasz158** [comment]
when I compile the code of ndpiSimpleIntegration.c, I get the following errors:
`ndpi_ssl_version2str(flow_to_process->ndpi_flow->protos.stun_ssl.ssl.ssl_version,
                                             &unknown_tls_version),`
invalid conversion from ‘u_int16_t’ {aka ‘short unsigned int’} to ‘ndpi_flow_struct*’ [-fpermissive]|
invalid conversion from ‘uint8_t*’ {aka ‘unsigned char*’} to ‘u_int16_t’ {aka ‘short unsigned int’} [-fpermissive]|
too few arguments to function ‘char* ndpi_ssl_version2str(ndpi_flow_struct*, u_int16_t, u_int8_t*)’|

`ndpi_ssl_version2str(flow_to_process->ndpi_flow->protos.stun_ssl.ssl.ssl_version,
                                             &unknown_tls_version),`
error: invalid conversion from ‘uint8_t*’ {aka ‘unsigned char*’} to ‘u_int16_t’ {aka ‘short unsigned int’} [-fpermissive]|
error: too few arguments to function ‘char* ndpi_ssl_version2str(ndpi_flow_struct*, u_int16_t, u_int8_t*)’|

**Comment by utoni** [comment]
Whoops! This was my fault. Will fix this ASAP.

I've changed the singature of `ndpi_ssl_version2str` to prevent a possible race condition but forgot to change function usage in `ndpiSimpleIntegration`.
`ndpiSimpleIntegration` should be part of at least 1 CI build job to prevent such things in the future...

**Comment by utoni** [comment]
PR #976 should fix this issue.

**Comment by Tomasz158** [comment]
it finally works, but I have another issue. I rewrote the main function of ndpi to look like that:
`int readpacket()
{
    char* nic = "eth0";

    if (start_reader_threads() != 0) {
        fprintf(stderr, "%s: start_reader_threads\n", nic);
        return 1;
    }

    signal(SIGINT, sighandler);
    signal(SIGTERM, sighandler);
    while (main_thread_shutdown == 0 && processing_threads_error_or_eof() == 0) {
        sleep(1);
    }

    if (main_thread_shutdown == 0 && stop_reader_threads() != 0) {
        fprintf(stderr, "%s: stop_reader_threads\n", nic);
        return 1;
    }

    return 0;
}
`
and the main function of my main.cpp file:
`int main()
{
    readpacket();
    return 0;
}
`
However when I run the code (it compiles properly) I have a segmentation fault error

main.cpp also have a main.hpp file and it contains #include packetreader.hpp
packetreader.hpp cointains the packetreader function and code is in packetreader.cpp file

**Comment by Tomasz158** [comment]
Ok, it worked. Forgot to setup reader threads. Finally works
