### ISSUE TITLE
moving functions in ndpiSimpleIntegration

### ISSUE THREAD

**Issue by Tomasz158** [ntop/nDPI#979]
Good Evening,
I would like seperate packet reading and packet capture logic in ndpiSimpleIntegration. 
Do I understand correctly, that I should move all functions connected with pcap, pcap_open_live and struct nDPI_workflow?

**Comment by utoni** [comment]
> Do I understand correctly, that I should move all functions connected with pcap, pcap_open_live and struct nDPI_workflow?

All functions prefixed with `pcap_` and the `pcap_handle`. I would not recommend to move `nDPI_workflow` struct as a whole.

**Comment by Tomasz158** [comment]
okay, thank you.
