### ISSUE TITLE
problem with packet recognising

### ISSUE THREAD

**Issue by Tomasz158** [ntop/nDPI#980]
I have the following code (in place of your business logic in simpleintegration file:
`   
 if (flow_to_process->ndpi_flow->num_extra_packets_checked <
            flow_to_process->ndpi_flow->max_extra_packets_to_check)
    {
            if(flow_to_process->detected_l7_protocol.app_protocol == NDPI_PROTOCOL_IP_ICMP)
        {
            std::cout << "ICMP" << "\n";

        }
    }`
When I compile the code and run it, run ping command in the second terminal window, the "ICMP" is not displayed

**Comment by utoni** [comment]
Did you choose the correct network interface?
Did you compare the expected output with wireshark?

**Comment by Tomasz158** [comment]
Yes, it was set to the correct interface and I did not

**Comment by utoni** [comment]
Did the ICMP request target the correct subnet (and its associated network interface) ?

**Comment by utoni** [comment]
I've updated PR #976, there was an issue with `max_extra_packets_to_check` which can of course be `0` for some protocols.
