### ISSUE TITLE
nDPI quick start

### ISSUE THREAD

**Issue by Tomasz158** [ntop/nDPI#981]
I am trying to follow nDPI_QucikGuide.pdf 
and I have a question connected with:

`ndpi_struct = ndpi_init_detection_module(  detection_ticks_resolution,  malloc_wrapper,  free_wrapper,  debug_print)`

what is meant by  
`void* (*__ndpi_malloc)(unsigned long size);`  
Function pointer to a memory allocator. ?

**Comment by lucaderi** [comment]
Yes.
Please refrain from opening tickets for question. Please jump in discord and ask https://www.ntop.org/community/
