### ISSUE TITLE
ipv6 version of ndpi_guess_undetected_protocol

### ISSUE THREAD

**Issue by Tomasu** [ntop/nDPI#99]
ndpi_guess_undetected_protocol only supports ipv4 currently. It would be useful if it also supported ipv6 or there was an ipv6 variant of it.

**Comment by kYroL01** [comment]
This is a thing to do. Thank you

**Comment by kYroL01** [comment]
@Tomasu can you also provide a pcap with an ipv6 guess undetected protocol, if you have it ?

**Comment by Tomasu** [comment]
I can grab a pcap file with some IPV6 data in it, but that function only accepts ipv4 addresses.

**Comment by kYroL01** [comment]
It's ok, then i'll modify using that pcap ;)

**Comment by Tomasu** [comment]
http://tomasu.net/~moose/ipv6.pcap

I tried attaching it here, but it seems github tries really hard to be annoying.

**Comment by kYroL01** [comment]
It's ok. Thanks man. I'll doing in the following days.

**Comment by kYroL01** [comment]
fixed 59d0af33b89acd55f0ffb69aaabc2c2160c436bf

The problem was before the ndpi_guess_undetected_protocol.
Now the program test could recognize tunneling 6in4.
