### ISSUE TITLE
Generic Protocol Support

### ISSUE THREAD

**Issue by akibsayyed** [ntop/nDPI#993]
I am trying to perform vendors custom protocol DPI. As of now vendonr have given library which convert protocol into json. 

is it possible to write JSON dissector in a generic way.

simple example is given below

 
          "frame.encap_type": "25",
          "frame.time": "Jul 26, 2019 01:22:54.626669515 GMT",
          "frame.offset_shift": "0.000000000",
          "frame.time_epoch": "1598385174.626669515",
          "frame.time_delta": "0.000000000",
          "frame.time_delta_displayed": "0.000000000",
          "frame.time_relative": "0.000000000",
          "frame.number": "1",
          "frame.len": "676",
          "frame.cap_len": "676",
          "frame.marked": "0",
          "frame.ignored": "0",

 
 above data is just  frame json part .

I would like to findout  frame.number by just querying frame.number in nDPI app and then perform transactions

**Comment by lucaderi** [comment]
This is not supported at the moment, but if you can implement it and send a pull request that would be nice
