### ISSUE TITLE
how do you know encrypted application data to detect application protocol?

### ISSUE THREAD

**Issue by xinfenglee** [ntop/nDPI#995]
"Handling Encrypted Content
The trend of Internet traffic is going towards encrypted content often using SSL. In order to let nDPI support encrypted connections, we have added a decoder for SSL (both client and server) certificates, thus we can figure out the protocol using the encryption certificate. This allows us to identify protocols such as Citrix Online and Apple iCloud that otherwise would be undetected."
I had read nDPI source code,but I still don't understand how nDPI know what is under ssl transmission。source code of "tls.c" file just do dissect tls protocol content ,like ClientServerHello,  Certificate。how do you know encrypted application data to detect application protocol?

**Comment by xinfenglee** [comment]
do you use 'tls.handshake.extensions_server_name' and 'static ndpi_protocol_match host_match' to judge which is upper protocol  on ssl? this handle is like you say 'Handling Encrypted Content',but actually you just decode tls protocol content.

**Comment by utoni** [comment]
AFAIK `tls.c` just tries to decode server&client hello's as well as certs. And if a server or client hello could be decoded, it set's NDPI_PROTOCOL_TLS. Not sure if that answers your question.

**Comment by xinfenglee** [comment]
ok thanks ,I know .
